### ISSUE TITLE
Provide a way to kill a client

### ISSUE THREAD

**Issue by artagel** [n1nj4sec/pupy#10]
Currently, I don't see a way to kill a client from the server.
The only way I can see to do this is finding the proc and killing it like this:
```
>> exec tasklist /v | findstr pupy
pupyx862.exe                  1464 Console                    1     33,976 K Unknown        XXXX-VM\artagel                                       0:00:00 N/A
>> exec taskkill /PID 1464 /F
connection closed by peer
```
Adding a kill client command would be useful.

**Comment by byt3bl33d3r** [comment]
@artagel you can do ```run exit --yes``` to kill a client

**Comment by artagel** [comment]
That simply exits the entire server.  It doesn't specifically kill only one client.  If I have 10 clients calling back, I want to kill just one.

**Comment by deathfantasy** [comment]
Works for me. Did you confuse it with the server `exit` command?
Try `run -f <id> exit --yes`

**Comment by artagel** [comment]
Yes, I see didn't notice the run.  Yes, that works.

**Comment by n1nj4sec** [comment]
as @deathfantasy said exit --yes exit (cleanly) the client. If you are injected into a process it wont kill it. use -f to filter to a specific client. If you want to kill a client and the process you can create an alias in pupy.conf like killme= pyexec -c 'import os;os.kill(os.getpid(),9)'
