### ISSUE TITLE
Commands/options visible even if the target is not compatible

### ISSUE THREAD

**Issue by quentinhardy** [n1nj4sec/pupy#103]
I wish to begin by saying this project is **really awesome**. It is very useful when I pentest. Thank you very much for that.

I just want to make the point that **some commands/options are visible even if the target is not compatible** with them. 
For example, you have a Linux target and the _migrate_ command or _gather/webcamsnap_ module are visible while these ones are not compatible with Linux.
I think it should be better to have only commands/modules visible for the target selected. I think it's just a small improvement for a better usage.

Again thank you for this project,

**Comment by n1nj4sec** [comment]
Hello, are you talking about the command-completion feature ? 
Because you can filter by using `run linux/<TAB>` and only the linux-compatible modules will be shown. But filter automatically the command completion when ```session -i``` is used is a good idea, I add it to my TODO list, thanks

**Comment by quentinhardy** [comment]
Good news for the filter feature when _session -i_ is used.

I was talking about the _list_modules_ command. I think it will be great to know possible target types (windows, Linux, etc.) of each module when you use this command.

**Comment by AlessandroZ** [comment]
This issue can be closed. It has already been implemented
