### ISSUE TITLE
ImportError: No module named creddump.addrspace

### ISSUE THREAD

**Issue by guistory** [n1nj4sec/pupy#104]
win7 32bit + python 2.7
when i run puypysh.py this error was been found

**Comment by n1nj4sec** [comment]
Are you running the pupysh.py server on windows ? If yes, it's because symbolink links does not work on windows.
```
$ ls -la modules/lib/windows/creddump
lrwxrwxrwx 1 me me 37 mai   31 17:40 modules/lib/windows/creddump -> ../../../external/creddump7/framework
```
So copy the repository manually or install pupy on linux

**Comment by guistory** [comment]
ImportError: No module named external.creddump7.framework.addrspace
i instead it with true path ，but error like above。

**Comment by n1nj4sec** [comment]
python imports don't work like that, do as I said, copy the directory and it will work ;)
