### ISSUE TITLE
Feature Request: Keyloggers platforms

### ISSUE THREAD

**Issue by golind** [n1nj4sec/pupy#105]
Request for adding linux/osx versions as ell.

**Comment by n1nj4sec** [comment]
@AlessandroZ made an awesome keylogger module for linux (cf 712d5d97b920494a5ab76eb77aae22f5d1be954b ). I just tried it on a ubuntu desktop and it works great !

**Comment by AlessandroZ** [comment]
You could close this issue now, the keylogger exists for all system now.

**Comment by jboss38** [comment]
Keylogger not working for Android atm :)
