### ISSUE TITLE
exe_x86 and exe_x64 don't work with ssl transport

### ISSUE THREAD

**Issue by quentinhardy** [n1nj4sec/pupy#108]
Hello,

When I generate an _exe_x86_ or _exe_x64_ with these following commands (_ssl_ transport), binaries don't work on windows 7 x64 SP1:
```
root@kali:/pupy# python pupygen.py -f exe_x86 simple --transport ssl
[!] required argument missing, automatically adding parameter --host 192.168.0.27:443 from local ip address
[+] payload successfully generated with config :
OUTPUT_PATH = /pupy/pupyx86.exe
LAUNCHER = 'simple'
LAUNCHER_ARGS = ['--host', '192.168.0.27:443', '--transport', 'ssl']
SCRIPTLETS = []

root@kali:/pupy# python pupygen.py -f exe_x64 simple --transport ssl
[!] required argument missing, automatically adding parameter --host 192.168.0.27:443 from local ip address
[+] payload successfully generated with config :
OUTPUT_PATH = /pupy/pupyx64.exe
LAUNCHER = 'simple'
LAUNCHER_ARGS = ['--host', '192.168.0.27:443', '--transport', 'ssl']
SCRIPTLETS = []
```
I have not tried to debug these binaries. I see no one connection from my windows desktop with Wireshark. 

However, I have tried **with the _tcp_cleartext_ protocol** (_python pupygen.py -f exe_x64 simple --transport tcp_cleartext_ and _python pupygen.py -f exe_x86 simple --transport tcp_cleartext_) and **it's OK**: I have reverse connections. Consequently, I think the problem come from **ssl transport module**...

I have not tried with other transport methods yet.

Again thank you for this very good project,

**Comment by n1nj4sec** [comment]
yep, it's because I changed the name from tcp_ssl to ssl and didn't recompile the binaries. You can recompile the binaries, wait I finish the big changes I'm bringing to pupy's transports or rename ssl to tcp_ssl in network/conf.py

**Comment by n1nj4sec** [comment]
It should be fixed ;)
