### ISSUE TITLE
Possible addition to Keylogger

### ISSUE THREAD

**Issue by golind** [n1nj4sec/pupy#11]
Adding mouse clicks to the Keylogger, and screencapture around the mouse using [1]. Log would show something like "Left mouse click: see img_091515_explorer."

Get's active window process name, and using a list of processes as a filter so there aren't an excess of screenshots.

[1] http://sourceforge.net/p/pykeylogger/code/ci/master/tree/onclickimagecapture.py
(I think this should work).

**Comment by kilbyjmichael** [comment]
I think it would be cool if the keylogger could dump to a file too.

**Comment by golind** [comment]
That should be an easy change, really just a change in /modules/keylogger.py (thanksninja), so it streams to a file. Personally I would like more timestamps and active window names.

**Comment by Demannu** [comment]
I'll see if I can get this done and push it to the main.

**Comment by golind** [comment]
@Demannu this should cover it i think: https://github.com/n1nj4sec/pupy/pull/44
