### ISSUE TITLE
Linux process hiding

### ISSUE THREAD

**Issue by corefx** [n1nj4sec/pupy#115]
Currently only port hiding is possible but it would be an useful feature to be able to hide client's process as well. (Hiding from ps, pstree, top and lsof).

**Comment by void-in** [comment]
I don't think that is possible unless you either changes all those binaries or make pupy agent a kernel module and run it in kernel space.

**Comment by DeveloppSoft** [comment]
@void-in or you can load a LKM root kit which will hide pupy :smile:

**Comment by n1nj4sec** [comment]
The easier to do without any privilege is to edit argv and environ to look like another process, I will add a module for that later
