### ISSUE TITLE
Feature request: daemonize with pyinstaller

### ISSUE THREAD

**Issue by alxchk** [n1nj4sec/pupy#121]
Not really sure that this is not possible now, but at least I can't find this easily. It's quite useful to add option to start application with detached TTY.

**Comment by n1nj4sec** [comment]
apt-get install screen ?

**Comment by alxchk** [comment]
It for that situations when you need to upload shell

**Comment by s0undt3ch** [comment]
Aside from screen, which really isn't a way since it defeats the single binary purpose, is there a solution?
