### ISSUE TITLE
Using custom launcher causes generated PE to crash?

### ISSUE THREAD

**Issue by mnogostuff** [n1nj4sec/pupy#125]
I don't have a lot of experience writing issues, so please bear with me here.

I was trying to write my own network launcher in `pupy/network/lib/launchers/` and found that each time I generated a PE which used the launcher, the pupy instance would do nothing and immediately crash. When I generated a python file and ran it in both windows and linux, my custom launcher would work as intended.

I simplified my process even further by adding a test launcher, to `pupy/network/conf.py` which just linked to the existing `connect` launcher.

`launchers["test"]=ConnectLauncher` is how I wrote this. I have changed absolutely nothing about the functionality of ConnectLauncher, yet it causes EXEs to fail when test is specified as the launcher. It works perfectly fine for generated python files in windows.

I tried modifying `LauncherArgumentParser(prog="connect"` to
`LauncherArgumentParser(prog="test"` in `pupy/network/lib/launchers/connect.py:13` and it made absolutely no difference. This is the only place where I can find "connect" being referred to in a source file.

I do not understand why this is happening and don't know if it's just my mistake or not.

https://github.com/mnogostuff/pupy/blob/218845459a9144c68f9211a74a109a42482c7cbb/pupy/network/conf.py is the only change I've made, which I have made into an executable with `python pupygen.py -o test.exe -f exe_x86 test --host="127.0.0.1:1234`, when run with `python pupygen.py -o test.exe -f exe_x86 connect --host="127.0.0.1:1234`, which is the exact same code but does not refer to the dummy launcher, it works flawlessly.

**Comment by n1nj4sec** [comment]
You need to recompile the windows templates if you changed the launcher. If
you try to generate a pure python payload with pupygen -f py it should work

**Comment by mnogostuff** [comment]
That's perfect! Thank you, I was pretty sure it was my mistake.
