### ISSUE TITLE
Add buildozer.spec on android_sources 

### ISSUE THREAD

**Issue by technoabh** [n1nj4sec/pupy#128]
Kindly attach buildozer.spec file on client/android_sources for reference.

**Comment by n1nj4sec** [comment]
I used the default buildozer.spec generated with build.sh with perhaps some additional permissions. It all depends what you want to do ;)

**Comment by n1nj4sec** [comment]
cf https://github.com/n1nj4sec/pupy/wiki/Build-payloads-from-sources#android-apk-
