### ISSUE TITLE
updates

### ISSUE THREAD

**Issue by rav3n-80-bl4ck** [n1nj4sec/pupy#130]
hi, would it be possible to add an update feature instead of cloning the repo everytime?

Thanks in adv.

**Comment by n1nj4sec** [comment]
git pull ?

**Comment by rav3n-80-bl4ck** [comment]
Thanks for answering. i meant git clone ..

**Comment by n1nj4sec** [comment]
But the command you are looking for is git pull, isn't it ?

**Comment by rav3n-80-bl4ck** [comment]
actually no, but never mind .. Thx anyway
