### ISSUE TITLE
ctype error in x64 systems

### ISSUE THREAD

**Issue by marcovillar** [n1nj4sec/pupy#135]
recently i started having problem with the keylogger when testing with x64 system
i get this error:
[*] Session 2 opened (192.168.X.X:443 <- 0.0.0.0:0)
>> Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
  File "<memimport>\pupwinutils\keylogger.py", line 125, in run
  File "<memimport>\pupwinutils\keylogger.py", line 143, in install_hook
ArgumentError: argument 3: <type 'exceptions.OverflowError'>: long int too long to convert

[*] on_connect: gather/keylogger start

I tried to read about it online but the only thing i found was the ctype error in casting long int
as anyone else have the same problem?

**Comment by n1nj4sec** [comment]
exact, the problem is on Windows 10 in a x64 process. As a workaround you can migrate to a x86 process : 
```
run migrate -c 'C:\Windows\SysWOW64\notepad.exe'
```

**Comment by marcovillar** [comment]
Windows 2008 r2 as well, btw when i migrated to another x64 process (explorer.exe)
it worked fine as well which i find very strange.
