### ISSUE TITLE
SSL_BIND_KEY SSL_BIND_CERT not found

### ISSUE THREAD

**Issue by dromero1452** [n1nj4sec/pupy#139]
No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2043-06-10) or after any future revocation date.

**Comment by n1nj4sec** [comment]
Nevermind, 2042 is the end of the world. What is the relation with the issue's title ?

**Comment by dromero1452** [comment]
When compiling the apk I get the preceding error, I trying gen new keys,
follow installation to a tee, although I finally figured out the issue, btw
a fantastic tool, just possibly needs a more in depth tutorial, once I get
a little free time I could perhaps help with writing this up and submit it
to you for review

**Comment by n1nj4sec** [comment]
Yes, of course you are welcome if you want to document stuff in the wiki :-)
