### ISSUE TITLE
suggestion: ducky script generator

### ISSUE THREAD

**Issue by vay3t** [n1nj4sec/pupy#143]
a good idea is ducky script by pupy's backdoors.
reference: https://github.com/PowerShellEmpire/Empire/blob/master/lib/stagers/ducky.py
expand the attack vector for rubber ducky and nethunter

note: I confirm that pupy works fine in raspbian

**Comment by quentinhardy** [comment]
Good idea. Implemented here https://github.com/n1nj4sec/pupy/pull/151. Only for Windows for the moment.
