### ISSUE TITLE
Can't generate payload missing payload templates? 

### ISSUE THREAD

**Issue by coolbotic** [n1nj4sec/pupy#158]
When I am running this command 
`./pupygen.py -f exe_x86 -o hacker.exe connect --host 192.168.1.213:444`

I get this message error
`Traceback (most recent call last):
  File "./pupygen.py", line 317, in <module>
    binary=get_edit_pupyx86_exe(conf)
  File "./pupygen.py", line 27, in get_edit_pupyx86_exe
    return get_edit_binary(os.path.join("payload_templates","pupyx86.exe"), conf)
  File "./pupygen.py", line 35, in get_edit_binary
    with open(path, 'rb') as f:
IOError: [Errno 2] No such file or directory: 'payload_templates/pupyx86.exe'`

What am i doing wrong? Any help ?

**Comment by n1nj4sec** [comment]
cf issue #145
