### ISSUE TITLE
Module gather/check_vm empty output

### ISSUE THREAD

**Issue by void-in** [n1nj4sec/pupy#159]
Hi

First of all congrats on a wonderful project. This is my first time working with pupy so wanted to check that I am understanding all the parts correctly. The module gather/check_vm when run in the current form returns an empty string if no vm is detected.
```
>> run gather/check_vm
[+]
```
It would make more sense if an output like "No virtual machine detected" is outputted instead.
```
>> run gather/check_vm
[+] No virtual machine detected
```
Just need an if else statement like:
```python
    def run(self, args):
        content = open(os.path.join(ROOT, "external", "Nishang", "Check-VM.ps1"), 'r').read()
        function = 'Check-VM'
        output = execute_powershell_script(self, content, function)
        if len(output) > 0:
                self.success("%s" % output)
        else:
                self.success("No virtual machine detected")
```
If the above patch is appropriate, I will generate a PR.

Thanks

**Comment by n1nj4sec** [comment]
thx
