### ISSUE TITLE
Horrible performance

### ISSUE THREAD

**Issue by alxchk** [n1nj4sec/pupy#161]
Very unlikely that is something new, but..
On channels with high latency pupy almost unusable. Pressing button in interactive shell takes about 1 second to actually draw letter. Without measurments, I'ts ~5-10 times slower than using raw tcp socket (without RPYC). So.. I don't know what to do.

**Comment by n1nj4sec** [comment]
I think what you are observing is the difference between a line buffered shell where the socket is written and flushed when you press enter and a true interactive shell like in pupy or ssh. Did you try to use ssh with this host ? It is probably as slow as pupy's interactive shell. 
You should avoid using an interactive shell when you don't have a correct network connectivity and use the shell_exec module instead. 
You can also try the interactive_shell -T option, I haven't tried if it will do the trick as I don't know if rpyc's stdin redirection is line buffered or not but I suspect it is.
If not, you will have to write a half interactive shell module could by using raw_input on the server's pupysh side to issue commands only when a complete shell command is issued by the user (when enter is pressed and raw_input return), however the shell won't be able to use interactive programs like vi, less, man, etc...

**Comment by alxchk** [comment]
I check difference with tsh shell (there are a lot of modifications, just for example - https://github.com/creaktive/tsh) and pupy's interactive shell (btw, there is mistake there with allocating terminal - https://github.com/alxchk/pupy/commit/49ae6024e89fa553538e0378418864b44c42a7aa, line 64). Tsh is dumb, so performance is ultimate. As far as I see, there is next situation.

1. I press button in shell 1 time
2. I press button in shell 2 time
3. pupy catches 1 press
4. pupy sends 1 press to client
5. client sends 1 press to tty
6. tty draws output
7. client reads output 
8. client sends output using rpyc callback
9. pupy reads output
10. pupy draws output to tty
11. pupy catches 2 press
...

I'm not really sure things working and how rpyc works over network, but it really feels like issues with rpyc communication.

**Comment by n1nj4sec** [comment]
It works like this after your patch, but before your patch, the keys were sent over the network by block (not one by one) if multiple keys were typed simulteanously and self.ps.wirte (which call rpyc and write on the socket) were only called the minimum of time (when there is no more data to read in sys.stdin)
https://github.com/alxchk/pupy/commit/49ae6024e89fa553538e0378418864b44c42a7aa#diff-58551c742be8993c81035ffae7f0fdd1L89

**Comment by alxchk** [comment]
Yes, you right.
Still not so smooth like with tsh, but at least usable
