### ISSUE TITLE
Pupy hangs forever when command for execution also hangs

### ISSUE THREAD

**Issue by alxchk** [n1nj4sec/pupy#163]
So, currently I try to use pupy with targets which are quite far and which are quite laggy. The main problem is that after things like this

```
>> ERROR:root:timeout occured !
ERROR:root:Traceback (most recent call last):
  File "pupy/pupylib/PupyService.py", line 67, in on_connect
    self.pupy_srv.add_client(self)
  File "pupy/pupylib/PupyServer.py", line 352, in add_client
    addr = conn.modules['pupy'].get_connect_back_host()
  File "python2.7/site-packages/rpyc/core/netref.py", line 196, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "python2.7/site-packages/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "python2.7/site-packages/rpyc/core/protocol.py", line 438, in sync_request
    self.serve(0.1)
  File "python2.7/site-packages/rpyc/core/protocol.py", line 387, in serve
    data = self._recv(timeout, wait_for_lock = True)
  File "python2.7/site-packages/rpyc/core/protocol.py", line 344, in _recv
    if self._channel.poll(timeout):
  File "python2.7/site-packages/rpyc/core/channel.py", line 43, in poll
    return self.stream.poll(timeout)
  File "pupy/network/lib/streams/PupySocketStream.py", line 74, in poll
    return len(self.upstream)>0 or self.sock_poll(timeout)
  File "pupy/network/lib/streams/PupySocketStream.py", line 79, in sock_poll
    self._read()
  File "pupy/network/lib/streams/PupySocketStream.py", line 58, in _read
    buf = self.sock.recv(self.MAX_IO_CHUNK)
  File "python2.7/site-packages/rpyc/core/stream.py", line 76, in __getattr__
    raise EOFError("stream has been closed")
EOFError: stream has been closed
```
connection silently dies and client doesn't call back any more. But it stays alive in memory.

**Comment by n1nj4sec** [comment]
try to change the timeout (default is 10s) in  pp.py and  network/lib/servers.py.
I just simulated a huge network latency and incrementing the timeout to 60s works in my case but I couldn't reproduce the fact that the client doesn't call back anymore
```
$ tc qdisc add dev lo root netem delay 600ms 60ms
$ ping 127.0.0.1
PING 127.0.0.1 (127.0.0.1) 56(84) bytes of data.
64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=1225 ms
64 bytes from 127.0.0.1: icmp_seq=2 ttl=64 time=1286 ms
64 bytes from 127.0.0.1: icmp_seq=3 ttl=64 time=1236 ms
```

**Comment by alxchk** [comment]
So, here is simple test case

1. Windows client
2. exec "start /B C:\\temp\\lolwut.exe"
(At this moment nice dialog appears on the other end, that we don't have this executable, blablabla, but we don't see it here)
3. WTF?! ^C^C^C^C^C
4. ^C[!] interrupting job ... (please wait)
[*] Session 4 closed
>> [!] job interrupted
5. Silence

**Comment by alxchk** [comment]
Well, looks like it's two different problems, which leads to the same result. I'll play a bit more with netem, but this behavior with hanged program should be resolved somehow I think

**Comment by n1nj4sec** [comment]
The problem is that python2.7 Popen doesn't have a timeout argument like in python3. We could add a timeout manually and kill the process if it takes too long.
To avoid your command from hanging, don't use start, that will make a blocking popup, just start your exe directly
```
>> exec 'C:\temp\lolwut.exe'
Le chemin d'accès spécifié est introuvable.
```

**Comment by alxchk** [comment]
I think two things should be done.
1. Killing any foreground client's job with ^C in pupysh
2. Adding possibility to execute command in background as Job using Popen. Job interface is ok for that - you can get output or terminate process - same as Popen interface. To not be blocked Popen.poll can be used

**Comment by alxchk** [comment]
https://github.com/alxchk/pupy/commit/d6f04b91688f57e8dab472f663d5aa4cb12b5cd5

Pupy need some API to make tasks interactive/non-interactive on request. Like ^Z in shell.

**Comment by n1nj4sec** [comment]
There is no ^Z yet, but you can use run --bg yourmodule to make it run as a job

**Comment by alxchk** [comment]
Something wrong with popen. What ever I try I couldn't write fully reliable code.
I even tried next:
on pp.py side there is thread, which in blocking mode reads stdout, and places to queue. Then main pp.py thread read with get_nowait() data from there. Even in that case when stdout reader thread blocks, pp.py doesn't receive commands from pupy shell. In pupy shell I see that it tries to make remote call of termination thread, but it's not called until program unblocks.

**Comment by alxchk** [comment]
Well, I'm just an idiot

**Comment by alxchk** [comment]
So, here is my final version. If you'll have time check it somewhere:

https://github.com/alxchk/pupy/commit/e1719b6c3b68117f814e8766286ac1735a1ea1d1

**Comment by alxchk** [comment]
And finally last part of the puzzle:
https://github.com/alxchk/pupy/commit/720e85a156a4c64606460d2838b83fd0c469530b
