### ISSUE TITLE
make ARCH=x86 issue

### ISSUE THREAD

**Issue by dimpol** [n1nj4sec/pupy#167]
Output error: 
/out:..\..\pupy\payload_templates\pupyx86.exe
/subsystem:windows
/ENTRY:mainCRTStartup
main_exe.obj
_memimporter.obj
MyLoadLibrary.obj
Python-dynload.obj
pupy_load.obj
pupy.obj
base_inject.obj
resources_bootloader_pyc.obj
resources_python27_dll.obj
MemoryModule.obj
resources_library_compressed_string_txt.obj
actctx.obj
list.obj
thread.obj
remote_thread.obj
LoadLibraryR.obj
resources_msvcr90_dll.obj
base_inject.obj : error LNK2019: unresolved external symbol __imp__VirtualAlloc@20 referenced in function _inject_via_remotethread_wow64
base_inject.obj : error LNK2019: unresolved external symbol __imp__VirtualFree@16 referenced in function _inject_via_remotethread_wow64
base_inject.obj : error LNK2019: unresolved external symbol __imp__VirtualAllocEx@24 referenced in function _inject_via_apcthread
base_inject.obj : error LNK2019: unresolved external symbol __imp__VirtualQueryEx@20 referenced in function _inject_via_apcthread
base_inject.obj : error LNK2019: unresolved external symbol __imp__WriteProcessMemory@24 referenced in function _inject_via_apcthread
..\..\pupy\payload_templates\pupyx86.exe : fatal error LNK1120: 5 unresolved externals
Makefile:70: recipe for target '..\..\pupy\payload_templates\pupyx86.exe' failed
mingw32-make: *** [..\..\pupy\payload_templates\pupyx86.exe] Error 2

Any ideas?
I have set the correct PATH variables and even run vcvars32 on the sources directory.

python 2.7 x86 , pywin32 x86 and everything just like the wiki says.

windows 10 x64 host

**Comment by n1nj4sec** [comment]
I see you use mingw32-make and if you read the wiki it says GNU make

**Comment by dimpol** [comment]
Yeap wrong output I have also tried with gnuwin32.sourceforge.net/packages/make.htm and www.equation.com/servlet/equation.cmd?fa=make (GNU make for windows) with the same results. I must be doing something really stupid but I don't know what exactly I am screwing up....

**Comment by dimpol** [comment]
It was a wrong msvcr90.dll..you can close this. Sorry for the bother
