### ISSUE TITLE
git submodule update --depth 1 error

### ISSUE THREAD

**Issue by dimpol** [n1nj4sec/pupy#169]
Same results on both windows 10 and kali linux

c:\Users\x0rc1\Downloads\pupy>git submodule update --depth 1
Cloning into 'C:/Users/x0rc1/Downloads/pupy/client/sources-linux/linux-inject'...
Cloning into 'C:/Users/x0rc1/Downloads/pupy/pupy/external/LaZagne'...
Cloning into 'C:/Users/x0rc1/Downloads/pupy/pupy/external/impacket'...
Cloning into 'C:/Users/x0rc1/Downloads/pupy/pupy/packages/src/scapy'...
Cloning into 'C:/Users/x0rc1/Downloads/pupy/pupy/payload_templates'...
Submodule path 'client/sources-linux/linux-inject': checked out 'ce6d7e4b1d6c06b2fb36548e23d62685a1f91209'
Submodule path 'pupy/external/LaZagne': checked out '0c7268c7cbd47c556d57404493cb32786417b676'
error: no such remote ref 8af9271f656b6d420466f8bcaec8b81253388340
Fetched in submodule path 'pupy/external/impacket', but it did not contain 8af9271f656b6d420466f8bcaec8b81253388340. Direct fetching of that commit failed.

**Comment by n1nj4sec** [comment]
yep, try without the --depth 1. I added this option for the payload_templates to avoid downloading the full bin diff which can be quite big, but it break other packages when the commit is not on the HEAD. The option it's not mandatory if you are patient ;)

**Comment by n1nj4sec** [comment]
wiki updated

**Comment by void-in** [comment]
@n1nj4sec Since you are in the process of updating the wiki, I think it should be mentioned in the installation that the user need to git add the upstream repository as well. Since there is no upstream added by default, we can't git fetch the latest changes. Thoughts?
