### ISSUE TITLE
Permission Issue?? Errno 13 

### ISSUE THREAD

**Issue by BIGNASTY202** [n1nj4sec/pupy#178]
Hi i need some help
Ive been trying to get pupy to generate a apk for the past couple hours and i have had no luck just get this error :( ------------->

---------------------------------------------------------------------------------------------------------------------
asdasda@asdasd:~/Desktop/pupy/pupy$ ./pupygen.py -f apk connect  --host 192.168.2.98 /home/badbytes/Desktop/test.apk
[+] generating payload ...
[+] packaging the apk ... (can take 10-20 seconds)
Traceback (most recent call last):
  File "./pupygen.py", line 389, in <module>
    get_edit_apk(os.path.join(ROOT, "payload_templates","pupy.apk"), outpath, conf)
  File "./pupygen.py", line 192, in get_edit_apk
    updateTar(os.path.join(tempdir,"assets/private.mp3"), "service/pp.pyo", os.path.join(tempdir,"pp.pyo"))
  File "./pupygen.py", line 172, in updateTar
    shutil.rmtree(tempdir)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 250, in rmtree
    os.remove(fullname)
OSError: [Errno 13] Permission denied: '/tmp/tmp_pupy_LqVZsO/lib/python2.7'
-----------------------------------------------------------------------------------------------------------------

If any one can help me that would be awesome!!!
p.s hope i gave enough info for maybe fix or something along those lines!

**Comment by n1nj4sec** [comment]
Yep, I was on kali when I compiled the apk, so you need root to untar.
Another solution is to recompile the apk from sources

**Comment by BIGNASTY202** [comment]
Thank you very much for quick reply appreciate it :)

**Comment by BIGNASTY202** [comment]
The fix i used for this was to do these simple steps:
1. sudo -i
2. paste the install in root terminal
git clone https://github.com/n1nj4sec/pupy.git pupy
cd pupy
git submodule update --init --depth 1 pupy/payload_templates
git submodule init
git submodule update
pip install -r requirements.txt
3.And if it worked then you can now use pupygen as sudo or in the root terminal 
hope this helped people with the permission problem like me!
