### ISSUE TITLE
'run persistence' UnboundLocalError

### ISSUE THREAD

**Issue by kilbyjmichael** [n1nj4sec/pupy#18]
>> run persistence -m registry
#>#>  PupyClient(id=1, user=Andrew, hostname=AndrewPC, platform=Windows)  <#<#
[%] generating exe ...
[%] uploading to C:\Users\Andrew\AppData\Local\Temp\gnhyiyai.exe ...
[+] upload successful
[%] adding to registry ...
[%] registry key added
[+] persistence added !

>>#>#>  PupyClient(id=5, user=mkilby, hostname=OU146-11, platform=Windows)  <#<#
[%] generating exe ...
[%] uploading to C:\Users\mkilby\AppData\Local\Temp\pfvhscx.exe ...
[+] upload successful
[%] adding to registry ...
[-] local variable 'aKey' referenced before assignment

>>========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "rpyc\core\protocol.pyc", line 305, in _dispatch_request
  File "rpyc\core\protocol.pyc", line 535, in _handle_call
  File "<string>", line 33, in add_registry_startup
UnboundLocalError: local variable 'aKey' referenced before assignment

Persistence runs correctly when two computers are connected, however, the last one always comes back with an UnboundLocalError. If one computer is connected, it comes back with UnboundLocalError.

**Comment by n1nj4sec** [comment]
There was a typo error, it should be fixed now. Anyway, the persistence module is really basic for now, it was written in 10 minutes and will be improved in the future
