### ISSUE TITLE
weard error on victim machine

### ISSUE THREAD

**Issue by leoxnidas** [n1nj4sec/pupy#180]
Error while loading package yaml.cyaml (py) : No module named _yaml

any suggestion?

**Comment by asyazwan** [comment]
Have you tried installing pyyaml package?

**Comment by leoxnidas** [comment]
on the victim machine??

**Comment by asyazwan** [comment]
That would be pointless... Try out your generated payload or build it yourself and ensure pyyaml package is included. That's what I'd do. I remember getting this problem too when trying out of the box.

**Comment by n1nj4sec** [comment]
it's a warning
