### ISSUE TITLE
AttributeError: 'ReverseSlaveService' object has no attribute 'exposed_json_dumps'

### ISSUE THREAD

**Issue by goshawkwarm** [n1nj4sec/pupy#181]
Hello,

I'm using pupy since the first versions, I've never had problems, until last update.

After update it, each time a client tried to connect, I get this error:

`
[*] Server started on port 11111 with transport ssl
>> INFO:PUPY/11111:server started on [::]:11111
INFO:PUPY/11111:accepted ::ffff:190.209.122.111:1782
ERROR:root:Traceback (most recent call last):
  File "/opt/pupy/pupy/pupylib/PupyService.py", line 67, in on_connect
    self.pupy_srv.add_client(self)
  File "/opt/pupy/pupy/pupylib/PupyServer.py", line 346, in add_client
    "launcher_args" : obtain(conn.get_infos("launcher_args")),
  File "/opt/pupy/pupy/pupylib/utils/rpyc_utils.py", line 32, in obtain
    return safe_obtain(proxy)
  File "/opt/pupy/pupy/pupylib/utils/rpyc_utils.py", line 29, in safe_obtain
    return json.loads(conn.root.json_dumps(proxy)) # should prevent any code execution
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 150, in __getattr__
    return syncreq(self, consts.HANDLE_GETATTR, name)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 441, in sync_request
    raise obj
AttributeError: 'ReverseSlaveService' object has no attribute 'exposed_json_dumps'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "rpyc\core\protocol.pyc", line 305, in _dispatch_request
  File "rpyc\core\protocol.pyc", line 541, in _handle_getattr
  File "rpyc\core\protocol.pyc", line 507, in _access_attr
  File "rpyc\core\service.pyc", line 69, in _rpyc_getattr
AttributeError: 'ReverseSlaveService' object has no attribute 'exposed_json_dumps'`

All dependencies are met:

`#178  pip install -r requirements.txt
Requirement already satisfied (use --upgrade to upgrade): rpyc in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): pycrypto in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): pefile in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): pyyaml in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): image in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): rsa in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): plumbum in /usr/local/lib/python2.7/dist-packages (from rpyc->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): future in /usr/local/lib/python2.7/dist-packages (from pefile->-r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): pillow in /usr/local/lib/python2.7/dist-packages (from image->-r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): django in /usr/local/lib/python2.7/dist-packages (from image->-r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.3 in /usr/lib/python2.7/dist-packages (from rsa->-r requirements.txt (line 6))
#`

I'm running the server on Ubuntu 16.04.1 LTS. You have any idea what might be happening?

Thanks

Best,

**Comment by n1nj4sec** [comment]
You need to generate the payloads again using the last templates, if you
use an old payload generated by an old version, it won't work with the last
version of the server

**Comment by goshawkwarm** [comment]
Ah ok, thanks.

**Comment by goshawkwarm** [comment]
So, I need a old version, to reconnect with my old clients first, right ?

**Comment by n1nj4sec** [comment]
yup
