### ISSUE TITLE
pupygen.py error

### ISSUE THREAD

**Issue by volt72** [n1nj4sec/pupy#192]
Hello i seem to be having issues creating payloads for android, osx, and linux. This is the output i receive, any help would be greatly appreciated thanks.

volt72@killadelph:~/pupy/pupy$ ./pupygen.py -f py connect --transport ssl --host 192.168.1.1
[+] generating payload ...
Traceback (most recent call last):
  File "./pupygen.py", line 396, in <module>
    packed_payload=pack_py_payload(get_raw_conf(conf))
  File "/home/volt72/pupy/pupy/pupylib/payloads/py_oneliner.py", line 41, in pack_py_payload
    modules_dic=gen_package_pickled_dic(rsa.__path__[0],"rsa")
  File "/home/volt72/pupy/pupy/pupylib/payloads/python_packer.py", line 45, in gen_package_pickled_dic
    raise NameError("path %s not found"%path)
NameError: path /usr/local/lib/python2.7/dist-packages/rsa-3.4.2-py2.7.egg/rsa not found
volt72@killadelph:~/pupy/pupy$

**Comment by n1nj4sec** [comment]
don't use python eggs, it's not supported

**Comment by n1nj4sec** [comment]
unzip rsa-3.4.2-py2.7.egg to /usr/local/lib/python2.7/dist-packages/rsa
