### ISSUE TITLE
OSX Pupygen.py failing due to rpyc import

### ISSUE THREAD

**Issue by ArThoX** [n1nj4sec/pupy#197]
```
./pupygen.py 
Traceback (most recent call last):
  File "./pupygen.py", line 7, in <module>
    from pupylib.utils.network import get_local_ip
  File "/Users/serveurachat/Downloads/pupy/pupy/pupylib/__init__.py", line 4, in <module>
    from utils.rpyc_utils import *
  File "/Users/serveurachat/Downloads/pupy/pupy/pupylib/utils/rpyc_utils.py", line 19, in <module>
    from rpyc.utils.helpers import restricted
ImportError: No module named rpyc.utils.helpers
```

Followed installation instructions. Pupygen seems to fail due to restricted import of rpyc ? Any Idea why ?

Note: deps are ok ` pip install -r requirements.txt --upgrade` without error.

**Comment by n1nj4sec** [comment]
the restricted function exists in the last rpyc package, so try that https://github.com/tomerfiliba/rpyc/blob/master/rpyc/utils/helpers.py#L48

**Comment by ArThoX** [comment]
```
$ python -c "import rpyc"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named rpyc
```

**Comment by ArThoX** [comment]
Now

```
./pupygen.py -f py connect --transport ssl --host 192.168.150.64
WARNING:root:pycrypto not available, using pure python libraries (slower)
WARNING:root:pycrypto not available, using pure python libraries (slower)
WARNING:root:Could not load transport obfs3 : No module named Crypto.Cipher. Transport disabled
WARNING:root:Could not load transport scramblesuit : No module named Crypto.Hash.SHA256. Transport disabled
[+] generating payload ...
Traceback (most recent call last):
  File "./pupygen.py", line 396, in <module>
    packed_payload=pack_py_payload(get_raw_conf(conf))
  File "/Users/serveurachat/Downloads/pupy/pupy/pupylib/payloads/py_oneliner.py", line 38, in pack_py_payload
    modules_dic=gen_package_pickled_dic(pyasn1.__path__[0],"pyasn1")
  File "/Users/serveurachat/Downloads/pupy/pupy/pupylib/payloads/python_packer.py", line 45, in gen_package_pickled_dic
    raise NameError("path %s not found"%path)
NameError: path /Library/Python/2.7/site-packages/pyasn1-0.1.9-py2.7.egg/pyasn1 not found
```

**Comment by quentinhardy** [comment]
You have to install rpyc...

You can install pip on your system (perhaps see [http://softwaretester.info/install-and-upgrade-pip-on-mac-os-x/](http://softwaretester.info/install-and-upgrade-pip-on-mac-os-x/)) or [http://stackoverflow.com/questions/17271319/installing-pip-on-mac-os-x](http://stackoverflow.com/questions/17271319/installing-pip-on-mac-os-x)
```
sudo easy_install pip
```
and after install your python modules (e.g. rpyc)
```
sudo pip install rpyc
```

These python modules have to be installed (See _requirements.txt_):
- rpyc
- pycrypto
- pefile 
- pyyaml
- image
- rsa
- netaddr

See [https://github.com/n1nj4sec/pupy/wiki/Installation](https://github.com/n1nj4sec/pupy/wiki/Installation) for pupy installation.

**Comment by quentinhardy** [comment]
For installing _pyasn1_ (missing module on your OSX), you can use the following command:
```
pip install pyasn1
```

**Comment by ArThoX** [comment]
@quentinhardy Thanks for your answers; but I have already done that.

I will try to clean my pip/python and reinstall..

**Comment by ArThoX** [comment]
Same issue, 
`NameError: path /Library/Python/2.7/site-packages/pyasn1-0.1.9-py2.7.egg/pyasn1 not found`

PS: `/Library/Python/2.7/site-packages/pyasn1-0.1.9-py2.7.egg` exists on my hd.

**Comment by n1nj4sec** [comment]
don't use eggs, eggs are not supported, so unzip them

**Comment by ArThoX** [comment]
I must say I have no idea how to make it work.
Egg unzipped, but the .egg error still happens.

**Comment by n1nj4sec** [comment]
unzip and obviously remove the .egg

**Comment by ArThoX** [comment]
Such obviousness :D (I didn't know what was the use of an egg yesterday).

Thanks for the help.

**Comment by Aspect9** [comment]
such installing dependencies - nammit
