### ISSUE TITLE
Impossible connect Android

### ISSUE THREAD

**Issue by enjutomojamutote** [n1nj4sec/pupy#203]
Hi

I tried to connect an android clients to my Pupy server but I couldn't. I have the terminal rooted so I could see the netstat and see how the android was making a sys-sen in the port I specified. But at the pupy server nothing happens. I tried with several wifis, public ip, and differents ports. 

I have root's rights, i use xubuntu 16.04 and I just don't know what else i can do. Can you help me? Thanks!

My ifconfig:

wlp4s0f0  
          inet addr:10.0.0.5  Bcast:10.0.0.255  Mask:255.255.255.0
          inet6 addr: fe80::7817:6ea5:e1ec:56e3/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:271103 errors:0 dropped:0 overruns:0 frame:0
          TX packets:229331 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:302910065 (302.9 MB)  TX bytes:76926645 (76.9 MB)

My " netstat -anpt | grep LISTEN" command

tcp        0      0 10.0.0.5:4444           0.0.0.0:*               LISTEN      -               
tcp        0      0 0.0.0.0:17500           0.0.0.0:*               LISTEN      2018/dropbox    
tcp        0      0 0.0.0.0:445             0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:17600         0.0.0.0:*               LISTEN      2018/dropbox    
tcp        0      0 127.0.0.1:17603         0.0.0.0:*               LISTEN      2018/dropbox    
tcp        0      0 0.0.0.0:139             0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:5939          0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.1.1:53            0.0.0.0:*               LISTEN      -               
tcp6       0      0 :::17500                :::*                    LISTEN      2018/dropbox    
tcp6       0      0 :::445                  :::*                    LISTEN      -               
tcp6       0      0 127.0.0.1:8005          :::*                    LISTEN      -               
tcp6       0      0 :::139                  :::*                    LISTEN      -      

My pupy.conf:

[pupyd]
#listen on all interfaces by default
address = 10.0.0.5
port = 4444
ipv6 = true
keyfile = crypto/server.pem
certfile = crypto/cert.pem

And part of the error I get:

  File "/usr/local/lib/python2.7/dist-packages/rpyc/utils/server.py", line 78, in __init__
    self.listener.bind((hostname, port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 99] Cannot assign requested address

**Comment by n1nj4sec** [comment]
duplicate issue #211
