### ISSUE TITLE
"Module not found" error in port_scan module

### ISSUE THREAD

**Issue by quentinhardy** [n1nj4sec/pupy#207]
Hello,

When I would like to use _port_scan_ module on wind7_x64 through _ps1_oneliner_ payload, I have an error: "_(126, The specified module has been not found)_". 

There is no information about this module in the error or stack trace.
I have tried to import gzip module and others but always the same error. I think the error comes from an import in _scapy_ module, but I don't know which one...

**Comment by n1nj4sec** [comment]
Yes, I just fixed it, NPcap changed their install repository from windows\system32 to windows\system32\NPcap and winpcapy couldn't find Packet.dll and wpcap.dll on the system

**Comment by hsluoyz** [comment]
Hi. Npcap will install into ``C:\Windows\System32\Npcap``if ``Install Npcap in WinPcap API-compatible Mode`` is not chosen in the installer, which is by default. You can see [this docs](https://htmlpreview.github.io/?https://github.com/nmap/npcap/blob/master/docs/npcap-guide-wrapper.html#npcap-feature-native) about how to use Npcap first when Npcap and WinPcap coexist.
