### ISSUE TITLE
pupyx86.so is missing?

### ISSUE THREAD

**Issue by Vanciel** [n1nj4sec/pupy#213]
I want to run my backdoor in persistence mode 
but it gives me this error
`[Errno 2] No such file or directory: '/root/pupy/payload_templates/pupyx86.so'`
it seems the file is missing, I ran the git submodule before, but it doesn't download the pupyx86.so file

```
root@kali:# ls -la
total 47217
-rwxrwxrwx 1 root root 8974866 Oct 22 15:01 pupy.apk
-rwxrwxrwx 1 root root 8075264 Oct 22 15:01 pupyx64.dll
-rwxrwxrwx 1 root root 8068608 Oct 22 15:01 pupyx64.exe
-rwxrwxrwx 1 root root 4751760 Oct 22 15:01 pupyx64.lin
-rwxrwxrwx 1 root root 4756624 Oct 22 15:01 pupyx64.so
-rwxrwxrwx 1 root root 6938624 Oct 22 15:01 pupyx86.dll
-rwxrwxrwx 1 root root 6914560 Oct 22 15:01 pupyx86.exe
-rwxrwxrwx 1 root root      47 Oct 22 15:01 README.md

```

**Comment by quentinhardy** [comment]
You have true. 
The _pupyx86.so_ is missing, as _pupyx86.lin_ in [https://github.com/n1nj4sec/pupy-binaries](https://github.com/n1nj4sec/pupy-binaries).

**Comment by n1nj4sec** [comment]
yup, I did not took the time to install an old 32bit linux distrib to pre-compile the binaries. In the meantime you can compile them yourself or wait an undefined amount of time ;)

**Comment by n1nj4sec** [comment]
duplicate #206
