### ISSUE TITLE
I cannot make it work

### ISSUE THREAD

**Issue by enjutomojamutote** [n1nj4sec/pupy#216]
Hi

I have been trying to make it work but it was imposible. 

I have tried the server in a xubuntu 16.04 and with a wifislax with the same result. The clients with I tried were several android devices, and several notebook. Also I tried several networks (if the problem were with the router) but It didn't work.

So I realize the problem its with the server or the way I generate Payload (for android ./pupygen.py -f apk connect --host LOCALIP:PORT and for linux: ./pupygen.py -f py connect --transport ssl --host LOCALIP:PORT

 If I run the server and run the client in the same machine it works obviusly. But if I run the server and run the client in other device (android, computer) using the local ip it cant reach the server. 

If I run the server without modifying pupy.conf uncomment address. It runs apparently without a problem: INFO:PUPY/443 SERVER STARTED ON [::]:443 . If I uncomment the addres from pupy.conf it returns error: [Errno 99] Cannot assign requested address . So at this point I replace the addres to 0.0.0.0 127.0.0.1 or my localip. And with several ports. And none of these choices worked. The py payload returns to me :  No route to host and tried cleaning iptables, and the android apk I can see how it tries to connect with the local ip but it rejects it because in the netstat appears syn_sent.

I'm pretty stuck here. Can anybody help me? Which OS you use with?

**Comment by n1nj4sec** [comment]
duplicate issue #211

**Comment by enjutomojamutote** [comment]
Duplicated?
