### ISSUE TITLE
AV Evasion

### ISSUE THREAD

**Issue by Xx-KaAzZ-xX** [n1nj4sec/pupy#218]
Hi I tried many tools for AV Evasion once the exe file is generated ( Veil , Msfvenom , Pecloack.py , Shellter ) and I can't make it working so I would like to know if someone suceed to encrypt or obfuscate in one way the payload.

**Comment by quentinhardy** [comment]
Hi. 
I think the best solution (time/result) is to use Powershell output (script or oneliner) of Pupy when your target is WIndows.
See [https://github.com/n1nj4sec/pupy/issues/168](https://github.com/n1nj4sec/pupy/issues/168) about this same subject. See also these old issues:
- [https://github.com/n1nj4sec/pupy/issues/41](https://github.com/n1nj4sec/pupy/issues/41)
- [https://github.com/n1nj4sec/pupy/issues/34](https://github.com/n1nj4sec/pupy/issues/34)

**Comment by alxchk** [comment]
https://bitbucket.org/alxchk/ps1toexe -- horrible, but may work :D

**Comment by Xx-KaAzZ-xX** [comment]
Hi guys , sry for the long time replying.
I'm quite surprising for the ps1toexe script , it is written in bash but I have to run it in a Windows Environment if I understand well ?
