### ISSUE TITLE
Android service on bootup

### ISSUE THREAD

**Issue by MrVu** [n1nj4sec/pupy#223]
I'm trying to figure out why my pupy.apk cannot start on bootup. When I checked the AndroidManifest.xml I saw this code 
```
<receiver android:enabled="true" android:name=".MyBroadcastReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"/>
            </intent-filter>
        </receiver>
```
-As I know this code is used to start up kivy on boot but I don't know why It doesn't work as expected
Does any one run into this problem, I tested on 2 phone and It doesn't work

**Comment by asyazwan** [comment]
Check if this helps to answer some of your questions: https://github.com/n1nj4sec/pupy/issues/171

**Comment by MrVu** [comment]
Pupy is working very well, it just can not auto start on bootup. I've just check the logcat and this is what I found
`E/AndroidRuntime( 2253): java.lang.RuntimeException: Unable to instantiate receiver org.pupy.pupy.MyBroadcastReceiver: java.lang.ClassNotFoundException: org.pupy.pupy.MyBroadcastReceiver`

Any one know how to fix this

**Comment by MrVu** [comment]
Fixed:
change .MyBroadcastReceiver into the right package org.egambit.das.MyBroadcastReceiver and every thing work just fine. Pupy will auto start on every reboot
