### ISSUE TITLE
failed to serve client

### ISSUE THREAD

**Issue by belko-letyago** [n1nj4sec/pupy#23]
```
2015-09-28 13:32:43,783 - WARNING - failed to serve client, caught exception : [Errno 104] Connection reset by peer
```
Same pc, win7 x64. Suddenly stopped working.

**Comment by n1nj4sec** [comment]
Do you have some idea on how to reproduce this ? can you give the context of this error ? thank you

**Comment by belko-letyago** [comment]
I will try to reproduce this issue tomorrow on my work pc.
How can I get more information about this error?
