### ISSUE TITLE
Cloning submodule LaZagne fails

### ISSUE THREAD

**Issue by rokups** [n1nj4sec/pupy#238]
> error: no such remote ref adf982740b40628e13b11aeb9b2844ca3b72ab21
> Fetched in submodule path 'pupy/external/LaZagne', but it did not contain adf982740b40628e13b11aeb9b2844ca3b72ab21. Direct fetching of that commit failed.

After running

> git clone --recurse https://github.com/n1nj4sec/pupy.git

**Comment by n1nj4sec** [comment]
follow the wiki
