### ISSUE TITLE
Interactive_shell problems on Android

### ISSUE THREAD

**Issue by MrVu** [n1nj4sec/pupy#244]
Hi every one, I'm working with interactive_shell on Android. I saw some changes on the last commit and there is some problem that make interactive_shell cannot work on Android
![screenshot from 2016-11-24 22-29-16](https://cloud.githubusercontent.com/assets/17061628/20603762/96ba899a-b295-11e6-8627-b32f841ad323.png)
This piece of code is the problem because sys.platform on android is still linux. For now I fixed it by add an other condition with client.is_android() and it work as I expected but I know it's not the best solution. So if some one have the same problems please let me know your solution.

**Comment by n1nj4sec** [comment]
thx, it's fixed it was just a missing symlink to import some dependencies on android
