### ISSUE TITLE
Visual Studio 2015 _snprintf declaration in Python-dynload.h

### ISSUE THREAD

**Issue by i128** [n1nj4sec/pupy#247]
As of VS 14, snprintf is predefined, as such, declaring it in Python-dynload.h causes redefinition conflicts.

![image](https://cloud.githubusercontent.com/assets/2417131/20735020/d04d282c-b662-11e6-8ca5-0ed350b2c0a2.png)

This issue can be avoided either by commenting out the affected code on line 29. 
OR i believe you can change it to the following, but i could be mistaken:
`#if _MSC_VER>=1900`
`#  define STDC99`
`#endif`

Source reference: http://stackoverflow.com/questions/27754492/vs-2015-compiling-cocos2d-x-3-3-error-fatal-error-c1189-error-macro-definiti

**Comment by alxchk** [comment]
What Is the reason to build client using windows/MSVC? Pupysh doesn't work properly there anyway, is it?

**Comment by i128** [comment]
Yup, you're right, was able to compile via build scripts. Closing
