### ISSUE TITLE
Windows 10 x64: failed to poll clients

### ISSUE THREAD

**Issue by deathfantasy** [n1nj4sec/pupy#25]
On killing remote client with `run exit --yes`, I get errors like this on the server:

    WARNING - failed to poll clients, caught exception : (10038, 'An operation was attempted on something that is not a socket')

This might be related to #23 since both exceptions comes from rpyc.

Both server and client run on Windows 10 x64.

**Comment by n1nj4sec** [comment]
I think it is not related. Your error also happens for me when I run the server on windows, I think it comes from the fact that rpyc under linux uses select system calls on sockets but it does not exists on windows, so it have to do polling and it seems some exception is not caught somewhere when a connection is interrupted.

**Comment by 0x27** [comment]
I think [this might help solve it](http://stackoverflow.com/questions/10842428/can-select-be-used-with-files-in-python-under-windows), ran into this error in another project recently. Its to do with how WinSock handles things. Might need to patch rpyc accordingly, or monkeypatch the method in use.

**Comment by deathfantasy** [comment]
You are right @n1nj4sec, if the connection is closed abruptly then rpyc keeps calling the poller on the dead fd; however, their implementation of the poller (`SelectingPoll` class in `rpyc/lib/compat.py`) use `select.select()`, which does not handle dead fd event like `select.poll()`.

I made a patch on [my rpyc fork](https://github.com/n1nj4sec/pupy/issues/25), but there might be a better way of signaling `select()` failure.

**Comment by n1nj4sec** [comment]
nice ! perhaps you should push a pull request to the rpyc repository ?
