### ISSUE TITLE
make payload undetectable

### ISSUE THREAD

**Issue by Axe-Usa** [n1nj4sec/pupy#252]
Hi if i create my own binaries maybe will be undetectable again?

**Comment by alxchk** [comment]
Cmon. This is opensource tool. It _will_ be detectable. Always.

**Comment by Axe-Usa** [comment]
Yeah but some payloads like veil evasion are undetectable maybe i can edit the code or do something to get less detected for this i ask.

**Comment by Axe-Usa** [comment]
i think i'm not good like you but i think when something is opensource doesnt mean that will be more detected. This deppend of the payload how you did or if you encrypted the payload and the source of puppy is important too. The contrary when something is private and is public fastly will be detected however when something is opensource and is updated a lot of time for different person's with new code it's more difficult to be detected by antivirus.
