### ISSUE TITLE
DNS communication [FEATURE]

### ISSUE THREAD

**Issue by glira** [n1nj4sec/pupy#26]
please add communication under dns and will be very competitive!
best regards!

**Comment by 0x27** [comment]
See [Issue#4](https://github.com/n1nj4sec/pupy/issues/4) which encapsulates this. 

I am trying (mostly failing!) to write a DNS tunnelling client in Python at the moment for [another project](http://dnstun.com), which uses the Tor Pluggable Transport mechanism. Hopefully that works eventually and can fold that in on top of the extant rpyc/pluggable transport mechanisms proposed :)

**Comment by n1nj4sec** [comment]
I implemented a first asynchronous http transport where the client pull the server, so a DNS transport shouldn't be hard to implement now

**Comment by n1nj4sec** [comment]
https://github.com/n1nj4sec/pupy/blob/master/pupy/network/lib/launchers/dnscnc.py

**Comment by asaf53409** [comment]
Hi I try to use with dnscsc, maybe can you help with this?
How to return requests to the server?Is there a need to use with pupysh.py

**Comment by asaf53409** [comment]
@n1nj4sec 
Hi I try to use with dnscsc, maybe can you help with this?
How to return requests to the server?Is there a need to use with pupysh.py
