### ISSUE TITLE
Resiliency in environments with poor connections / issues?

### ISSUE THREAD

**Issue by dwendt** [n1nj4sec/pupy#265]
In this environment nodes are on a wifi mesh network with spotty signal. It seems like, occasionally, when executing a `run` module, the terminal will hang indefinitely. When ctrl+c is passed, it interrupts the job and the session is closed. The session doesn't attempt to reestablish connection as far as I can tell.

I was looking through the transports, where does pupy attempt to reconnect when the TCP connection times out? This should probably be a thing.

If that actually exists already, maybe the process was crashed somehow? It's happened to me with a variety of `run` commands from time to time when they are rather simplistic modules. Maybe the spotty connection is to blame for that and there's debugging I should try?

I've only seen this occur in windows x86/64 agents, I need to test this on linux machines in the environment too.

**Comment by alxchk** [comment]
Likely connection hang. When you press ^C pupysh run background ping. It fails and it breaks connection. Other side may not know that connection was interrupted. You can try to find out, does netstat have registered connection from client or not. Also you may build|use debug demplate to find what is going on on client.

**Comment by dwendt** [comment]
Yeah, there's connections in the TCP table that are still showing as "established", however, the client has been disconnected for a few minutes. 

I'll try out the debug template to get more details when running in this sort of situation. 

I've spent a while looking, where does a pupy client handle checking if an established transport is alive still? It seems to me that that would be handled by the timeouts in PupySocketStream's poll functions, but I couldn't follow where the values for those are set. It'd make sense for the transport to decide on the timeouts, but that doesn't seem to be the case either.

https://github.com/n1nj4sec/pupy/blob/fcfc731b8897f312131a20c9a6a298bfb8373051/pupy/pp.py#L232
Maybe this timeout should be configurable? If a client is offline when it runs this loop, we shouldn't hold the loop back for a minute before attempting the launchers again. 

All this is because I'd be interested in writing the code to make the delay between connection/keepalive checks more configurable. Low-delay checks would be preferable in a poor network so that clients stay responsive to the server.

**Comment by alxchk** [comment]
This in not that timeout you look for. This one for authentication. Keepalives for client set here - https://github.com/n1nj4sec/pupy/blob/master/pupy/network/lib/clients.py#L38. Btw, you are using "connect" (default) launcher for pp.py, right?

You can try to play with them, and if they fix your situation, probably they should become configurable (or maybe new hardcoded values will be good for all :) ). 

As far as I remember, client rely just on network stack to find that connection is dead. Probably it also be good to have client level pinging or something like that..

**Comment by alxchk** [comment]
Also you probably should investigate what is going on using wireshark. There should be the reason why your channel becomes dead. Maybe some issues with fragmented traffic, or traffic with low delays, or something like that.
