### ISSUE TITLE
Get error when i gen on kali nethunter 

### ISSUE THREAD

**Issue by jboss38** [n1nj4sec/pupy#276]
When i try to gen any support (apk, exe...)
t@kali:/home/kali/pupy/pupy-master/pupy# python pupygen.papk connect --host 192.168.1.150:444
Traceback (most recent call last):
  File "pupygen.py", line 361, in <module>
    binary=get_edit_pupyx86_exe(conf, debug=args.debug)
  File "pupygen.py", line 38, in get_edit_pupyx86_exe
    return get_edit_binary(os.path.join(ROOT, "payload_templates","pupyx86.exe"), conf)
  File "pupygen.py", line 68, in get_edit_binary
    with open(path, 'rb') as f:
IOError: [Errno 2] No such file or directory: '/home/kali/pupy/pupy-master/pupy/payload_templates/pupyx86.exe'

Error when apk is : get_edit_apk

**Comment by quentinhardy** [comment]
The command to use for example (for an apk): 
```
python pupygen.py -f apk connect --host 192.168.1.150:444
```
Otherwise, folder named _payload_templates_ has to have _pupy_ templates. They can be found here: [https://github.com/n1nj4sec/pupy-binaries](https://github.com/n1nj4sec/pupy-binaries)

**Comment by jboss38** [comment]
Oh thx for the info i added the binaires but i still have the same kind of error 

ot@kali:/home/kali/pupy/pupy-master/pupy# python pupygen.post 192.168.1.150:444
[+] generating payload ...
[+] packaging the apk ... (can take 10-20 seconds)
/bin/sh: 1: jarsigner: not found
Traceback (most recent call last):
  File "pupygen.py", line 415, in <module>
    get_edit_apk(os.path.join(ROOT, "payload_templates","pupy.apk"), outpath, conf)
  File "pupygen.py", line 222, in get_edit_apk
    res=subprocess.check_output("jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore crypto/pupy-apk-release-key.keystore -storepass pupyp4ssword '%s' pupy_key"%new_path, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore crypto/pupy-apk-release-key.keystore -storepass pupyp4ssword 'pupy.apk' pupy_key' returned non-zero exit status 127
root@kali:/home/kali/pupy/pupy-master/pupy#

I noticed that you dont see my cmd synthax correctly but its the same has you give me :)

**Comment by jboss38** [comment]
Fixed with 
apt-get install openjdk-7-jdk 

On kali nethunter.
