### ISSUE TITLE
Android TTS and webcamsnap not working 

### ISSUE THREAD

**Issue by jboss38** [n1nj4sec/pupy#277]
Installed apk on a CM12

This Android specific :

Text to speech for Android to say stuff out loud
webcam snapshot (front cam & back cam)

Not work on me, webcamsnap take Black screen, no sound send on TTS

Those specific work with a specific Android version ?

**Comment by quentinhardy** [comment]
"webcamsnap take Black screen": Have you tried to select the other cam ("front cam")?
By default, the "back cam" is used for taking a photo: Of course, if your phone is on a table, the picture will be all black. -:)

**Comment by jboss38** [comment]
The phone was in the air.
There is no minimum Android required ? This fonction work on every Android ? With All model ?

**Comment by n1nj4sec** [comment]
probably, I tested it on android 5.1 and 6.0 and it works great. You should look at logcat output for debug

**Comment by quentinhardy** [comment]
Tested on 4.4.2 and no problem with _webcamsnap_ module

**Comment by jboss38** [comment]
Hum cannot do it work with 5.1.1 Android with CM 12 on OnePlus one with kali nethunter Installed. 

I mean he take screen but it always Black (phone not on table) 
And still nothing happening with text to speech also
