### ISSUE TITLE
[Android] GPS tracking

### ISSUE THREAD

**Issue by jboss38** [n1nj4sec/pupy#278]
Hey !

What do you think about GPS Tracking feature ?

Like if GPS is ON record X,Y,Z with time like every 5min or less and export as text (or csv), then you will be able to import in google map to get a route.

**Comment by quentinhardy** [comment]
Yes. I'm developing it.
It will be finished this week end.

**Comment by jboss38** [comment]
Perfect. 
Have a Nice Day !
