### ISSUE TITLE
PLS HELP ME

### ISSUE THREAD

**Issue by Kaizokuou99** [n1nj4sec/pupy#280]
```
OUTPUT_PATH = /root/pupy/pupy/test.apk
LAUNCHER = 'connect'
LAUNCHER_ARGS = ['--host', 'IP:kaizokuou.ddns.net:443']
SCRIPTLETS = []
DEBUG = False
```

what's wrong with this?

**Comment by n1nj4sec** [comment]
I return you the question

**Comment by Kaizokuou99** [comment]
wht???????????

**Comment by n1nj4sec** [comment]
what's wrong with this?

**Comment by Kaizokuou99** [comment]
can i get your fb or something.. i wanna talk with you

**Comment by Kaizokuou99** [comment]
is it okay with this?
`DEBUG = `False``

**Comment by void-in** [comment]
@Kaizokuou99 You paste the error message you are receiving rather than asking what is wrong.

**Comment by Kaizokuou99** [comment]
@void-in the problem is, i dont know what is wrong with this.. i followed all the steps given.. but it still not working

**Comment by jboss38** [comment]
Dude,  nothing is wrong, This output mean that the compilation is a succes.

**Comment by Kaizokuou99** [comment]
![image](https://cloud.githubusercontent.com/assets/25056619/21886915/b10bef9e-d8f8-11e6-9e58-add61d2aa52d.png)


is it okay?

**Comment by jboss38** [comment]
This is not a pupy issues, you will have better chance to resolve this on kali forums..

**Comment by Kaizokuou99** [comment]
thanks
