### ISSUE TITLE
pupygen.py tryed to make an pay load nothing is ok 

### ISSUE THREAD

**Issue by matsaa93** [n1nj4sec/pupy#283]
#280 

22:49:20  ~/pupy/pupy 
$ ./pupygen.py  -h
  File "./pupygen.py", line 93
    exec creds_src in {}, creds
                 ^
SyntaxError: Missing parentheses in call to 'exec'

 22:49:23  ✘  ~/pupy/pupy 

#281 
missing line or problem with syntax 
maybe it is my fault for installing dependency in user dir 

I'm using Arch-Linux

**Comment by matsaa93** [comment]
one thing i have not maked an bug report on git before so if there is some thing i forgot 
not sure if i have done the report right

**Comment by alxchk** [comment]
Use python2

**Comment by matsaa93** [comment]
ok i will do that 
thanks
