### ISSUE TITLE
Error in installation 

### ISSUE THREAD

**Issue by pyx86** [n1nj4sec/pupy#284]
When I install puppy, I have an error when using sudo git submodule update : 
Cloning into '/home/masxnz/pupy/client/sources-linux/linux-inject'...
Cloning into '/home/masxnz/pupy/pupy/external/LaZagne'...
Cloning into '/home/masxnz/pupy/pupy/external/impacket'...
Cloning into '/home/masxnz/pupy/pupy/external/memorpy'...
Cloning into '/home/masxnz/pupy/pupy/external/pywerview'...
Cloning into '/home/masxnz/pupy/pupy/external/scapy'...
Cloning into '/home/masxnz/pupy/pupy/external/winpty'...
Cloning into '/home/masxnz/pupy/pupy/payload_templates'...
Submodule path 'client/sources-linux/linux-inject': checked out 'ce6d7e4b1d6c06b2fb36548e23d62685a1f91209'
error: no such remote ref 3135aefe986d2a411309022039b931f2a45936ea
Fetched in submodule path 'pupy/external/LaZagne', but it did not contain 3135aefe986d2a411309022039b931f2a45936ea. Direct fetching of that commit failed.

**Comment by horllste** [comment]
wow...got the same error too on new installation.

**Comment by traget** [comment]
Same here

**Comment by jboss38** [comment]
Did u follow those step :

git clone https://github.com/n1nj4sec/pupy.git pupy
cd pupy
git submodule init
git submodule update
pip install -r requirements.txt

**Comment by traget** [comment]
Yes

**Comment by traget** [comment]
Also, generating an apk payload returns an error that may be related to this issue, but I ll make a a new issue for that.

**Comment by pyx86** [comment]
me too , I followed exactly the installation instructions

**Comment by n1nj4sec** [comment]
This can be for two reasons. 
The first is that one of the submodule's owner rebased their whole project and commits number doesn't exist anymore. 
It is not the case, because as you can see https://github.com/AlessandroZ/LaZagne/commit/3135aefe986d2a411309022039b931f2a45936ea is available
The second reason is that there is something wrong with your git installation, you probably used the --depth option on one of the submodule in the past, and now you can't find the good version after a pull.
Try to remove everything and reinstall from the start
If it does not fix the problem, use the following command : 
```bash
man git 
```
as suggested in issue #239 by alxchk, it could come from your git version

**Comment by traget** [comment]
My git version is 2.11.0, and I never used the  --depth option, also by removing everything, you mean deleting the pupy directory, or that and reinstalling git.

**Comment by traget** [comment]
I tried to remove the pupy and then download it again.. nothing changed.

**Comment by traget** [comment]
n1nj4sec: I may sound stupid cuz I don't know how git exactly works, but can't we get Lazagne from you instead of Alessandro since you forked his project? 

Again, I don't really understand from where git gets the submodules so this may not make sens.. Correct me if I'm wrong..

**Comment by traget** [comment]
Anyone solved this issue yet?

**Comment by jboss38** [comment]
I think it because LaZagne pushed New commit. 
Maybe you can try install LaZagne by your own

**Comment by traget** [comment]
jboss38: how to do that... Like git clone <Lazagne repo> inside /pupy/external/LaZagne?

**Comment by n1nj4sec** [comment]
I don't have the issue everything is running fine with my conf
You probably have a shallow issue, try to change the "git submodule init" with a big depth like --depth 1000

**Comment by n1nj4sec** [comment]
since git 2.9.0 there is also the --shallow-submodules option which look nice. So perhaps the easier would be to try : 
```
git clone --shallow-submodules --recursive
cd pupy
pip install -r requirements.txt
```
tell me if that worked so I can edit the wiki

**Comment by traget** [comment]
Nope :(
Here is the output: 
`git clone --shallow-submodules --recursive https://github.com/n1nj4sec/pupy.git
Cloning into 'pupy'...
remote: Counting objects: 6547, done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 6547 (delta 16), reused 0 (delta 0), pack-reused 6512
Receiving objects: 100% (6547/6547), 23.75 MiB | 4.53 MiB/s, done.
Resolving deltas: 100% (4150/4150), done.
Submodule 'client/sources-linux/linux-inject' (https://github.com/gaffe23/linux-inject.git) registered for path 'client/sources-linux/linux-inject'
Submodule 'pupy/external/LaZagne' (https://github.com/AlessandroZ/LaZagne) registered for path 'pupy/external/LaZagne'
Submodule 'pupy/external/impacket' (https://github.com/CoreSecurity/impacket) registered for path 'pupy/external/impacket'
Submodule 'pupy/memorpy' (https://github.com/n1nj4sec/memorpy) registered for path 'pupy/external/memorpy'
Submodule 'pupy/external/pywerview' (https://github.com/the-useless-one/pywerview.git) registered for path 'pupy/external/pywerview'
Submodule 'pupy/packages/src/scapy' (https://github.com/secdev/scapy) registered for path 'pupy/external/scapy'
Submodule 'pupy/external/winpty' (https://github.com/alxchk/winpty) registered for path 'pupy/external/winpty'
Submodule 'pupy/payload_templates' (https://github.com/n1nj4sec/pupy-binaries.git) registered for path 'pupy/payload_templates'
Cloning into '/root/pupy/client/sources-linux/linux-inject'...
remote: Counting objects: 16, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 16 (delta 2), reused 3 (delta 0), pack-reused 0
Cloning into '/root/pupy/pupy/external/LaZagne'...
remote: Counting objects: 124, done.
remote: Compressing objects: 100% (120/120), done.
remote: Total 124 (delta 16), reused 43 (delta 1), pack-reused 0
Receiving objects: 100% (124/124), 481.53 KiB | 0 bytes/s, done.
Resolving deltas: 100% (16/16), done.
Cloning into '/root/pupy/pupy/external/impacket'...
remote: Counting objects: 219, done.
remote: Compressing objects: 100% (206/206), done.
remote: Total 219 (delta 21), reused 47 (delta 11), pack-reused 0
Receiving objects: 100% (219/219), 1.14 MiB | 1.88 MiB/s, done.
Resolving deltas: 100% (21/21), done.
Cloning into '/root/pupy/pupy/external/memorpy'...
remote: Counting objects: 22, done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 22 (delta 2), reused 12 (delta 0), pack-reused 0
Cloning into '/root/pupy/pupy/external/pywerview'...
remote: Counting objects: 26, done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 26 (delta 0), reused 10 (delta 0), pack-reused 0
Cloning into '/root/pupy/pupy/external/scapy'...
remote: Counting objects: 242, done.
remote: Compressing objects: 100% (237/237), done.
remote: Total 242 (delta 8), reused 98 (delta 1), pack-reused 0
Receiving objects: 100% (242/242), 1.57 MiB | 604.00 KiB/s, done.
Resolving deltas: 100% (8/8), done.
Cloning into '/root/pupy/pupy/external/winpty'...
remote: Counting objects: 190, done.
remote: Compressing objects: 100% (179/179), done.
remote: Total 190 (delta 49), reused 67 (delta 9), pack-reused 0
Receiving objects: 100% (190/190), 235.91 KiB | 0 bytes/s, done.
Resolving deltas: 100% (49/49), done.
Cloning into '/root/pupy/pupy/payload_templates'...
remote: Counting objects: 8, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 8 (delta 2), reused 6 (delta 2), pack-reused 0
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
error: no such remote ref ce6d7e4b1d6c06b2fb36548e23d62685a1f91209
Fetched in submodule path 'client/sources-linux/linux-inject', but it did not contain ce6d7e4b1d6c06b2fb36548e23d62685a1f91209. Direct fetching of that commit`

**Comment by traget** [comment]
Man, I did it! :)
You were right using the depth option. 
Here is how:
`https://github.com/n1nj4sec/pupy.git
cd pupy
git submodule init
git submodule update --depth 1000`

Thank you very much!

**Comment by traget** [comment]
Also I can now generate payloads successfully! :)

**Comment by traget** [comment]
But I still get an error when trying to generate a payload :'( 


[+] generating payload ...
[+] packaging the apk ... (can take 10-20 seconds)
/bin/sh: 1: jarsigner: not found
Traceback (most recent call last):
  File "./pupygen.py", line 415, in <module>
    get_edit_apk(os.path.join(ROOT, "payload_templates","pupy.apk"), outpath, conf)  File "./pupygen.py", line 222, in get_edit_apk
    res=subprocess.check_output("jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore crypto/pupy-apk-release-key.keystore -storepass pupyp4ssword '%s' pupy_key"%new_path, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore crypto/pupy-apk-release-key.keystore -storepass pupyp4ssword 'pupy.apk' pupy_key' returned non-zero exit status 127
root@kali-arm64:~/pupy/pupy#

**Comment by traget** [comment]
Hm.. Already fixed that. :) 
I needed default-jdk. :P

**Comment by jdjdbsudgskdododolldlx** [comment]
I have an error help me
Error name is

Importerror: no module named tornado.ioloop

What's happend?

**Comment by ShawnCena121** [comment]
Hey I have a problem installing pupy.
After i run the command pip install -r pupy/requirements.txt i get an error
plz help ASAP
