### ISSUE TITLE
compress_encode_obfs bug

### ISSUE THREAD

**Issue by KiUserExceptionDispatcher** [n1nj4sec/pupy#288]
Hello!

From: pupy/pupy/pupylib/utils/obfuscate.py:
`return "import base64,zlib;exec zlib.decompress(base64.b64decode(%s))"%repr(base64.b64encode(zlib.compress(code+"\n")))`
\n between _import * ;_ and _exec *_ is missed. _"\n"_ in compress() argument is not necessary. Fixed version:

`return 'import base64, zlib;\nexec zlib.decompress(base64.b64decode(%s))' % repr(base64.b64encode(zlib.compress(code)))`

Fix me if I'm wrong.

**Comment by n1nj4sec** [comment]
You can dispatch your exceptions elsewhere
Fix me if I'm wrong

**Comment by n1nj4sec** [comment]
And FYI, the new line is here because in some cases it doesn't work without on compiled code
https://docs.python.org/2/library/functions.html#compile
```
Note

When compiling a string with multi-line code in 'single' or 'eval' mode, input must be terminated by at least one newline character. This is to facilitate detection of incomplete and complete statements in the code module. 
```
