### ISSUE TITLE
Error Submodule Update

### ISSUE THREAD

**Issue by its-arun** [n1nj4sec/pupy#297]
root@kali:~/pupy# git submodule update
error: no such remote ref 3135aefe986d2a411309022039b931f2a45936ea
Fetched in submodule path 'pupy/external/LaZagne', but it did not contain 3135aefe986d2a411309022039b931f2a45936ea. Direct fetching of that commit failed.

**Comment by its-arun** [comment]
Sorry for being silly. BTW following fixed it
git clone https://github.com/n1nj4sec/pupy.git
cd pupy
git submodule init
git submodule update --depth 1000

**Comment by Kulme** [comment]
kali linux?
try with ubuntu

**Comment by n1nj4sec** [comment]
Could you try again after my last commit ? thx

**Comment by molospg** [comment]
Issue still exists. Any known workaround?

**Comment by its-arun** [comment]
I am currently having issues with Latest build of Kali (Auto Logout during usage) so can't test right now. I will open this issue once I am running stable build.
