### ISSUE TITLE
In-memory loading of .pyd files on Linux

### ISSUE THREAD

**Issue by HarryR** [n1nj4sec/pupy#298]
In _memimporter.c  - https://github.com/n1nj4sec/pupy/blob/a0532281a398a41eeb62c5bafb898a24e5e9e57e/client/sources/_memimporter.c - the MemoryModule code by Joachim Bauch is used.

I think it's about time we support loading `.pyd` files from memory on Linux too :+1: 

Refer to the [NetELF](https://github.com/XiphosResearch/netelf) project, which uses /proc/self/fd/X, tmpfs and memfd to run ELF executables from memory, but this can also be used with dlopen :)

`memfd` lets you create a file descriptor and put data into it even if the filesystem is read-only, then you can get the fd-no of it and `dlopen` via `/proc/self/fd/N`, this should work on grsecurity, and may work with most standard apparmour profiles due to the template files being kinda lax about /proc/self/fd...

If `memfd` syscall isn't supported, you can create a file in /dev/shm, then unlink it, write some crap into it, then `dlopen` via `/proc/self/fd/N` as you did with `memfd`.

**Comment by n1nj4sec** [comment]
This is already supported thank's to @alxchk work (on linux python dynamic libraries are not renamed .pyd but stays named .so)
https://github.com/n1nj4sec/pupy/blob/master/client/sources-linux/_memimporter.c

**Comment by HarryR** [comment]
I didn't notice that memdlopen was already included, but after reviewing the source code I see that the .so is still written to disk, this leaves a forensic footprint...

Is it worth adding 'memfd' support?

**Comment by alxchk** [comment]
>  the .so is still written to disk, this leaves a forensic footprint...

Well, it's better to integrate https://github.com/infosecguerrilla/ReflectiveSOInjection.
It's on my todo list, but currently I simply don't have time to do that. If you are interested in such things, you can try.

> Is it worth adding 'memfd' support?

It's better to use ancient technologies to make pupy works on any binary distro. Currently single agent can run on any distro since 2003.

**Comment by HarryR** [comment]
Why use ReflectiveSO when its significantly more complex and only supports x86_64?

Memfd support can be detected at compile time without a configure script, it should gracefully fallback - `syscall` will return ENOSYS, and will work across all architectures.

As it is the tmplibrary code seems to do the job, portably and cleanly, while memfd should be a relatively simple patch.

**Comment by alxchk** [comment]
> Why use ReflectiveSO when its significantly more complex and only supports x86_64?
It will be better because it will work everywhere.

It supports only x86_64 because author just write code for that arch. Nobody prevent us to write missing parts for x86 and arm for example.

> As it is the tmplibrary code seems to do the job, portably and cleanly, while memfd should be a relatively simple patch.

Well, why not.  But this will works only on kernels >= 3.17, and also can be built only with recent glibc. If use memfd as an runtime option, then probably syscalls should be written manually, without touching glibc functions to be able to use same binary template everywhere.

**Comment by HarryR** [comment]
If there's one thing that sounds fun but very tedious is adding support for new architectures to an ELF loader... Not something I would be very happy to maintain.

Anyway, aside from glibc's syscall wrapper, it has no dependency on glibc, so no ABI or link time dependency, iirc the syscall function has existed for a very long time. The only thing necessary is recent Linux kernel headers at compile time to get the syacall number specific to the architecture.

Hmm, so ya its probably worth me having a quick go at this when I get back to a Linux box.

**Comment by alxchk** [comment]
> Linux kernel headers at compile time to get the syacall number specific to the architecture.

Can be hardcoded.

> Hmm, so ya its probably worth me having a quick go at this when I get back to a Linux box.

You can try to build it with my branch (https://github.com/alxchk/pupy/blob/master/client/sources-linux/buildenv.sh).

**Comment by alxchk** [comment]
I added memfd support to my experemental branch - https://github.com/alxchk/pupy/commit/f1e7ace087fb4adca56e7ee4f299203ae0e5b298

Looks like it works. I will check on more systems and will create pull request here then.

**Comment by n1nj4sec** [comment]
omg this memfd technique is awesome ! it looks like we have a new oneliner for linux :)
```
import os
from ctypes import *
c = CDLL("libc.so.6")
fd = c.syscall(319,"plop",0)
os.write(fd,open("pupy.so","rb").read())
CDLL("/proc/self/fd/%s"%fd)
```

**Comment by HarryR** [comment]
Yay!
