### ISSUE TITLE
How about injecting pupy in any Android .apk

### ISSUE THREAD

**Issue by NeverMine17** [n1nj4sec/pupy#301]
##### *Bad English warning*
So for example I have a some app. Let's call it Flappy bird.
I have an .apk of this game. I could say to `pupygen.py` that I want to inject pupy in that .apk.
Its creates a copy of that app but with pupy in it. 
And if you run the injected apk it would look like an our app to user. 
How is that?
### Also:
I tried putting different apk's in `/pupy/pupy/payload_template`.
All I get is error that sayed there is no `assets/private.mp3` in apk.
If apk contained that file it wouldn't install normally, although `pupygen.py` didn't give any error.

**Comment by samdunsavy** [comment]
Thats already suggested and acknowledged... If I am not wrong

**Comment by samdunsavy** [comment]
https://github.com/n1nj4sec/pupy/issues/97

**Comment by NeverMine17** [comment]
And? There is no comment on that issue what so ever.

**Comment by samdunsavy** [comment]
It's marked as "Android" and "Feature" isn't it?

**Comment by NeverMine17** [comment]
Yes

**Comment by samdunsavy** [comment]
It's added by the developer... So they will work on it when the time is right. So I guess you can close your issue now

**Comment by NeverMine17** [comment]
Ok

**Comment by n1nj4sec** [comment]
you can start working on it !
unless I win the lottery and I have too much free time, I won't find time to work on this before approximately year 2032 ;)
If I acknowledge it doesn't mean I will work on it, it means it's a good idea

**Comment by babanaweed** [comment]
I generate a android payload after installing it in my phone
it's not giving me any session tnx

**Comment by babanaweed** [comment]
someone answer me fast please
