### ISSUE TITLE
pupyx64.lin throws list index out of range exception

### ISSUE THREAD

**Issue by SagiSatish** [n1nj4sec/pupy#305]
Hi,

I compiled sources-linux to get the pupyx64.lin binary. I created a test client file and started the server on the same system. 
`./pupygen.py -f lin_x64 connect   --host 192.168.0.30:8989`
` ./pupysh.py --log-lvl DEBUG -p 8989`

Server shows the "list index out of range" exception. No seesion was created and I didn't understand the issue. The output of server debug is as follows:

> DEBUG:root:Sync poll complete: 12/inactive=0.000183820724487
> DEBUG:root:Sync request handled: 12
> ERROR:root:Traceback (most recent call last):
>   File "/root/Desktop/cra/pupy/pupy/pupylib/PupyService.py", line 67, in on_connect
>     self.pupy_srv.add_client(self)
>   File "/root/Desktop/cra/pupy/pupy/pupylib/PupyServer.py", line 107, in add_client
>     l=conn.namespace["get_uuid"]()
>   File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 196, in __call__
>     return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 71, in syncreq
>     return conn.sync_request(handler, oid, *args)
>   File "/root/Desktop/cra/pupy/pupy/network/lib/servers.py", line 58, in sync_request
>     raise obj
> IndexError: list index out of range
> 
> ========= Remote Traceback (1) =========
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 305, in _dispatch_request
>     res = self._HANDLERS[handler](self, *args)
>   File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 535, in _handle_call
>     return self._local_objects[oid](*args, **dict(kwargs))
>   File "<loader>", line 217, in get_uuid
>   File "<string>", line 131, in load_module
> IndexError: list index out of range
> 
> 
> DEBUG:root:Async request: 13
> DEBUG:PUPY/8989:{}:{} Initializing service... complete. Locking
> DEBUG:PUPY/8989:::ffff:192.168.0.30:35970 Serving main loop. Inactive: 0.000892877578735
> 
> \>\> sessions -l

Can you provide me with any solution for this problem?

**Comment by n1nj4sec** [comment]
try using the py format instead of lin_x64 in the meantime I review/merge alxchk work on this
