### ISSUE TITLE
 No module named 'PupyErrors'

### ISSUE THREAD

**Issue by heroek** [n1nj4sec/pupy#306]
i have this error under windows and also linux

Traceback (most recent call last):
  File ...pupysh.py", line 19, in <module>
    import pupylib.PupyServer
  File "...\pupy-master\pupy\pupylib\__init__.py", line 1, in <module>
    from PupyErrors import *
ImportError: No module named 'PupyErrors'

**Comment by googleadmin1** [comment]
I also have this same error. 

I Noticed there is no PupyError Module within the pupylibs folder. 

Also to note, the PupyServer.py uses:: from <module_name> import *. 

I commented out the first line out to see what would happen. I am by no means a master with python but I will experiment. 

After the first line was commented out, it read the next module was also not there.  The entire __init.py__ in the pupylib appears to be the culprit. 

The file PupyServer.py line 18 has a from (*) import <module> .. The * with with no following declaration seems a little off as well. 


The odd part is the "modules" do exist, but only as part of the same program. -- Isn't an illegal move? How does the system use a lib that it is currently reading from. Again sorry for the noob question. 

This project is amazing! Reading line by line I'm excited to use it in my research. 

thanks -- Look forward to learning the fix.

**Comment by n1nj4sec** [comment]
use python 2.7, not python 3, I will add a warning concerning the version 3

**Comment by googleadmin1** [comment]
Cheers!

I'm on got, I'll throw a shout into the comment block for you.

Thanks again!

I'm so pumped for this project!
