### ISSUE TITLE
git submodule not updating

### ISSUE THREAD

**Issue by noh950** [n1nj4sec/pupy#312]
When :git submodule update
It hangs on this forever :
Cloning into '/root/pupy/pupy/external/LaZagne'...
I also tried the depth options mentioned in previous issue posts.
Any solution to fix this ?
Thanks.

**Comment by OBuntu** [comment]
Had the same issue, just git clone lazagne by yourself to /root/pupy/pupy/external
And then rerun submodule update

**Comment by noh950** [comment]
Thank you OBuntu for you help. I did what what you suggested and got this; 


root@localhost:~/pupy/pupy/external# git clone https://github.com/AlessandroZ/LaZagne
Cloning into 'LaZagne'...
remote: Counting objects: 1641, done.
error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by OBuntu** [comment]
That's a different issue.
I am using openssl with git though, so you may want to rebuild git with openssl instead of GnuTLS and try again.

**Comment by noh950** [comment]
Thanks you OBuntu !
It solved the problem.
