### ISSUE TITLE
WARNING:root:No module named dumbnet : module tcpdump disabled

### ISSUE THREAD

**Issue by OBuntu** [n1nj4sec/pupy#314]
I made an APK payload, installed it on my rooted Android, all seems to be going well.
Except when I start pupysh.py to listen I get the following warning : 
`WARNING:root:No module named dumbnet : module tcpdump disabled`

And I don't see any sessions opened either, even if I can see pupy is running on memory in the client android.

How can I debug this ? 

EDIT : 
Before the dumbnet warning, I had the same warning concerning pncapy, which I installed manually using pip.
Tried doing the same thing with the dumbnet but I get this : 
`
  Could not find a version that satisfies the requirement dumbnet (from versions: )
No matching distribution found for dumbnet
`
Edit 2 : 
I'm on a Mac Sierra.

**Comment by OBuntu** [comment]
Just a quick update, I ended up fixing the dumbnet issue by installing libdnet through homebrew.

Still no sessions opened though.

**Comment by n1nj4sec** [comment]
try to debug with 
```adb logcat```
