### ISSUE TITLE
Build payloads from source: cl.sh command not found

### ISSUE THREAD

**Issue by jusch2211** [n1nj4sec/pupy#317]
Hi,
 
when I try to compile the payloads under kali linux with: 

1. cd client/sources
2. ./buildenv.sh
3. ./build.sh

I get an error during the execution of build.sh: 
`make: /root/Desktop/pupy/pupy/client/sources/buildenv/win32/cl.sh: Command not found
Makefile.linux:85: recipe for target 'main_exe.obj' failed`

The previos executed buildenv.sh seems to have run correctly.

=====
`root@kali:~/Desktop/pupy/pupy/client/sources# ./build.sh 
rm -f *.obj
rm -f *.pyo
rm -f *.pyc
rm -f *.txt
rm -f *_txt.c
rm -f *_pyc.c
rm -f *_dll.c
rm -f resources/*.pyo
rm -f resources/*.pyc
rm -f resources/*.txt
rm -f resources/*_txt.c
rm -f resources/library.zip
rm -f resources/python27.dll
rm -f resources/msvcr90.dll
/root/Desktop/pupy/pupy/client/sources/buildenv/win32/cl.sh /c  /DWIN_X86 /nologo main_exe.c
make: /root/Desktop/pupy/pupy/client/sources/buildenv/win32/cl.sh: Command not found
Makefile.linux:85: recipe for target 'main_exe.obj' failed`

**Comment by jboss38** [comment]
To build source payload for Windows on Kali you need wine && vcpp

**Comment by jusch2211** [comment]
I have the package build-essentials installed, as well as wine. 
Do I need another version?

Thanks

**Comment by n1nj4sec** [comment]
check if there is any error when running buildenv, it seems cl.sh doesn't exists, so your buildenv didn't succeeded
