### ISSUE TITLE
What language is even supported?!?!

### ISSUE THREAD

**Issue by xSynthx** [n1nj4sec/pupy#324]
I try using the command `troll/text_to_speach --lang ENGLISH text_to_speek` and I get this error:
```
[-] Error in setLanguage: LANG_NOT_SUPPORTED for lang: ENGLISH

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "<memimport>/rpyc/core/protocol.py", line 305, in _dispatch_request
  File "<memimport>/rpyc/core/protocol.py", line 535, in _handle_call
  File "<memimport>/pupydroid/text_to_speech.py", line 23, in speak
Exception: Error in setLanguage: LANG_NOT_SUPPORTED for lang: ENGLISH
```
I have tried `English` as well, even `english`.... I have had this command work before with `ENGLISH` but it doesnt work anymore for some reason..

**Comment by n1nj4sec** [comment]
you can blame google for that ;) https://developer.android.com/reference/android/speech/tts/TextToSpeech.html

**Comment by xSynthx** [comment]
then what language?

**Comment by xSynthx** [comment]
or what do I put as the language?

**Comment by n1nj4sec** [comment]
You have to know your language or implement getAvailableLanguages() from the link I gave you. The code you have to edit is https://github.com/n1nj4sec/pupy/blob/master/pupy/packages/android/pupydroid/text_to_speech.py
I accept Pull Requests, thx :)
