### ISSUE TITLE
Build payloads from sources custom spec

### ISSUE THREAD

**Issue by jboss38** [n1nj4sec/pupy#328]
i Build the payloads from sources with custom spec like, custom icon and name.

When i generate payload with apk and install on phone it's working.

But pupysh doesn't find any client, if i don't use custom spec, it's working fine pupysh find 1 client.

I just edtited the icone and name.

**Comment by n1nj4sec** [comment]
well, I guess you did something else wrong ! try to use ```adb logcat``` to debug

**Comment by jboss38** [comment]
I renamed the package name to androidsys. 
Here cat log :

03-14 16:26:50.368 I/Timeline(1672): Timeline: Activity_launch_request id:org.androidsys.android time:216378845
03-14 16:26:50.369 I/ActivityManager(802): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.androidsys.android/org.renpy.android.PythonActivity (has extras)} from uid 10066 on display 0
03-14 16:26:50.373 V/WindowManager(802): addAppToken: AppWindowToken{3117627f token=Token{11e3179e ActivityRecord{36ec01d9 u0 org.androidsys.android/org.renpy.android.PythonActivity t978}}} to stack=1 task=978 at 0
03-14 16:26:50.386 V/WindowManager(802): Adding window Window{2d561ee4 u0 Starting org.androidsys.android} at 15 of 20 (after Window{752fcea u0 com.nolanlawson.logcat/com.nolanlawson.logcat.LogcatActivity})
03-14 16:26:50.413 I/ActivityManager(802): Start proc 17409:org.androidsys.android:python/u0a152 for activity org.androidsys.android/org.renpy.android.PythonActivity
03-14 16:26:50.528 E/art     (17409): dlopen("/data/data/org.androidsys.android/files/lib/python2.7/lib-dynload/_sqlite3.so", RTLD_LAZY) failed: dlopen failed: library "/data/data/org.androidsys.android/files/lib/python2.7/lib-dynload/_sqlite3.so" not found
03-14 16:26:50.528 E/art     (17409): dlopen("/data/data/org.androidsys.android/files/lib/python2.7/lib-dynload/_imaging.so", RTLD_LAZY) failed: dlopen failed: library "/data/data/org.androidsys.android/files/lib/python2.7/lib-dynload/_imaging.so" not found
03-14 16:26:50.544 V/WindowManager(802): Adding window Window{1752a44e u0 org.androidsys.android/org.renpy.android.PythonActivity} at 15 of 21 (before Window{2d561ee4 u0 Starting org.androidsys.android})
03-14 16:26:50.606 I/ActivityManager(802): Displayed org.androidsys.android/org.renpy.android.PythonActivity: +213ms
03-14 16:26:50.886 I/Timeline(802): Timeline: Activity_windows_visible id: ActivityRecord{36ec01d9 u0 org.androidsys.android/org.renpy.android.PythonActivity t978} time:216379363
03-14 16:26:52.157 W/PackageManager(1237): Failure retrieving resources for org.androidsys.android: Resource ID #0x0
03-14 16:26:53.194 W/PackageManager(1237): Failure retrieving resources for org.androidsys.android: Resource ID #0x0

**Comment by jboss38** [comment]
Same if i edit just the name without touch package name or logo

03-14 16:38:40.519 I/Timeline(1672): Timeline: Activity_launch_request id:org.pupy.android time:217088996
03-14 16:38:40.520 I/ActivityManager(802): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.pupy.android/org.renpy.android.PythonActivity (has extras)} from uid 10066 on display 0
03-14 16:38:40.526 V/WindowManager(802): addAppToken: AppWindowToken{21997c99 token=Token{2bf741e0 ActivityRecord{295d43e3 u0 org.pupy.android/org.renpy.android.PythonActivity t999}}} to stack=1 task=999 at 0
03-14 16:38:40.545 V/WindowManager(802): Adding window Window{6dcf836 u0 Starting org.pupy.android} at 4 of 9 (after Window{1ca89afe u0 com.nolanlawson.logcat/com.nolanlawson.logcat.LogcatActivity})
03-14 16:38:40.574 I/ActivityManager(802): Start proc 21547:org.pupy.android:python/u0a155 for activity org.pupy.android/org.renpy.android.PythonActivity
03-14 16:38:40.670 E/art     (21547): dlopen("/data/data/org.pupy.android/files/lib/python2.7/lib-dynload/_sqlite3.so", RTLD_LAZY) failed: dlopen failed: library "/data/data/org.pupy.android/files/lib/python2.7/lib-dynload/_sqlite3.so" not found
03-14 16:38:40.671 E/art     (21547): dlopen("/data/data/org.pupy.android/files/lib/python2.7/lib-dynload/_imaging.so", RTLD_LAZY) failed: dlopen failed: library "/data/data/org.pupy.android/files/lib/python2.7/lib-dynload/_imaging.so" not found
03-14 16:38:40.686 V/WindowManager(802): Adding window Window{17cee310 u0 org.pupy.android/org.renpy.android.PythonActivity} at 4 of 10 (before Window{6dcf836 u0 Starting org.pupy.android})
03-14 16:38:40.746 I/ActivityManager(802): Displayed org.pupy.android/org.renpy.android.PythonActivity: +205ms
03-14 16:38:41.042 I/Timeline(802): Timeline: Activity_windows_visible id: ActivityRecord{295d43e3 u0 org.pupy.android/org.renpy.android.PythonActivity t999} time:217089519
03-14 16:38:43.969 W/PackageManager(1237): Failure retrieving resources for org.pupy.android: Resource ID #0x0

**Comment by jboss38** [comment]
Did i miss somethings when compiling ? 
Cuz there is no error when generate the payload. Look All ok but i dont find why Its not working :/

**Comment by n1nj4sec** [comment]
IDK, it looks like you have multiple problems: missing some .so and you can't load some resources : 
```
 03-14 16:38:40.670 E/art (21547): dlopen("/data/data/org.pupy.android/files/lib/python2.7/lib-dynload/_sqlite3.so", RTLD_LAZY) failed: dlopen failed: library "/data/data/org.pupy.android/files/lib/python2.7/lib-dynload/_sqlite3.so" not found
03-14 16:38:40.671 E/art (21547): dlopen("/data/data/org.pupy.android/files/lib/python2.7/lib-dynload/_imaging.so", RTLD_LAZY) failed: dlopen failed: library "/data/data/org.pupy.android/files/lib/python2.7/lib-dynload/_imaging.so" not found
Failure retrieving resources for org.pupy.android: Resource ID #0x0
```
obvious solution : compile the .so and embed the missing resource

**Comment by jboss38** [comment]
Cannot find any working solution to the .so missing resource on the web atm

Is this can be the cause ? : https://github.com/kivy/python-for-android/issues/925

**Comment by quentinhardy** [comment]
The last time I have tried to compile the apk from source (few months ago), it think I had the same problem as you  :unamused:

**Comment by nostaldamask** [comment]
I experienced the same problem and I was able to resolve it by,

1) Changing the copy path for PythonActivity.java in build.sh
```
pupy/client/android_sources/build.sh
- cp PythonActivity.java .buildozer/android/platform/python-for-android/src/src/org/renpy/android/PythonActivity.java
+ cp PythonActivity.java .buildozer/android/platform/python-for-android/dist/pupy/src/org/renpy/android/PythonActivity.java

```
2) Uncommenting setContentView in PythonActivity.java
```
pupy/client/android_sources/PythonActivity.java
- //setContentView(mView);
+ setContentView(mView);

```
