### ISSUE TITLE
Running pupy in mac OS Sierra

### ISSUE THREAD

**Issue by santidediego** [n1nj4sec/pupy#332]
I´m trying to run pupy in a mac OS Sierra system and I´m unable to connect with a Linux host using a python payload. 

I generate the payload with: ./pupygen.py -f py connect --transport ssl --host 172.20.96.110

and I create the server with: sudo ./pupysh.py -t ssl

I have no idea about what´s happening, is pupy tested to work in a Mac computer?

**Comment by n1nj4sec** [comment]
are you running the payload on mac or pupysh ? The payload works on mac, pupysh on mac should work but is not really tested. If you don't have any errors, check your firewall rules, start tcpdump and see what happens

**Comment by santidediego** [comment]
I'm running pupysh in mac (the server) and the payload in a Linux system. It seem's that the payload is correctly generated but when I execute it in Linux while the server is running in my mac I have an error (handshake error) in my Linux terminal. I'll keep investigating.
