### ISSUE TITLE
Use telegram or other c&c server 

### ISSUE THREAD

**Issue by LeaklessGfy** [n1nj4sec/pupy#337]
Hello,

First, thanks for your work on pupy. I was wondering if it's possible to use a c&c server (like telegram) ? Or, have you plan to make it possible ? Like braindamage does.

Thanks you :)

**Comment by ChipWolf** [comment]
As in, the chat platform?

**Comment by n1nj4sec** [comment]
not planned but everything is possible, If you wish to make it I will gladly accept PR :)
