### ISSUE TITLE
Modular based client - lowering AV detection

### ISSUE THREAD

**Issue by CyDoor** [n1nj4sec/pupy#338]
Overall, you guys doing great work.
i would like to suggest to implent a option that you could which features going to be implemented in the client build.
this should lower the av detection rate and make the stub smaller. # # # #

**Comment by n1nj4sec** [comment]
Too complicated there are other ways to bypass AV. For the stub size, @alxchk made it awesomely small check out the unstable branch, the PE size has been smashed to 3.2 MB

**Comment by CyDoor** [comment]
ty 4 youre fast reply & the information.
