### ISSUE TITLE
Pyinstaller support

### ISSUE THREAD

**Issue by byt3bl33d3r** [n1nj4sec/pupy#34]
Pyinstaller 3.0 added python bytecode encryption and UAC elevation support which would benefit pupy a great deal IMHO, was wondering if there's a specific reason why py2exe was used and if it was possible to make the pupy bootloader compatible with pyinstaller?

**Comment by n1nj4sec** [comment]
the pupy bootloader was inspired from py2exe because py2exe can load .pyd from zip files. pyinstaller just drop all .py, .pyc and .pyd in a temp folder and change the python path. I guess that's why encrypting python bytecode is usefull in this case. In our case I don't see the point of dooing this as the code is already opensource and the rpyc bootloader is very small. for the UAC, it's just a manifest to attach to the exe and we are done :) you can do it using mt.exe

**Comment by byt3bl33d3r** [comment]
@n1nj4sec yup totally get that just thought it would be a cool feature to have anyway, as for the manifest I wasn't aware of mt.exe will have to look into that

**Comment by n1nj4sec** [comment]
On the other hand, I think you can natively use pyinstaller to build linux & osx payloads without any problem. For windows, the only problem is you would have to compile the "pupy" module from pupy.c into a standalone .pyd, but it is probable that this .pyd would be detected by antiviruses as soon as you start the payload and pyinstaller drops it into it's temp folder _MEI*

**Comment by darmoy** [comment]
I wish to be able to use PyInstaller also. Well mainly being able to get my hand on the pre compiled code before it become a PE. 
Because the problem is, the binary generated by pupy are flagged by most A/V

**Comment by n1nj4sec** [comment]
Hello @darmoy !
You can get your hands on it, all the pupy source code is in the repository ! search harder :p 
For pyinstaller, we could make pupy compatible without too much effort by compiling the builtin pupy.c into a .pyd. The main problem is that antivirus software will probably detect pupy with the .pyd which will be dropped at runtime by pyinstaller in %TEMP%/_MEIXXX. 
If all you want is to have an undetectable exe, it is really simple and it only takes around 10 lines of C code with the following steps :
1. download MemoryModule.c and MemoryModule.h from the amazing [MemoryModule](https://github.com/fancycode/MemoryModule) project
2. generate a pupyx86.dll with pupygen.py
2. encode/xor/crypt/obfuscate as you wish the raw dll and embed it into a char buffer[]
3. decode your buffer at execution
4. call MemoryLoadLibrary(buffer);
5. enjoy ;-)

**Comment by darmoy** [comment]
Thx, i did that and .... worked like a charm :+1: 
Sorry for the delay in my response

**Comment by marcovillar** [comment]
Can you share what you done exactly? i been trying to figure out how to bypass a simple av
without any luck:/ i read everything i could on loadmodule project to understand how its working (coming from a unix backgroud) but i didnt understand the whole decode your buffer at execution :/
Would love to get some input from people who already succeed doing so.
Thanks in advance.
