### ISSUE TITLE
Feature List for IOS support

### ISSUE THREAD

**Issue by LAzyFrAAnk** [n1nj4sec/pupy#350]
It would be great if add IOS supports

Ref: https://github.com/neoneggplant/EggShell

**Comment by n1nj4sec** [comment]
offer me an iphone and I will definitively work on this ;)

**Comment by LAzyFrAAnk** [comment]
Definitely yes..... :P

**Comment by jboss38** [comment]
https://developer.apple.com/library/content/documentation/IDEs/Conceptual/iOS_Simulator_Guide/TestingontheiOSSimulator/TestingontheiOSSimulator.html

Good Luck !
