### ISSUE TITLE
Cant listen to my public ip

### ISSUE THREAD

**Issue by adalenv** [n1nj4sec/pupy#352]
i have open port 4444 and edited pypy.conf addres to my public ip
error:

`[*] Server started on xx.xx.xx.xx port 4444 with transport ssl
>> ERROR:root:[Errno 99] Cannot assign requested address
Traceback (most recent call last):
  File "/root/Desktop/pupy/pupy/pupylib/PupyServer.py", line 300, in run
    self.server = t.server(PupyService.PupyService, port = self.port, hostname=self.address, authenticator=authenticator, stream=t.stream, transport=t.server_transport, transport_kwargs=t.server_transport_kwargs, ipv6=self.ipv6)
  File "/root/Desktop/pupy/pupy/network/lib/servers.py", line 119, in __init__
    ThreadedServer.__init__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/utils/server.py", line 78, in __init__
    self.listener.bind((hostname, port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 99] Cannot assign requested address

`

**Comment by CyDoor** [comment]
if you r behind a firewall or router, the public ip is not set at your local eth.
if so, you can pupy let listen to 0.0.0.0, then pupy listen to port 4444 on all incoming connections

**Comment by adalenv** [comment]
i hav forwarded the port

**Comment by n1nj4sec** [comment]
http://bfy.tw/4wGy

**Comment by adalenv** [comment]
![1](https://cloud.githubusercontent.com/assets/7238874/25048797/97b5acae-213e-11e7-9dae-bcaac28b060e.PNG)
![2](https://cloud.githubusercontent.com/assets/7238874/25048798/995937ec-213e-11e7-9b58-a1efa1b0ac63.PNG)

**Comment by n1nj4sec** [comment]
Please try to open a python shell and bind a socket on your public IP. If you can't the problem, go report this on python.org. I bet the problem is either in python or between your seat and your keyboard

**Comment by adalenv** [comment]
I would be very grateful if you make a tutorial video with public ip
thanks
