### ISSUE TITLE
UTF 8 code/Unicode Support

### ISSUE THREAD

**Issue by LAzyFrAAnk** [n1nj4sec/pupy#355]
Hi guy,
I tried to make some Chinese (Traditional and Simplified) folders and files into target computer. It's shown as below screen. 
![image](https://cloud.githubusercontent.com/assets/27416170/25169190/acc7b852-2518-11e7-8c10-bb2db5ea7fc3.png)

How can display any language? Such as Chinese, Japanese...etc

**Comment by alxchk** [comment]
https://github.com/alxchk/pupy/commit/96bbb4f89585eb52cde7c4aaced420201c8c5a04

**Comment by AlessandroZ** [comment]
To avoid errors, I replace not printable char by "?"

However, it changes now. I also had some printing errors. With the last version of basic_cmd I have this error doing an ls: 
`[-] 'ascii' codec can't encode character u'\xe9' in position 6: ordinal not in range(128)`

And when I use your last basic_cmd @alxchk, I have this issue (which is the same with the stacktrace in addition): 
```
[-] 'ascii' codec can't encode character u'\xe9' in position 2006: ordinal not in range(128)

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\rpyc\core\protocol.py", line 305, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "C:\Python27\Lib\site-packages\rpyc\core\protocol.py", line 535, in _handle_call
    return self._local_objects[oid](*args, **dict(kwargs))
  File "<string>", line 208, in exposed_json_dumps
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 2006: ordinal not in range(128)
```

**Comment by AlessandroZ** [comment]
It's easy to fix my issue changing the the "ls" module (removing the unicode prefix and adding the ".encode('utf-8', errors='ignore')" as following: 

```
def output_format(file):
    out = '  {}{}{}{}{}{}{}'.format(
        '{:<10}'.format(file_timestamp(file['ts'])),
        '{:<3}'.format(file['type']),
        '{:<5}'.format(file['uid']),
        '{:<5}'.format(file['gid']),
        ' {:06o} '.format(file['mode']),
        '{:<11}'.format(size_human_readable(file['size'])),
        '{:<40}'.format(file['name'].encode('utf-8', errors='ignore')))
```
However, doing like that unicode will be never managed. So I won't do a pull request before to decide if we stay in ascii or we use unicode (and find a solution for encoding issue).

**Comment by alxchk** [comment]
I changed to unicode, because in other case there will no be any unicode on windows at all. This should work on latest templates (because pp.py/obtain were changed). I'll double check when be at home

**Comment by n1nj4sec** [comment]
I confirm it's working with @alxchk patch if you recompile the templates (I only push them to the pupy-binaries repository for the master branch)
![screenshot from 2017-04-21 18-34-39](https://cloud.githubusercontent.com/assets/12549318/25287452/a1e46908-26c1-11e7-9079-a22abd632906.png)

**Comment by LAzyFrAAnk** [comment]
@alxchk @n1nj4sec @AlessandroZ Thanks for your reply. I will try to coming week. Will let you know the outcome. And I may plan to make UI to pupy and test some WOL script to remote host. hope let it amazing. Coz have time. :P

**Comment by alxchk** [comment]
> And I may plan to make UI 

This will not be an easy task. Currently architecture is a bit "stdio-oriented". Also tonns of logic in Cmd handler and so on.  Maybe it's better to put efforts in other directions..

**Comment by LAzyFrAAnk** [comment]
@alxchk Alright, I'll put efforts in other directions. 

And just got some errors  after upgraded pupy by git. 

![capture](https://cloud.githubusercontent.com/assets/27416170/25312478/847a8e74-284c-11e7-92da-7063499ef006.JPG)

**Comment by n1nj4sec** [comment]
```pip install -r requirements.txt```

**Comment by LAzyFrAAnk** [comment]
Error had solved. But all remote hosts had gone, nothing is shown on pupysh, even I installed new one to new remote host..

**Comment by LAzyFrAAnk** [comment]
hi @alxchk Got the below error after recompiled #96bbb4f 

![image](https://cloud.githubusercontent.com/assets/27416170/25449071/259347d6-2aed-11e7-957a-6c16aa398845.png)

**Comment by alxchk** [comment]
Well, on my latest head I don't have this, but didn't met earlier either.

**Comment by LAzyFrAAnk** [comment]
hmmm...... no idea on it.... just rechecking again.

**Comment by LAzyFrAAnk** [comment]
@alxchk  problem solved, I made stupid mistake. Anyways, I really appreciated your help. And will close this ticket after test all features

**Comment by LAzyFrAAnk** [comment]
Just tested, everything is working fine, just little error as below 
![image](https://cloud.githubusercontent.com/assets/27416170/25493226/05f70776-2ba8-11e7-8d47-9fb438f2d71a.png)

**Comment by n1nj4sec** [comment]
You probably made a mistake again

**Comment by LAzyFrAAnk** [comment]
@n1nj4sec @alxchk @AlessandroZ 

Language display had been solved, even Chinese with traditional, simplified, Russian, Japanese . Many tks all guys effort  

![image](https://cloud.githubusercontent.com/assets/27416170/25565479/229b6e68-2dfa-11e7-954e-b0dc520cbc6c.png)
