### ISSUE TITLE
Bypass Nautilus execution control

### ISSUE THREAD

**Issue by fastfire** [n1nj4sec/pupy#357]
Hi! How can I bypass "view executable text files when they are opened" control in Nautilus? In which format I need to generate payload? Thank you!
![nautilus_execution_control](https://cloud.githubusercontent.com/assets/16737186/25264898/41005cde-266a-11e7-8842-c5dfe6a189da.png)

**Comment by fastfire** [comment]
mmm... why closed?

**Comment by n1nj4sec** [comment]
Because I don't have a 0day on nautilus and your question is not pupy related.
