### ISSUE TITLE
Transport keys and certificates missing

### ISSUE THREAD

**Issue by grafnugi** [n1nj4sec/pupy#366]
I had this tool working until the last update, about a week ago... ever since then, every time I try to generate a payload, it generates but with the error:

[+] Required credentials:
[+] SIMPLE_RSA_PRIV_KEY, SSL_CA_CERT, SSL_CLIENT_CERT, ECPV_RC4_PUBLIC_KEY, SSL_BIND_KEY, SSL_BIND_CERT, SSL_CLIENT_KEY, SCRAMBLESUIT_PASSWD, SIMPLE_RSA_PUB_KEY, ECPV_RC4_PRIVATE_KEY, DNSCNC_PUB_KEY

There must be something obvious Im missing here, because it was working almost perfectly before the update... any help would be appreciated.

**Comment by n1nj4sec** [comment]
Try :
```
rm crypto/credentials.py
```
And restart pupysh.py to regenerate the file

**Comment by grafnugi** [comment]
Same problem persists. Any other ideas?

**Comment by grafnugi** [comment]
That error occurs when I try to generate a dnscnc payload... when i try to generate a pyinst payload with ssl transport I get
[+] Required credentials:
[+] SSL_BIND_CERT, SSL_CA_CERT, SSL_CLIENT_CERT, SSL_BIND_KEY, SSL_CLIENT_KEY

This problem persists over multiple different servers that I have tested.

**Comment by n1nj4sec** [comment]
if there is no exception and the payload is well created, it's a standard message to warn you about the credentials it will embed in the payload, it's not an error

**Comment by xuxuedong** [comment]
thanks a lot
