### ISSUE TITLE
 git submodule update  take a lot of time 

### ISSUE THREAD

**Issue by mamoudmatook** [n1nj4sec/pupy#367]
hi 
 git submodule update   is trapped at this step 
it took  a lot of time but still at this 
`git submodule update
`Cloning into '/root/play/pupy/pupy/external/LaZagne'...
`

**Comment by NeverMine17** [comment]
Try to retry update. There is might be something with your internet connection. Have you tried checking your options?

**Comment by mamoudmatook** [comment]
Internet connection is woking 
Settings of what ?

**Comment by NeverMine17** [comment]
Im talking about your system settings, like proxy. Maybe its something with your PC.

**Comment by NeverMine17** [comment]
Just tried `git submodule update`. Everything is fine.
