### ISSUE TITLE
Loading pupy.dll with memorymodule( fancycode )

### ISSUE THREAD

**Issue by whit3he4d** [n1nj4sec/pupy#383]
Hi everyone,
i want to load the pupy.dll from memorymodul which works. But I don't know how I can load functions.
Heres my code.
What Im doing wrong?

`
       typedef void(*initpupy)(void);
       void LoadFromMemory(void)
       {
          void *data;
          size_t size;
          HMEMORYMODULE handle;
          addNumberProc addNumber;
          HMEMORYRSRC resourceInfo;
         DWORD resourceSize;
         LPVOID resourceData;
         TCHAR buffer[100];

	initpupy initp;

    //data = ReadLibrary(&size);
	
	data = rawData;
	size = sizeof(rawData);
	if (data == NULL)
    {
        return;
    }

    handle = MemoryLoadLibrary(data, size);
    if (handle == NULL)
    {
        _tprintf(_T("Can't load library from memory.\n"));
        goto exit;
    }
	
	initp = (initpupy)MemoryGetProcAddress(handle, "initpupy");

    MemoryFreeLibrary(handle);

    exit:
        free(data);
    }
`

**Comment by n1nj4sec** [comment]
you don't need to call anything except MemoryLoadLibrary follower by while(1){Sleep(10000);} (because pupy's DLL creates a new thread and you don't want your main thread to exit.) You probably also want to rethink what sizeof actually do, but I let you figure it out

**Comment by whit3he4d** [comment]
thank you very much. no its clear to me
