### ISSUE TITLE
Unable to run pupy client on MacOS

### ISSUE THREAD

**Issue by ABorrello** [n1nj4sec/pupy#386]
Hey,
I'm having some trouble building and running payloads on MacOS.

The command I am using to generate the payload is `python pupygen.py -f py -O linux connect --host [IP]:[PORT] --transport ssl`. I have also tried several variations on that command, but I get the same result every time I run the payload on my test machine.

When I run the payload with `python payload.py`, the following error is returned:
```
Traceback (most recent call last):
  File "payload.py", line 4, in <module>
    [BASE64 SEGMENT FROM payload.py]'))
  File "<string>", line 11, in <module>
  File "<string>", line 567, in install
  File "<string>", line 424, in find_module
KeyError: 'pywintypes27.dll'
```
Every payload I tried to generate resulted in the same error. I did some searching but could find no similar issues on the GitHub repo.

Let me know if I am just doing something stupid, or if you need more information.

**Comment by n1nj4sec** [comment]
fixed
