### ISSUE TITLE
Credentials password

### ISSUE THREAD

**Issue by mny123** [n1nj4sec/pupy#388]
Hi,

I'm new to pupy and I've a problem with the credentials password. I'm using kali linux 2.0 and the newest release of pupy. Every time I try to generate a payload (no matter which one), pupy ask me to insert the credentials password.

I've googled a lot, studied the wiki, had a search whithin pupy, but without success. There is a credentials.py file, but editing gives me no password.

Please, tell me the credentials password or, if this is impossible, give me the exact way to find it out.

Thanks in advance

**Comment by n1nj4sec** [comment]
it's your password defined at install
