### ISSUE TITLE
installation failed. 

### ISSUE THREAD

**Issue by osmancoskun** [n1nj4sec/pupy#392]
i got this error at the end of last command while installing 
`pip install -r pupy/requirements.txt`
*******
Collecting scapy (from -r pupy/requirements.txt (line 17))
  Using cached scapy-2.3.3.tgz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-t6zp_tak/scapy/setup.py", line 36
        os.chmod(fname, 0755)
                           ^
    SyntaxError: invalid token
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-t6zp_tak/scapy/
*******

**Comment by n1nj4sec** [comment]
scapy issue
