### ISSUE TITLE
hangs on git submodule update.

### ISSUE THREAD

**Issue by praveenyadav1602** [n1nj4sec/pupy#393]
git submodule update
Cloning into '/root/pupy/pupy/external/LaZagne'...

and its never ends.

 i am using kali 2016.2 amd64

**Comment by jiraiyalegendarysannin** [comment]
It is a very big module, so it takes some time. If you want to see the progress you could directly clone it into the "external" folder.

```
#cd external/
#git clone https://github.com/AlessandroZ/LaZagne
```

**Comment by praveenyadav1602** [comment]
thanks, its solved
