### ISSUE TITLE
Suggestion: Multi-User

### ISSUE THREAD

**Issue by aidden-laoch** [n1nj4sec/pupy#397]
It seems to me the only thing lacking is the ability to have multiple users. Similar to how Cobalt Strike allows for multiple pentesters to connect to a single server running the listener. That would be amazing! Even if multiple users couldn't control the same session at the same time. It would be a great feature to be able to have one user leverage session 1 while another user works with session 2. Hopefully that makes sense.

**Comment by AlessandroZ** [comment]
It seems to be very complicated to add this feature without creating a GUI (a web application or a thick client) but interactive modules should not work as well on an interface as it works now on a terminal. 

The only interactive shell I have seen in a web application is the shell used by cozy cloud which is great, you feel to be in a real terminal: https://github.com/alpha14/cozy-term

But integrating pupy in a web application it's a lot of work and that's not my priority at this moment. I just wanted to share the interactive shell project.
