### ISSUE TITLE
Bind not working?

### ISSUE THREAD

**Issue by wormy638** [n1nj4sec/pupy#398]
I have yet to get the bind launcher option to work for Windows or Linux.
./pupygen.py -f [tried py,client,ps1] bind --host {tried localip and global} --port ####
--Attempted on Debian Jessie and Windows 7x64
I can get regular connect launchers to work, so I know its not a network issue or an issue with windows defender or anything.

**Comment by wormy638** [comment]
Clarifying: I did change the architecture with the '-A' option, just forgot to put it in the OP.

**Comment by alxchk** [comment]
Try to build with --debug.
Likely fails because of this: https://github.com/alxchk/pupy/commit/0238d7c610622671821bdab5ecc37751d8b20dc9
