### ISSUE TITLE
Abstract/Modular-ize the communication channel

### ISSUE THREAD

**Issue by 0x27** [n1nj4sec/pupy#4]
Not sure how to phrase this, but it would be perhaps interesting to make the communication channel modular, so that you can have whatever communication channel you can think of implemented (DNS, ICMP, UDP, etc), so long as it passes a functioning filedescriptor for a socket object back to the main implant/client.

This way modules can be written for C&C channels over say, UDP, DNS, ICMP... etc.

**Comment by byt3bl33d3r** [comment]
@0x27 I was actually just looking into this, unfortunately i don't see a simple way of implementing this since communication with the bots revolves around the rpyc library which only support SSL/TLS and SSH.

I'm guessing we could somehow tunnel rpyc traffic through other protocols but it would require writing a lot of code server and client side, and might complicate things way too much. Would love to hear if @n1nj4sec has any idea on how to do this efficiently

**Comment by 0x27** [comment]
Well, it could be easier to just modify rpyc and ship a modified version as part of the codebase, than trying to tunnel it over other stuff?

After all, SSH/SSL/TLS and all that just acts as a socket in the end, so we can probably just "snip" at some point. Then again, could be oversimplifying the problem :)

**Comment by deathfantasy** [comment]
It's doable by writing an alternate transport and accompanying authenticator for rpyc, then the rest is plug-and-play.

**Comment by byt3bl33d3r** [comment]
@deathfantasy agreed, thats probably the best way to go about it

**Comment by n1nj4sec** [comment]
I totally agree with @deathfantasy, I didn't looked deeply in rpyc implementation yet, but it seems that the right way to do it would be to create a subclass of "rpyc.core.stream.Stream"

**Comment by 0x27** [comment]
Was looking through the pile of "stuff", and this stuck out as interesting as potentially a source of ideas for alternative C&C channels.

https://github.com/ytisf/PyExfil

Will have to look into how rpyc actually works, see if extra "channels" can be trivially added to it :)

**Comment by deathfantasy** [comment]
I am eyeing the [Tor pluggable transport](https://gitweb.torproject.org/torspec.git/tree/pt-spec.txt) mechanism; all we need to do is manage the PT proxy and wrap the rpyc socket under socks5 (using e.g. PySocks). obfsproxy is written in Python so we can perhaps even embed it in our process, I'll have to ask @n1nj4sec for that. I might do it if I have some time, but please chip in if you can.

**Comment by 0x27** [comment]
As much as I hate to promote projects I work on in other projects... Here's something that would be fairly cool to implement/add once we have a working release (soon!). This way you could have the C&C server as a Tor hidden service, or do it in reverse and have the pwned box spin up its own HS that the client connects to (kind of like a bindshell).

[pycepa - Pure Python Tor Implementation](https://github.com/pycepa/pycepa/)

As per [pycepa - Pure Python Tor Implementation/Issue 19](https://github.com/pycepa/pycepa/issues/19), we actually intend to implement pluggable transport support using the extant pluggable transport framework (for compatibility with extant Torproject stuff) once we reach that goal (eventually.)

**Comment by byt3bl33d3r** [comment]
@deathfantasy that's really clever, will probably take a stab at implementing this today if it's ok with everybody

**Comment by byt3bl33d3r** [comment]
@n1nj4sec @0x27 Just tested @deathfantasy's idea of using obfsproxy and it works beautifully, better yet only two lines of code to tie us in! Just need to integrate obfsproxy and will send a PR later today! \o/

**Comment by n1nj4sec** [comment]
nice ! :D thx @byt3bl33d3r

**Comment by n1nj4sec** [comment]
obfsproxy is a good idea btw :-)

**Comment by 0x27** [comment]
Beautiful work @byt3bl33d3r :D

**Comment by 0x27** [comment]
Related (and now possible thanks to you guys being awesome): Now that obfsproxy/pluggable transport support is soon to be in place... An interesting avenue of development (that I intend to pursue) is "Adversary Simulation" ala [the Cobalt Strike functionality](http://blog.cobaltstrike.com/2014/11/12/adversary-simulation-becomes-a-thing/). Probably the easiest way to do this (off the top of my head) is to simply write a pluggable transport module that does traffic like the thing I want to simulate/model or something.

**Comment by byt3bl33d3r** [comment]
Ok so I encountered an initial problem when integrating obfsproxy, after adding the required deps to the libraryx*.zip files so we can have it built into the payloads the resulting size is too big (33MB), so I'm currently trying to see if I can rip out the client part of obfsproxy and just add that in. fingers crossed

**Comment by deathfantasy** [comment]
Most of the size is in Twisted. Instead of ripping out the client obfsproxy code, you can gut Twisted to its minimum needed to run obfsproxy. I deleted most of the unneeded modules and got it down to 8.5 MB, and you can probably slim it down further. Same applies to other packages.

**Comment by byt3bl33d3r** [comment]
@deathfantasy yep I was just about to start doing that actually :+1:

**Comment by byt3bl33d3r** [comment]
Ok I got twisted down to 3.1 MB (I could slim that down even further i think)! Huzzah! the whole zip file  currently comes to a grand total of 18M which i still think is to big in my opinion
```
108K	libraryx64/unittest
20K	libraryx64/pyptlib/util
76K	libraryx64/pyptlib
12K	libraryx64/xml/parsers
20K	libraryx64/xml
52K	libraryx64/json
68K	libraryx64/zope/interface/common
308K	libraryx64/zope/interface
312K	libraryx64/zope
396K	libraryx64/pydoc_data
552K	libraryx64/twisted/protocols
728K	libraryx64/twisted/python
124K	libraryx64/twisted/logger
668K	libraryx64/twisted/web
976K	libraryx64/twisted/internet
3.1M	libraryx64/twisted
76K	libraryx64/rpyc/utils
112K	libraryx64/rpyc/core
24K	libraryx64/rpyc/lib
224K	libraryx64/rpyc
8.0K	libraryx64/email/mime
164K	libraryx64/email
212K	libraryx64/yaml
60K	libraryx64/distutils
40K	libraryx64/pyreadline/keysyms
60K	libraryx64/pyreadline/lineeditor
136K	libraryx64/pyreadline/modes
48K	libraryx64/pyreadline/console
20K	libraryx64/pyreadline/clipboard
356K	libraryx64/pyreadline
24K	libraryx64/ctypes/macholib
68K	libraryx64/ctypes
16K	libraryx64/multiprocessing/dummy
192K	libraryx64/multiprocessing
100K	libraryx64/logging
84K	libraryx64/Crypto/Cipher
200K	libraryx64/Crypto/Util
36K	libraryx64/Crypto/Protocol
28K	libraryx64/Crypto/Random/Fortuna
24K	libraryx64/Crypto/Random/OSRNG
80K	libraryx64/Crypto/Random
96K	libraryx64/Crypto/PublicKey
56K	libraryx64/Crypto/Hash
28K	libraryx64/Crypto/Signature
592K	libraryx64/Crypto
604K	libraryx64/encodings
18M	libraryx64
```

**Comment by deathfantasy** [comment]
Could you push your code and the library file? I would like to have a look if possible.
Is the library slimming scripted or manual?

**Comment by byt3bl33d3r** [comment]
@deathfantasy Done! https://github.com/byt3bl33d3r/pupy-lib added you and @n1nj4sec  as collaborators so you can push directly

**Comment by byt3bl33d3r** [comment]
slimming is manual atm, once we have it nailed down it can be easily scripted

**Comment by byt3bl33d3r** [comment]
just to be clear ( I should have made this clearer earlier) the library is 18M uncompressed, compressed its 6.4MB (vs the original 5.2MB )

**Comment by shellster** [comment]
Maybe not the right thread, but one transport I'd like to see is SSH via the paramiko library.

To toot my own horn, I recently made major changes to MeterSSH, which just got pulled into the original tool.  Using the library is pretty straightforward (as can be seen in the MeterSSH source).  The nice thing about SSH is the portfwd can be completely transparent to the client and server.

**Comment by byt3bl33d3r** [comment]
@shellster rpyc supports ssh out-of-the-box so that shouldn't be a problem ;)

**Comment by shellster** [comment]
Even better!

**Comment by n1nj4sec** [comment]
and port forward shouldn't be hard to implement in pure python using rpyc. All we have to do is retrieve a socket object from the client proxyfied through rpyc and pipe it with a local socket :-) (like in the socks5 module)

**Comment by n1nj4sec** [comment]
In case some of you are working on it, stop :-) modularized transports are on their way I just need to clean up a little my code and make the windows binary customizable in pupygen :) I already have implemented tcp_cleartext, tcp_base64, obfs3 and tcp_ssl transports ! other obfsproxy modules should integrate fine with a little work on dropping twisted dependencies (like I did for obfs3)
