### ISSUE TITLE
rpyc crash on run memory_exec

### ISSUE THREAD

**Issue by kilbyjmichael** [n1nj4sec/pupy#40]
> run memory_exec /root/hack/kiwi/x64/mimikatz.exe
[-] Error in MapNewExecutableRegionInProcess: Errno 87

>========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "rpyc\core\protocol.pyc", line 305, in _dispatch_request
  File "rpyc\core\protocol.pyc", line 535, in _handle_call
  File "<string>", line 86, in run
Exception: Error in MapNewExecutableRegionInProcess: Errno 87
[%] interrupting remote process, please wait ...

**Comment by n1nj4sec** [comment]
I have the strange feeling you are trying to inject a x64 PE exe with a x86 Pupy payload. Can you confirm ? Please first migrate into a x64 process and try again ;)
migrate -c 'C:\Windows\SysNative\notepad.exe'

**Comment by n1nj4sec** [comment]
And another thing, you need to pass mimikatz arguments in parameter because I did not had time to implement the interactive stdin/stdout handling with this module yet
