### ISSUE TITLE
Pyinstaller: Failed to execute script pupy_xxxx.exe

### ISSUE THREAD

**Issue by grafnugi** [n1nj4sec/pupy#401]
Got a new problem that didnt used to happen until about two updates ago. When I build an exe file with pyinstaller from the py file generated by the "pyinst" option with pupygen, it fails to run, with the error message "Failed to execute script pupy_xxxx.exe."

This is a new problem, as I used to be able to generate exe's with pyinstaller and they worked perfectly.

**Comment by quentinhardy** [comment]
Probably some dependencies are missing in the py file generated.
Look if all dependencies in `requirements.txt` are in the pyinstaller file generated with _pyinst_ output.
Add `requests` in `requirements.txt` too (see https://github.com/n1nj4sec/pupy/pull/419/commits/293a7552635692c0ea6e7cf773105e2daffef17e).
