### ISSUE TITLE
Cant generate a android payload (Work with others one) [Pupy Server with docker]

### ISSUE THREAD

**Issue by tugdualnicolas** [n1nj4sec/pupy#405]
I got this error when i try to generate a android payload on pupy working on docker on my server (I removed my ip to ***.***.***.***) : 
`>> gen -O android connect --host ***.***.***.***
WARNING:root:Your templates are not synced with your pupy version ! , you should update them with "git submodule update"
[+] Generate client: android/x86
[C] launcher: connect
[C] launcher_args: ['--host', '***.***.***.***']
[C] debug: False
[C] offline_script: 
[+] Required credentials:
[+] SSL_BIND_CERT, SSL_CA_CERT, SSL_CLIENT_CERT, SSL_BIND_KEY, SSL_CLIENT_KEY
[+] generating payload ...
[+] packaging the apk ... (can take 10-20 seconds)
/bin/sh: 1: jarsigner: not found
[-] payload generation failed: Command 'jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore crypto/pupy-apk-release-key.keystore -storepass pupyp4ssword '/tmp/tmp_pupy_k6hMXR' pupy_key' returned non-zero exit status 127
`
My docker version `Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:13:40 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:13:40 2017
 OS/Arch:      linux/amd64
 Experimental: false
`

My server OS and version : 
`Distributor ID:	Parrot
Description:	Parrot 3.6 - JollyRoger
Release:	3.6
Codename:	JollyRoger
`

**Comment by alxchk** [comment]
Yes.. APK generation is not ready in docker image now

**Comment by tugdualnicolas** [comment]
Ho so its normal my bad ^^`

**Comment by alxchk** [comment]
Now it should works (but keystore should be generated manually)
