### ISSUE TITLE
Dont know what is this error :(

### ISSUE THREAD

**Issue by kdelia12** [n1nj4sec/pupy#406]
> Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-7IxkvZ/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-k3g_tu-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-7IxkvZ/cryptography/

Why?

**Comment by theCake75** [comment]
I think its about dependencies, you should install them manually

**Comment by kdelia12** [comment]
Manually?
can you explain the code? thanks :D

2017-05-31 3:53 GMT+07:00 theCake75 <notifications@github.com>:

**Comment by patoborracho** [comment]
try to install the requirements.txt one by one and u can find the error.

**Comment by kdelia12** [comment]
Ok problem Solved. But now, how can i start pupy? Thanks xD
Pada tanggal 1 Jun 2017 09.22, "patoborracho" <notifications@github.com>
menulis:

**Comment by harryw3266** [comment]
Thank you!
Spark by Readdle

**Comment by kdelia12** [comment]
Guys? Hoe to start it please
Pada tanggal 1 Jun 2017 14.50, "harryw3266" <notifications@github.com>
menulis:

**Comment by ABorrello** [comment]
Check out the wiki for information on setting up and using the pupy server:
https://github.com/n1nj4sec/pupy/wiki/Setting-up-the-server
