### ISSUE TITLE
ImportError: No module named platform (Not solvable with pip)

### ISSUE THREAD

**Issue by patoborracho** [n1nj4sec/pupy#409]
Hi,

I generate payloads with the next commands:

`python pupygen.py -A x86 -O windows -f py connect --host x.x.x.x`
`python pupygen.py -f py connect --host x.x.x.x`

I test the .py in linux and windows and I get this error:

> Traceback (most recent call last):
>   File "pupy_ed1jac.py", line 4, in <module>
>     QCWiTYrOsGgsfLqq5..../QMytuvm'))
>   File "<string>", line 11, in <module>
>   File "<string>", line 472, in install
> ImportError: No module named platform

**Comment by patoborracho** [comment]
any help here? pls

**Comment by n1nj4sec** [comment]
platform is python standard library, please do not remove python standard library files

**Comment by patoborracho** [comment]
I reinstalled python 2.7 and the pupy requirements and it work :)

Now I have some other problems with autentication, with ssl in pupysh with debug on, it show failed autentication ( I put the same password in pupygen and pupysh, and checked multiple times xD).
And when I try with RSA it shows "polling on already closed connection"  (# The root of evil??)


Thanks @n1nj4sec

**Comment by quentinhardy** [comment]
Do you have more details about the problem (e.g. logs)?
