### ISSUE TITLE
error pip install -r pupy/requirements.txt

### ISSUE THREAD

**Issue by zProAle** [n1nj4sec/pupy#413]
psutil/_psutil_linux.c:12:20: fatal error: Python.h: No such file or directory

compilation terminated.

error: command 'gcc' failed with exit status 1

----------------------------------------
Command /usr/bin/python -c "import setuptools;__file__='/root/pupy/build/psutil/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-D5_CGI-record/install-record.txt failed with error code 1 in /root/pupy/build/psutil
Storing complete log in /root/.pip/pip.log

**Comment by Souhardya** [comment]
any comments tho ?
