### ISSUE TITLE
Installation Issue. followed Instructions Correctly

### ISSUE THREAD

**Issue by ThalaHemanth** [n1nj4sec/pupy#414]
Traceback (most recent call last):
  File "./pupygen.py", line 7, in <module>
    from pupylib.utils.network import get_listener_ip, get_listener_port
  File "/root/Desktop/pupy/pupy/pupylib/__init__.py", line 6, in <module>
    from PupyServer import *
  File "/root/Desktop/pupy/pupy/pupylib/PupyServer.py", line 30, in <module>
    from pupylib.PupyDnsCnc import PupyDnsCnc
  File "/root/Desktop/pupy/pupy/pupylib/PupyDnsCnc.py", line 4, in <module>
    from network.lib.picocmd.server import *
  File "/root/Desktop/pupy/pupy/network/lib/picocmd/server.py", line 17, in <module>
    import socketserver
ImportError: No module named socketserver

**Comment by n1nj4sec** [comment]
one of the pip dependency have failed, try pip install -r requirements.txt again

**Comment by ThalaHemanth** [comment]
pip install -r requirements.txt 
Requirement already satisfied (use --upgrade to upgrade): rpyc in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): pycryptodome in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): pefile in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): pyyaml in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): rsa in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): netaddr in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): ecdsa==0.13 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): paramiko==2.0.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): tinyec in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): psutil in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): netifaces in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): m2crypto in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 12))
Requirement already satisfied (use --upgrade to upgrade): pylzma in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 13))
Requirement already satisfied (use --upgrade to upgrade): mss in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 14))
Requirement already satisfied (use --upgrade to upgrade): colorama in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 15))
Requirement already satisfied (use --upgrade to upgrade): pyOpenSSL in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 16))
Requirement already satisfied (use --upgrade to upgrade): scapy in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 17))
Requirement already satisfied (use --upgrade to upgrade): impacket in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 18))
Requirement already satisfied (use --upgrade to upgrade): pyuv in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 19))
Requirement already satisfied (use --upgrade to upgrade): dnslib in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 20))
Requirement already satisfied (use --upgrade to upgrade): http-parser in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 21))
Requirement already satisfied (use --upgrade to upgrade): cerberus in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 22))
Requirement already satisfied (use --upgrade to upgrade): logutils in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 23))
Requirement already satisfied (use --upgrade to upgrade): secretstorage in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 24))
Requirement already satisfied (use --upgrade to upgrade): pygments in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 25))
Requirement already satisfied (use --upgrade to upgrade): plumbum in /usr/local/lib/python2.7/dist-packages (from rpyc->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.3 in /usr/lib/python2.7/dist-packages (from rsa->-r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): cryptography>=0.7 in /usr/lib/python2.7/dist-packages (from pyOpenSSL->-r requirements.txt (line 16))
Requirement already satisfied (use --upgrade to upgrade): six>=1.5.2 in /usr/lib/python2.7/dist-packages (from pyOpenSSL->-r requirements.txt (line 16))
Cleaning up...

**Comment by n1nj4sec** [comment]
try ``` pip install future ```

**Comment by ThalaHemanth** [comment]
It Worked, Thanks Mate for ur patience

**Comment by edenanthony** [comment]
installation issue! (on ubuntu 16.04 LTS X64) : 

:/opt/pupy/pupy# pip install -r requirements.txt
Requirement already satisfied: rpyc in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: pycryptodome in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: pefile in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied: pyyaml in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied: rsa in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 5))
Requirement already satisfied: netaddr in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 6))
Requirement already satisfied: ecdsa==0.13 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 7))
Requirement already satisfied: paramiko==2.0.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 8))
Requirement already satisfied: tinyec in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 9))
Requirement already satisfied: psutil in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 10))
Requirement already satisfied: netifaces in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 11))
Requirement already satisfied: m2crypto in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 12))
Requirement already satisfied: pylzma in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 13))
Requirement already satisfied: mss in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 14))
Requirement already satisfied: colorama in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 15))
Requirement already satisfied: pyOpenSSL in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 16))
Requirement already satisfied: scapy in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 17))
Requirement already satisfied: impacket in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 18))
Requirement already satisfied: pyuv in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 19))
Requirement already satisfied: dnslib in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 20))
Requirement already satisfied: http-parser in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 21))
Requirement already satisfied: cerberus in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 22))
Requirement already satisfied: logutils in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 23))
Requirement already satisfied: secretstorage in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 24))
Requirement already satisfied: pygments in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 25))
Requirement already satisfied: plumbum in /usr/local/lib/python2.7/dist-packages (from rpyc->-r requirements.txt (line 1))
**Requirement already satisfied: future** in /usr/local/lib/python2.7/dist-packages (from pefile->-r requirements.txt (line 3))
Requirement already satisfied: pyasn1>=0.1.3 in /usr/local/lib/python2.7/dist-packages (from rsa->-r requirements.txt (line 5))
Requirement already satisfied: cryptography>=1.1 in /usr/local/lib/python2.7/dist-packages (from paramiko==2.0.2->-r requirements.txt (line 8))
Requirement already satisfied: typing in /usr/local/lib/python2.7/dist-packages (from m2crypto->-r requirements.txt (line 12))
Requirement already satisfied: six>=1.5.2 in /usr/local/lib/python2.7/dist-packages (from pyOpenSSL->-r requirements.txt (line 16))
Requirement already satisfied: ipaddress in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.1->paramiko==2.0.2->-r requirements.txt (line 8))
Requirement already satisfied: idna>=2.1 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.1->paramiko==2.0.2->-r requirements.txt (line 8))
Requirement already satisfied: asn1crypto>=0.21.0 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.1->paramiko==2.0.2->-r requirements.txt (line 8))
Requirement already satisfied: enum34 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.1->paramiko==2.0.2->-r requirements.txt (line 8))
Requirement already satisfied: cffi>=1.7 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.1->paramiko==2.0.2->-r requirements.txt (line 8))
Requirement already satisfied: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.7->cryptography>=1.1->paramiko==2.0.2->-r requirements.txt (line 8))

**Comment by edenanthony** [comment]
I could fix it :)

install two packages : 

apt-get install python-requests-futures
apt-get install python3-requests-futures

**Comment by quentinhardy** [comment]
`pip install requests`

I think this issue can be closed now.
