### ISSUE TITLE
Not Working outside my Network. Port Forwarded on my Router.

### ISSUE THREAD

**Issue by ThalaHemanth** [n1nj4sec/pupy#415]
I'm Still a noob. How to make this thing work outside my network. i didn't find any proper documentation or tutorials on this topic

**Comment by patoborracho** [comment]
You need to open the port in the router and in pupy you have to use your public IP.

**Comment by ThalaHemanth** [comment]
Added rule in firewall, opened port in vmware and router as well. used public ip in pupy. still didnt work

**Comment by patoborracho** [comment]
First make a test in the host:

-Open port 82
-With netcat:

`nc -lvvp 82`

-Then go to http://www.yougetsignal.com/tools/open-ports/

and put your public ip and port 82, it will show you if it is open or close.

PS: In Vmware you have to check your networking, I guess the bridge mode is where you receive your own ip.

**Comment by glides** [comment]
No offense, but you're going to constantly have questions if you're struggling with that part. That's basic networking and has nothing to do with the code.

If you're trying to get into IT sec/Pen Testing but are very novice, try checking out Metasploit Unleashed for a reference guide for beginners and maybe brush up on some basic networking concepts.

**Comment by ThalaHemanth** [comment]
i agree there is no problem with code. i'm unable to open port in windows 10. i'll figure it out.

**Comment by quentinhardy** [comment]
I think this issue can be closed now.
