### ISSUE TITLE
Can't "ps" when ps1_oneliner payload is used

### ISSUE THREAD

**Issue by haxxxor2k** [n1nj4sec/pupy#416]
Steps taken
1) generate ps1_oneliner
2) delivered + executed on Windows 10 (one of thoe microsoft provided pre-built VMs for testing)
3) wait for connection, run "ps"

But pupy shell just kinda hangs.. 

![pupyhang](https://user-images.githubusercontent.com/29338842/27004865-94db6690-4ddf-11e7-8ddb-2a541d8dfe37.jpg)

This doesn't happen with file based payloads (i.e. exe or ps1)

**Comment by quentinhardy** [comment]
Strange. 
I have not this error on my Wind10.
Perhaps not enough memory on the system.
Do you have tried to run another command (e.g. `run admin/ip`) ?
