### ISSUE TITLE
No session after system reboot in target machine

### ISSUE THREAD

**Issue by kelvin2185** [n1nj4sec/pupy#420]
Hello, 

I have installed pupy and everything is working properly in a test environment.  When I run payload in a target machine i see session but if target system reboot I don't see session anymore from target unless I run payload again in target machine. I want to know if there is a way pupy can make payload always running in target system even if target reboot system or lost internet connectivity? Payload should always run in target machine as far target system is running.

Thanks.

**Comment by tugdualnicolas** [comment]
You need to make it persistent look at the wiki and the try "persistence -h" in the pupy shell

**Comment by kelvin2185** [comment]
i cant find it in wiki and when i run command  persistence -h in pupy shell i get  output:

>> persistence -h
[-] Unknown syntax: persistence -h

please kindly advise in details on how to achieve this.

**Comment by tugdualnicolas** [comment]
Sorry the command was : `run manage/persistence -h
`

**Comment by Raemey** [comment]
there is a small bug in the registry persistence code that keeps it from populating the correct registry value data. I've noted that as another issue.

**Comment by kelvin2185** [comment]
when i issue command     run manage/persistence -e virus.exe -m registry 

i get upload successful virus.exe added to registry! but if i reboot target system session still doesn't  come into server unless i manually click the payload in target machine

am i missing something? kindly advice.

**Comment by nano727** [comment]
I have the same problem. Please, fix this.

**Comment by xp4xbox** [comment]
There are also other methods of making it launch at startup, if you want to do it manually: http://www.megasecurity.org/Trojaninfo/auto_start_methods.htm
