### ISSUE TITLE
[Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by kelvin2185** [n1nj4sec/pupy#425]
i tried to test persistence module in a test environment but when i run command

run manage/persistence -e C:\\Users\\kelvin\\Desktop\\pupyx86.7x0WQ9.exe -m registry

i keep getting error:
[-] [Errno 2] No such file or directory: 'C:\\Users\\kelvin\\Desktop\\pupyx86.7x0WQ9.exe'

but that is the correct path in target machine

 someone should help or maybe i am missing something.

Thanks

**Comment by void-in** [comment]
Try:
```
run manage/persistence -e C:\\Users\\kelvin\\Desktop\\pupyx86.7x0WQ9.exe -m registry
```

**Comment by kelvin2185** [comment]
still same issue

output of info command:

>> info
-----------------------------------------------------------------
hostname      : BIVINO
user          : kelvin
release       : 8
version       : 6.2.9200
os_arch       : AMD64
proc_arch     : 32bit
pid           : 12488
exec_path     : C:\Users\kelvin\Desktop\pupyx86.7x0WQ9.exe
address       : ::ffff:192.168.30.8
macaddr       : 02:00:4D:4F:9F:50
revision      : 893fc971
uac_lvl       : ?
intgty_lvl    : Medium
local_adm     : Yes
transport     : ssl
launcher      : connect
launcher_args : [u'--host', u'192.168.30.39:443', u'-t', u'ssl']
platform      : windows/x86
-----------------------------------------------------------------

Output of persistence command:

>> run manage/persistence -e C:\\Users\\kelvin\\Desktop\\pupyx86.7x0WQ9.exe -m registry

[-] [Errno 2] No such file or directory: 'C:\\Users\\kelvin\\Desktop\\pupyx86.7x0WQ9.exe'
----------------------------------------------------------------------------------------------------

i really dont understand this issue, kindly advise.

Thanks

**Comment by kelvin2185** [comment]
Output of persistence command:

run manage/persistence -e C:\\Users\\kelvin\\Desktop\\pupyx86.7x0WQ9.exe -m registry
[-] [Errno 2] No such file or directory: 'C:\\Users\\kelvin\\Desktop\\pupyx86.7x0WQ9.exe'

i really dont understand this issue, kindly advise.

Thanks

**Comment by kelvin2185** [comment]
run manage/persistence -e C:\\Users\\kelvin\\Desktop\\pupyx86.7x0WQ9.exe -m registry

**Comment by BTone** [comment]
The path specified by -e is a local path, not a remote path! The module will then upload the executable to the target.
