### ISSUE TITLE
LaZagne cleartext

### ISSUE THREAD

**Issue by pathanirfan6** [n1nj4sec/pupy#428]
Hello,

lazagne dumping passwords to encrypted json file. How can I decrypt  it?
or how can I dump clear text passwords?

**Comment by reillychase** [comment]
bump ?

**Comment by n1nj4sec** [comment]
use the "creds" commands

**Comment by quentinhardy** [comment]
I think this issue could be closed.

**Comment by reillychase** [comment]
yes it can be closed thanks ninja
