### ISSUE TITLE
 SWIG/_m2crypto_wrap.c(3541) : fatal error C1083: Cannot open include file: 'openssl/err.h': No such file or directory

### ISSUE THREAD

**Issue by firmanrpl** [n1nj4sec/pupy#429]
`    C:\Users\mendoanjoe\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ic:\python27\include -Ic:\python27\PC -Ic:\pkg\include -Ic:\users\mendoa~1\appdata\local\temp\pip-build-1jysqp\m2crypto\SWIG /TcSWIG/_m2crypto_wrap.c /Fobuild\temp.win32-2.7\Release\SWIG/_m2crypto_wrap.obj -DTHREADING _m2crypto_wrap.c
    SWIG/_m2crypto_wrap.c(3541) : fatal error C1083: Cannot open include file: 'openssl/err.h': No such file or directory
    error: command 'C:\\Users\\mendoanjoe\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2`

please help me

**Comment by n1nj4sec** [comment]
only build with wine is officially supported

**Comment by AguNnamdi** [comment]
On kali linux.. please help
failed to build m2crypto

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/root/Desktop/PUPY/pupy_env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-9dk3XO/m2crypto/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-4jNJWN-record/install-record.txt --single-version-externally-managed --compile --install-headers /root/Desktop/PUPY/pupy_env/include/site/python2.7/m2crypto" failed with error code 1 in /tmp/pip-build-9dk3XO/m2crypto/

**Comment by thechiefalone** [comment]
i have same problem on ubuntu 16.04 

Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ts2sH2/m2crypto/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-r7EED4-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-ts2sH2/m2crypto/
