### ISSUE TITLE
pupy does not create sessions after update

### ISSUE THREAD

**Issue by amainyebriggs** [n1nj4sec/pupy#43]
after i generarte a payload pupy does not see any open session(client not connecting back)

**Comment by L34Rn** [comment]
maybe u should check ur generate options and network first.

**Comment by n1nj4sec** [comment]
the payload itself has not been updated

**Comment by amainyebriggs** [comment]
my network configuration is okay , other frameworks (metasploit, cobalt, empire,netcat) receives sessions , this happened after update

**Comment by amainyebriggs** [comment]
i have also use reflective_dll its still not calling home

**Comment by n1nj4sec** [comment]
ok I found the bug, argument parsing was buggy when manually providing IP in pupygen after the auto-ip assignment update. I hope to be able to release a first stable version soon to avoid such minor regressions

**Comment by amainyebriggs** [comment]
thanks bro let me try it out

**Comment by amainyebriggs** [comment]
i love the ideal of making persistence with custom exe (-e)

 but i would love another ideal where persistence will not have random generation
 so we can call it any name like (windows update, java  update, adobe firewall etc) maybe add (-n)
 because with recourehacker or icon spoofer or other icon changing programs we can change the icon to look like the normal icons of those softwares i mention
