### ISSUE TITLE
Strange build script

### ISSUE THREAD

**Issue by bedbad** [n1nj4sec/pupy#435]
#!/bin/sh
./buildenv.sh
./buildenv.sh
make -f Makefile ARCH=win32 clean
make -f Makefile ARCH=win32
make -f Makefile DEBUG=1 ARCH=win32 clean
make -f Makefile DEBUG=1 ARCH=win32
make -f Makefile ARCH=win64 clean
make -f Makefile ARCH=win64
make -f Makefile DEBUG=1 ARCH=win64 clean
make -f Makefile DEBUG=1 ARCH=win64

I understand that you building all possible flavours of payloads, but is there buildenv, and why twice?

**Comment by alxchk** [comment]
Well.. Once upon a time there was a bug.. :)
