### ISSUE TITLE
Build Payloads from Source fails due to dependency change

### ISSUE THREAD

**Issue by royragsdale** [n1nj4sec/pupy#437]
Currently building master using the instructions from the [wiki](https://github.com/n1nj4sec/pupy/wiki/Build-payloads-from-sources) fails.

```
./buildenv.sh
./build.sh
```

This error can be observed in a recent [PR build](https://travis-ci.org/n1nj4sec/pupy/builds/251088711#L1273-L1275) from a few days ago. The same error occurs when re-running a build directly from master ([forked example](https://travis-ci.org/royragsdale/pupy/builds/252783715)).

The root cause appears to be as the result of an update of a transitive dependency on [pycparser](https://github.com/eliben/pycparser) from v2.17 to v2.18, on 6 July.  The issue tracked on that project (closed) is [#197](https://github.com/eliben/pycparser/issues/197)  and appears to be the result of using of python optimization flags, like `-OO`.  Since the pupy `buildenv.sh` heavily uses this flag it is likely necessary to pin to the previous version.

**Comment by n1nj4sec** [comment]
Thank you for the PR :)
