### ISSUE TITLE
Writing modules error

### ISSUE THREAD

**Issue by jxlx** [n1nj4sec/pupy#442]
I am writing my own module, I have everything written and the code compiles correctly, but I keep getting this error that says module has no attribute then the name of the function i'm trying to call that's in the packages/windows/all/pupwinutils 
I even tried copying the code that he has in the Wiki as a test run, but it doesn't work if I change the name when I call

self.client.conn.modules['pupwinutils.test'].MessageBox(...
The error is "AttributeError: 'module' object has no attribute 'nameofmymethod'

I'm new to custom APIs and just want to know if i'm missing a step or  place that I need to put this new file I made?

**Comment by alxchk** [comment]
You need to be sure you either loaded your module manually (prior to reference it from self.client.conn.modules), or added it to dependencies
