### ISSUE TITLE
Encrypt payload (FUD) and bind payload to .doc .pdf

### ISSUE THREAD

**Issue by kelvin2185** [n1nj4sec/pupy#446]
1 -  Can pupy generate an encrypted payload (FUD) that can't be detected by antivirus? if YES kindly show me 
      the command but if NO kindly reommend  free tools that can be use to achive this.

2 - Can pupy bind a payload to doc, pdf or jpeg if YES what is the command? if No kindly recommend  
     free tools.

Thanks.

**Comment by CyDoor** [comment]
https://github.com/n1nj4sec/pupy/wiki/Generate-payloads

**Comment by kelvin2185** [comment]
i already generated a payload but still yet most antivirus can detect my payload. i am asking if there is a command to make the payload fully FUD  and  also do you have an idea about no 2?

**Comment by s1st3r** [comment]
A lot of people have already started using these payloads and a lot of them have "stupiditily" uploaded them to virustotal coz they are jerks!, and so pupy will be caught by any AV out there by now.

Making the payload FUD has two steps

1. Rewrite the whole code, into something new, by this i mean change the libs, functions and variables to something new.

2. Build a crypter that will clean your payloads and encrypt them.

Dont be a script kiddie.
