### ISSUE TITLE
[Question] Is it possible to use only one port?

### ISSUE THREAD

**Issue by ClearGateTeam** [n1nj4sec/pupy#447]
Hi,

I wanted to know if it's possible to create a listener that will act both as the server and also provide the one liner payload.

Thanks.

**Comment by alxchk** [comment]
It is possible to have shared port for http server and non-https tcp payload (rsa,ec4,obfs and so on). But command which generates py oneliner doesn't use this functionality.

**Comment by ClearGateTeam** [comment]
Can we do like if the ssl handshake of server fails then it will serve the payload?

**Comment by alxchk** [comment]
Technically it's possible, but this will require refactoring. Personally I don't like ssl/tls for this kind of stuff at all (also ssl api is horrible in python 2.7), so I'm not going to do anything about that.

**Comment by ClearGateTeam** [comment]
I must changed the code for that, right?

I changed the conf like you said and the server is running but the payload part is missing , correct?

**Comment by alxchk** [comment]
Payload part shown during generation (when you do this from pupysh)

**Comment by ClearGateTeam** [comment]
I don't think I quite understand.

after I changed the settings. pupy server is working. but is there a way to access the payload like that and to serve the powershell payload :

https://[Pupy server IP]/eiloShaegae1

**Comment by alxchk** [comment]
Yes. With httpd enabled it starts serving (in very simple way) data/wwwroot folder as web root. On each connection it checks first, is this GET request, and if it is, tries to serve it. If not, it will treat traffic as pupy transport data and pass it up the stack.

**Comment by ClearGateTeam** [comment]
I did try to create some file on wwwroot and GET it, but it doesn't work. If log-lvl = DEBUG then after request server says:

[-] ::1:39404: GET ['test.txt'] | SECRET = TNmee

DEBUG:root:No clients matches request: <pupylib.PupyService.PupyService object at 0xb2cd5b0c>
ERROR:root:Traceback (most recent call last):
  File "/root/pupy/pupy/pupylib/PupyService.py", line 56, in on_connect
    self.namespace=self._conn.root.namespace
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 515, in root
    self._remote_root = self.sync_request(consts.HANDLE_GETROOT)
  File "/root/pupy/pupy/network/lib/connection.py", line 78, in sync_request
    if not self.serve(self._serve_timeout):
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 411, in serve
    data = self._recv(timeout, wait_for_lock = True)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 368, in _recv
    if self._channel.poll(timeout):
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/channel.py", line 43, in poll
    return self.stream.poll(timeout)
  File "/root/pupy/pupy/network/lib/streams/PupySocketStream.py", line 120, in poll
    result = ( len(self.upstream)>0 or self.sock_poll(timeout) )
  File "/root/pupy/pupy/network/lib/streams/PupySocketStream.py", line 143, in sock_poll
    self.transport.downstream_recv(self.buf_in)
  File "/root/pupy/pupy/network/lib/base.py", line 183, in downstream_recv
    self.chain[idx].downstream_recv(data)
  File "/root/pupy/pupy/network/lib/transports/httpwrap.py", line 134, in downstream_recv
    self._handle_http(payload)
  File "/root/pupy/pupy/network/lib/transports/httpwrap.py", line 123, in _handle_http
    self.close()
  File "/root/pupy/pupy/network/lib/base.py", line 72, in close
    raise EOFError()
EOFError

**Comment by alxchk** [comment]
You enabled 
```config set httpd secret true```
which requires to access files with some random (per pupysh session) prefix. In your case "TNmee".
If you generate payload from pupysh with default output with configured httpd, it will place generated file in data/wwwroot and it will show you how to access payload ("WWW URI PATH:" in the output).

**Comment by ClearGateTeam** [comment]
what arguments should be supplied to pupygen?

**Comment by alxchk** [comment]
Use pypysh, not pupygen. Usual args, like -f py or whatever you like

**Comment by ClearGateTeam** [comment]
pupysh does not have -f argument.

**Comment by alxchk** [comment]
https://github.com/n1nj4sec/pupy/issues/447#issuecomment-318280434

**Comment by ClearGateTeam** [comment]
where do I need to type this:

"gen -f py" 

?

**Comment by alxchk** [comment]
How do you think? In pupysh of course.

**Comment by ClearGateTeam** [comment]
ok. sorry for that :)

**Comment by ClearGateTeam** [comment]
I now understand. really appreciated for you help and patience.

**Comment by ClearGateTeam** [comment]
@alxchk , is there a way to contact with you.

I would like to ask you few general questions about Pupy.

Thanks.

**Comment by killercoderz4** [comment]
Please how can I I enable persistence and keyloggers via scriptlet for my power shell one liner. I have built the one liner works great on my virtual machine but when I restart I loose session. Any command line snippet would help
