### ISSUE TITLE
How does the shell recorder (ttyrec/asciinema) work?

### ISSUE THREAD

**Issue by berney** [n1nj4sec/pupy#448]
I see that shell has a recorder option, but I can't work out how to use it. I don't see anything in the `data` dir or current working directory.

I'm reading through the source and I'm still confused. Does this feature work?

**Comment by alxchk** [comment]
You need to enable logging (either in config or for one command):
```run -o /tmp/output.json interactive_shell -R asciinema```

**Comment by berney** [comment]
Ah I didn't realise there was more options (in the `run` part rather than the `shell`/`interactive_shell` part). Thanks that should be it.

**Comment by ClearGateTeam** [comment]
@alxchk how can you log the entire session?

**Comment by alxchk** [comment]
In case logs enabled in config separate file will be created for each command output. There is no entire session recording.

**Comment by berney** [comment]
@ClearGateTeam start `ttyrec` before you start `pupy`, that will record everything you do.

@alxchk Thanks for this feature and explaining it a bit more for me. I have used it found it working as desired.
