### ISSUE TITLE
pupyimporter looking for wrong module

### ISSUE THREAD

**Issue by 474172261** [n1nj4sec/pupy#449]
## Hi,I compiled pupy with debug mode,it shows that pupyimporter's module finder get a wrong module name,it's just like follows:
find_module(network,None) in ['network/__init__.pyo'])
network found in "network/__init__.pyo" / size = 112
--> Loading network (network/__init__.pyo) package=True
XXX network remove network/__init__.pyo from bundle / count = 422
loading module network

find_module(network.launcher,None) in ['network/launcher/__init__.pyo'])
network.launcher found in "network/launcher/__init__.pyo" / size = 121
--> Loading network.launcher (network/launcher/__init__.pyo) package=True
XXX network.launcher remove network/launcher/__init__.pyo from bundle / count = 421
loading module network.launcher

find_module(network.launcher.launchers,None) in ['network/launcher/launchers.pyo'])
network.launcher.launchers found in "network/launcher/launchers.pyo" / size = 1589
--> Loading network.launcher.launchers (network/launcher/launchers.pyo) package=False
XXX network.launcher.launchers remove network/launcher/launchers.pyo from bundle / count = 420
loading module network.launcher.launchers

find_module(network.launcher.utils,None) in [])
network.launcher.utils not found in []: not in 0 files
$$$$$$$$$$$$$$$$<--------------------------------------------here should load utils module,but it loads a wrong module name.

## do you have this issue?
I can't understand why this happened,please give me some suggestion.Thanks!

**Comment by 474172261** [comment]
well,I seem to understand why this happened,because python looking for modules with relative search first in python 2.x,so it find network/launcher/utils first.and then search utils again.

**Comment by n1nj4sec** [comment]
do you have a custom module named utils ?

**Comment by 474172261** [comment]
I added "utils" modules into compressed libraries.I figure out that this result  is not a issue because of pythons's import mechanism.Thanks for your comment! :)
