### ISSUE TITLE
Rootkit/boot sector

### ISSUE THREAD

**Issue by m3tal** [n1nj4sec/pupy#45]
Hi, i have a idea to make much good persistence module, add them the function to implement rootkit on MBR( master boot record) i have writed it in py.
Give me the aut to publish it :)

**Comment by n1nj4sec** [comment]
Hi there !
If the code is yours, I don't think I have a word in what you do or do not publish. But if you are willing to share your code I think it could be an awesome gift to all the security research community as it would be much easier to understand and analyze how to prevent/detect such persistent threats. On another hand, bad people could use it for evil purposes but it is more likely that these people already have developed similar tools, so IMHO the good still prevails. The choice is yours. Be assured that if you do publish it, I will have a look at it :)

**Comment by L34Rn** [comment]
that's good, why not add it?

**Comment by n1nj4sec** [comment]
because he finally did not sent any PR ?

**Comment by m3tal** [comment]
Hey, I'm sorry I don't have the time to reply but the module will be good in a week (need time to release it )
So he can do this functions :
- hooking windows API (vista,seven,win8)NOT WORK ON XP( because the kernel is on the base of win2000 and in vista and highter the kernel is not the same ..)
-Hide files.. Process,ports(secret add user)
-RM BACKDOOR (remote backdoor,connection goes on a https/activeX encrypted session.. That you can control it on your vps or other hacked server. (Work with proxychains ;)) (backdr functions: shell, reverse proxy.. :))
-instaling remote vpn (pptp tuneling)
-making nmap flood ( send wget request with spoofed IP to kill remote server ) so this the rootkit will install winpcap ;)
-arp poisoning( over network)
-installing Responder (yeah on windows !!) 
WORK good on windows 10 but need some corection for windows 7 ! :/) 
- Install MBR persistence/ GPU persitence !! ( I think i will give the python code just for real programmer : contact at resky@programmer.net ;))

**Comment by gulg** [comment]
Yeah that's a good way to do persistence !
Your code work good !

**Comment by gulg** [comment]
Why do not integrate code in pupy ?
