### ISSUE TITLE
3 issues, help needed

### ISSUE THREAD

**Issue by my7hical** [n1nj4sec/pupy#451]
1. Also, I may be looking at a older tutorial, but is this the correct format for generating a payload? `./pupygen.py -f exe_x86 -o test.exe connect --host IP:PORT`

2. earlier when I did just ./pupygen.py it gave me this:
`[!] required argument missing, automatically adding parameter --host someIP:443 from local or external ip address
[+] Generate client: windows/x86
[C] launcher: connect
[C] launcher_args: ['--host', 'someIP:443', '-t', 'ssl']
[C] debug: False
[C] offline_script: 
WARNING:root:Generating credentials to /home/myuser/pupy/pupy/crypto/credentials.py
..........++
....................................................................++
...................................++
...............................................................................................................................................................................................................................................................................................................................++
....++++++
....................++++++
..............................++++++
.................++++++
..............++++++
..++++++
....................................++++++
..............................++++++
................++++++
..............................................................++++++
[I] Credentials password: 
[+] Required credentials:
[+] SSL_BIND_CERT, SSL_CA_CERT, SSL_CLIENT_CERT, SSL_BIND_KEY, SSL_CLIENT_KEY
[+] OUTPUT_PATH = /home/myuser/pupy/pupy/pupyx86.JO2HYl.exe
[+] SCRIPTLETS = []
[+] DEBUG = False`

It created a .exe file that I can't open cause I have Ubuntu. Any help?

3. Doing ./pupysh.py it asks for credential password then after putting it in, it gives a traceback thing and ends with  `File "/home/myuser/pupy/pupy/modules/SocketServer.py", line 1
    %!PS-Adobe-3.0
    ^
SyntaxError: invalid syntax`

**Comment by my7hical** [comment]
For 1 it was an incorrect format, but now when I try to make a android payload, it doesnt seem to be a apk file. Whats wrong?

**Comment by my7hical** [comment]
For 3, I was able to fix it by simply removing the file. I was the one who added it because it seemed to have had a error earlier that it was missing. Removing it fixed it.

**Comment by my7hical** [comment]
I'm going to assume that for no. 2, the issue was that it didn't receive the correct parameters, so it just created them. And so that was just the targets file.

**Comment by n1nj4sec** [comment]
yup all is working fine, refer to the wiki for the new syntax
