### ISSUE TITLE
ERROR:root:Insufficient privileges to bind on port 444

### ISSUE THREAD

**Issue by my7hical** [n1nj4sec/pupy#455]
So doing `./pupysh.py` asks for password, then gives me 
>>[*] Server started on port 443 with transport ssl
>> ERROR:root:Insufficient privileges to bind on port 443`

I'm guessing it has to do with port forwarding but its a little confusing. I have a verizon router.

**Comment by void-in** [comment]
Are you running pupysh.py as root? 443 is a privileged port and require root privileges to bind. If you have a limited user account, you will have to bind to a port > 1024

**Comment by n1nj4sec** [comment]
your error is pretty self explanatory
