### ISSUE TITLE
Pushing Impacket into Pupy

### ISSUE THREAD

**Issue by s1st3r** [n1nj4sec/pupy#456]
Is there any one working on pushing Impacket into this project as a module?

**Comment by alxchk** [comment]
There is no need to do this. Impacket doesnt contain any binary modules, so may be loaded from system path

**Comment by n1nj4sec** [comment]
that's the beauty of it, just install impacket on the server side and you can access it from all the clients

**Comment by s1st3r** [comment]
Amazing... you close the query without even wondering what i really asked? Did you even read what i requested?

check...

if you already have a session to a windows machine, and you just do 

run windows/network/impacket/psexec.py administartor:password123 @TargetInsideTheNetwork cmd.exe

And then you have a shell from remote in the network

**Comment by alxchk** [comment]
run psexec ...
