### ISSUE TITLE
[Question] payload_templates source codes

### ISSUE THREAD

**Issue by ClearGateTeam** [n1nj4sec/pupy#459]
I'm trying to change the Window client behavior and I need  "pupyx86.dll" source code.

Where can I get it from?

Thanks.

**Comment by alxchk** [comment]
client/sources

**Comment by ClearGateTeam** [comment]
@alxchk , is there a way to use CA signed certificate. what variables should be modified on PupyCredentials.py.   In addition, is there a way to stop the client checking for the CA certificate?
