### ISSUE TITLE
Persistence on windows, gather/screenshot on android do not work 

### ISSUE THREAD

**Issue by rupyx0** [n1nj4sec/pupy#461]
Great tool! Been testing for a while.
1. Found that persistence did not work for windowsXP_32 with either method registry or startup folder.
2. Is there a module/utility/way to identify a client uniquely say by generating and asigining a UUID to each new client? This UUID should be queried at the session start automatically? Currently MACId is being used to identify a client but this would be much more robust if a UUID is used instead. It can be generated and saved to client when client connects for the very first time. It can then be queried for later sessions.
3. The apk file keeps stopping on android_86_7.1rc until "Enable Native Bridge" is turned on in application compatibility section. Documenting this would save lot of time for users.
4. run gather/screenshot fails with the following error:
>> sessions
id  user    hostname   platform  release             os_arch  proc_arch  intgty_lvl  address                 tags  
-------------------------------------------------------------------------------------------------------------------
1   u0_a72  localhost  android   4.9.31-android-x86  armv7l   32bit      Medium      ::ffff:192.168.225.100
>> run gather/screenshot 
[-] ('$DISPLAY not set.', "{'self': <mss.linux.MSS object at 0x8ad11b10>, 'display': None}")

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 346, in _dispatch_request
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 601, in _handle_call
  File "screenshot.py", line 45, in screenshot
  File "/tmp/pip-build-9SrJ7w/mss/mss/factory.py", line 33, in mss
  File "/tmp/pip-build-9SrJ7w/mss/mss/linux.py", line 133, in __init__
ScreenShotError: ('$DISPLAY not set.', {'self': <mss.linux.MSS object at 0x8ad11b10>, 'display': None})
>>

**Comment by quentinhardy** [comment]
_screenshot_ module on Android is not implemented yet. See https://github.com/n1nj4sec/pupy/pull/441/commits/2beaa0c75219810080c92b32111dd92841629689
