### ISSUE TITLE
"Not Installed"

### ISSUE THREAD

**Issue by miaoski** [n1nj4sec/pupy#462]
Hi.
I made several APK with either `./pupygen.py -f client -O android connect 192.168.1.2:2222 -t http` or `-t tcp_cleartext`, and the generated APKs can't be installed properly on either Android 17, 19, 21 (Genymotion, Google Nexus images).

The APKs are downloaded.  I turned on "Install from unknown source".  I saw the permission page and clicked on "Install", but the next screen is always "Not Installed".  Any possibilities?

Thank you!

**Comment by quentinhardy** [comment]
Can you give us debugs/logs with adb ?
