### ISSUE TITLE
Run it on Raspberry pi Zero

### ISSUE THREAD

**Issue by totor59** [n1nj4sec/pupy#463]
Hey,
I'm running pupy server on a raspberry pi zero, fresher raspbian flavour....
I currently have some problems when i'm run pupysh.
I run successfully the pupygen:

![pupygen](https://user-images.githubusercontent.com/19945973/29431510-75af5daa-8398-11e7-96ac-f2391d214460.png)

But when i run pupysh client can't connect to me...

![pupysh](https://user-images.githubusercontent.com/19945973/29431537-93ab0e58-8398-11e7-9c7a-884265b07289.png)

When i execute the same manipulation on the same target with my laptop running debian jessie the problem doesn't appear and i can access to the client.
Any ideas ?

**Comment by quentinhardy** [comment]
Can you try with another transport method ? and give us debugs.
