### ISSUE TITLE
Powershell: The server committed a protocol violation

### ISSUE THREAD

**Issue by CG-root** [n1nj4sec/pupy#465]
While trying to download the ps1 payload to Windows 10 machine, I get the following message from Powershell:

`Exception calling "DownloadString" with "1" argument(s): "The server committed a protocol violation.
Section=ResponseStatusLine"`

I'm running Pupy in single port (server + httpd on port 443) as described [here](https://github.com/n1nj4sec/pupy/issues/447).

I suspect that the cause for the issue (which occurs only with Windows 10)  happens because on TLS negotiation, PowerShell send the "Client Hello" packet  with the extension "SessionTicket TLS".

Big thanks for helpers

**Comment by n1nj4sec** [comment]
is it fixed ?

**Comment by ClearGateTeam** [comment]
@n1nj4sec , not really. looking on the request performed by the client using Wireshark (doing SSL decryption) to get the ps1 file it seems that after performing the handshake with the server, it seems that the GET request is being SSL segmented:

`GET /randomfile.ps1 HTTP/1.1`

The first byte which is the letter G is the first segment and after that the rest of the request and second segment.
putting "print payload" command afer `payload = data.read()` in `downstream_recv` function found in httpwrap.py file shows that only the first SSL segment is acknowledged by the server, thus making problems. I tried to fix it, but no luck :(
