### ISSUE TITLE
Clients not connecting (raspberry pi2)

### ISSUE THREAD

**Issue by WarrenHood** [n1nj4sec/pupy#467]
Hi.. 
So i built the apk payload using my local ip. And used connect... Then i run the payload on my phone ( which i am using vnc viewer through usb0 to control, so they both have the same local ip since I'm using USB tethering for the pi's internet)... Then i run pupysh.py and i just get no clients connecting but the port is both 443 on client and server...

Please help

**Comment by n1nj4sec** [comment]
show us both pupygen and pupysh commands you used

**Comment by WarrenHood** [comment]
i didn't change the config... Should i?
![00_conf](https://user-images.githubusercontent.com/18058977/29744436-fc399e40-8aa4-11e7-84d9-02ce3e4e25ac.png)

Pupygen
![00_pupygen](https://user-images.githubusercontent.com/18058977/29744448-2c0aacb8-8aa5-11e7-9072-0af338f6626d.png)
![00_out](https://user-images.githubusercontent.com/18058977/29744454-3d3b77b0-8aa5-11e7-870b-2e2c867c729d.png)

Pupysh
![00_pupysh](https://user-images.githubusercontent.com/18058977/29744461-50957e32-8aa5-11e7-9d74-280b61bd76ef.png)
![screenshot_2017-08-26-20-33-48](https://user-images.githubusercontent.com/18058977/29744473-719b4756-8aa5-11e7-93f9-3dc4175783c5.png)

**Comment by WarrenHood** [comment]
I'm trying with http transport on 127.0.0.1 now... Still not working...
![screenshot_2017-08-27-16-40-01](https://user-images.githubusercontent.com/18058977/29750830-1f661d42-8b47-11e7-9ceb-fa577f109602.png)

Also i tried a pure python file but it had an error about no get_modules method :
![screenshot_2017-08-27-16-40-12](https://user-images.githubusercontent.com/18058977/29750822-04ac62ae-8b47-11e7-8366-ecd0c7bf0af9.png)

**Comment by n1nj4sec** [comment]
do not call your payload pupy.py

**Comment by WarrenHood** [comment]
@n1nj4sec ok i will try calling it something else
