### ISSUE TITLE
Server will not establish a session

### ISSUE THREAD

**Issue by leapordcaun** [n1nj4sec/pupy#468]
pupy server will not establish a session.
generated a  default client and executed on windows 7 x86
all server configs are default.
netstat output:
tcp6       0      0 [::]:https              [::]:*                  LISTEN      4487/python 
htop output verified pupysh.py is pid 4487
Wireshark trace verifies the client is sending data. 

assistance would be appreciated.

**Comment by ClearGateTeam** [comment]
@leapordcaun , if you execute the Powershell without hidden flag, what do you see?

**Comment by leapordcaun** [comment]
@ClearGateTeam 

./pupy_******.ps1
WARNING: PE is not compatible with DEP, might cause issues

is what I get, any suggestions?

**Comment by leapordcaun** [comment]
Issue resolved.
Figured it out. The service was running on ipv6 and the client was looking for an ipv4 address. Changing the ipv6 option to false resolved the issue.
Closing.
