### ISSUE TITLE
How to generate dll payload? 

### ISSUE THREAD

**Issue by nano727** [n1nj4sec/pupy#472]
How to generate dll payload? I looked at the documentation and I didn't  find how to do it. Earlier it could be done with genpayload, but now I can't found this function in pupygen.py. 
Sorry, for my bad English.

**Comment by n1nj4sec** [comment]
pupygen.py -h

**Comment by nano727** [comment]
./pupygen.py -h
usage: pupygen.py [-h]
                  [-f {client,py,pyinst,py_oneliner,ps1,ps1_oneliner,rubber_ducky}]
                  [-O {android,windows,linux}] [-A {x86,x64}] [-S] [-o OUTPUT]
                  [-D OUTPUT_DIR] [-s SCRIPTLET] [-l] [-E] [--no-use-proxy]
                  [--randomize-hash]
                  [--oneliner-listen-port ONELINER_LISTEN_PORT]
                  [--debug-scriptlets] [--debug] [--workdir WORKDIR]
                  [{bind,auto_proxy,dnscnc,connect}] ...

Generate payloads for windows, linux, osx and android.

positional arguments:
  {bind,auto_proxy,dnscnc,connect}
                        Choose a launcher. Launchers make payloads behave
                        differently at startup.
  launcher_args         launcher options

optional arguments:
  -h, --help            show this help message and exit
  -f {client,py,pyinst,py_oneliner,ps1,ps1_oneliner,rubber_ducky}, --format {client,py,pyinst,py_oneliner,ps1,ps1_oneliner,rubber_ducky}
                        (default: client)
  -O {android,windows,linux}, --os {android,windows,linux}
                        Target OS (default: windows)
  -A {x86,x64}, --arch {x86,x64}
                        Target arch (default: x86)
  -S, --shared          Create shared object
  -o OUTPUT, --output OUTPUT
                        output path
  -D OUTPUT_DIR, --output-dir OUTPUT_DIR
                        output folder
  -s SCRIPTLET, --scriptlet SCRIPTLET
                        offline python scriptlets to execute before starting
                        the connection. Multiple scriptlets can be privided.
  -l, --list            list available formats, transports, scriptlets and
                        options
  -E, --prefer-external
                        In case of autodetection prefer external IP
  --no-use-proxy        Don't use the target's proxy configuration even if it
                        is used by target (for ps1_oneliner only for now)
  --randomize-hash      add a random string in the exe to make it's hash
                        unknown
  --oneliner-listen-port ONELINER_LISTEN_PORT
                        Port used by oneliner listeners ps1,py (default: 8080)
  --debug-scriptlets    don't catch scriptlets exceptions on the client for
                        debug purposes
  --debug               build with the debug template (the payload open a
                        console)
  --workdir WORKDIR     Set Workdir (Default = current workdir)
Where is line about dll payload?

**Comment by n1nj4sec** [comment]
yep that's the command ! next step involves reading the output
