### ISSUE TITLE
unsuccessfully build from sources

### ISSUE THREAD

**Issue by dcland** [n1nj4sec/pupy#473]
I just try to build your sources unfortunately without success, my flow is : 
 cd sources
./buildenv.sh
./build.sh, here i got this error : 

> /root/pupy/pupy/client/sources/buildenv/win64/cl.sh /c /DWIN_X64 /D_WIN64 /nologo main_exe.c
make: /root/pupy/pupy/client/sources/buildenv/win64/cl.sh: Command not found
Makefile.linux:85: recipe for target 'main_exe.obj' failed
make: *** [main_exe.obj] Error 127

i see does someone else with the same problem but he doesn't get answer =\

**Comment by void-in** [comment]
Line 2 is telling you make command not found. Make sure make is installed and in the PATH

**Comment by n1nj4sec** [comment]
look at the travis-ci build, if it can build it from sources, you can
