### ISSUE TITLE
[RESOLVED] Python BIND payload?

### ISSUE THREAD

**Issue by reillychase** [n1nj4sec/pupy#474]
I haven't found a way to generate a python BIND payload.

python pupygen.py bind -f py --os linux --port 1337

all I get is the pupygen help page displayed

**Comment by reillychase** [comment]
nevermind, the args need to be in the right order IE python pupygen.py bind --port 1337 will work

**Comment by reillychase** [comment]
Now how do i connect to the port the payload binded to? python pupysh.py doesnt have a bind option?

**Comment by alxchk** [comment]
It has connect command

**Comment by reillychase** [comment]
makes sense of course since it is the one connecting not binding (duh) thanks!
