### ISSUE TITLE
pupy stops working after credentials password is entered

### ISSUE THREAD

**Issue by HorneyAttorney** [n1nj4sec/pupy#476]
Hello, everyone..

I'm running Kali on Oracle VM VirtualBox
I installed pupy as correctly as possible, followed instructions step by step.
and I actually did that multiple times trying to solve the issue, but it persists..

I run pp.py for the first time, it asks for Credentials Password to generate, I enter the password, and then it stops..
I exit and run it again, it asks for the credentials password, yes I know, the one I entered the first time I ran it, it stops..
I tried deleting and re-cloning over and over again but the issue remains.

Attached a screenshot of the terminal running the tool, I even thought it needs time, it stayed like that for 7 hours..

![screenshot from 2017-09-08 22-18-55](https://user-images.githubusercontent.com/30851863/30236299-ecd0b80e-9516-11e7-9d18-c133df091b83.png)

**Comment by HorneyAttorney** [comment]
So no one will try to help me figure out what's going on here?

**Comment by quentinhardy** [comment]
Run ```python pupygen.py``` for generating a payload. Use ```python pupysh.py``` for controling a target.
See wiki: **https://github.com/n1nj4sec/pupy/wiki**

**Comment by HorneyAttorney** [comment]
thanks :D

**Comment by xuxuedong** [comment]
hey guy, you should RTFM
