### ISSUE TITLE
[Feature Req]

### ISSUE THREAD

**Issue by danvollans** [n1nj4sec/pupy#482]
Have any of the developers considered implementing any of the AMSI or ScriptBlock bypass work for Powershell done by cobbr?  https://cobbr.io/ScriptBlock-Logging-Bypass.html

Some of it could definitely be done at the Powershell module level itself, but I was wondering if it's possible that it could be done at the Agent execution level, before scripts/modules are executed on the Agent.  Maybe I'm just being crazy. 

Love all the hard work you have put into Pupy, and it really shows with such a polished product. Thanks!

**Comment by n1nj4sec** [comment]
if you have time to code that, PR are welcome, in the meantime I close the issue cause it's not something I want to spend time on
