### ISSUE TITLE
I can't use pupygen.py

### ISSUE THREAD

**Issue by DarthShined** [n1nj4sec/pupy#488]
Hi.
When I type "python pupygen.py" command I got this error.
`python pupygen.py
WARNING:root:Your templates are not synced with your pupy version ! , you should update them with "git submodule update"
WARNING:root:Your templates are not synced with your pupy version ! , you should update them with "git submodule update"
[!] required argument missing, automatically adding parameter --host 192.168.0.28:443 from local or external ip address
[+] Generate client: windows/x86
[C] launcher: connect
[C] launcher_args: ['--host', '192.168.0.28:443', '-t', 'ssl']
[C] debug: False
ERROR:root:Corrupted file: /root/pupy/pupy/pupylib/../crypto/credentials.py
Traceback (most recent call last):
  File "pupygen.py", line 643, in <module>
    pupygen(parser.parse_args(), config)
  File "pupygen.py", line 508, in pupygen
    compressed=not ( args.uncompressed or args.packer )
  File "pupygen.py", line 321, in generate_binary_from_template
    return generator(template, config, compressed), filename, makex
  File "pupygen.py", line 63, in get_edit_binary
    new_conf = marshal.dumps(compile(get_raw_conf(conf), '<config>', 'exec'))
  File "pupygen.py", line 86, in get_raw_conf
    credentials = Credentials(role='client')
  File "/root/pupy/pupy/pupylib/PupyCredentials.py", line 196, in __init__
    raise ValueError('Corrupted file: {}'.format(configfile))
ValueError: Corrupted file: /root/pupy/pupy/pupylib/../crypto/credentials.py
Corrupted file: /root/pupy/pupy/pupylib/../crypto/credentials.py
`
I am in Kali Linux 2017.1 and I have followed all installation steps.
Best regards and thanks for your time.

**Comment by DarthShined** [comment]
Also I have tried to use "git submodule update" and "sudo git submodule update" but It does not work.

**Comment by n1nj4sec** [comment]
try to remove or rename /root/pupy/pupy/pupylib/../crypto/credentials.py and restart pupysh

**Comment by DarthShined** [comment]
Thanks you very much!!
Now It works perfeclty =D
