### ISSUE TITLE
Can I go from DLL to Py

### ISSUE THREAD

**Issue by r3comp1le** [n1nj4sec/pupy#491]
Possible to convert dll back to source code?

**Comment by n1nj4sec** [comment]
I have never done it but yes it should be possible it's just python bytecode compressed with lzma embedded in the dll.
1. Search at the offset of this string **(https://github.com/n1nj4sec/pupy/blob/unstable/client/sources/pupy.c#L23)** (you can approximately find the offset by searching in the template but it may vary)
2. Decompress the bytecode using lzma https://github.com/n1nj4sec/pupy/blob/unstable/client/sources/pupy.c#L63
3. write the python bytecode to a .pyc file and decompile it (using some tool like uncompyle)
