### ISSUE TITLE
I can't use pupygen.py

### ISSUE THREAD

**Issue by johnjohny1990** [n1nj4sec/pupy#495]
Hi.
When I type "python pupygen.py" command I got this error.
./pupygen.py 
WARNING:root:Your templates are not synced with your pupy version ! , you should update them with "git submodule update"
WARNING:root:Your templates are not synced with your pupy version ! , you should update them with "git submodule update"
[!] required argument missing, automatically adding parameter --host 192.168.1.139:443 from local or external ip address
[+] Generate client: windows/x86
ERROR:root:Template not found (/opt/pupy/pupy/payload_templates/pupyx86.exe)
Traceback (most recent call last):
  File "./pupygen.py", line 643, in <module>
    pupygen(parser.parse_args(), config)
  File "./pupygen.py", line 508, in pupygen
    compressed=not ( args.uncompressed or args.packer )
  File "./pupygen.py", line 313, in generate_binary_from_template
    raise ValueError('Template not found ({})'.format(template))
ValueError: Template not found (/opt/pupy/pupy/payload_templates/pupyx86.exe)
Template not found (/opt/pupy/pupy/payload_templates/pupyx86.exe)
I have Kali Linux 2017.2 and I have followed all installation steps.
Best regards and thanks for your time.

**Comment by HorneyAttorney** [comment]
Don't type "python"
it's just ./pupygen.py

ex: ./pupygen.py  connect --host 192.168.1.2:8080

**Comment by johnjohny1990** [comment]
I type ./pupygen.py but display this error
WARNING:root:Your templates are not synced with your pupy version ! , you should update them with "git submodule update"
WARNING:root:Your templates are not synced with your pupy version ! , you should update them with "git submodule update"
[!] required argument missing, automatically adding parameter --host 192.168.15.140:443 from local or external ip address
[+] Generate client: windows/x86
ERROR:root:Template not found (/opt/pupy/pupy/payload_templates/pupyx86.exe)
Traceback (most recent call last):
  File "./pupygen.py", line 643, in <module>
    pupygen(parser.parse_args(), config)
  File "./pupygen.py", line 508, in pupygen
    compressed=not ( args.uncompressed or args.packer )
  File "./pupygen.py", line 313, in generate_binary_from_template
    raise ValueError('Template not found ({})'.format(template))
ValueError: Template not found (/opt/pupy/pupy/payload_templates/pupyx86.exe)
Template not found (/opt/pupy/pupy/payload_templates/pupyx86.exe)

**Comment by johnjohny1990** [comment]
i update them with "git submodule update" but it does not work

**Comment by CalfCrusher** [comment]
https://github.com/n1nj4sec/pupy/releases/download/latest/payload_templates.txz doesn't exist anymore. if i run ./pupygen **i get Template not found**

**Comment by nadir3392** [comment]
if i run ./pupygen i get Template not found

**Comment by Dc884200** [comment]
i get

(freddiexanxz㉿LAPTOP-S1PPBM9L)-[/pupy]
└─$   ./pupygen.py
  File "/pupy/./pupygen.py", line 221
    os.chmod(os.path.join(root, dir), 0700)
                                         ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
