### ISSUE TITLE
"git submodule update"  ERROR

### ISSUE THREAD

**Issue by privatebuyer** [n1nj4sec/pupy#499]
I have installed pupy and made follow steps:
-------------------------------------------------------------------------
git clone https://github.com/n1nj4sec/pupy.git pupy
cd pupy
git submodule init
git submodule update
pip install -r pupy/requirements.txt
wget https://github.com/n1nj4sec/pupy/releases/download/latest/payload_templates.txz
tar xvf payload_templates.txz && mv payload_templates/* pupy/payload_templates/ && rm payload_templates.txz && rm -r payload_templates
------------------------------------------------------------------------
As You can see I have updated templates. Then I`m tried to create a DLL:
--------------------------------------------------------------------------------------------------------
root@kali:~/pupy/pupy# ./pupygen.py -f exe_x64 -o myServer.dll connect --host 10.0.2.15:443
WARNING:root:Your templates are not synced with your pupy version ! , you should update them with "git submodule update"
WARNING:root:Your templates are not synced with your pupy version ! , you should update them with "git submodule update"
usage: pupygen.py [-h]
                  [-f {client,py,pyinst,py_oneliner,ps1,ps1_oneliner,rubber_ducky}]
                  [-O {android,windows,linux,solaris}] [-A {x86,x64}] [-U]
                  [-P PACKER] [-S] [-o OUTPUT] [-D OUTPUT_DIR] [-s SCRIPTLET]
                  [-l] [-E] [--no-use-proxy] [--randomize-hash]
                  [--oneliner-listen-port ONELINER_LISTEN_PORT]
                  [--oneliner-no-ssl] [--debug-scriptlets] [--debug]
                  [--workdir WORKDIR]
                  [{bind,auto_proxy,dnscnc,connect}] ...
pupygen.py: error: argument -f/--format: invalid choice: 'exe_x64' (choose from 'client', 'py', 'pyinst', 'py_oneliner', 'ps1', 'ps1_oneliner', 'rubber_ducky')
---------------------------------------------------------------------------------------------------------

Why I`m still see this error "git submodule update" ???

**Comment by th4ne** [comment]
`./pupygen.py connect --host IP/DNS:PORT`     <-- estandar pupy32bit exe 

try "./pupygen.py -l"   or  "./pupygen.py -h" 

for more info https://github.com/n1nj4sec/pupy/wiki
