### ISSUE TITLE
Can`t create EXEx64 and DLLx64

### ISSUE THREAD

**Issue by privatebuyer** [n1nj4sec/pupy#501]
Hello!
 
I have a problem! I cannot create an exe file for Windows 64bit. Which command should I make?
 
Early it was like this : ./pupygen.py -f exe_x64 -o pupyx64.exe connect --host 10.0.2.15:443
 
Now it`s not working. I see this error:
 
pupygen.py: error: argument -f/--format: invalid choice: 'exe_x64' (choose from 'client', 'py', 'pyinst', 'py_oneliner', 'ps1', 'ps1_oneliner', 'rubber_ducky')
 
 
Please help me! I need to create few files:
 
1. EXE for Windows 64 bit
 
2. DLL for Windows 64 bit

**Comment by n1nj4sec** [comment]
rtfm
