### ISSUE TITLE
WARNING:root:cannot import

### ISSUE THREAD

**Issue by th4ne** [n1nj4sec/pupy#504]
`WARNING:root:cannot import name create_ps_command : module psexec disabled`

**Comment by gnomefish** [comment]
I'm on the latest build and still getting: WARNING:root:cannot import name create_ps_command : module psexec disabled.

git checkout unstable
Already on 'unstable'
Your branch is up-to-date with 'origin/unstable'.

Just wanted to let you know.
L.

**Comment by AlessandroZ** [comment]
When the pull request [506](https://github.com/n1nj4sec/pupy/pull/506) will be merged, you should not see the error message anymore.

**Comment by gnomefish** [comment]
Okidoki, thanks!
