### ISSUE TITLE
Command to generate a  scriptlets payload that automatically dump Keystroke to pupy server when i am not connected to pupy server.

### ISSUE THREAD

**Issue by kelvin2185** [n1nj4sec/pupy#508]
Hi everyone, please is there a way i can dump keystroke  from target machine to my pupy server  when i am not connect to my pupy server?  if yes, what is the command? i know it possible to run  persistence + keylogger payload scriptlets  but the issue is when  i connect to my pupy server and  target machine isnt online i cant run keylogger dump command because target machine isnt online. i just want payload to automatically dump all keystroke to my pupy server so that i can just use filezilla to view all keystokes whenever i am connect to my server.

**Comment by DarthShined** [comment]
Your answer is in [Wiki](https://github.com/n1nj4sec/pupy/wiki)
I give you a clue
`./pupygen.py -l`

Good Luck

**Comment by s1st3r** [comment]
Best way is to upload your own code.exe to target box, and have it write to disk, in a hidden folder, then when target is online, upload and delete.
