### ISSUE TITLE
base64 transport

### ISSUE THREAD

**Issue by amainyebriggs** [n1nj4sec/pupy#52]
base64 transport does not call home

**Comment by n1nj4sec** [comment]
I just tried on windows 7 & linux everything works just fine

**Comment by amainyebriggs** [comment]
it works thanks i have figured out my mistakes

**Comment by amainyebriggs** [comment]
i forgot to specify the transport so when i generate  payload using tcp_base64 the listeners listen on default tcp_ssl and session never calls home 

thanks
