### ISSUE TITLE
[Question] New Client-Functions

### ISSUE THREAD

**Issue by b2az** [n1nj4sec/pupy#520]
Hi Dudes/Dudettes,

Im interested in modifying the client.
Theres a new working redpill function, i want to implement.

But i've got no clue where the "main" could be found in /sources/*.

Is there anywhere a little documentation about the client itself?

Thanks,
b2az

**Comment by n1nj4sec** [comment]
Hey,

What do you have in mind exactly ? I doubt you need to change the main, but here it is : 

```bash
$ find client/sources | egrep -e 'main.*\.c$'
client/sources/main_reflective.c
client/sources/main_exe.c
 ```
Sorry for the Doc there is not ! but the C code is pretty small and concise ;)

**Comment by b2az** [comment]
Ok thanks, i stumbled upon those two already, but didn't had any clue.
Well. I guess i've got to pull out my C-Books again.

Thx, for pointing to the right direction.

Thanks,
b2az
