### ISSUE TITLE
lazagne not working

### ISSUE THREAD

**Issue by cnilsecure** [n1nj4sec/pupy#521]
hi I cloned the lastest version of pupy but when i tried to run lazagne module on windows 2008
this is what i get
[!] Error loading package lazagne.config.WinStructure (lazagne/config/WinStructure.pyc pkg=False) : Traceback (most recent call last):
WindowsError: [Error 126] The specified module could not be found
[!] Error loading package lazagne.config.changePrivileges (lazagne/config/changePrivileges.pyc pkg=False) : Traceback (most recent call last):
WindowsError: [Error 126] The specified module could not be found
[!] Error loading package laZagne (laZagne.pyc pkg=False) : Traceback (most recent call last):
WindowsError: [Error 126] The specified module could not be found
[-] (126, 'The specified module could not be found')

========= Remote Traceback (1) =========
Traceback (most recent call last):
WindowsError: [Error 126] The specified module could not be found
Traceback (most recent call last):
  File "/root/pupy/pupy/pupylib/PupyJob.py", line 129, in module_worker
    module.run(args)
  File "/root/pupy/pupy/modules/lazagne.py", line 72, in run
    self.client.conn.modules["laZagne"].runLaZagne,
  File "/usr/lib/python2.7/site-packages/rpyc/core/netref.py", line 213, in method
    return syncreq(_self, consts.HANDLE_CALLATTR, name, args, kwargs)
  File "/usr/lib/python2.7/site-packages/rpyc/core/netref.py", line 72, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/root/pupy/pupy/network/lib/connection.py", line 109, in sync_request
    raise obj
exceptions.WindowsError: (126, 'The specified module could not be found')

========= Remote Traceback (1) =========
Traceback (most recent call last):
WindowsError: [Error 126] The specified module could not be found

any idea what is wrong?

**Comment by b2az** [comment]
Have you followed the installation tutorial? you have to git add the submodules.

**Comment by cnilsecure** [comment]
yes i did
