### ISSUE TITLE
NotFoundError: rsa

### ISSUE THREAD

**Issue by n00py** [n1nj4sec/pupy#527]
`root@kali:~/pupy/pupy# ./pupygen.py -f py connect --transport ssl --host 172.16.155.196

[I] Credentials password: 

[+] Required credentials:

[+] SSL_BIND_CERT, SSL_CA_CERT, SSL_CLIENT_CERT, SSL_BIND_KEY, SSL_CLIENT_KEY

[C] launcher: connect

[C] launcher_args: ['--transport', 'ssl', '--host', '172.16.155.196']

[C] debug: False

[+] generating payload ...

ERROR:root:rsa`
`
Traceback (most recent call last):

  File "./pupygen.py", line 674, in <module>

    pupygen(parser.parse_args(), config)

  File "./pupygen.py", line 633, in pupygen

    packed_payload=pack_py_payload(get_raw_conf(conf, verbose=True))

  File "/root/pupy/pupy/pupylib/payloads/py_oneliner.py", line 36, in pack_py_payload
    dependencies.importer(('rpyc', 'pyasn1', 'rsa', 'netaddr', 'tinyec'))

  File "/root/pupy/pupy/pupylib/payloads/dependencies.py", line 123, in importer
    blob, modules, _ = package(dependencies, os, arch, posix=posix)

  File "/root/pupy/pupy/pupylib/payloads/dependencies.py", line 421, in package
    remote=remote, posix=posix

  File "/root/pupy/pupy/pupylib/payloads/dependencies.py", line 382, in _package
    raise NotFoundError(module_name)

NotFoundError: rsa

rsa
`

Base install of Kali Linux, followed the steps on:
https://github.com/n1nj4sec/pupy/wiki/Installation

**Comment by n00py** [comment]
oot@kali:~/pupy/pupy# pip install rsa
Requirement already satisfied: rsa in /usr/local/lib/python2.7/dist-packages/rsa-3.4.2-py2.7.egg
Requirement already satisfied: pyasn1>=0.1.3 in /usr/local/lib/python2.7/dist-packages (from rsa)

**Comment by n1nj4sec** [comment]
unzip le .egg and rename "rsa-3.4.2-py2.7" to "rsa"

**Comment by n00py** [comment]
that worked, thanks.

`root@kali:/usr/local/lib/python2.7/dist-packages# unzip rsa-3.4.2-py2.7.egg `
