### ISSUE TITLE
ValueError: Module not found: pyuv

### ISSUE THREAD

**Issue by xcrypt999** [n1nj4sec/pupy#528]
I run the command: run forward -L 1234
python format payload can not use the forward module?
Experiment in linux and mac, this error occurs. Ps1 format on Windows can use the forward module.

**Comment by mailinneberg** [comment]
So, I just wanted to ask.
Can I use Blueborne vulnerability and overflow bluetooth stack and make
pupy payload for android or iOS?

thx
Mai

**Comment by n1nj4sec** [comment]
yup I added back the old portfwd/socks5proxy modules in case pyuv is not available
