### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-1eZcb4/pyautogui/ Error

### ISSUE THREAD

**Issue by PoireWilliams** [n1nj4sec/pupy#540]
I am using Linux Kali and I am getting 
`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-1eZcb4/pyautogui/`
this error when I write `pip install -r pupy/requirements.txt` 
please help. 

Thank you.

**Comment by ire4ever1190** [comment]
goto [here](http://pyautogui.readthedocs.io/en/latest/install.html) for steps on how to install pyautogui

**Comment by PoireWilliams** [comment]
@ire4ever1190 i already did that, but i am getting same message. should i reinstall?

**Comment by sparklespdx** [comment]
It only works if you have a display.

**Comment by emans841** [comment]
have any one found solution to this?

**Comment by andika223** [comment]
first you need install pip with apt-get, and install them whit pip
`
pip3 install python3-xlib
sudo apt-get install scrot
sudo apt-get install python3-tk
sudo apt-get install python3-dev
pip3 install pyautogui`

**Comment by elfantasmo** [comment]
I actually solved this by doing the following
```
pip install python3-xlib
sudo apt-get install 
sudo apt-get install python3-tk
sudo apt-get install python3-dev
pip install pyautogui
```
this was based upon the comment from "andika223", but instead of using `pip3` use `pip` which is the command used in installing the requirements:
`pip install -r pupy/requirements.txt`

**Comment by Rhuax** [comment]
I followed all the previous replies guidelines but none of them worked for me. I'm on Ubuntu 17

**Comment by jrenaud007** [comment]
cli or desktop ?

**Comment by xuxuedong** [comment]
@Rhuax if you ssh to the target, that you cannot install pyautogui, you must connect to the target use something like vnc

**Comment by Rhuax** [comment]
I'm installing it on my machine just for tests. Why should I use ssh?

**Comment by xuxuedong** [comment]
If your vps is ubuntu

**Comment by salesdbs** [comment]
@Rhuax 
Tente da seguinte forma:

# xhost +
# touch ~/.Xauthority
# pip install pyautogui

Comigo deu certo!

**Comment by jonaed1230** [comment]
Try with this
$ pip install setuptools
or
$ pip3 install setuptools

**Comment by jonaed1230** [comment]
then
$ pip3 install pyautogui
$ pip install pyautogui
