### ISSUE TITLE
[Question] Multiple Sessions Concurrently

### ISSUE THREAD

**Issue by CG-root** [n1nj4sec/pupy#541]
Hi everyone,

Is it possible to interact with few sessions simultaneously?

For example, while typing session -i X, then the new session will be reachable through new console window.

Thanks

**Comment by s1st3r** [comment]
Negative, 

Unless GUI, like QT

**Comment by killercoderz4** [comment]
Please how can I I enable persistence and keyloggers via scriptlet for my power shell one liner. I have built the one liner works great on my virtual machine but when I restart I loose session. Any command line snippet would help
