### ISSUE TITLE
how to pyinstaller to exe

### ISSUE THREAD

**Issue by adastmins** [n1nj4sec/pupy#543]
m2crypto error.

C:\RAT\Super\pupy-unstable>C:\Super\pupy-unstable\dist\Bacvk
er\Bacvker.exe
Traceback (most recent call last):
  File "Bacvker.py", line 4, in <module>
    from Crypto.Cipher import AES
  File "c:\windows\temp\pip-build-3ucyrc\pyinstaller\PyInstaller\loader\pyimod03
_importers.py", line 396, in load_module
  File "site-packages\Crypto\Cipher\__init__.py", line 3, in <module>
  File "c:\windows\temp\pip-build-3ucyrc\pyinstaller\PyInstaller\loader\pyimod03
_importers.py", line 396, in load_module
  File "site-packages\Crypto\Cipher\_mode_ecb.py", line 46, in <module>
  File "site-packages\Crypto\Util\_raw_api.py", line 189, in load_pycryptodome_r
aw_lib
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb'
[12016] Failed to execute script Bacvker

**Comment by adastmins** [comment]
Collecting M2Crypto
  Using cached M2Crypto-0.27.0.tar.gz
Requirement already satisfied: typing in c:\python27\lib\site-packages (from M2C
rypto)
Building wheels for collected packages: M2Crypto
  Running setup.py bdist_wheel for M2Crypto ... error
  Complete output from command c:\python27\python.exe -u -c "import setuptools,
tokenize;__file__='c:\\windows\\temp\\pip-build-rk8rnr\\M2Crypto\\setup.py';f=ge
tattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.cl
ose();exec(compile(code, __file__, 'exec'))" bdist_wheel -d c:\windows\temp\tmpx
lfdwrpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  copying M2Crypto\ASN1.py -> build\lib.win32-2.7\M2Crypto
  copying M2Crypto\AuthCookie.py -> build\lib.win32-2.7\M2Crypto
  copying M2Crypto\BIO.py -> build\lib.win32-2.7\M2Crypto
  copying M2Crypto\BN.py -> build\lib.win32-2.7\M2Crypto
  copying M2Crypto\callback.py -> build\lib.win32-2.7\M2Crypto
  copying M2Crypto\DH.py -> build\lib.win32-2.7\M2Crypto
  copying M2Crypto\DSA.py -> build\lib.win32-2.7\M2Crypto
  copying M2Crypto\EC.py -> build\lib.win32-2.7\M2Crypto
  copying M2Crypto\Engine.py -> build\lib.win32-2.7\M2Crypto
  copying M2Crypto\Err.py -> build\lib.win32-2.7\M2Crypto
  copying M2Crypto\EVP.py -> build\lib.win32-2.7\M2Crypto
  copying M2Crypto\ftpslib.py -> build\lib.win32-2.7\M2Crypto
  copying M2Crypto\httpslib.py -> build\lib.win32-2.7\M2Crypto
  copying M2Crypto\m2.py -> build\lib.win32-2.7\M2Crypto
  copying M2Crypto\m2crypto.py -> build\lib.win32-2.7\M2Crypto
  copying M2Crypto\m2urllib.py -> build\lib.win32-2.7\M2Crypto
  copying M2Crypto\m2urllib2.py -> build\lib.win32-2.7\M2Crypto
  copying M2Crypto\m2xmlrpclib.py -> build\lib.win32-2.7\M2Crypto
  copying M2Crypto\Rand.py -> build\lib.win32-2.7\M2Crypto
  copying M2Crypto\RC4.py -> build\lib.win32-2.7\M2Crypto
  copying M2Crypto\RSA.py -> build\lib.win32-2.7\M2Crypto
  copying M2Crypto\six.py -> build\lib.win32-2.7\M2Crypto
  copying M2Crypto\SMIME.py -> build\lib.win32-2.7\M2Crypto
  copying M2Crypto\threading.py -> build\lib.win32-2.7\M2Crypto
  copying M2Crypto\util.py -> build\lib.win32-2.7\M2Crypto
  copying M2Crypto\X509.py -> build\lib.win32-2.7\M2Crypto
  copying M2Crypto\__init__.py -> build\lib.win32-2.7\M2Crypto
  creating build\lib.win32-2.7\M2Crypto\PGP
  copying M2Crypto\PGP\constants.py -> build\lib.win32-2.7\M2Crypto\PGP
  copying M2Crypto\PGP\packet.py -> build\lib.win32-2.7\M2Crypto\PGP
  copying M2Crypto\PGP\PublicKey.py -> build\lib.win32-2.7\M2Crypto\PGP
  copying M2Crypto\PGP\PublicKeyRing.py -> build\lib.win32-2.7\M2Crypto\PGP
  copying M2Crypto\PGP\RSA.py -> build\lib.win32-2.7\M2Crypto\PGP
  copying M2Crypto\PGP\__init__.py -> build\lib.win32-2.7\M2Crypto\PGP
  creating build\lib.win32-2.7\M2Crypto\SSL
  copying M2Crypto\SSL\cb.py -> build\lib.win32-2.7\M2Crypto\SSL
  copying M2Crypto\SSL\Checker.py -> build\lib.win32-2.7\M2Crypto\SSL
  copying M2Crypto\SSL\Cipher.py -> build\lib.win32-2.7\M2Crypto\SSL
  copying M2Crypto\SSL\Connection.py -> build\lib.win32-2.7\M2Crypto\SSL
  copying M2Crypto\SSL\Context.py -> build\lib.win32-2.7\M2Crypto\SSL
  copying M2Crypto\SSL\Session.py -> build\lib.win32-2.7\M2Crypto\SSL
  copying M2Crypto\SSL\SSLServer.py -> build\lib.win32-2.7\M2Crypto\SSL
  copying M2Crypto\SSL\ssl_dispatcher.py -> build\lib.win32-2.7\M2Crypto\SSL
  copying M2Crypto\SSL\timeout.py -> build\lib.win32-2.7\M2Crypto\SSL
  copying M2Crypto\SSL\TwistedProtocolWrapper.py -> build\lib.win32-2.7\M2Crypto
\SSL
  copying M2Crypto\SSL\__init__.py -> build\lib.win32-2.7\M2Crypto\SSL
  running build_ext
  building 'M2Crypto._m2crypto' extension
  creating build\temp.win32-2.7
  creating build\temp.win32-2.7\Release
  creating build\temp.win32-2.7\Release\SWIG
  C:\Users\admin\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9
.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ic:\python27\include -Ic:
\python27\PC -Ic:\windows\temp\pip-build-rk8rnr\M2Crypto\SWIG /TcSWIG/_m2crypto_
wrap.c /Fobuild\temp.win32-2.7\Release\SWIG/_m2crypto_wrap.obj -DTHREADING -D_CR
T_SECURE_NO_WARNINGS
  _m2crypto_wrap.c
  SWIG/_m2crypto_wrap.c(3550) : warning C4068: unknown pragma
  SWIG/_m2crypto_wrap.c(3551) : warning C4068: unknown pragma
  SWIG/_m2crypto_wrap.c(3554) : fatal error C1083: Cannot open include file: 'op
enssl/err.h': No such file or directory
  error: command 'C:\\Users\\admin\\AppData\\Local\\Programs\\Common\\Microsoft\
\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for M2Crypto
  Running setup.py clean for M2Crypto
Failed to build M2Crypto
Installing collected packages: M2Crypto
  Running setup.py install for M2Crypto ... error
    Complete output from command c:\python27\python.exe -u -c "import setuptools
, tokenize;__file__='c:\\windows\\temp\\pip-build-rk8rnr\\M2Crypto\\setup.py';f=
getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.
close();exec(compile(code, __file__, 'exec'))" install --record c:\windows\temp\
pip-kak0kz-record\install-record.txt --single-version-externally-managed --compi
le:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-2.7
    creating build\lib.win32-2.7\M2Crypto
    copying M2Crypto\ASN1.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\AuthCookie.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\BIO.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\BN.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\callback.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\DH.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\DSA.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\EC.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\Engine.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\Err.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\EVP.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\ftpslib.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\httpslib.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\m2.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\m2crypto.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\m2urllib.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\m2urllib2.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\m2xmlrpclib.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\Rand.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\RC4.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\RSA.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\six.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\SMIME.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\threading.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\util.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\X509.py -> build\lib.win32-2.7\M2Crypto
    copying M2Crypto\__init__.py -> build\lib.win32-2.7\M2Crypto
    creating build\lib.win32-2.7\M2Crypto\PGP
    copying M2Crypto\PGP\constants.py -> build\lib.win32-2.7\M2Crypto\PGP
    copying M2Crypto\PGP\packet.py -> build\lib.win32-2.7\M2Crypto\PGP
    copying M2Crypto\PGP\PublicKey.py -> build\lib.win32-2.7\M2Crypto\PGP
    copying M2Crypto\PGP\PublicKeyRing.py -> build\lib.win32-2.7\M2Crypto\PGP
    copying M2Crypto\PGP\RSA.py -> build\lib.win32-2.7\M2Crypto\PGP
    copying M2Crypto\PGP\__init__.py -> build\lib.win32-2.7\M2Crypto\PGP
    creating build\lib.win32-2.7\M2Crypto\SSL
    copying M2Crypto\SSL\cb.py -> build\lib.win32-2.7\M2Crypto\SSL
    copying M2Crypto\SSL\Checker.py -> build\lib.win32-2.7\M2Crypto\SSL
    copying M2Crypto\SSL\Cipher.py -> build\lib.win32-2.7\M2Crypto\SSL
    copying M2Crypto\SSL\Connection.py -> build\lib.win32-2.7\M2Crypto\SSL
    copying M2Crypto\SSL\Context.py -> build\lib.win32-2.7\M2Crypto\SSL
    copying M2Crypto\SSL\Session.py -> build\lib.win32-2.7\M2Crypto\SSL
    copying M2Crypto\SSL\SSLServer.py -> build\lib.win32-2.7\M2Crypto\SSL
    copying M2Crypto\SSL\ssl_dispatcher.py -> build\lib.win32-2.7\M2Crypto\SSL
    copying M2Crypto\SSL\timeout.py -> build\lib.win32-2.7\M2Crypto\SSL
    copying M2Crypto\SSL\TwistedProtocolWrapper.py -> build\lib.win32-2.7\M2Cryp
to\SSL
    copying M2Crypto\SSL\__init__.py -> build\lib.win32-2.7\M2Crypto\SSL
    running build_ext
    building 'M2Crypto._m2crypto' extension
    creating build\temp.win32-2.7
    creating build\temp.win32-2.7\Release
    creating build\temp.win32-2.7\Release\SWIG
    C:\Users\admin\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python
\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ic:\python27\include -I
c:\python27\PC -Ic:\windows\temp\pip-build-rk8rnr\M2Crypto\SWIG /TcSWIG/_m2crypt
o_wrap.c /Fobuild\temp.win32-2.7\Release\SWIG/_m2crypto_wrap.obj -DTHREADING -D_
CRT_SECURE_NO_WARNINGS
    _m2crypto_wrap.c
    SWIG/_m2crypto_wrap.c(3550) : warning C4068: unknown pragma
    SWIG/_m2crypto_wrap.c(3551) : warning C4068: unknown pragma
    SWIG/_m2crypto_wrap.c(3554) : fatal error C1083: Cannot open include file: '
openssl/err.h': No such file or directory
    error: command 'C:\\Users\\admin\\AppData\\Local\\Programs\\Common\\Microsof
t\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\
\windows\\temp\\pip-build-rk8rnr\\M2Crypto\\setup.py';f=getattr(tokenize, 'open'
, open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(cod
e, __file__, 'exec'))" install --record c:\windows\temp\pip-kak0kz-record\instal
l-record.txt --single-version-externally-managed --compile" failed with error co
de 1 in c:\windows\temp\pip-build-rk8rnr\M2Crypto\

**Comment by lincoln1233** [comment]
Is this similar issue of any help? 
https://github.com/pyinstaller/pyinstaller/issues/2881#issuecomment-333311726

https://stackoverflow.com/questions/32944919/pyinstaller-does-not-work-when-including-pysnmp

**Comment by passwordleak** [comment]
What do we replace for

`             hiddenimports=PyInstaller.utils.hooks.collect_submodules('pysnmp'),
`

**Comment by quentinhardy** [comment]
I think I is not anymore a good idea to generate an exe with pyinstaller from pupy python code.
If it is for avoiding AV, I think you should use a packer with the pupy DDL or EXE file.
