### ISSUE TITLE
Can not generate Linux payload ?

### ISSUE THREAD

**Issue by ibaka9** [n1nj4sec/pupy#547]
Why I can not generate linux payload now? I checked "payload_template" folder, there is no template for linux like older version.

Is pupy no longer support Linux ?

**Comment by ibaka9** [comment]
@lincoln1233 Yes I noticed that, I tried to copy the "pupyx64.lin.so" from older version of pupy, but it's still not working.

**Comment by xuxuedong** [comment]
hey, i have the same question, is that mean, i must compiled the template by myself?

**Comment by ibaka9** [comment]
@xuxuedong so where is the source code of linux's payload?

**Comment by xuxuedong** [comment]
isn't it sources-linux and sources on https://github.com/n1nj4sec/pupy/tree/unstable/client?

**Comment by n1nj4sec** [comment]
try to download the templates again, they are available in the txz
