### ISSUE TITLE
Payload Sources

### ISSUE THREAD

**Issue by realoriginal** [n1nj4sec/pupy#551]
Hello!

I did find the precompiled binaries for the payloads, I was wondering for the DLL / EXE files, where could I obtain the C++ / C source? Hoping to learn from it :D 
thank you

**Comment by xuxuedong** [comment]
is there, sources-linux and sources -> https://github.com/n1nj4sec/pupy/tree/unstable/client
and the instructions is there -> https://github.com/n1nj4sec/pupy/wiki/Build-payloads-from-sources
