### ISSUE TITLE
Allowing pupy server to run without a GUI

### ISSUE THREAD

**Issue by archey** [n1nj4sec/pupy#554]
I noticed that when running pupsh.py from a ssh terminal it will try load all of the modules. However this is an issue as one of the modules being the redesktop.py module requires the pyautogui library which requires an x11 display. Would it be possible to add a switch like say --gui to pupy server to have it load up the modules and then a default option to load all of the modules that dont require pyautogui. Or may have it detect the display and load the modules that need pyautogui and if not dont load them into the server. Not sure what the best option is, just thinking its basically a cli application except for the modules which require pyautogui.

**Comment by archey** [comment]
I have temporarily removed the rdesktop module in my setup, to run it without a GUI

**Comment by jrenaud007** [comment]
I removed pyautogui from requirements.txt and it worked for me, i added a section on the wiki

**Comment by archey** [comment]
Yeah thats great, but that just breaks the rdesktop module. I see a few ways of handling it either remove the rdesktop module completely so we dont have to use pyautogui at all. Or setup an option to only load modules that need pyautogui with a --gui option to the server. I dont think the authors intent would be to remove the module entirely as that would break current functionality.

**Comment by jrenaud007** [comment]
You're totally right, but that's the fix for now, when n1nj4 fix it i'll update the documentation.

i plan to use this shell as a remote software for a product i'll distribute soon. i'll try to add documentation with further changes.

**Comment by archey** [comment]
Lets hope the option is sorted out by the Author at some point. I will close this for now. As your fix and my temporary hack are good enough for now.
