### ISSUE TITLE
Error in build_library_helper.py for x64

### ISSUE THREAD

**Issue by msidagni** [n1nj4sec/pupy#56]
When I try to recreate the libraryx64.zip using build_library_helper.py it errors out towards the end with the following error:

Traceback (most recent call last):
  File "build_library_helper.py", line 76, in <module>
    os.chdir('build/bdist.win%s/winexe/collect-2.7' % platform)
WindowsError: [Error 3] The system cannot find the path specified: 'build/bdist.
win-amd64/winexe/collect-2.7'

This only happens for x64 not for x86. The corresponding compressed archive libraryx64.zip is created but it has 0 byte.

**Comment by n1nj4sec** [comment]
you probably have a particularity on your system, check what name py2exe generate for you in build/bdist.winXXXXX

**Comment by n1nj4sec** [comment]
btw, do you have python x64 installer ? ...

**Comment by msidagni** [comment]
That must be it. I do not have the python x64 installer.

Thanks.
