### ISSUE TITLE
Problem installing/getting started with Pupy

### ISSUE THREAD

**Issue by TheMostGloriousAsteroids** [n1nj4sec/pupy#566]
Hi,

So I followed the instructions exactly for both the unstable and master branches for pupy and I get script errors, and it does not run at all. I'm using Ubuntu 16.04, Python 3.5.2, and Pip version 8.1.1. 

The exact error I get when attempting to run the Pupy shell is: 
  File "pupysh.py", line 86
    except PupyCredentials.EncryptionError, e:
                                          ^
SyntaxError: invalid syntax

Looks like a syntax error in the code itself; is there something I'm missing here? Nothing I've done so far has seemed to fix the problem in any way, nor can I find a solution anywhere else.

**Comment by xuxuedong** [comment]
@TheMostGloriousAsteroids have a test of python 2.7.x

**Comment by TheMostGloriousAsteroids** [comment]
Hi, I did test on the same platform with Python 2.7.x, with Pip updated, and I got an error saying it couldn't find the rpyc.core module.

**Comment by xuxuedong** [comment]
have you installed rpyc inside the requirements.txt correctly?
