### ISSUE TITLE
Pyinst: ImportError: No module named Crypto.Cipher

### ISSUE THREAD

**Issue by passwordleak** [n1nj4sec/pupy#569]
I am attempting to compile the pyinst payload to a windows .exe. I was unable to install pycrypto using pip, so I downloaded PyCrypto 2.6 for Python 2.7 64 and 32 bit: 
http://www.voidspace.org.uk/python/modules.shtml#pycrypto

EDIT: I also installed pycrypto using pip, and I still have the same error. 

Afterwards, when I open python with wine, all the imports worked, so I compiled with pyinstaller:

`wine C:\\Python27\\Scripts\\pyinstaller.exe --onedir /opt/pupy_vy2Df6.py`

But, when I try to run the .exe on windows: 
```
Traceback (most recent call last):
  File "pupy_vy2Df6.py", line 4, in <module>
ImportError: No module named Crypto.Cipher
[19364] Failed to execute script pupy_vy2Df6
```

I tried --onedir and still the same error. I even tried cyrptodome, which was supposed to be a replacement, but still no luck. 

I tried doing the same thing on windows and I get this error: 

```
Traceback (most recent call last):
  File "pupy_vy2Df6.py", line 4, in <module>
    from Crypto.Cipher import AES
  File "Crypto\Cipher\__init__.pyc", line 3, in <module>
  File "Crypto\Cipher\_mode_ecb.pyc", line 46, in <module>
  File "Crypto\Util\_raw_api.pyc", line 189, in load_pycryptodome_raw_lib
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb'
```
I tried both pyinstaller and py2exe and still no success. 
Kali Linux with Wine and Windows 10

**Comment by n1nj4sec** [comment]
try to remove pycrypto and install pycryptodome (https://github.com/Legrandin/pycryptodome). If it does not work, you can still totally remove pycrypto as it is not a necessary dependency and pupy will automatically use an alternate method for AES ...
