### ISSUE TITLE
Pupygen.py isn't working - traceback error

### ISSUE THREAD

**Issue by AlanCrytex** [n1nj4sec/pupy#585]
I installed all the things that needed and when I try to run pupygen.py

**Traceback (most recent call last):
  File "./pupygen.py", line 7, in <module>
    from pupylib.utils.network import get_listener_ip, get_listener_port
  File "/root/pupy/pupy/pupylib/__init__.py", line 5, in <module>
    from PupyService import *
  File "/root/pupy/pupy/pupylib/PupyService.py", line 17, in <module>
    import rpyc.core.service
ImportError: No module named rpyc.core.service**

Can someone tell me what should I do to fix this?

I'm on Kali Linux 2018.1 using Oracle VM Virtualbox

**Comment by NightxGod** [comment]
Hi yes I ran into this issue, is it referenced into the Wiki.
But if you navigate to the pupy folder and find the requirments.txt and remove the line "pyautogui", should fix your issue.
https://github.com/n1nj4sec/pupy/wiki/Installation
