### ISSUE TITLE
[Request] Sort and Display Modules by OS

### ISSUE THREAD

**Issue by zero77** [n1nj4sec/pupy#588]
Can you please add the option to display modules that only work with a specific OS, because this would make it a lot easier to find a module.

For example, 
list_modules  -W “only shows Window compatible modules” 
list_modules  -L “only shows Linux compatible modules”

Thanks

**Comment by AlessandroZ** [comment]
This functionality has already been implemented. Select a host and if it's a windows, only windows module will be printed (same thing for other OS). To unselect all targets and list all module: `select -g`

**Comment by zero77** [comment]
So there’s no way to run a module on all your hosts and sort modules by OS at the same time.
