### ISSUE TITLE
[Question] Linux Persistence

### ISSUE THREAD

**Issue by zero77** [n1nj4sec/pupy#589]
Can anyone suggest a persistence module or method in Pupy, for Linux and Ideally in memory.

Some think that works weather the client is root or not, so maybe not /etc/init.d or rc.local or /etc/systemd as I think root is required.

Thanks

**Comment by b2az** [comment]
maybe you add the payload to the bashrc?

**Comment by zero77** [comment]
Is it possible to edit bashrc without being root or having root permissions.

**Comment by b2az** [comment]
@zero77 check out this one:
[](url)

**Comment by zero77** [comment]
thanks, i will have a look.
