### ISSUE TITLE
Help me requirments.txt install error

### ISSUE THREAD

**Issue by jdjdbsudgskdododolldlx** [n1nj4sec/pupy#598]
When i install requirments.txt, i have error
My last error name is
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
I try update python3.6 devpakage but now, it don't worked. i have cpu i5 2450(?). It doesn't work because of cpu? Because my cpu is old? Help me! you can be my hero

**Comment by glides** [comment]
We'd need to see the entire output leading up to that error to more accurately troubleshoot.

However, try 'apt-get install python-dev' or 'sudo apt-get install python-dev' is where I would start.

**Comment by AlphaMufasaOmega** [comment]
dont forget that the command line commands change slightly depending on the type of linux operating system you are usinf it changes between debian and fedora (.rpm verses other setups)

**Comment by AlphaMufasaOmega** [comment]
it looks like an error in memory.. not enough space on disk, maybe ram as w ell definetly on disk

**Comment by AlessandroZ** [comment]
You should have some missing dependencies on your system.
