### ISSUE TITLE
How to use own custom exe payload?

### ISSUE THREAD

**Issue by Mr-BlackHat** [n1nj4sec/pupy#599]
Hello i want to use my own custom payload exe is there anyone who can me with this?

**Comment by glides** [comment]
The code to generate the exe templates is in client/source. Customize it however you want.
If you have a binary already generated but want to bypass AV, look at Veil Evasion.

**Comment by Mr-BlackHat** [comment]
@glides 
Yes i know but got some error after file was created used that exe to create payload but they are not throwing connection back..

**Comment by Mr-BlackHat** [comment]
Have a look running buildenv.sh from client/sources




------------------------------------------------------
Running Wine/winetricks as root is highly discouraged. See https://wiki.winehq.org/FAQ#Should_I_run_Wine_as_root.3F
------------------------------------------------------
------------------------------------------------------
Your version of wine 1.8.7 is no longer supported upstream. You should upgrade to 2.x
------------------------------------------------------
Using winetricks 20180217-next - sha256sum: 9d0d23c3b1c5277dc50ed5e6eb7a5dac85628370788763ce9a6da68c538e0225 with wine-1.8.7 (Debian 1.8.7-2) and WINEARCH=win32
Executing w_do_call winxp
Executing load_winxp 
Setting Windows version to winxp
Executing wine regedit C:\windows\Temp\_winxp\set-winver.reg
------------------------------------------------------
Running /usr/bin/wineserver -w. This will hang until all wine processes in prefix=/root/pupy/client/sources/buildenv/win32 terminate
------------------------------------------------------
------------------------------------------------------
Running Wine/winetricks as root is highly discouraged. See https://wiki.winehq.org/FAQ#Should_I_run_Wine_as_root.3F
------------------------------------------------------
------------------------------------------------------
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
------------------------------------------------------
Your version of wine 1.8.7 is no longer supported upstream. You should upgrade to 2.x
------------------------------------------------------
Using winetricks 20180217-next - sha256sum: 9d0d23c3b1c5277dc50ed5e6eb7a5dac85628370788763ce9a6da68c538e0225 with wine-1.8.7 (Debian 1.8.7-2) and WINEARCH=win64
Executing w_do_call win7
Executing load_win7 
The operation completed successfully
Setting Windows version to win7
Executing wine regedit C:\windows\Temp\_win7\set-winver.reg
Executing wine64 regedit C:\windows\Temp\_win7\set-winver.reg
------------------------------------------------------
Running /usr/bin/wineserver -w. This will hang until all wine processes in prefix=/root/pupy/client/sources/buildenv/win64 terminate
------------------------------------------------------
The operation completed successfully
The operation completed successfully
The operation completed successfully
Compiling C:\Python27\Lib\lib2to3\tests\data\py3_test_grammar.py ...
  File "C:\Python27\Lib\lib2to3\tests\data\py3_test_grammar.py", line 130
    x = ...
        ^
SyntaxError: invalid syntax

Compiling C:\Python27\Lib\test\bad_coding.py ...
  File "C:\Python27\Lib\test\bad_coding.py", line 0
SyntaxError: unknown encoding: uft-8

Compiling C:\Python27\Lib\test\bad_coding2.py ...
  File "C:\Python27\Lib\test\bad_coding2.py", line 0
SyntaxError: encoding problem: utf8 with BOM

Compiling C:\Python27\Lib\test\bad_coding3.py ...
  File "C:\Python27\Lib\test\bad_coding3.py", line 0
SyntaxError: decoder did not return an unicode object (type=str)

Compiling C:\Python27\Lib\test\badsyntax_future3.py ...
SyntaxError: future feature rested_snopes is not defined (badsyntax_future3.py, line 3)

Compiling C:\Python27\Lib\test\badsyntax_future4.py ...
  File "C:\Python27\Lib\test\badsyntax_future4.py", line 3
    from __future__ import nested_scopes
SyntaxError: from __future__ imports must occur at the beginning of the file

Compiling C:\Python27\Lib\test\badsyntax_future5.py ...
  File "C:\Python27\Lib\test\badsyntax_future5.py", line 4
    from __future__ import nested_scopes
SyntaxError: from __future__ imports must occur at the beginning of the file

Compiling C:\Python27\Lib\test\badsyntax_future6.py ...
  File "C:\Python27\Lib\test\badsyntax_future6.py", line 3
    from __future__ import nested_scopes
SyntaxError: from __future__ imports must occur at the beginning of the file

Compiling C:\Python27\Lib\test\badsyntax_future7.py ...
SyntaxError: from __future__ imports must occur at the beginning of the file (badsyntax_future7.py, line 3)

Compiling C:\Python27\Lib\test\badsyntax_future8.py ...
SyntaxError: future feature * is not defined (badsyntax_future8.py, line 3)

Compiling C:\Python27\Lib\test\badsyntax_future9.py ...
SyntaxError: not a chance (badsyntax_future9.py, line 3)

Compiling C:\Python27\Lib\test\badsyntax_nocaret.py ...
  File "C:\Python27\Lib\test\badsyntax_nocaret.py", line 2
    [x for x in x] = x
SyntaxError: can't assign to list comprehension

Compiling C:\Python27\Lib\lib2to3\tests\data\py3_test_grammar.py ...
  File "C:\Python27\Lib\lib2to3\tests\data\py3_test_grammar.py", line 130
    x = ...
        ^
SyntaxError: invalid syntax

Compiling C:\Python27\Lib\test\bad_coding.py ...
  File "C:\Python27\Lib\test\bad_coding.py", line 0
SyntaxError: unknown encoding: uft-8

Compiling C:\Python27\Lib\test\bad_coding2.py ...
  File "C:\Python27\Lib\test\bad_coding2.py", line 0
SyntaxError: encoding problem: utf8 with BOM

Compiling C:\Python27\Lib\test\bad_coding3.py ...
  File "C:\Python27\Lib\test\bad_coding3.py", line 0
SyntaxError: decoder did not return an unicode object (type=str)

Compiling C:\Python27\Lib\test\badsyntax_future3.py ...
SyntaxError: future feature rested_snopes is not defined (badsyntax_future3.py, line 3)

Compiling C:\Python27\Lib\test\badsyntax_future4.py ...
  File "C:\Python27\Lib\test\badsyntax_future4.py", line 3
    from __future__ import nested_scopes
SyntaxError: from __future__ imports must occur at the beginning of the file

Compiling C:\Python27\Lib\test\badsyntax_future5.py ...
  File "C:\Python27\Lib\test\badsyntax_future5.py", line 4
    from __future__ import nested_scopes
SyntaxError: from __future__ imports must occur at the beginning of the file

Compiling C:\Python27\Lib\test\badsyntax_future6.py ...
  File "C:\Python27\Lib\test\badsyntax_future6.py", line 3
    from __future__ import nested_scopes
SyntaxError: from __future__ imports must occur at the beginning of the file

Compiling C:\Python27\Lib\test\badsyntax_future7.py ...
SyntaxError: from __future__ imports must occur at the beginning of the file (badsyntax_future7.py, line 3)

Compiling C:\Python27\Lib\test\badsyntax_future8.py ...
SyntaxError: future feature * is not defined (badsyntax_future8.py, line 3)

Compiling C:\Python27\Lib\test\badsyntax_future9.py ...
SyntaxError: not a chance (badsyntax_future9.py, line 3)

Compiling C:\Python27\Lib\test\badsyntax_nocaret.py ...
  File "C:\Python27\Lib\test\badsyntax_nocaret.py", line 2
    [x for x in x] = x
SyntaxError: can't assign to list comprehension

Compiling C:\Python27\Lib\lib2to3\tests\data\py3_test_grammar.py ...
  File "C:\Python27\Lib\lib2to3\tests\data\py3_test_grammar.py", line 130
    x = ...
        ^
SyntaxError: invalid syntax

Compiling C:\Python27\Lib\test\bad_coding.py ...
  File "C:\Python27\Lib\test\bad_coding.py", line 0
SyntaxError: unknown encoding: uft-8

Compiling C:\Python27\Lib\test\bad_coding2.py ...
  File "C:\Python27\Lib\test\bad_coding2.py", line 0
SyntaxError: encoding problem: utf8 with BOM

Compiling C:\Python27\Lib\test\bad_coding3.py ...
  File "C:\Python27\Lib\test\bad_coding3.py", line 0
SyntaxError: decoder did not return an unicode object (type=str)

Compiling C:\Python27\Lib\test\badsyntax_future3.py ...
SyntaxError: future feature rested_snopes is not defined (badsyntax_future3.py, line 3)

Compiling C:\Python27\Lib\test\badsyntax_future4.py ...
  File "C:\Python27\Lib\test\badsyntax_future4.py", line 3
    from __future__ import nested_scopes
SyntaxError: from __future__ imports must occur at the beginning of the file

Compiling C:\Python27\Lib\test\badsyntax_future5.py ...
  File "C:\Python27\Lib\test\badsyntax_future5.py", line 4
    from __future__ import nested_scopes
SyntaxError: from __future__ imports must occur at the beginning of the file

Compiling C:\Python27\Lib\test\badsyntax_future6.py ...
  File "C:\Python27\Lib\test\badsyntax_future6.py", line 3
    from __future__ import nested_scopes
SyntaxError: from __future__ imports must occur at the beginning of the file

Compiling C:\Python27\Lib\test\badsyntax_future7.py ...
SyntaxError: from __future__ imports must occur at the beginning of the file (badsyntax_future7.py, line 3)

Compiling C:\Python27\Lib\test\badsyntax_future8.py ...
SyntaxError: future feature * is not defined (badsyntax_future8.py, line 3)

Compiling C:\Python27\Lib\test\badsyntax_future9.py ...
SyntaxError: not a chance (badsyntax_future9.py, line 3)

Compiling C:\Python27\Lib\test\badsyntax_nocaret.py ...
  File "C:\Python27\Lib\test\badsyntax_nocaret.py", line 2
    [x for x in x] = x
SyntaxError: can't assign to list comprehension

Compiling C:\Python27\Lib\lib2to3\tests\data\py3_test_grammar.py ...
  File "C:\Python27\Lib\lib2to3\tests\data\py3_test_grammar.py", line 130
    x = ...
        ^
SyntaxError: invalid syntax

Compiling C:\Python27\Lib\test\bad_coding.py ...
  File "C:\Python27\Lib\test\bad_coding.py", line 0
SyntaxError: unknown encoding: uft-8

Compiling C:\Python27\Lib\test\bad_coding2.py ...
  File "C:\Python27\Lib\test\bad_coding2.py", line 0
SyntaxError: encoding problem: utf8 with BOM

Compiling C:\Python27\Lib\test\bad_coding3.py ...
  File "C:\Python27\Lib\test\bad_coding3.py", line 0
SyntaxError: decoder did not return an unicode object (type=str)

Compiling C:\Python27\Lib\test\badsyntax_future3.py ...
SyntaxError: future feature rested_snopes is not defined (badsyntax_future3.py, line 3)

Compiling C:\Python27\Lib\test\badsyntax_future4.py ...
  File "C:\Python27\Lib\test\badsyntax_future4.py", line 3
    from __future__ import nested_scopes
SyntaxError: from __future__ imports must occur at the beginning of the file

Compiling C:\Python27\Lib\test\badsyntax_future5.py ...
  File "C:\Python27\Lib\test\badsyntax_future5.py", line 4
    from __future__ import nested_scopes
SyntaxError: from __future__ imports must occur at the beginning of the file

Compiling C:\Python27\Lib\test\badsyntax_future6.py ...
  File "C:\Python27\Lib\test\badsyntax_future6.py", line 3
    from __future__ import nested_scopes
SyntaxError: from __future__ imports must occur at the beginning of the file

Compiling C:\Python27\Lib\test\badsyntax_future7.py ...
SyntaxError: from __future__ imports must occur at the beginning of the file (badsyntax_future7.py, line 3)

Compiling C:\Python27\Lib\test\badsyntax_future8.py ...
SyntaxError: future feature * is not defined (badsyntax_future8.py, line 3)

Compiling C:\Python27\Lib\test\badsyntax_future9.py ...
SyntaxError: not a chance (badsyntax_future9.py, line 3)

Compiling C:\Python27\Lib\test\badsyntax_nocaret.py ...
  File "C:\Python27\Lib\test\badsyntax_nocaret.py", line 2
    [x for x in x] = x
SyntaxError: can't assign to list comprehension

pupymemexec.c
Microsoft (R) Incremental Linker Version 9.00.30729.01
Copyright (C) Microsoft Corporation.  All rights reserved.

/NXCOMPAT:NO /LTCG 
/ltcg 
/dll 
/implib:C:\Python27\Lib\site-packages\pupymemexec.lib 
/out:C:\Python27\Lib\site-packages\pupymemexec.pyd 
pupymemexec.obj 
C:\Python27\libs\python27.lib 
advapi32.lib 
   Creating library C:\Python27\Lib\site-packages\pupymemexec.lib and object C:\Python27\Lib\site-packages\pupymemexec.exp
Generating code
Finished generating code
pupymemexec.c
Microsoft (R) Incremental Linker Version 9.00.30729.01
Copyright (C) Microsoft Corporation.  All rights reserved.

/NXCOMPAT:NO /LTCG 
/ltcg 
/dll 
/implib:C:\Python27\Lib\site-packages\pupymemexec.lib 
/out:C:\Python27\Lib\site-packages\pupymemexec.pyd 
pupymemexec.obj 
C:\Python27\libs\python27.lib 
advapi32.lib 
   Creating library C:\Python27\Lib\site-packages\pupymemexec.lib and object C:\Python27\Lib\site-packages\pupymemexec.exp
Generating code
Finished generating code
make: Entering directory '/root/pupy/pupy/external/winpty'
rm -fr build
make: Leaving directory '/root/pupy/pupy/external/winpty'
make: Entering directory '/root/pupy/pupy/external/winpty'
Creating directory build/mingw/
Copying src/shared/PrecompiledHeader.h to build/mingw/PrecompiledHeader.h
Compiling build/mingw/PrecompiledHeader.h
Makefile:83: recipe for target 'build/mingw/PrecompiledHeader.h.gch' failed
make: Leaving directory '/root/pupy/pupy/external/winpty'

**Comment by glides** [comment]
Well - you never said you were having trouble generating the templates. You just said you wanted to use a custom exe and ask if someone could help. I think my answer addresses your original post.

This is an unstable branch, you're going to be running into ALL kinds of stability issues and errors. You'll need to troubleshoot them. And if you want others to help troubleshoot them you need to start adding details to your help requests. What OS are you building from? What steps did you take already to fix the issue? etc.

I'm not sure how much time @n1nj4sec has for this project but his commits and comments have coming in slower lately.

You could always take a look at @alxchk's fork which uses docker to build the templates and that (for the most part) is working out of the box: https://github.com/alxchk/pupy (keep in mind, his branch is very much a WIP as well)

**Comment by Mr-BlackHat** [comment]
Okay thanks and I forgot to mention 

Im using Kali Linux 2017

**Comment by glides** [comment]
No worries.

If you clone @alxchk's fork you'll want to run "./create-workspace.py -P <path to pupy dir> <new workspace path>

Might need to make a few tweaks....for instance, I had to change:
"subprocess.check_call(['build-docker.sh'], env=env)" 
to
"subprocess.check_call(['./build-docker.sh'], env=env)"
 
Add ~/.local/bin to your path. (export PATH=$PATH:/root/.local/bin)

**Comment by AlessandroZ** [comment]
otherwise, generate a dll and load it from a custom payload
`>> gen -S -f client -O windows -A x64 connect --host ip:port -t transport`
