### ISSUE TITLE
How do you pronounce "pupy"?

### ISSUE THREAD

**Issue by passwordleak** [n1nj4sec/pupy#601]
Is it "p-you-pee" or "puppy"? Where does the name stem from? The py part probably stems from python, like scrapy.

**Comment by HorneyAttorney** [comment]
I think it's like puppy.. everybody I know says it like this..

**Comment by dytra** [comment]
everybod loves  puppy 🐶, so say it that way 😀

**Comment by sparklespdx** [comment]
It's pupi, like, bug babies.

**Comment by Tapmemer** [comment]
it's p-you-pee due to only one p before the y

**Comment by AlessandroZ** [comment]
> It's pupi, like, bug babies.
I also pronounce like that ;)
