### ISSUE TITLE
can not install buildozer

### ISSUE THREAD

**Issue by cexdelta** [n1nj4sec/pupy#602]
i try to install buildozer but show.

> Traceback (most recent call last):
>   File "/usr/bin/pip", line 9, in <module>
>     from pip import main
> ImportError: cannot import name main
> 

someone help?

**Comment by glides** [comment]
That's a pip error. Take a look here: https://github.com/pypa/pip/issues/5240
If you upgraded pip to 10 - that might be the issue.

**Comment by AlessandroZ** [comment]
pip seems broken. It's not related to pupy. 
Try: `hash -r pip`
