### ISSUE TITLE
 Why does this mistake appear on the Ubuntu&centos in the process of installing pupy???

### ISSUE THREAD

**Issue by currysmygod** [n1nj4sec/pupy#609]
in the process of installing pupy
Test it on Virtual Private Server(centos 6.9&ubuntu 16.4)
When I run Python pupysh.py 
The result will appear "ValueError:value must be precomputed hash"
Who can help me ?
@n1nj4sec
@everybody

**Comment by glides** [comment]
Paste the entire error. I believe it's looking for the credential.py file and unable to find it, but I need to see the entire output

**Comment by sharpbazil** [comment]
Same issue here, ran the same setup as I did before (exactly as in instructions, plus libopenssl-dev and such to build dependencies).  Fails on that same error.  Maybe m2crypto has changed?

**Comment by sharpbazil** [comment]
Also, here's the error (right after generating certs):
Traceback (most recent call last):
  File "pupysh.py", line 85, in <module>
    credentials = PupyCredentials.Credentials()
  File "/home/ubuntu/pupy/pupy/pupylib/PupyCredentials.py", line 180, in __init__
    self._generate(password=password, configfile=configfile)
  File "/home/ubuntu/pupy/pupy/pupylib/PupyCredentials.py", line 352, in _generate
    SSL_CA_PRIVATE_KEY, SSL_CA_CERTIFICATE, CAKEY, CACERT = self._generate_ssl_ca()
  File "/home/ubuntu/pupy/pupy/pupylib/PupyCredentials.py", line 291, in _generate_ssl_ca
    cert.add_ext(X509.new_extension('subjectKeyIdentifier', cert.get_fingerprint()))
  File "/usr/local/lib/python2.7/dist-packages/M2Crypto/X509.py", line 45, in new_extension
    raise ValueError('value must be precomputed hash')
ValueError: value must be precomputed hash

**Comment by glides** [comment]
While we wait for M2Crypto to patch

You can modify PupyCredentials.py this line in two spots:
`cert.add_ext(X509.new_extension('subjectKeyIdentifier', cert.get_fingerprint()))
`with
`cert.add_ext(X509.new_extension('subjectKeyIdentifier', str(cert.get_fingerprint())))
`

**Comment by currysmygod** [comment]
when i executed this order (pip install -r pupy/requirements.txt)
The errors are as follows
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-xQmc2e/m2crypto/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-TB4xU2/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-xQmc2e/m2crypto/

@glides

**Comment by glides** [comment]
@currysmygod Try:
`apt-get install python-m2crypto`

**Comment by mlzxgzy** [comment]
pip uninstall m2crypto
apt-get install python-m2crypto

**Comment by Caleb1994** [comment]
I had the m2crypto compilation issue as well, but a better solution (at least on up to date Arch), is to just install the `swig` package (e.g. `pacman -S swig`) and then try to install m2crypto again. That worked for me, and keeps python libraries out of my system package manager.
