### ISSUE TITLE
can't make apk file

### ISSUE THREAD

**Issue by sam1591** [n1nj4sec/pupy#616]
root@kali:~/pupy/pupy# ./pupygen.py -f mytest.apk connect --host 192.168.0.3 --transport ssl
usage: pupygen.py [-h]
                  [-f {client,py,pyinst,py_oneliner,ps1,ps1_oneliner,rubber_ducky}]
                  [-O {android,windows,linux,solaris}] [-A {x86,x64}] [-U]
                  [-P PACKER] [-S] [-o OUTPUT] [-D OUTPUT_DIR] [-s SCRIPTLET]
                  [-l] [-E] [--no-use-proxy] [--randomize-hash]
                  [--oneliner-listen-port ONELINER_LISTEN_PORT]
                  [--oneliner-no-ssl] [--oneliner-nothidden]
                  [--debug-scriptlets] [--debug] [--workdir WORKDIR]
                  [{bind,auto_proxy,dnscnc,connect}] ...
pupygen.py: error: argument -f/--format: invalid choice: 'mytest.apk' (choose from 'client', 'py', 'pyinst', 'py_oneliner', 'ps1', 'ps1_oneliner', 'rubber_ducky')

**Comment by glides** [comment]
You aren't using pupygen correctly.

https://github.com/n1nj4sec/pupy/wiki/Generate-payloads

close 616
