### ISSUE TITLE
Older Versions of this Project

### ISSUE THREAD

**Issue by s1st3r** [n1nj4sec/pupy#617]
Hey guys,

Am looking for older versions of this project for learning purposes, is there a link somewhere?

**Comment by glides** [comment]
The entire history of the project is able to be cloned using git from this repository.
What you need to do is make a branch from the commit you want to clone. Do a little digging on how to use git and you will figure it out.

**Comment by s1st3r** [comment]
@glides I just  did, i have found the first pages of commits. for those who wonna look at it and study, check out here

https://github.com/n1nj4sec/pupy/commits/unstable?after=aa95dc42ff131f291fed229029c545203ad5932d+1749
