### ISSUE TITLE
Execution of Pupy on Windows 10 April 2018 Update (version 1803) Doesn't work

### ISSUE THREAD

**Issue by CG-root** [n1nj4sec/pupy#619]
@alxchk 

Can you commit below fix ?

https://github.com/PowerShellMafia/PowerSploit/issues/293

Thanks

**Comment by alxchk** [comment]
Hi! Upstream project belongs to @n1nj4sec, I can only commit to my branch. Ill test this on W10 this week

**Comment by CG-root** [comment]
Thanks.

btw, I noticed that you update your branch more frequently. How can I use (=build) it ? :)

**Comment by alxchk** [comment]
You need to have docker, which you can control with user which will build pupy.
Next steps depends on how much you are going to trust builds generated by travis automatically.
You may want to build toolchain by yourself (https://github.com/alxchk/docker-old-tc-bootstrap -- for Linux environment, https://github.com/alxchk/docker-old-tc -- pupy build environment).
Then you may want to look into build-docker.sh script and client/build-docker.sh script. It should work as is, but depends on environment some manual fixes may be required.
Generally you can just fire 
```
cd pupy-git-dir; sh build-docker.sh
```
or in case you want to use toolchain from your machine:
```
cd pupy-git-dir; sh REPO="" build-docker.sh 
```

After first full successful build you can easily rebuild targets with 
```
docker start -a build-pupy-linux64
```
etc

**Comment by CG-root** [comment]
I'm trying to build it using build-docker.sh. but I get:
```
[+] Compile pykcp
Directory '../../pupy/external/pykcp' is not installable. File 'setup.py' not found.
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
And then script terminates

**Comment by alxchk** [comment]
You should clone repo recursively (--recurisve option, or git submodule init && git submodule update).

**Comment by CG-root** [comment]
What are the main features in your branch ?

**Comment by alxchk** [comment]
https://github.com/n1nj4sec/pupy/pull/594

**Comment by CG-root** [comment]
ok using --recursive flag it is working, what should I suppose to perform after executing `docker start -a build-pupy-linux64` ?

**Comment by CG-root** [comment]
I'm using Kali 2018.2 distro. what arguments should I supply to create-workspace ?

**Comment by AlessandroZ** [comment]
Lots of things have changed since June, so I close the issue
