### ISSUE TITLE
Pupy ELF payload completely static?

### ISSUE THREAD

**Issue by dfclin073** [n1nj4sec/pupy#630]
Using the client option creates an elf file that is dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.0.30, stripped. Using pyinstall produced the same results.   Can we get something like dropbear which is statically linked, for GNU/Linux 3.2.0. Is this possible?

**Comment by alxchk** [comment]
Technically this may be possible, but it's why to do that?

Actually there are two main things why pupy for linux looks this way.
1. Kernel ABI workarounds (like vsyscall presence/absence).
2. Easy interfacing with system (dbus, libX11 etc).
3. Custom ELF/SO loader should be written to load modules to static base image.
