### ISSUE TITLE
Missing dependency umsgpack, poor documentation for pupygen, broken android payload

### ISSUE THREAD

**Issue by Strazzom** [n1nj4sec/pupy#635]
1) When attempting to generate an android payload, pupy complains about missing umsgpack. This is solved by installing this package via `pip install umsgpack`.

2) The documentation is also very poor. After much trial and error, I found that it must be specified in the following order to work correctly: `./pupygen.py [payload options] [connection options]`.

For instance, to correctly generate a python oneliner: `./pupygen.py --format py_oneliner connect --host 192.168.1.2:8443 -t tcp_cleartext`

The `--format` option is (what I am calling) a payload option. This category includes anything that isn't the payload type (bind, connect, dnscnc, auto_proxy), the host and port options, and the transport. For these specific parameters, they must be specified at the END of the line, otherwise an error is thrown.

3) When attempting to generate an android payload, the following error is thrown:

```
root@3eb2830e07f2:/opt/pupy# ./pupygen.py -O android connect --host 192.168.0.1:8443 -t tcp_cleartext
[+] Generate client: android/x86
[C] launcher: connect
[C] launcher_args: ['--host', '192.168.0.1:8443', '-t', 'tcp_cleartext']
[C] cid: 0xbf8c9168L
[C] debug: False
[I] Credentials password: 
[+] Required credentials (found):
[+] SSL_BIND_CERT
[+] generating PY payload ...
ERROR:pupy.gen:invalid syntax (<unknown>, line 10)
Traceback (most recent call last):
  File "./pupygen.py", line 735, in <module>
    pupygen(parser.parse_args(), config)
  File "./pupygen.py", line 623, in pupygen
    compressed=not ( args.uncompressed or args.packer )
  File "./pupygen.py", line 416, in generate_binary_from_template
    return generator(template, config, compressed, debug), filename, makex
  File "./pupygen.py", line 219, in get_edit_apk
    packed_payload=pack_py_payload(get_raw_conf(conf), debug)
  File "/opt/pupy/pupylib/payloads/py_oneliner.py", line 62, in pack_py_payload
    return compress_encode_obfs(payload, main=True)
  File "/opt/pupy/pupylib/utils/obfuscate.py", line 11, in compress_encode_obfs
    zlib.compress(pupycompile(code, main=main, raw=True), 9))
  File "/opt/pupy/pupylib/PupyCompile.py", line 77, in pupycompile
    data = Compiler(data, path, main).compile(filename, obfuscate, raw)
  File "/opt/pupy/pupylib/PupyCompile.py", line 25, in __init__
    self._source_ast = ast.parse(source)
  File "/usr/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 10
    pupyimporter.install(debug=)
                               ^
SyntaxError: invalid syntax
invalid syntax (<unknown>, line 10)
```

Apologies for putting this all in one issue, I was in a hurry. If these issues haven't been fixed by next week, I will work on that myself. The last one in particular confounds me though.

**Comment by alxchk** [comment]
Strange, umsgpack is bundled with pupy (because "fixed" a bit)

**Comment by Strazzom** [comment]
Perhaps the install for that component failed? I am testing this in the latest docker pull.

**Comment by alxchk** [comment]
I will try to check this evening

**Comment by Strazzom** [comment]
I have narrowed it down some.

Output of recursive grep:
`./pupylib/payloads/py_oneliner.py:            'pupyimporter.install(debug={})'.format(str(debug)),`

It looks like the debug parameter is null, because there is nothing after the "=" in the output, which means nothing is being written to that variable. Will test further and report back.

**Comment by alxchk** [comment]
Maybe because of this - https://github.com/alxchk/pupy/blob/unstable/pupy/pupylib/PupyCompile.py#L66

**Comment by Strazzom** [comment]
I think I "fixed" it.

I changed line 34 in ./pupylib/payloads/py_oneliner.py to `'pupyimporter.install()',`. This will probably break debug mode for apk generation (I assume that is what it is doing), but it at least seems to correctly output the apk.

I will try installing it on an old android phone i have lying around to see if it actually works.

**Comment by Strazzom** [comment]
@alxchk So, after a hiatus I am back.

The umsgpack issue has been fixed.

I will update the CLI documentation today.

However, after having done a lot of testing last week, the android payload may be broken. All it seems to do is print "Hello from Pupy!" on the screen. It does not seem to successfully connect back to the server however, and I never get a session.

This may be due to incorrect firewall configuration, because an external nmap scan shows the listener port blocked. I will test this again with a Windows payload using the same parameters, and see if it can connect. If so, we know it is in fact an issue with the APK version.

I am not sure it is an issue right now though, so I am going to close this one because 2/3 are fixed. If I can confirm that the Android payload does not work, I will open a new one.
