### ISSUE TITLE
Correct way to access docker container shell

### ISSUE THREAD

**Issue by Strazzom** [n1nj4sec/pupy#643]
Reading over the installation steps, the docker container SSH setup is needlessly complicated.

Why not just use `docker attach <name>` instead?

I ask because I want to improve the documentation, and I am planning on automating docker config with  docker compose.

EDIT: While I am on the subject of documentation: can I have carte blanche permission to edit anything documentation related however I want? I don't want to infringe, but there is a lot that needs tweaking and/or complete rewriting.

**Comment by alxchk** [comment]
> can I have carte blanche permission to edit anything documentation related however I want? 

Sure. We don't have documentation any way :) In case something incorrect Ill fix.

> Why not just use docker attach <name> instead?

If it works as expected - why not

**Comment by Strazzom** [comment]
Ok.
