### ISSUE TITLE
Auto run keylogger module when client connected [FEATURE]

### ISSUE THREAD

**Issue by arthurspa** [n1nj4sec/pupy#65]
It would be nice if I didn't have to manually run a module when a client connects.

Another option would be to save the state of a client in the server, like the modules previously running and restore them.

Thanks.

**Comment by Viss** [comment]
yes - autorun modules would be great!

**Comment by n1nj4sec** [comment]
I implemented a real basic autorun feature some time ago, I forgot to mention it https://github.com/n1nj4sec/pupy/commit/0d6797e3c22b4ee7fe9a4447352ea1f760e228c3. For the state of the client, it is also better handled for some modules like keylogger, a disconnection/reconnection will not clear keystrokes buffers (https://github.com/n1nj4sec/pupy/commit/d7115dcf7a8cb94116639340543a036d3ca2ca75)
