### ISSUE TITLE
Clarification for docs in adding listener  and add_listener() error handling 

### ISSUE THREAD

**Issue by lonewolf210** [n1nj4sec/pupy#652]
So after some debugging I figured out that the NAME argument must be the name of a transport protocol. You can specify the name as a secondary argument but this is not clear in the docs.  Additionally, if the named transport is not in an internal list it fails silently rather than alerting the user.  

edit: sorry it fails silently if provided a name plus any other argument. If you provide just a name it fails properly

**Comment by lonewolf210** [comment]
Also the docs seem to imply that the name of the listener needs to be added twice which is not true and will cause the listener to fail silently as well

**Comment by lonewolf210** [comment]
The issue seems to be how args are being passed with the call to Server.add_listener()

'server.add_listener(name, ' '.join(args), motd=False)'

which when called is using the arguments as the config and bypassing the check 
 
'''
def add_listener(self, name, config=None, motd=False):
        
    
        if self.listeners and name in self.listeners:
            self.handler.display_warning('Listener {} already registered'.format(name))
            return

        listener_config = config or self.config.get('listeners', name)
'''
Seems like the check should be on a separate line so it's always called rather then only when a config is not provided.

**Comment by alxchk** [comment]
Can you add some examples here?

**Comment by lonewolf210** [comment]
Sure 

Here is the current help doc statement which as I said before is at the very least confusing: 
```
>> listen -h
usage: listen [-h] [-l | -a ADD [ADD ...] | -r REMOVE]

start/stop/show current listeners

optional arguments:
  -h, --help            show this help message and exit
  -l, --list            show current listeners
  -a ADD [ADD ...], --add ADD [ADD ...]
                        start listener NAME [ARGS]
  -r REMOVE, --remove REMOVE
                        stop listener NAME
```
Here is what happens when you put an unknown transport without any arguments and it fails properly:
```
>> listen -a test
[-] Listener test is not known
```
Know here is a couple of different cases where it fails silently:
```
>> listen -a test 445

>> 
```

```
>> listen -a http http 445

>> 
```

```
>> listen -a test http 8080

>> 
```

If you at the very least add the try-except around the Listener object initialization you start getting:
```
>> listen -a test 445
[!] 'test'
Exception AttributeError: "'Listener' object has no attribute 'igd_mapping'" in <bound method Listener.__del__ of <Listener(test, initial daemon)>> ignored
```

```
>> listen -a http http 445
[!] Invalid local port: t
```

Which aren't necessarily the most informative exception statements but at least it tells you something is going wrong.
