### ISSUE TITLE
"payload_templates.txz" No Longer Available?

### ISSUE THREAD

**Issue by nimaid** [n1nj4sec/pupy#657]
All user posts and documentation say that the precompiled payload templates can be obtained from "https://github.com/n1nj4sec/pupy/releases/download/latest/payload_templates.txz". However, it seems this gives a 404.

Are the payload templates still available elsewhere? If not, could you please either make them available or provide info on compiling my own?

All the best,
nimaid

**Comment by alxchk** [comment]
They are no longer available. You should try to use [these instructions](https://github.com/n1nj4sec/pupy/wiki/Installation-(Debian-9))

**Comment by n1nj4sec** [comment]
They are back if you want a lightweight install, use create-workspace.py -DG

**Comment by sidahmed-malaoui** [comment]
The file [https://github.com/n1nj4sec/pupy/releases/download/latest/payload_templates.txz](https://github.com/n1nj4sec/pupy/releases/download/latest/payload_templates.txz) is no longer available.
