### ISSUE TITLE
pupy memory_exec target?

### ISSUE THREAD

**Issue by kitty8904** [n1nj4sec/pupy#660]
possible

memory_exec /s notepad.exe /root/desktop/test.exe

memory_exec /s calc.exe /root/desktop/test.exe

no possible

memory_exec /s iexplorer.exe /root/desktop/test.exe

memory_exec /s firefox.exe /root/desktop/test.exe

system root file create memory_exec possible

but

In older versions, it was possible to insert the process specified by the -p command

For example, is there a feature that forces you to insert in Chrome, Firefox, or other running processes?

**Comment by Strazzom** [comment]
I am not familiar with how this worked in older versions. What are you trying to do?

Please refer to the [Contribution Guidelines](https://github.com/n1nj4sec/pupy/wiki/Contribution-Guidelines), especially the part about grammar. If you can, please try to be more specific, and write in properly formatted sentences.
