### ISSUE TITLE
Invalid module: rfs at (/root/pupy/pupy/modules/rfs.py): Unable to find libfuse. Traceback:

### ISSUE THREAD

**Issue by currymygod** [n1nj4sec/pupy#661]
![2018-09-11_195716](https://user-images.githubusercontent.com/25946850/45399613-9cfd4f00-b5fd-11e8-8295-67512f3676c6.jpg)

**Comment by currymygod** [comment]
@alxchk  @Strazzom @Strazzom i need help now..... please help me to solve the ploblem

**Comment by currymygod** [comment]
@n1nj4sec @alxchk @Strazzom  i need help now..... please help me to solve the ploblem

**Comment by alxchk** [comment]
Either
apt-get install libfuse2
Or
pull from https://github.com/alxchk/pupy
Or
pull latest docker image

**Comment by currymygod** [comment]
in centos 7 
yum install fuse fuse-devel 
thanks
