### ISSUE TITLE
Prebuilt templates cannot be downloaded.

### ISSUE THREAD

**Issue by ambient-singularity** [n1nj4sec/pupy#666]
This doesn't impact me much as I usually build templates form source, but if I do try to download the precompiled templates (or run the workspace build script with -DG flag), I get the following error from an s3 webpage: 

This XML file does not appear to have any style information associated with it. The document tree is shown below.

**Comment by ambient-singularity** [comment]
This appears to have been resolved since last night, though am having issues with PS payloads; will open a new issue if needed. Thanks!

**Comment by alxchk** [comment]
Yeah.. I pushed head of my branch to upsteram. PS may be broken after merge, write an issue please ^^
