### ISSUE TITLE
duplicate module broken on linux ? 

### ISSUE THREAD

**Issue by AlessandroZ** [n1nj4sec/pupy#668]
Running duplicate on linux failed saying that [MExec](https://github.com/n1nj4sec/pupy/blob/unstable/pupy/packages/linux/all/memexec.py#L13) does not exists. 

The problems comes from an error that occurs on that class (so the class is not well loaded). It cannot fint [mexec](https://github.com/n1nj4sec/pupy/blob/unstable/pupy/packages/linux/all/memexec.py#L183). 

I have listed what is inside the [pupy](https://github.com/n1nj4sec/pupy/blob/unstable/pupy/packages/linux/all/memexec.py#L9) package and in fact I don't have any memec function. 
`['Task', '__doc__', '__file__', '__name__', '__package__', 'cid', 'connected', 'creds_cache', 'get_connect_back_host', 'infos', 'initialized', 'manager', 'namespace', 'obtain', 'pseudo']`

I don't know how the pupy package is managed so maybe @alxchk, you will have a better idea than mine.

**Comment by alxchk** [comment]
You are using pure python agent? Injection code stays in client only. Maybe I should reuse pupyimporter code..

**Comment by AlessandroZ** [comment]
You are right it works using the compiled bin :). 
Thanks !
