### ISSUE TITLE
Unable to generate the file libraryx64.zip

### ISSUE THREAD

**Issue by mekhalleh** [n1nj4sec/pupy#67]
Hello,

I try to compile the source but I am having the following problem (unable to generate the zip file in 64-bit mode).

The archive generation works perfectly in x86. 

Let me know if you have an idea?

Thank you for this great job.

Kind regards.
-------------------------------------------------------------------------------------------------------
C:\Projects\pupy\client>c:\Python27_x64\python.exe build_library_helper.py genzi
p x64
NOTE: you must install the following packages before proceeding:

        -pywin32
        -pycrypto
        -pyaml (scramblesuit dependency)

running py2exe
*** searching for required modules ***
Traceback (most recent call last):
  File "build_library_helper.py", line 48, in <module>
    "excludes": ["Tkinter", "pyreadline", "IPython","readline"]
  File "c:\Python27_x64\lib\distutils\core.py", line 152, in setup
    dist.run_commands()
  File "c:\Python27_x64\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "c:\Python27_x64\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "c:\Python27_x64\lib\site-packages\py2exe\build_exe.py", line 243, in run

    self._run()
  File "c:\Python27_x64\lib\site-packages\py2exe\build_exe.py", line 296, in _ru
n
    self.find_needed_modules(mf, required_files, required_modules)
  File "c:\Python27_x64\lib\site-packages\py2exe\build_exe.py", line 1306, in fi
nd_needed_modules
    mf.import_hook(f)
  File "c:\Python27_x64\lib\site-packages\py2exe\mf.py", line 719, in import_hoo
k
    return Base.import_hook(self,name,caller,fromlist,level)
  File "c:\Python27_x64\lib\site-packages\py2exe\mf.py", line 136, in import_hoo
k
    q, tail = self.find_head_package(parent, name)
  File "c:\Python27_x64\lib\site-packages\py2exe\mf.py", line 204, in find_head_
package
    raise ImportError, "No module named " + qname
ImportError: **No module named Crypto**

C:\Projects\pupy\client>
-----------------------------------------------------------------------------------------

**Comment by n1nj4sec** [comment]
Well, if you read the traceback it seems you need to install pycrypto in
your python27_x64
Le 17 févr. 2016 08:01, "mekhalleh" <notifications@github.com> a écrit :
>
> Hello,
>
> I try to compile the source but I am having the following problem (unable
to generate the zip file in 64-bit mode).
>
> The archive generation works perfectly in x86.
>
> Let me know if you have an idea?
>
> Thank you for this great job.
>
> Kind regards.
>
> C:\Projects\pupy\client>c:\Python27_x64\python.exe
build_library_helper.py genzi
> p x64
> NOTE: you must install the following packages before proceeding:
>
>     -pywin32
>     -pycrypto
>     -pyaml (scramblesuit dependency)
>
> running py2exe
> *** searching for required modules ***
> Traceback (most recent call last):
> File "build_library_helper.py", line 48, in
> "excludes": ["Tkinter", "pyreadline", "IPython","readline"]
> File "c:\Python27_x64\lib\distutils\core.py", line 152, in setup
> dist.run_commands()
> File "c:\Python27_x64\lib\distutils\dist.py", line 953, in run_commands
> self.run_command(cmd)
> File "c:\Python27_x64\lib\distutils\dist.py", line 972, in run_command
> cmd_obj.run()
> File "c:\Python27_x64\lib\site-packages\py2exe\build_exe.py", line 243,
in run
>
> self._run()
>
> File "c:\Python27_x64\lib\site-packages\py2exe\build_exe.py", line 296,
in ru
> n
> self.find_needed_modules(mf, required_files, required_modules)
> File "c:\Python27_x64\lib\site-packages\py2exe\build_exe.py", line 1306,
in fi
> nd_needed_modules
> mf.import_hook(f)
> File "c:\Python27_x64\lib\site-packages\py2exe\mf.py", line 719, in
import_hoo
> k
> return Base.import_hook(self,name,caller,fromlist,level)
> File "c:\Python27_x64\lib\site-packages\py2exe\mf.py", line 136, in
import_hoo
> k
> q, tail = self.find_head_package(parent, name)
> File "c:\Python27_x64\lib\site-packages\py2exe\mf.py", line 204, in
find_head

**Comment by mekhalleh** [comment]
Thanks for your reply.
I already check the installation of pycrypto in python x64.
 -------------------------
C:\Users\xxx>c:\Python27_x64\Scripts\easy_install.exe pycrypto
Searching for pycrypto
Best match: pycrypto 2.6.1
Processing pycrypto-2.6.1-py2.7-win-amd64.egg
pycrypto 2.6.1 is already the active version in easy-install.pth

Using c:\python27_x64\lib\site-packages\pycrypto-2.6.1-py2.7-win-amd64.egg
Processing dependencies for pycrypto
Finished processing dependencies for pycrypto

C:\Users\xxx>

**Comment by n1nj4sec** [comment]
try to uninstall pycrypto and reinstall it without python eggs

**Comment by mekhalleh** [comment]
Really thank you for your help.

I uninstalled pycrypto (installation from easy_install) and reinstall manually.

Everything is working :)
