### ISSUE TITLE
Interactive shell after impersonating a user

### ISSUE THREAD

**Issue by AlessandroZ** [n1nj4sec/pupy#670]
I have detected a problem trying to launch an interactive shell after impersonating a user (after using `become` module). 

I have tried to fix it but I didn't find a clean way to do it, so maybe @alxchk you will have a better idea. 

Changing the real uid instead of the effective uid [here](https://github.com/n1nj4sec/pupy/blob/unstable/pupy/packages/posix/all/become.py#L35) allow the user to launch a shell but it is not possible to revert to the previous user with higher privilege (which is normal), so that's not a good solution. 

However, it is possible to launch a shell impersonating a user (from a high session, so before using the `become` module), using `shell -S user_to_impersonate`. 

So my idea, is when a user is impersonated, and we want to launch an interactive shell, we check if the real uid and the effective uid is equal, if not it means that the user has been impersonated, so we go back to the previous user and we launch a shell using the suid method. 
For example, we add [here](https://github.com/n1nj4sec/pupy/blob/unstable/pupy/packages/posix/all/ptyshell.py#L114), this kind of test (which is the same as `become -r`): 
```
ruid, euid, _ = os.getresuid()
if ruid != euid:          
    suid = euid
    os.seteuid(sys._SAVED_UID)
    os.setegid(sys._SAVED_GID)
    os.setgroups(sys._SAVED_GROUPS)
    os.chdir(sys._SAVED_CWD)
    os.environ = sys._SAVED_ENV
```
This code works but it's quite ugly. So maybe, something cleaner could be done. I have tried many fixes without success.

**Comment by alxchk** [comment]
Can you provide some sequence to show what are you trying to achieve?

**Comment by alxchk** [comment]
Ok, you probably trying to use shell after become. I see. The issue here that glibc openpty implementation do have stupid way of chowning newly crated pty device. It checks UID (not EUID). UID == 0, so it tries to chown device with EUID != 0 thus failed. 

The only proper way to implement the things you want - reimplement openpty in other way.

**Comment by AlessandroZ** [comment]
Awesome it fixed the issue, it seems to easy for you :)
