### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by AlessandroZ** [n1nj4sec/pupy#679]
I wanted to know if you (@alxchk, @n1nj4sec) are ok if I removed [shell_exec](https://github.com/n1nj4sec/pupy/blob/unstable/pupy/modules/shell_exec.py) module to let only [pexec](https://github.com/n1nj4sec/pupy/blob/unstable/pupy/modules/pexec.py). Both use safepopen, the only different is that shell_exec does not run its command in a thread. 

Moreover, I wanted to remove the option to [upload or download](https://github.com/n1nj4sec/pupy/blob/unstable/pupy/modules/pexec.py#L60) using pexec, which is equivalent to do a simple upload or download. It seems not used and broken because these [function](https://github.com/n1nj4sec/pupy/blob/unstable/pupy/modules/pexec.py#L118) have changed. Instead of correcting it, I suggest to remove it if no one use it. In the other case, I will patch it.

**Comment by alxchk** [comment]
It's ok to modify pexec, but I like to leave shell_exec as is

**Comment by AlessandroZ** [comment]
Ok, no problem to let shell_exec. Just for my curiosity, in which case will you use shell_exec instead of pexec?

**Comment by alxchk** [comment]
In all cases :)
I wrote pexec because shell_exec was dangerous to use, but it's slower. Then I rework shell_exec a bit. In case when amount of output is predictable and short shell_exec is preferable.  For rest cases I usually use interactive_shell.

**Comment by AlessandroZ** [comment]
Ok I understand. 
I also use the interactive_shell, but it happens in some hardened Windows (mostly Citrix environment) that cmd and powershell are blocked.
