### ISSUE TITLE
Issues with pip install -r requirements.txt

### ISSUE THREAD

**Issue by Gutzblackswordsman** [n1nj4sec/pupy#688]
root@lu-cdc:~/pupy/pupy# pip install -r requirements.txt 
Collecting https://github.com/CoreSecurity/impacket/archive/master.zip (from -r requirements.txt (line 17))
  Downloading https://github.com/CoreSecurity/impacket/archive/master.zip
     \ 3.6MB 8.0MB/s
Collecting https://github.com/AlessandroZ/pypykatz/archive/master.zip (from -r requirements.txt (line 24))
  Downloading https://github.com/AlessandroZ/pypykatz/archive/master.zip (118kB)
    100% |████████████████████████████████| 122kB 4.9MB/s 
Obtaining file:///root/pupy/pupy/external/pykcp (from -r requirements.txt (line 39))
Requirement already satisfied: rpyc==3.4.4 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: pycryptodome in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: pefile in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied: pyyaml in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied: rsa in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 5))
Requirement already satisfied: netaddr in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 6))
Requirement already satisfied: ecdsa==0.13 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 7))
Requirement already satisfied: paramiko==2.0.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 8))
Requirement already satisfied: tinyec in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 9))
Requirement already satisfied: psutil in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 10))
Requirement already satisfied: netifaces in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 11))
Requirement already satisfied: pylzma in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 12))
Requirement already satisfied: colorama in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 13))
Requirement already satisfied: mss in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 14))
Requirement already satisfied: pyOpenSSL in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 15))
Requirement already satisfied: scapy in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 16))
Requirement already satisfied: pyuv in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 18))
Requirement already satisfied: dnslib in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 19))
Requirement already satisfied: http-parser in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 20))
Requirement already satisfied: cerberus in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 21))
Requirement already satisfied: logutils in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 22))
Requirement already satisfied: secretstorage in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 23))
Requirement already satisfied: pygments in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 25))
Requirement already satisfied: requests in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 26))
Requirement already satisfied: tornado in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 27))
Requirement already satisfied: poster in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 28))
Requirement already satisfied: win_inet_pton in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 29))
Requirement already satisfied: scandir in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 30))
Requirement already satisfied: msgpack in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 31))
Requirement already satisfied: hexdump in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 32))
Collecting M2Crypto>=0.30.1 (from -r requirements.txt (line 33))
  Using cached https://files.pythonhosted.org/packages/41/50/7d85dc99b1c4f29eca83873d851ec29a8e484a66b31351e62e30be9db7d1/M2Crypto-0.30.1.tar.gz
Collecting fusepy (from -r requirements.txt (line 34))
Collecting defusedxml (from -r requirements.txt (line 35))
  Using cached https://files.pythonhosted.org/packages/87/1c/17f3e3935a913dfe2a5ca85fa5ccbef366bfd82eb318b1f75dadbf0affca/defusedxml-0.5.0-py2.py3-none-any.whl
Collecting keyboard (from -r requirements.txt (line 36))
  Using cached https://files.pythonhosted.org/packages/4f/e0/3addb693f9387268044c5268880777cad3cc2ac457789884cca8381b2f7a/keyboard-0.13.2-py2.py3-none-any.whl
Collecting puttykeys (from -r requirements.txt (line 37))
  Using cached https://files.pythonhosted.org/packages/61/d3/55fade65bc6080180d0e347533924a5e7e3b090f9ba1e7b1ac0c41ff85c0/puttykeys-1.0.2-py2.py3-none-any.whl
Collecting pyelftools (from -r requirements.txt (line 38))
Collecting flake8 (from -r requirements.txt (line 40))
  Using cached https://files.pythonhosted.org/packages/b9/dc/14e9d94c770b8c4ef584e906c7583e74864786a58d47de101f2767d50c0b/flake8-3.5.0-py2.py3-none-any.whl
Collecting flake8-per-file-ignores (from -r requirements.txt (line 41))
  Using cached https://files.pythonhosted.org/packages/2f/fe/c33f7af5dc77b69ec90e891774f0b04c175b58e9cc16197d0e9f2b61e6ca/flake8_per_file_ignores-0.6-py2.py3-none-any.whl
Requirement already satisfied: flask>=1.0 in /usr/lib/python2.7/dist-packages (from impacket==0.9.18.dev0->-r requirements.txt (line 17))
Collecting ldap3>=2.5.0 (from impacket==0.9.18.dev0->-r requirements.txt (line 17))
Collecting ldapdomaindump (from impacket==0.9.18.dev0->-r requirements.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/cd/c1/b10ad2a90f293c028b657618a12f8990522b09ecc08881f415764202e154/ldapdomaindump-0.8.7-py2-none-any.whl
Requirement already satisfied: pyasn1>=0.2.3 in /usr/lib/python2.7/dist-packages (from impacket==0.9.18.dev0->-r requirements.txt (line 17))
Requirement already satisfied: pycryptodomex in /usr/lib/python2.7/dist-packages (from impacket==0.9.18.dev0->-r requirements.txt (line 17))
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from impacket==0.9.18.dev0->-r requirements.txt (line 17))
Requirement already satisfied: plumbum in /usr/local/lib/python2.7/dist-packages (from rpyc==3.4.4->-r requirements.txt (line 1))
Requirement already satisfied: cryptography>=1.1 in /usr/lib/python2.7/dist-packages (from paramiko==2.0.2->-r requirements.txt (line 8))
Requirement already satisfied: typing in /usr/lib/python2.7/dist-packages (from M2Crypto>=0.30.1->-r requirements.txt (line 33))
Requirement already satisfied: enum34; python_version < "3.4" in /usr/lib/python2.7/dist-packages (from flake8->-r requirements.txt (line 40))
Requirement already satisfied: configparser; python_version < "3.2" in /usr/lib/python2.7/dist-packages (from flake8->-r requirements.txt (line 40))
Collecting pycodestyle<2.4.0,>=2.0.0 (from flake8->-r requirements.txt (line 40))
  Using cached https://files.pythonhosted.org/packages/e4/81/78fe51eb4038d1388b7217dd63770b0f428370207125047312886c923b26/pycodestyle-2.3.1-py2.py3-none-any.whl
Collecting pyflakes<1.7.0,>=1.5.0 (from flake8->-r requirements.txt (line 40))
  Using cached https://files.pythonhosted.org/packages/d7/40/733bcc64da3161ae4122c11e88269f276358ca29335468005cb0ee538665/pyflakes-1.6.0-py2.py3-none-any.whl
Collecting mccabe<0.7.0,>=0.6.0 (from flake8->-r requirements.txt (line 40))
  Using cached https://files.pythonhosted.org/packages/87/89/479dc97e18549e21354893e4ee4ef36db1d237534982482c3681ee6e7b57/mccabe-0.6.1-py2.py3-none-any.whl
Collecting pathmatch (from flake8-per-file-ignores->-r requirements.txt (line 41))
Requirement already satisfied: dnspython in /usr/lib/python2.7/dist-packages (from ldapdomaindump->impacket==0.9.18.dev0->-r requirements.txt (line 17))
Building wheels for collected packages: M2Crypto
  Running setup.py bdist_wheel for M2Crypto ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-vlz1ww/M2Crypto/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpc57VpLpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  copying M2Crypto/ASN1.py -> build/lib.linux-x86_64-2.7/M2Crypto
  copying M2Crypto/m2urllib2.py -> build/lib.linux-x86_64-2.7/M2Crypto
  copying M2Crypto/Rand.py -> build/lib.linux-x86_64-2.7/M2Crypto
  copying M2Crypto/m2.py -> build/lib.linux-x86_64-2.7/M2Crypto
  copying M2Crypto/Engine.py -> build/lib.linux-x86_64-2.7/M2Crypto
  copying M2Crypto/BN.py -> build/lib.linux-x86_64-2.7/M2Crypto
  copying M2Crypto/callback.py -> build/lib.linux-x86_64-2.7/M2Crypto
  copying M2Crypto/m2xmlrpclib.py -> build/lib.linux-x86_64-2.7/M2Crypto
  copying M2Crypto/util.py -> build/lib.linux-x86_64-2.7/M2Crypto
  copying M2Crypto/ftpslib.py -> build/lib.linux-x86_64-2.7/M2Crypto
  copying M2Crypto/DSA.py -> build/lib.linux-x86_64-2.7/M2Crypto
  copying M2Crypto/httpslib.py -> build/lib.linux-x86_64-2.7/M2Crypto
  copying M2Crypto/EC.py -> build/lib.linux-x86_64-2.7/M2Crypto
  copying M2Crypto/RC4.py -> build/lib.linux-x86_64-2.7/M2Crypto
  copying M2Crypto/m2urllib.py -> build/lib.linux-x86_64-2.7/M2Crypto
  copying M2Crypto/SMIME.py -> build/lib.linux-x86_64-2.7/M2Crypto
  copying M2Crypto/DH.py -> build/lib.linux-x86_64-2.7/M2Crypto
  copying M2Crypto/m2crypto.py -> build/lib.linux-x86_64-2.7/M2Crypto
  copying M2Crypto/Err.py -> build/lib.linux-x86_64-2.7/M2Crypto
  copying M2Crypto/BIO.py -> build/lib.linux-x86_64-2.7/M2Crypto
  copying M2Crypto/threading.py -> build/lib.linux-x86_64-2.7/M2Crypto
  copying M2Crypto/RSA.py -> build/lib.linux-x86_64-2.7/M2Crypto
  copying M2Crypto/X509.py -> build/lib.linux-x86_64-2.7/M2Crypto
  copying M2Crypto/__init__.py -> build/lib.linux-x86_64-2.7/M2Crypto
  copying M2Crypto/six.py -> build/lib.linux-x86_64-2.7/M2Crypto
  copying M2Crypto/EVP.py -> build/lib.linux-x86_64-2.7/M2Crypto
  copying M2Crypto/AuthCookie.py -> build/lib.linux-x86_64-2.7/M2Crypto
  creating build/lib.linux-x86_64-2.7/M2Crypto/SSL
  copying M2Crypto/SSL/cb.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
  copying M2Crypto/SSL/ssl_dispatcher.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
  copying M2Crypto/SSL/TwistedProtocolWrapper.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
  copying M2Crypto/SSL/SSLServer.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
  copying M2Crypto/SSL/Cipher.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
  copying M2Crypto/SSL/Checker.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
  copying M2Crypto/SSL/Session.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
  copying M2Crypto/SSL/Connection.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
  copying M2Crypto/SSL/timeout.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
  copying M2Crypto/SSL/Context.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
  copying M2Crypto/SSL/__init__.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
  running build_ext
  building 'M2Crypto._m2crypto' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/SWIG
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-A8UpPM/python2.7-2.7.15=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -I/tmp/pip-build-vlz1ww/M2Crypto/SWIG -c SWIG/_m2crypto_wrap.c -o build/temp.linux-x86_64-2.7/SWIG/_m2crypto_wrap.o -Wno-deprecated-declarations -DTHREADING
  SWIG/_m2crypto_wrap.c:3557:10: fatal error: openssl/err.h: No such file or directory
   #include <openssl/err.h>
            ^~~~~~~~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for M2Crypto
  Running setup.py clean for M2Crypto
Failed to build M2Crypto
Installing collected packages: M2Crypto, fusepy, defusedxml, keyboard, puttykeys, pyelftools, pycodestyle, pyflakes, mccabe, flake8, pathmatch, flake8-per-file-ignores, ldap3, ldapdomaindump, impacket, pypykatz, KCP
  Found existing installation: M2Crypto 0.27.0
    Not uninstalling m2crypto at /usr/lib/python2.7/dist-packages, outside environment /usr
  Running setup.py install for M2Crypto ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-vlz1ww/M2Crypto/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-XwUnfl-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/ASN1.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/m2urllib2.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/Rand.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/m2.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/Engine.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/BN.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/callback.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/m2xmlrpclib.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/util.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/ftpslib.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/DSA.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/httpslib.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/EC.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/RC4.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/m2urllib.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/SMIME.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/DH.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/m2crypto.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/Err.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/BIO.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/threading.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/RSA.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/X509.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/__init__.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/six.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/EVP.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/AuthCookie.py -> build/lib.linux-x86_64-2.7/M2Crypto
    creating build/lib.linux-x86_64-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/cb.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/ssl_dispatcher.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/TwistedProtocolWrapper.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/SSLServer.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/Cipher.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/Checker.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/Session.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/Connection.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/timeout.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/Context.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/__init__.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
    running build_ext
    building 'M2Crypto._m2crypto' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/SWIG
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-A8UpPM/python2.7-2.7.15=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -I/tmp/pip-build-vlz1ww/M2Crypto/SWIG -c SWIG/_m2crypto_wrap.c -o build/temp.linux-x86_64-2.7/SWIG/_m2crypto_wrap.o -Wno-deprecated-declarations -DTHREADING
    SWIG/_m2crypto_wrap.c:3557:10: fatal error: openssl/err.h: No such file or directory
     #include <openssl/err.h>
              ^~~~~~~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
  Can't rollback M2Crypto, nothing uninstalled.
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-vlz1ww/M2Crypto/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-XwUnfl-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-vlz1ww/M2Crypto/

**Comment by Gutzblackswordsman** [comment]
currently trying to use this on kali, not sure if the issue is the linux distro

**Comment by alxchk** [comment]
You should install -dev packets

**Comment by alxchk** [comment]
Just follow the instruction from the wiki

**Comment by cs-simon** [comment]
I already install all dev still got same issue?

root@kali:~/Desktop/pupy/pupy# apt-get install git libssl1.1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libssl1.1 is already the newest version (1.1.0f-5).
git is already the newest version (1:2.14.1-3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@kali:~/Desktop/pupy/pupy# apt-get install git libssl1.0.2 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libssl1.0.2 is already the newest version (1.0.2l-2).
git is already the newest version (1:2.14.1-3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@kali:~/Desktop/pupy/pupy# apt-get install git libffi
libffi-dev  libffi6     
root@kali:~/Desktop/pupy/pupy# apt-get install git libffi
libffi-dev  libffi6     
root@kali:~/Desktop/pupy/pupy# apt-get install git libffi-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libffi-dev is already the newest version (3.2.1-6).
git is already the newest version (1:2.14.1-3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@kali:~/Desktop/pupy/pupy# apt-get install git python
Display all 313 possibilities? (y or n)
root@kali:~/Desktop/pupy/pupy# apt-get install git python-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-dev is already the newest version (2.7.13-2).
git is already the newest version (1:2.14.1-3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@kali:~/Desktop/pupy/pupy# apt-get install git python-pip
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-pip is already the newest version (9.0.1-2).
git is already the newest version (1:2.14.1-3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@kali:~/Desktop/pupy/pupy# ^C
