### ISSUE TITLE
Compiling linux client from sources

### ISSUE THREAD

**Issue by msidagni** [n1nj4sec/pupy#691]
When I try to compile the linux client from linux-sources using:

builenv.sh
build.sh

in both docker and regular environment it errors out saying:

chroot: failed to run command ‘/bin/bash’: No such file or directory

Thanks for your help.

**Comment by alxchk** [comment]
To compile linux client from sources you need docker. buildenv.sh and build.sh are deprecated and were not updated for a long time.

`cd client; ./build-docker.sh linux64 sources-linux`

Where - linux64 toolchain name (alxchk/tc-linux64) and sources-linux is folder at client/

**Comment by msidagni** [comment]
Thanks. It works for both linux32 and linux64. please include in the wiki documentation on how to compile client templates from source so that people can find it.
