### ISSUE TITLE
changeme module

### ISSUE THREAD

**Issue by AlessandroZ** [n1nj4sec/pupy#693]
The [changeme](https://github.com/ztgrace/changeme) project has evolved a lot, many new creds have been added and the core has changed too. Their is no sense to update my fork and spend lots of time doing the same thing. It would be cool to add it as an external module, but it needs lots of [requirements](https://github.com/ztgrace/changeme/blob/master/requirements.txt) that could be a pain to load. 
So I suggest to remove this module if it's ok for you @alxchk. It would be still possible to use it doing a socks proxy + proxychains.

**Comment by alxchk** [comment]
Yes, it's ok to remove. With time I will check if deps could be compiled to bundles, to make possible to use on target.

**Comment by AlessandroZ** [comment]
It's a really cool module, so I think it could be useful. But maintaining another tool whereas it's done on the main github project has no sense. I have removed it. Thanks.
