### ISSUE TITLE
Invalid transport args format causing client connection issues

### ISSUE THREAD

**Issue by thewerdisberd** [n1nj4sec/pupy#694]
I am running the server on the newest version of Debian 9. 
I am trying to run the client on an unpatched Windows 7 SP1 install (but I am receiving the same error on an up to date Windows 10 install).
The client was built using default templates with the transport config set to connect ssl.
This client configuration was working on the same target hosts a week ago.
I am using the latest commit, I cloned the repo and installed the server about 4 hours ago.

When I launch the client the process starts successfully but closes several seconds in without ever contacting the server. After some troubleshooting with no luck I decided to try the debug client to see what the issue was. I received the below error:
```
2018-10-13 15:24:53,746| Starting rpyc loop
2018-10-13 15:24:53,746| connecting to <SERVER IP:PORT> using transport ssl ...
2018-10-13 15:24:53,746| Attempt 0 - reconnect in 8 seconds...
Error: transport arguments must be in format NAME=VALUE or "NAME=value with spaces"
```
It looks like this error is thrown in parse_transports_args() (pupy/pupy/network/lib/utils.py) when the supplied arguments aren't in the proper format. I did not attempt to traceback which specific call to this function is causing my error.

I will continue to investigate the exact cause of this error on my end but any assistance in getting a fix out for this issue would be greatly appreciated.

Thanks!

**Comment by alxchk** [comment]
Right now there is no validation for these args at pupygen. They goes to payload as is, so in case there are issues with cmdline, there is no way to know this but execute generated payload.

Looks like for some reason you have garbage in cmdline. Maybe from messages shown by `gen` command it will be more clear what exactly was embedded to payload to reproduce the bug.

**Comment by thewerdisberd** [comment]
I was missing the `-t` argument for the transport options.

Was there a change to make this required? I do not remember needing that flag in the past.

Also, is there a reason pupygen doesn't validate the arguments?

**Comment by alxchk** [comment]
> I was missing the -t argument for the transport options.
> Was there a change to make this required? I do not remember needing that flag in the past.

This was from the early beginning.

> Also, is there a reason pupygen doesn't validate the arguments?

To make this possible some refactoring should be done first. So it's in todo list, but not on the top

**Comment by thewerdisberd** [comment]
Thanks for the help @alxchk
