### ISSUE TITLE
linux_stealth module not working

### ISSUE THREAD

**Issue by Narkle** [n1nj4sec/pupy#70]
When i run linux_stealth  i have that issue:
`>> run linux_stealth 443`
`[-] super(type, obj): obj must be an instance or subtype of type`

I added `print isinstance(self, SetStealth)` below is_compatbile function and it returns me False.

**Comment by RedSunEmpire** [comment]
If there are no changes made to the module, this is the proper way to execute it:

>> run linux_stealth --port 443

This is tested on various Linux distros with Python 2.7 and it worked properly.

I have improved the module and will make a pull request today.
