### ISSUE TITLE
start_webplugin() takes at least 3 arguments (2 given) - rdesktop module

### ISSUE THREAD

**Issue by bluethepill** [n1nj4sec/pupy#710]
Hi folks!
After moving to another environment, I have noticed that rdesktop module stopped working.
Problem looks like this:
```
>> sessions -i 1
[+] Default filter set to 1
>> rdesktop
[-] True
2018-11-15 11:29:43,293| start_webplugin() takes at least 3 arguments (2 given)
Traceback (most recent call last):
  File "/root/pupy/pupy/pupylib/PupyJob.py", line 161, in module_worker
    module.run(self.args)
  File "/root/pupy/pupy/modules/rdesktop.py", line 159, in run
    conninfo = self.start_webplugin()
  File "/root/pupy/pupy/pupylib/PupyModule.py", line 451, in start_webplugin
    return self.client.pupsrv.pupweb.start_webplugin(self.web_handlers)
TypeError: start_webplugin() takes at least 3 arguments (2 given)
[-] start_webplugin() takes at least 3 arguments (2 given)
>>
```
For testing purposes, I downloaded it today and set up with exactly:
```
$ git clone --recursive https://github.com/n1nj4sec/pupy
$ cd pupy
$ python create-workspace.py -DG pupyw
```
on debian 9 machine, more precisely inside openvz container.
Tested with client installed on various Windows versions.

Can You reproduce this? Thanks

**Comment by alxchk** [comment]
Yes, looks like there are several broken things. I'll fix when have free time

**Comment by xbhuang1994** [comment]
I also encountered the same problem, I am very happy to see it being fixed quickly, this project is really great! I am willing to donate a little bitcoin to buy a few cups of coffee during the development process! Give me your bitcoin wallet address! @alxchk

**Comment by bluethepill** [comment]
Many thanks.
You should really consider donation button :)
