### ISSUE TITLE
where should pupy.conf be located? 

### ISSUE THREAD

**Issue by TheOncomingStorm** [n1nj4sec/pupy#725]
I have successfully installed pupy and I edited, and renamed, pupy.default.conf to pupy.conf but I still get the same default settings. I didn't do a docker install so I'm not sure I've done the rest of this appropriately.

**Comment by alxchk** [comment]
You can enable debug log to see where it search config. Best place is workdir/conf/
Pupy uses workdir as project directory. The second option is ~/.config/pupy

**Comment by TheOncomingStorm** [comment]
That helped. Thanks.
