### ISSUE TITLE
Keylogger don't work

### ISSUE THREAD

**Issue by Manuel888Topik** [n1nj4sec/pupy#728]
>> run keylogger start
[!] [M/C:KeyLogger] Exception: Traceback (most recent call last):
  File "", line 455, in create
  File "keylogger.py", line 588, in __init__
NotAvailable
[+] keylogger started !
>> run keylogger dump
[-] keylogger not started
>> run keylogger stop
[+] keylogger stopped
>>

I'm doing something wrong ?

**Comment by alxchk** [comment]
Looks like you are trying to use keylogger on linux. This will works only if X server is accessible (there is DISPLAY=, authentication cookies found etc) + X server is recent, i.e. has input2 support.
