### ISSUE TITLE
problem with requirements.txt

### ISSUE THREAD

**Issue by Froas** [n1nj4sec/pupy#738]
`entrypoints` 0.3 has requirement configparser>=3.5; python_version == "2.7", but you'll have configparser 3.5.0b2 which is incompatible.
ldapdomaindump 0.9.1 has requirement ldap3==2.5.1, but you'll have ldap3 2.5.2 which is incompatible.
flake8-per-file-ignores 0.8.1 has requirement flake8<3.7,>=3, but you'll have flake8 3.7.6 which is incompatible.
Installing collected packages: rpyc, M2Crypto, fusepy, defusedxml, keyboard, regex, tzlocal, dateparser, puttykeys, filemagic, pycparser, cffi, xattr, pyflakes, mccabe, functools32, entrypoints, pycodestyle, flake8, pathmatch, flake8-per-file-ignores, ldap3, ldapdomaindump, pycryptodomex, impacket, pypykatz, KCP
  Found existing installation: rpyc 4.0.2
    Uninstalling rpyc-4.0.2:
      Successfully uninstalled rpyc-4.0.2
  Found existing installation: M2Crypto 0.27.0
    Not uninstalling m2crypto at /usr/lib/python2.7/dist-packages, outside environment /usr
    Can't uninstall 'M2Crypto'. No files were found to uninstall.
  Found existing installation: entrypoints 0.2.3.post3
    Not uninstalling entrypoints at /usr/lib/python2.7/dist-packages, outside environment /usr
    Can't uninstall 'entrypoints'. No files were found to uninstall.
  Found existing installation: impacket 0.9.15
    Not uninstalling impacket at /usr/lib/python2.7/dist-packages, outside environment /usr
    Can't uninstall 'impacket'. No files were found to uninstall.
  Running setup.py develop for KCP
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/root/pupy/pupy/pupy/external/pykcp/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps:
    running develop
    running egg_info
    writing KCP.egg-info/PKG-INFO
    writing top-level names to KCP.egg-info/top_level.txt
    writing dependency_links to KCP.egg-info/dependency_links.txt
    reading manifest file 'KCP.egg-info/SOURCES.txt'
    writing manifest file 'KCP.egg-info/SOURCES.txt'
    running build_ext
    building 'kcp' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-A8UpPM/python2.7-2.7.15=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c pykcp.c -o build/temp.linux-x86_64-2.7/pykcp.o -g -O3 -Wall -std=gnu89
    pykcp.c:10:10: fatal error: kcp/ikcp.h: No such file or directory
     #include "kcp/ikcp.h"
              ^~~~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/root/pupy/pupy/pupy/external/pykcp/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /root/pupy/pupy/pupy/external/pykcp/
`

**Comment by Froas** [comment]
No handlers could be found for logger "pupy.network.pss"

**Comment by Froas** [comment]
second problem

**Comment by alxchk** [comment]
You are installing something unknown in some strange way, sorry.
