### ISSUE TITLE
payload_templates for master branch

### ISSUE THREAD

**Issue by mny123** [n1nj4sec/pupy#739]
I'm unable to install the stable master branch of pupy, which I need. Problem is, that I cannot find the corresponding payload_templates. The submodule url gives me a 404 error. My question is, how to get the corresponding payload_templates, because the latest payload_templates.txz (via wget https://github.com/n1nj4sec/pupy/releases/download/latest/payload_templates.txz
tar xvf payload_templates.txz && mv payload_templates/* pupy/payload_templates/ && rm payload_templates.txz && rm -r payload_templates) don't work, naturally. I've tried that yet, but ./pupygen.py gave me a sync warning, as expected.

**Comment by alxchk** [comment]
Master branch is old and abandonned, don't try to use it
