### ISSUE TITLE
AdHoc --offline-script example for pupy persistence before connection to C&C server

### ISSUE THREAD

**Issue by LucaBongiorni** [n1nj4sec/pupy#74]
I was wondering that would be useful an ad-hoc option which will make persitent pupy before initialize any communication. (E.g. this would be useful in case the RAT is dropped while the victim is not connected to LAN/WAN).

Someone already thought to some solution?
Would be nice to add to wiki more info about persistence before connection.

**Comment by n1nj4sec** [comment]
hello, you can use something like [this](https://github.com/n1nj4sec/pupy/blob/master/pupy/packages/windows/all/pupwinutils/persistence.py) and copy paste the executable to a directory of you choice before adding the entry to the registry
