### ISSUE TITLE
Trying to generate .NET payload.

### ISSUE THREAD

**Issue by ibaka9** [n1nj4sec/pupy#747]
`
[!] Required argument missing, automatically adding parameter --host 127.0.0.1:443 from local or external ip address

{ Configuration }
KEY            VALUE                         
---------------------------------------------
launcher       connect                       
launcher_args  --host 127.0.0.1:443 -t ssl  
cid            0x858b5414L                   

[+] Required credentials (found)
  + SSL_BIND_CERT
  + SSL_CA_CERT
  + SSL_CLIENT_CERT
  + SSL_BIND_KEY
  + SSL_CLIENT_KEY
[+] packing pupy into C# source ...
Traceback (most recent call last):
  File "/home/ubuntu/tools/pupy/pupy/pupygen.py", line 832, in main
    pupygen(args, config, None, display)
  File "/home/ubuntu/tools/pupy/pupy/pupygen.py", line 752, in pupygen
    outpath = dn.gen_exe()
  File "/home/ubuntu/tools/pupy/pupy/pupylib/payloads/dotnet.py", line 73, in gen_exe
    sdk = self.server.config.get('gen', 'mcs_sdk', 4)
AttributeError: 'NoneType' object has no attribute 'config'
'NoneType' object has no attribute 'config'
`

I use pupygen like this:
`pupygen -f .NET`

What did i miss?

**Comment by alxchk** [comment]
This is a bug, which I will fix. But use `gen` from pupysh anyway. Direct `pupygen` call is a bit obsolete for now
