### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by chunxingque** [n1nj4sec/pupy#751]
[+] Install dependencies
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
File "setup.py" not found. Directory cannot be installed in editable mode: /root/tools/pupy/pupy/external/pykcp

**Comment by alxchk** [comment]
https://github.com/n1nj4sec/pupy/wiki/Installation
