### ISSUE TITLE
Dependency error using python payloads

### ISSUE THREAD

**Issue by AlessandroZ** [n1nj4sec/pupy#753]
Python payloads and python oneliner does not work anymore. 
I have a dependency error: `ImportError: No module named cryptoutils`

I didn't follow all your changes @alxchk, so maybe you will better understand why this error occurs.

**Comment by alxchk** [comment]
I don't have this. Can you share information about environment and stack traces?

**Comment by alxchk** [comment]
Also try to delete all .pyc/.pyo files first

**Comment by AlessandroZ** [comment]
I understood the problem. tinyec dependency should be installed on the remote host. It's not loaded remotely. 
Once I installed "https://github.com/alxchk/tinyec/archive/master.zip" it worked.

**Comment by alxchk** [comment]
tinyca is bundled into the generated .py file.

Check that all libs are upgraded on your machine with pupysh.

**Comment by AlessandroZ** [comment]
You were right, it worked now. Thanks for your help :+1:
