### ISSUE TITLE
finding payloads

### ISSUE THREAD

**Issue by paradoxfound** [n1nj4sec/pupy#754]
I am using the -D to try to get the payload to be loaded onto the Desktop 

`gen -f client -O windows -o system.exe -D /Desktop connect -c 192.168.0.3:8443 -t ssl`

but it is not being generated to the desktop. there is no error to generated, but i cannot find the projects folder or the payload file. I am using the search function in the directory as well. I cannot seem to find the output of the payload generation

**Comment by alxchk** [comment]
You should specify either `-o` or `-D`, only one option taken into account.  In your case `-o`. Also during generation there should be `OUTPUT_PATH` message

**Comment by paradoxfound** [comment]
the output path declaration merely puts it at /projects/system.exe, which isn't helpful as I can't find the projects directory either.

**Comment by glides** [comment]
The dir to your Desktop is in the root of your file system? I highly doubt it. Generally that dir is in /home/[user]/Desktop...

Try:
`gen -f client -O windows -o ~/Desktop/system.exe connect -c 192.168.0.3:8443 -t ssl`

To find your generated payload - in a new terminal:
`cd Desktop`
`ls`

And you should see system.exe there. The ~ is your user's home path, and the default location your terminal opens to. Telling pupy to generate the payload in /Desktop is not the same as ~/Desktop.

**Comment by paradoxfound** [comment]
so i literally copy and pasted the location from the properties box on the Desktop icon and this is the output

`[-] payload generation failed: [Errno 2] No such file or directory: '/home/doback/Desktop/system.exe'
Traceback (most recent call last):
  File "/opt/pupy/commands/gen.py", line 133, in do
    output = pupygen.pupygen(args, config, server, handler.display)
  File "/opt/pupy/pupygen.py", line 680, in pupygen
    outfile = open(outpath, 'w+b')
IOError: [Errno 2] No such file or directory: '/home/doback/Desktop/system.exe`

**Comment by glides** [comment]
The generation of payloads is working fine, pending you tell it a valid location and have access to write there.

Try writing to the directory you ran pupy from, we know that location exists. Then just copy it to where you want.

`gen -A x86 -o ./client.exe`

Or, just simply type `gen` and then navigate to the output path which will be:

`OUTPUT_PATH: /home/doback/.config/pupy/output/pupyxBLAHBLAH.exe`

You said in an earlier comment that the `OUTPUT_PATH showed: /Desktop/system.exe/pupyx86d.jOIc4M.exe`. That means it generated the payload successfully. If your Desktop is @ /home/doback/Desktop, then you won't see it there. It's in /Desktop, not /home/doback/Desktop

So, what do you see when you do this in a new terminal?:
`cd /Desktop`
`ls -al`

Unless you've deleted it, pupyx86d.jOIc4M.exe should be there from before. You've also probably inadvertently created a Desktop folder on the root of your filesystem.

**Comment by paradoxfound** [comment]
'└──╼ $cd /Desktop/system.exe
bash: cd: /Desktop/system.exe: No such file or directory
'

going to my desktop the output for `ls -al` is `└──╼ $ls -al
total 4
drwxr-xr-x 1 doback doback   36 Mar 22 00:51 .
drwxr-xr-x 1 doback doback  828 Mar 24 23:43 ..
drwxr-xr-x 1 doback doback  330 Mar 22 00:54 pupy
-rw-r--r-- 1 doback doback 2154 Mar  7 11:34 README.licen`

going to the root of my system 

`[doback@parrot]─[/]
└──╼ $ls -al
total 48
drwxr-xr-x   1 root root  260 Mar 15 18:59 .
drwxr-xr-x   1 root root  260 Mar 15 18:59 ..
-rw-r--r--   1 root root    0 Nov 23 10:45 0
-rw-r--r--   1 root root    0 Mar  7 11:48 .autorelabel
drwxr-xr-x   1 root root 2438 Mar 16 17:05 bin
drwxr-xr-x   1 root root  692 Mar 21 23:57 boot
drwxr-xr-x  21 root root 3700 Mar 25 10:45 dev
drwxr-xr-x   1 root root 6192 Mar 24 01:08 etc
drwxr-xr-x   1 root root   12 Mar  7 11:34 home
lrwxrwxrwx   1 root root   40 Mar 15 18:59 initrd.img -> boot/initrd.img-4.19.0-parrot1-20t-amd64
lrwxrwxrwx   1 root root   37 Mar  7 11:25 initrd.img.old -> boot/initrd.img-4.18.0-parrot10-amd64
drwxr-xr-x   1 root root  496 Mar 16 16:58 lib
drwxr-xr-x   1 root root 1250 Mar 16 16:56 lib32
drwxr-xr-x   1 root root   40 Mar 16 16:58 lib64
drwxr-xr-x   1 root root   22 Mar  7 11:59 media
drwxr-xr-x   1 root root    0 Nov 19 19:44 mnt
drwxr-xr-x   1 root root  136 Mar 16 01:19 opt
dr-xr-xr-x 202 root root    0 Mar 24 23:21 proc
drwxr-xr-x   1 root root  384 Mar 24 01:51 root
drwxr-xr-x  43 root root 1240 Mar 25 10:45 run
drwxr-xr-x   1 root root 4614 Mar 16 16:58 sbin
drwxr-xr-x   1 root root   12 Mar 15 18:59 snap
drwxr-xr-x   1 root root    8 Mar  7 11:26 srv
dr-xr-xr-x  13 root root    0 Mar 24 23:21 sys
drwxrwxrwt   1 root root 1250 Mar 25 10:49 tmp
drwxr-xr-x   1 root root  184 Mar 24 01:00 usr
drwxr-xr-x   1 root root  126 Mar  7 11:31 var
lrwxrwxrwx   1 root root   37 Mar 15 18:59 vmlinuz -> boot/vmlinuz-4.19.0-parrot1-20t-amd64
lrwxrwxrwx   1 root root   34 Mar  7 11:31 vmlinuz.old -> boot/vmlinuz-4.18.0-parrot10-amd64
'


using the simple command you suggest returns this output. 
'
>> gen -A x86 -o ./client.exe
[%] Connection point: Transport=ssl Address=172.18.0.2:8443
[+] Generate client: windows/x86

{ Configuration }
KEY            VALUE                          
----------------------------------------------
launcher       connect                        
launcher_args  -t ssl --host 172.18.0.2:8443  
cid            0xf2881b91L                    

[+] Required credentials (found)
  + SSL_BIND_CERT
  + SSL_CA_CERT
  + SSL_CLIENT_CERT
  + SSL_BIND_KEY
  + SSL_CLIENT_KEY
[+] OUTPUT_PATH: /project/client.exe
[+] SCRIPTLETS:  []
[+] DEBUG:       False
'

**Comment by glides** [comment]
Your issue appears to be with firejail on parrot OS. This isn't a pupy issue, it's a parrot OS issue.
See: **Whitelisting a Folder inside Home Directory** from [here](https://community.parrotsec.org/t/using-firejail/1560)

As it sounds like this issue: [here](https://community.parrotsec.org/t/unable-to-access-home-directory/1608/2)

**Comment by alxchk** [comment]
Execute and show the output:

```
in pupysh:
>> gen -A x86 -o ./client.exe
>> !ls -l ./client.exe
>> !readlink -f ./client.exe
>> !pwd
```

```
in your console:
ls -l PATH_RETURNED_BY_!pwd
```

**Comment by paradoxfound** [comment]
in pupy `>> gen -A x86 -o ./client.exe
[%] Connection point: Transport=ssl Address=172.18.0.2:8443
[+] Generate client: windows/x86

{ Configuration }
KEY            VALUE                          
----------------------------------------------
launcher       connect                        
launcher_args  -t ssl --host 172.18.0.2:8443  
cid            0x43109305L                    

[+] Required credentials (found)
  + SSL_BIND_CERT
  + SSL_CA_CERT
  + SSL_CLIENT_CERT
  + SSL_BIND_KEY
  + SSL_CLIENT_KEY
[+] OUTPUT_PATH: /project/client.exe
[+] SCRIPTLETS:  []
[+] DEBUG:       False
>> !ls -l ./client.exe
-rw-r--r-- 1 root root 3579392 Mar 25 19:00 ./client.exe
>> !readlink -f ./client.exe
/project/client.exe
>> !pwd
/project
>> 
`

in console

`$ls -l /project
ls: cannot access '/project': No such file or directory
`

I am going to do some more research on firejail and how to use it to start pupy.

**Comment by glides** [comment]
Yeah, that's definitely jailed.

> I am going to do some more research on firejail and how to use it to start pupy.

Most likely, you'll need to whitelist the python binary and not pupysh.
If you installed off the wiki and used the create-workspace.py script...that binary is probably located at pupyws/bin/python or whatever you named the pupyws folder. Good luck, sounds like it should work if you can figure out how to get it whitelisted.

**Comment by alxchk** [comment]
Well, your setup is really weird
