### ISSUE TITLE
requirements issue

### ISSUE THREAD

**Issue by pretech86** [n1nj4sec/pupy#757]
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-iue088u9/poster/

**Comment by alxchk** [comment]
what is this?

**Comment by pretech86** [comment]
when i try to setup requirements by pip install -r requirements it give me the following 

Collecting https://github.com/alxchk/tinyec/archive/master.zip (from -r requirements.txt (line 9))
  Downloading https://github.com/alxchk/tinyec/archive/master.zip
     / 163kB 3.1MB/s
Collecting https://github.com/CoreSecurity/impacket/archive/master.zip (from -r requirements.txt (line 17))
  Downloading https://github.com/CoreSecurity/impacket/archive/master.zip (1.4MB)
    100% |████████████████████████████████| 1.4MB 411kB/s 
Collecting https://github.com/AlessandroZ/pypykatz/archive/master.zip (from -r requirements.txt (line 24))
  Downloading https://github.com/AlessandroZ/pypykatz/archive/master.zip
     \ 839kB 3.0MB/s
Collecting https://github.com/warner/python-ed25519/archive/master.zip (from -r requirements.txt (line 25))
  Downloading https://github.com/warner/python-ed25519/archive/master.zip
     - 1.5MB 1.2MB/s
Obtaining file:///root/Downloads/2-undetectable%20payload%20generators/windows/pupy/pupy/external/pykcp (from -r requirements.txt (line 46))
Requirement already satisfied: rpyc==3.4.4 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 1)) (3.4.4)
Collecting pycryptodome (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/62/a8/06e9a96c07e334459eec9673af19f20e60aa7fdeaf31215c10c06a748206/pycryptodome-3.8.0-cp37-cp37m-manylinux1_x86_64.whl
Requirement already satisfied: pefile in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (2018.8.8)
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from -r requirements.txt (line 4)) (3.13)
Collecting rsa (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/02/e5/38518af393f7c214357079ce67a317307936896e961e35450b70fad2a9cf/rsa-4.0-py2.py3-none-any.whl
Requirement already satisfied: netaddr in /usr/lib/python3/dist-packages (from -r requirements.txt (line 6)) (0.7.19)
Requirement already satisfied: ecdsa==0.13 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 7)) (0.13)
Collecting paramiko==2.0.2 (from -r requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/d0/17/089b126c782b51f9e65c0ce1111f6ccf5ea5bf1e2dad03f3de2039003652/paramiko-2.0.2-py2.py3-none-any.whl
Requirement already satisfied: psutil in /usr/lib/python3/dist-packages (from -r requirements.txt (line 10)) (5.5.1)
Requirement already satisfied: netifaces in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 11)) (0.10.9)
Collecting pylzma (from -r requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/03/d8/10ef072c3cd4301a65a1b762b09eefa02baf8da23b9ea77ebe9546499975/pylzma-0.5.0.tar.gz
Requirement already satisfied: colorama in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 13)) (0.4.1)
Collecting mss (from -r requirements.txt (line 14))
  Using cached https://files.pythonhosted.org/packages/08/56/1b4c26936f1fd8fe0af1a6ce905389cad2f48b1b7cc7cafd1ae070ddff56/mss-4.0.2-py2.py3-none-any.whl
Requirement already satisfied: pyOpenSSL in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 15)) (17.2.0)
Collecting scapy (from -r requirements.txt (line 16))
  Using cached https://files.pythonhosted.org/packages/d0/04/b8512e5126a1816581767bf95cbf525e0681a22c055bcd45f47ecff60170/scapy-2.4.2.tar.gz
Collecting pyuv (from -r requirements.txt (line 18))
  Using cached https://files.pythonhosted.org/packages/53/cc/7f5313348a9212b455abe2d9dd2bb2fdb8d75d9a2ce5d5a2e8ba7819ff05/pyuv-1.4.0.tar.gz
Requirement already satisfied: dnslib in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 19)) (0.9.9)
Collecting http-parser (from -r requirements.txt (line 20))
  Using cached https://files.pythonhosted.org/packages/07/c4/22e3c76c2313c26dd5f84f1205b916ff38ea951aab0c4544b6e2f5920d64/http-parser-0.8.3.tar.gz
Collecting cerberus (from -r requirements.txt (line 21))
  Using cached https://files.pythonhosted.org/packages/90/31/e30784a1f9a4b46875cfed1c9f806c188e2181e7ba3b568e81e7b0bc5718/Cerberus-1.2.tar.gz
Collecting logutils (from -r requirements.txt (line 22))
  Using cached https://files.pythonhosted.org/packages/49/b2/b57450889bf73da26027f8b995fd5fbfab258ec24ef967e4c1892f7cb121/logutils-0.3.5.tar.gz
Requirement already satisfied: secretstorage==2.3.1 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 23)) (2.3.1)
Requirement already satisfied: pygments in /usr/lib/python3/dist-packages (from -r requirements.txt (line 26)) (2.3.1)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 27)) (2.18.4)
Requirement already satisfied: tornado==v5.1.1 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 28)) (5.1.1)
Collecting poster (from -r requirements.txt (line 29))
  Using cached https://files.pythonhosted.org/packages/9f/dc/0683a458d21c3d561ab2f71b4fcdd812bf04e55c54e560b0854cea95610e/poster-0.8.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-pc2m7m8x/poster/setup.py", line 2, in <module>
        import poster
      File "/tmp/pip-install-pc2m7m8x/poster/poster/__init__.py", line 29, in <module>
        import poster.streaminghttp
      File "/tmp/pip-install-pc2m7m8x/poster/poster/streaminghttp.py", line 61
        print "send:", repr(value)
                    ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-pc2m7m8x/poster/

**Comment by alxchk** [comment]
python3 is not supported

**Comment by pretech86** [comment]
so what i should do ?

**Comment by alxchk** [comment]
Use python2

**Comment by pretech86** [comment]
but if i removed python3 from kali , some other tools need it ? or i understood you wrong

**Comment by mrcnpp** [comment]
@pretech86 just type `pip2` instead of ` pip`  and `python2.7` instead of `python`
