### ISSUE TITLE
ImportError: No module named pylzma

### ISSUE THREAD

**Issue by AmirUncocoder** [n1nj4sec/pupy#765]
Traceback (most recent call last):
  File "./pupygen.py", line 26, in <module>
    import pylzma
ImportError: No module named pylzma

**Comment by alxchk** [comment]
https://github.com/n1nj4sec/pupy/blob/unstable/pupy/requirements.txt#L12

**Comment by AmirUncocoder** [comment]
I knew the problem is, what is the solution

**Comment by alxchk** [comment]
The solution is to use instruction in wiki. At least it's not clear, was it used or not.
