### ISSUE TITLE
pupy on windows

### ISSUE THREAD

**Issue by joker8989** [n1nj4sec/pupy#771]
Hey i wanted to know if pupy is able to run on windows machine with Docker maybe installed?
is that possible i need windows and not linux dont ask why,,..

**Comment by alxchk** [comment]
You can always install virtualbox

**Comment by joker8989** [comment]
I know i can install virtualbox but i need specisif to know if i can install pupy via cmd (python)+ pip ??
cause i want to test this project and try to combine it with mine and i need windows and not other platform.. is that possible??
with cmd?pip?..

**Comment by alxchk** [comment]
Out from the box most things will not work. readline/colors/pty/etc will not work on windows. If you want to have this on windows a lot of work should be done

**Comment by joker8989** [comment]
I am not familiar with Docker i just started to learn about it but if i
installed docker and use that can i combine pupy(what i install) with my
"projects" ? that are stored in the windows machine?

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
