### ISSUE TITLE
Pupy is not able to convert to exe

### ISSUE THREAD

**Issue by joker8989** [n1nj4sec/pupy#773]
I am testing this project for a while but besides that im developing tools to how to make scripts in python FUD well so it works everything works perfect (on my client-server project)
Well pupy is better then my project creators that work for years..

Now when i choose from pupygen.py format py or pyinst (i need that to add my code - written in python) the file creates in my output as usual but after converting the file to exe and trying to open error is displayed:

Fatal error detected:
Failed to execute script ....

Now the py of the pupy works, there is some error in the conversion my guess is that pupy did not "Moduled" all the modules that need to be import cause the modules are in pupy/pupy/modules and the ouput file is in /.config/pypy/output

I tried also copying files so they would be in the same directory..

anyway is there any i can do to convert it from py to exe without errors??

**Comment by joker8989** [comment]
Can please someone answer me? Whoever uses this project

**Comment by alxchk** [comment]
Use native clients

**Comment by joker8989** [comment]
> Use native clients

What do u mean by native clients?
need your help...

**Comment by joker8989** [comment]
Can u provide me a link for that? I did not see in the viki about native client..

**Comment by joker8989** [comment]
????
