### ISSUE TITLE
invalid choice: 'apk'

### ISSUE THREAD

**Issue by Nikoh72** [n1nj4sec/pupy#775]
`./pupygen.py -f apk -o khaleesi.apk connect --host 192.168.30 --transport ssl
usage: pupygen.py [-h]
                  [-f {client,py,pyinst,py_oneliner,ps1,ps1_oneliner,rubber_ducky,csharp,.NET,.NET_oneliner}]
                  [-O {android,windows,linux,solaris}] [-A {x86,x64}] [-U]
                  [-P PACKER] [-S] [-o OUTPUT]
                  [-d <ATTEMPTS> <MIN SEC> <MAX SEC>] [-D OUTPUT_DIR]
                  [-s SCRIPTLET] [-l] [-E] [--no-use-proxy]
                  [--oneliner-nothidden] [--debug-scriptlets] [--debug]
                  [--workdir WORKDIR]
                  [{bind,auto_proxy,dnscnc,connect}] ...
pupygen.py: error: argument -f/--format: invalid choice: 'apk' (choose from 'client', 'py', 'pyinst', 'py_oneliner', 'ps1', 'ps1_oneliner', 'rubber_ducky', 'csharp', '.NET', '.NET_oneliner')
`

**Comment by Nikoh72** [comment]
cannot create apk

**Comment by alxchk** [comment]
`gen -f client -O android`
