### ISSUE TITLE
binary can't execute

### ISSUE THREAD

**Issue by zablah** [n1nj4sec/pupy#781]
I'm using the following to generate binary for linux
`./pupygen.py -f client -O linux connect --host x.x.x.x:4444 --transport http`
when run the output binary:
```
sh pupyx86.lin
pupyx86.lin: 1: pupyx86.lin: Syntax error: ")" unexpected

```

```
./pupyx86.lin
bash: ./pupyx86.lin: No such file or directory
```

```
bash pupyx86.lin
pupyx86.lin: pupyx86.lin: cannot execute binary file
```

**Comment by alxchk** [comment]
Likely you are trying to execute x86 binary on x86_64 arch without multilib. Use -A x64

**Comment by zablah** [comment]
it's work thank you
