### ISSUE TITLE
backup Server 

### ISSUE THREAD

**Issue by zablah** [n1nj4sec/pupy#783]
how we can update Client connection back server ip and port after run the client ?

**Comment by takao8090** [comment]
you should specify the connection host and port after launcher 
```
./pupygen.py -f client -O linux -A x64 -D /tmp connect --host 1.1.1.1:8080 -t http
```
and you will see the server ip, port and connect type has been changed
```
➜  pupy git:(unstable) ✗ ./pupygen.py -f client -O linux -A x64 -D /tmp connect --host 1.1.1.1:8080 -t http
[+] Generate client: linux/x64

{ Configuration }
KEY            VALUE                        
--------------------------------------------
launcher       connect                      
launcher_args  --host 1.1.1.1:8080 -t http  
cid            0xf8d16256L                  

[+] Required credentials (found)
  + SSL_BIND_CERT
  + SIMPLE_RSA_PRIV_KEY
  + SIMPLE_RSA_PUB_KEY
[+] OUTPUT_PATH: /tmp/pupyx64.O3QUwY.lin
[+] SCRIPTLETS:  []
[+] DEBUG:       False
```

**Comment by glides** [comment]
You can also modify the config file.

**Comment by zablah** [comment]
maybe my question was not clear.
I have a pupy client connected to server x.x.x.x:yyyy
I want to set a backup Server (pupy Server) in the client,  so if x.x.x.x go down, my client will automatically connect to new server
"pupy client has multi server ip"
how we can do this ?

**Comment by glides** [comment]
Oh sorry. Yes, you can:

https://github.com/n1nj4sec/pupy/blob/fbdca4e1505299dafff9b65e57815dbf2258cb27/pupy/network/lib/launchers/connect.py#L46
