### ISSUE TITLE
pupy Net application memory_exec error?

### ISSUE THREAD

**Issue by kainpark7894** [n1nj4sec/pupy#79]
![neterror](https://cloud.githubusercontent.com/assets/18137745/14229774/742d5d20-f978-11e5-8255-4022378f9b45.png)

dotnet 4.0 application exe file memory_exec error why?

C# PE file memory_exec no?

and memory_exec -p(process selected) <-command auto cmd.exe 

select process(-p) Additional options are available ?

**Comment by n1nj4sec** [comment]
No, you can't, you need a real PE. To load .NET assemblies from memory, use something like https://msdn.microsoft.com/en-us/library/system.reflection.assembly.load%28v=vs.110%29.aspx
