### ISSUE TITLE
error on pip install requirements

### ISSUE THREAD

**Issue by LodeVanB** [n1nj4sec/pupy#790]
# excerpt last lines ...
Requirement already satisfied: requests in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 27)) (2.20.0)
Collecting tornado==v5.1.1 (from -r requirements.txt (line 28))
  Using cached https://files.pythonhosted.org/packages/e6/78/6e7b5af12c12bdf38ca9bfe863fcaf53dc10430a312d0324e76c1e5ca426/tornado-5.1.1.tar.gz
Collecting poster (from -r requirements.txt (line 29))
  Using cached https://files.pythonhosted.org/packages/9f/dc/0683a458d21c3d561ab2f71b4fcdd812bf04e55c54e560b0854cea95610e/poster-0.8.1.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/sbin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fddbm4fx/poster/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fddbm4fx/poster/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-fddbm4fx/poster/
    Complete output (10 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-fddbm4fx/poster/setup.py", line 2, in <module>
        import poster
      File "/tmp/pip-install-fddbm4fx/poster/poster/__init__.py", line 29, in <module>
        import poster.streaminghttp
      File "/tmp/pip-install-fddbm4fx/poster/poster/streaminghttp.py", line 61
        print "send:", repr(value)
                    ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by alxchk** [comment]
> python3.7
