### ISSUE TITLE
'pwd' command traces back

### ISSUE THREAD

**Issue by artagel** [n1nj4sec/pupy#8]
I believe this should be a proper command with a return.
```
>> exec pwd
========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "rpyc\core\protocol.pyc", line 305, in _dispatch_request
  File "rpyc\core\protocol.pyc", line 535, in _handle_call
  File "subprocess.pyc", line 573, in check_output
CalledProcessError: Command 'pwd' returned non-zero exit status 1
```

**Comment by n1nj4sec** [comment]
on what os ?

**Comment by artagel** [comment]
Running server on Kali 2.0, client on Windows 7 x86.

**Comment by deathfantasy** [comment]
Windows doesn't have `pwd`.
Try `exec cmd /c echo %cd%` instead (or just start an interactive shell).

**Comment by n1nj4sec** [comment]
yea that's why pwd does not exists on windows, try open a cmd.exe

**Comment by artagel** [comment]
Dang, you're right..I'm too used to being on windows in meterpreter!
