### ISSUE TITLE
OSX documentation

### ISSUE THREAD

**Issue by Viss** [n1nj4sec/pupy#80]
Hello!

I saw in the demo screenshots that pupy works as a framework to attack osx and you can land shells on macs - but I can't find in the documentation how to create a payload for osx. 

help?

**Comment by mandreko** [comment]
You should be able to use the pp.py file on OSX endpoints. Additionally, you can bundle it up into a single binary using py2installer and the instructions found here: https://github.com/n1nj4sec/pupy/wiki/Generate-payloads#on-osx

**Comment by Viss** [comment]
I had attempted this, but its output is an elf binary. I can provide a screenshot shortly

**Comment by mandreko** [comment]
Did you attempt it on an osx system? For pyinstaller to create mach-o binaries, you have to do it on OSX. If you run pyinstaller on linux, you'll create elf binaries.

**Comment by Viss** [comment]
so I guess I'm an asshole. 
I must have run the command on a shell and not on my mac. 

> > viss@localhost:~/tools/pupy/pupy> pyinstaller --hidden-import uuid --onefile /Users/viss/tools/pupy/pupy/pp.py
> 20 INFO: PyInstaller: 3.1.1
> 20 INFO: Python: 2.7.10
> 27 INFO: Platform: Darwin-15.3.0-x86_64-i386-64bit
> 28 INFO: wrote /Users/viss/tools/pupy/pupy/pp.spec
> 36 INFO: UPX is not available.
> 37 INFO: Extending PYTHONPATH with paths
> ['/Users/viss/tools/pupy/pupy', '/Users/viss/tools/pupy/pupy']
> 37 INFO: checking Analysis
> 37 INFO: Building Analysis because out00-Analysis.toc is non existent
> 38 INFO: Initializing module dependency graph...
> 41 INFO: Initializing module graph hooks...
> 42 INFO: Analyzing hidden import 'uuid'
> 1030 INFO: running Analysis out00-Analysis.toc
> 1033 INFO: Analyzing /Users/viss/tools/pupy/pupy/pp.py
> 1039 INFO: Processing pre-find module path hook   site
> 1039 INFO: site: retargeting to fake-dir '/Library/Python/2.7/site-packages/PyInstaller/fake-modules'
> 2673 INFO: Processing pre-safe import module hook   _xmlplus
> 2776 INFO: Processing pre-find module path hook   distutils
> 4286 INFO: Looking for import hooks ...
> 4288 INFO: Processing hook   hook-distutils.py
> 4291 INFO: Processing hook   hook-sysconfig.py
> 4291 INFO: Processing hook   hook-xml.py
> 4352 INFO: Processing hook   hook-httplib.py
> 4352 INFO: Processing hook   hook-encodings.py
> 4710 INFO: Processing hook   hook-_tkinter.py
> 4715 INFO: checking Tree
> 4715 INFO: Building Tree because out00-Tree.toc is non existent
> 4715 INFO: Building Tree out00-Tree.toc
> 4786 INFO: checking Tree
> 4786 INFO: Building Tree because out01-Tree.toc is non existent
> 4786 INFO: Building Tree out01-Tree.toc
> 4838 INFO: Looking for ctypes DLLs
> 4849 INFO: Analyzing run-time hooks ...
> 4854 INFO: Including run-time hook 'pyi_rth__tkinter.py'
> 4862 INFO: Looking for dynamic libraries
> 5054 INFO: Looking for eggs
> 5055 INFO: Python library not in binary depedencies. Doing additional searching...
> 5056 INFO: Using Python library /System/Library/Frameworks/Python.framework/Versions/2.7/Python
> 5065 INFO: Warnings written to /Users/viss/tools/pupy/pupy/build/pp/warnpp.txt
> 5244 INFO: checking PYZ
> 5244 INFO: Building PYZ because out00-PYZ.toc is non existent
> 5244 INFO: Building PYZ (ZlibArchive) /Users/viss/tools/pupy/pupy/build/pp/out00-PYZ.pyz
> 5657 INFO: checking PKG
> 5657 INFO: Building PKG because out00-PKG.toc is non existent
> 5657 INFO: Building PKG (CArchive) out00-PKG.pkg
> 8085 INFO: Bootloader /Library/Python/2.7/site-packages/PyInstaller/bootloader/Darwin-64bit/run
> 8085 INFO: checking EXE
> 8085 INFO: Building EXE because out00-EXE.toc is non existent
> 8085 INFO: Building EXE from out00-EXE.toc
> 8094 INFO: Appending archive to EXE /Users/viss/tools/pupy/pupy/dist/pp
> 8109 INFO: Fixing EXE for code signing /Users/viss/tools/pupy/pupy/dist/pp
> viss@localhost:~/tools/pupy/pupy> file dist/pp 
> dist/pp: Mach-O 64-bit executable x86_64

**Comment by mandreko** [comment]
Not an asshole. :)

I just had it fresh in my mind, since I *just* did the same on Friday.

**Comment by Viss** [comment]
Is there a way to hard-wire one (or more?) destination hosts/ports?

**Comment by mandreko** [comment]
I'd recommend reading through the pp.py file, especially around the "LAUNCHER" variable.

**Comment by n1nj4sec** [comment]
Thank's mandreko for you answers, I guess I can close the issue now
