### ISSUE TITLE
create-workspace error: libcap development headers

### ISSUE THREAD

**Issue by sc0ttex** [n1nj4sec/pupy#803]
Hi,
when running 
`./create-workspace.py pupyws`

i get this error:

`    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-PR8cBh/python-prctl/setup.py'"'"'; __file__='"'"'/tmp/pip-install-PR8cBh/python-prctl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-PR8cBh/python-prctl/pip-egg-info
         cwd: /tmp/pip-install-PR8cBh/python-prctl/
    Complete output (1 lines):
    You need to install libcap development headers to build this module
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Traceback (most recent call last):
  File "./create-workspace.py", line 196, in <module>
    main()
  File "./create-workspace.py", line 84, in main
    ], env=env, cwd=os.path.join(args.pupy_git_folder, 'client'))
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/andrea/tools/pupy/client/build-docker.sh']' returned non-zero exit status 1
`

I tried to install libcap dev with:
`sudo apt-get install libcap-dev`
but still the same error. Any ideas?

**Comment by glides** [comment]
“You need to install libcap development headers to build this module”

**Comment by sc0ttex** [comment]
Obviously i thought it was libcap-dev, if not can you indicate the right package please?

**Comment by glides** [comment]
I can’t suggest a package unless I know what OS you’re using.

**Comment by sc0ttex** [comment]
right, i'm on Ubuntu 18.04

**Comment by glides** [comment]
> right, i'm on Ubuntu 18.04

That should be the correct dependency. Is it possible setuptools is out of date? Try 
`pip install --upgrade setuptools`

**Comment by sc0ttex** [comment]
i close the issue because i recreated the ws and no problem was detected, thank you @glides
