### ISSUE TITLE
Problems with pip or pip3 install requirements.txt what I should to do to fix this error?

### ISSUE THREAD

**Issue by Rey-And** [n1nj4sec/pupy#812]
ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-evkbiocv/poster/setup.py'"'"'; __file__='"'"'/tmp/pip-install-evkbiocv/poster/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-evkbiocv/poster/pip-egg-info                                                             
         cwd: /tmp/pip-install-evkbiocv/poster/                                                                          
    Complete output (10 lines):                                                                                          
    Traceback (most recent call last):                                                                                   
      File "<string>", line 1, in <module>                                                                               
      File "/tmp/pip-install-evkbiocv/poster/setup.py", line 2, in <module>                                              
        import poster                                                                                                    
      File "/tmp/pip-install-evkbiocv/poster/poster/__init__.py", line 29, in <module>                                   
        import poster.streaminghttp                                                                                      
      File "/tmp/pip-install-evkbiocv/poster/poster/streaminghttp.py", line 61                                           
        print "send:", repr(value)                                                                                       
                    ^                                                                                                    
    SyntaxError: invalid syntax                                                                                          
    ----------------------------------------                                                                             
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by alxchk** [comment]
Python3 is not supported

**Comment by Rey-And** [comment]
okay but when I use pip, I have this error, so what I should to do  to fix this?

**Comment by alxchk** [comment]
It's not clear what exactly you are doing. Anyway, you always can call pip explicitly using python2:

python2 -m pip ....
