### ISSUE TITLE
alxchk  что я должен делать с этой ошибкой, именно когда я испльзую Python2.7  ее мне и выдает. Я просто уже не знаю что делать, что можно было сделать все пробовал без толку. Облазил все форумы что только можно, решения так и не нашел 

### ISSUE THREAD

**Issue by Rey-And** [n1nj4sec/pupy#813]

**Comment by Rey-And** [comment]
ERROR: Command errored out with exit status 1:
command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-evkbiocv/poster/setup.py'"'"'; file='"'"'/tmp/pip-install-evkbiocv/poster/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-evkbiocv/poster/pip-egg-info
cwd: /tmp/pip-install-evkbiocv/poster/
Complete output (10 lines):
Traceback (most recent call last):
File "", line 1, in
File "/tmp/pip-install-evkbiocv/poster/setup.py", line 2, in
import poster
File "/tmp/pip-install-evkbiocv/poster/poster/init.py", line 29, in
import poster.streaminghttp
File "/tmp/pip-install-evkbiocv/poster/poster/streaminghttp.py", line 61
print "send:", repr(value)
^
SyntaxError: invalid syntax
----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by alxchk** [comment]
```
Command errored out with exit status 1:
command: /usr/bin/python3 
```

```
>>>> python3  <<<<<
```
