### ISSUE TITLE
tinyec.ec module is imported into ecpv.py, but there is no  （to_bytes, from_bytes, ec2osp, osp2ec） method for tinyec.ec module

### ISSUE THREAD

**Issue by miss-outbond** [n1nj4sec/pupy#819]
>>> import tinyec.ec
>>> print (dir(tinyec.ec))
['Curve', 'ECDH', 'Inf', 'Keypair', 'Point', 'SubGroup', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'egcd', 'make_keypair', 'mod_inv', 'random', 'warnings']

from tinyec.ec import (
    to_bytes, from_bytes,
    ec2osp, osp2ec
)

**Comment by alxchk** [comment]
https://github.com/alxchk/tinyec

**Comment by miss-outbond** [comment]
> https://github.com/alxchk/tinyec

Tinyec.ec is a public library. If you change the public library, shouldn't you put the changed library into the project? Why not put it in the project?
