### ISSUE TITLE
when i do pip3 install -r requirements.txt i get this ERROR:

### ISSUE THREAD

**Issue by S0ndrikk** [n1nj4sec/pupy#827]
ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bc_8ycjy/poster/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bc_8ycjy/poster/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-bc_8ycjy/poster/pip-egg-info                                                                           
         cwd: /tmp/pip-install-bc_8ycjy/poster/                                    
    Complete output (10 lines):                                                    
    Traceback (most recent call last):                                             
      File "<string>", line 1, in <module>                                         
      File "/tmp/pip-install-bc_8ycjy/poster/setup.py", line 2, in <module>        
        import poster                                                              
      File "/tmp/pip-install-bc_8ycjy/poster/poster/__init__.py", line 29, in <module>                                                                                
        import poster.streaminghttp                                                
      File "/tmp/pip-install-bc_8ycjy/poster/poster/streaminghttp.py", line 61     
        print "send:", repr(value)                                                 
                    ^                                                              
    SyntaxError: invalid syntax                                                    
    ----------------------------------------                                       
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output

**Comment by TheAli711** [comment]
Try running this with python 2.
In python 3 print is actually a function.

**Comment by jayrod** [comment]
This and #837 are the same. Basically you will need to change the requirements file to have poster3 instead of just poster. 

[reproduction steps](https://asciinema.org/a/327138)

**Comment by alxchk** [comment]
Pupy does not support python3. At least now. So if you want to do something about that, you may put your efforts to futurize branch.
