### ISSUE TITLE
pupy PE exe&dll hexview ip&domain hide possible?

### ISSUE THREAD

**Issue by kainpark7894** [n1nj4sec/pupy#83]
hexview pe exe file & dll file

host& ip String Encrytion Option Possible?
![hide](https://cloud.githubusercontent.com/assets/18137745/14484909/a6fda5fc-018e-11e6-8094-8d8679553f49.png)

**Comment by n1nj4sec** [comment]
sure, the config is python code so it won't be difficult to obfuscate, I will add an option later on
