### ISSUE TITLE
Unable to install pykcp

### ISSUE THREAD

**Issue by jayrod** [n1nj4sec/pupy#835]
I am trying to install pupy on Kali Rolling

In the externals folder I am attempting to install pykcp but get the following error.

     pykcp.c:200:3: error: ‘struct <anonymous>’ has no member named ‘ob_type’
     200 |  v->ob_type->tp_free(self);

[Install script file](https://gist.github.com/2efcc05bfa4414c70ad16a872489c440)

**Comment by alxchk** [comment]
Try to update submodules:

git submodule --init --update --recursive

**Comment by jayrod** [comment]
Nope, I did an initial sub module git recourse. The project is there. I
just cant get it to build. I am going directly to the project and
performing a python3 setup.py build and receiving the error.

**Comment by jayrod** [comment]
I pulled down code from [here](https://github.com/alxchk/pykcp) and replaced it with the other external project and pip install -r requirements worked.
