### ISSUE TITLE
python 3.7 support - 'async' and 'await' are reserved keywords in python 3.7

### ISSUE THREAD

**Issue by jayrod** [n1nj4sec/pupy#836]
**ISSUE TYPE**
Bug

**SUMMARY**

async and await are reserved keywords in python 3.7, Pupy source code needs to be edited accordingly

**STEPS TO REPRODUCE**

* Install pupy
* python pupysh.py -l ec4 1234 --loglevel DEBUG

**EXPECTED OUTCOME**
pupysh server successfully starts

**PYTHON VERSION**
Python 3.8.2

**SUPPORTED OS**
Kali GNU/Linux Rolling

**Comment by jayrod** [comment]
Preliminary list of files effected:

- modules/rfs.py
- network/lib/connection.py
- network/lib/rpc/core/netref.py
- network/lib/rpc/core/protocol.py
- packages/windows/all/powershell.py
- pupylib/PupyJob.py

**Comment by alxchk** [comment]
Pupy does not support python3. At least now. So if you want to do something about that, you may put your efforts to futurize branch.
