### ISSUE TITLE
python 3.7 support -  Update poster library to corresponding python3 library

### ISSUE THREAD

**Issue by jayrod** [n1nj4sec/pupy#837]
**ISSUE TYPE**
Bug

**SUMMARY**

poster library is python 2 only and should be changed to "poster3" library from pypi

**STEPS TO REPRODUCE**
[asciienma](https://asciinema.org/a/327138)

**EXPECTED OUTCOME**
All Requirements are insstalled

**PYTHON VERSION**
Python 3.8.2

**SUPPORTED OS**
Kali GNU/Linux Rolling

**Comment by alxchk** [comment]
Pupy does not support python3. At least now. So if you want to do something about that, you may put your efforts to futurize branch.
