### ISSUE TITLE
OSX shell command doesn't work

### ISSUE THREAD

**Issue by shellster** [n1nj4sec/pupy#84]
If you attempt to run an interactive shell on an OSX victim,  you will get an import error about pty not existing.  That's because pty is Linux specific.  The pseudo shell still works so you can manually fall back to shell -T.  In the short term, the code should probably be updated to do that automatically on OSX.  Long term it would be nice to see if we could get full interactive shell.

**Comment by shellster** [comment]
It also appears that tty is not available, but termios is.

**Comment by n1nj4sec** [comment]
shell worked for me on osx last time I checked, your pyinstaller must miss some packages :
```
$ python
Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pty
>>> pty
<module 'pty' from '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pty.pyc'>
>>> import tty
>>> tty
<module 'tty' from '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tty.pyc'>
>>> 
```

**Comment by shellster** [comment]
Good catch.  I remotely loaded pty and tty and now I have a shell, but it isn't a true shell in my case.  Can you run sudo commands and the like?  I get errors about it not being a proper tty when I try.  It could be there is something broken still, on mine.  Also I loaded pty and tty libraries from my server, so they may not be the correct ones.

**Comment by shellster** [comment]
Rebuild Pyinstaller payload for OSX/Ubuntu with the following hidden imports and now it works (may indicate that there needs to be some additional work to make pyinstaller builds easier):
uuid, pty, tty

Closing this issue.

**Comment by n1nj4sec** [comment]
Thanks for your feedback, I will add this to the wiki
