### ISSUE TITLE
run interactive shell folder move error

### ISSUE THREAD

**Issue by kainpark7894** [n1nj4sec/pupy#85]
https://github.com/n1nj4sec/pupy/blob/6f942ce3204ca41689ceb840e6388fb4c563a786/pupy/modules/interactive_shell.py#L57

cp437 -> change cp936,950 cmd view possible

But Folder Move Error interactive shell
![error2](https://cloud.githubusercontent.com/assets/18137745/14524379/00e04806-0273-11e6-8dd8-862c74bf638b.png)

**Comment by n1nj4sec** [comment]
I improved locale detection in interactive_shell (changes are not yet on the master but on the dev branch)
