### ISSUE TITLE
Error if jarsigner is not installed

### ISSUE THREAD

**Issue by Krop-ac** [n1nj4sec/pupy#86]
`Traceback (most recent call last):
  File "./pupygen.py", line 208, in <module>
    get_edit_apk(os.path.join("payload_templates","pupy.apk"), outpath, conf)
  File "./pupygen.py", line 134, in get_edit_apk
    res=subprocess.check_output("jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore crypto/pupy-apk-release-key.keystore -storepass pupyp4ssword '{}' pupy_key".format(new_path), shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore crypto/pupy-apk-release-key.keystore -storepass pupyp4ssword 'pupy.apk' pupy_key' returned non-zero exit status 127`

I solved this issue with installing openjdk-8-jdk.

But I recommend encapsulate calling subprocess with try-catch block.

`#signing the tar`
              ` try:`
                     `res=subprocess.check_output("jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore crypto/pupy-apk-release-key.keystore -storepass pupyp4ssword '{}' pupy_key".format(n    +ew_path), shell=True)`
                 `except OSError as e:`
                     `if e.errno ==os.errno.ENOENT:`
                         `print "Please install jarsigner first."`
                         `sys.exit(1)`
                     `else:`
                        ` raise Exception("Error: Something went wrong.")`

**Comment by n1nj4sec** [comment]
added for the next version, thanks
