### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by leezp** [n1nj4sec/pupy#869]
./install.sh

return:

make: *** [pupy_load.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from pupy_load.c:22:
../common/Python-dynload.c: In function `initialize_python':
../common/Python-dynload.c:108: warning: passing arg 1 of `munmap' discards qualifiers from pointer target type
../common/Python-dynload.c: In function `py_eval_package_init':
../common/Python-dynload.c:277: warning: passing arg 1 of pointer to function from incompatible pointer type
../common/Python-dynload.c: In function `run_pupy':
../common/Python-dynload.c:469: warning: passing arg 1 of `munmap' discards qualifiers from pointer target type
Traceback (most recent call last):
  File "create-workspace.py", line 653, in <module>
    main()
  File "create-workspace.py", line 559, in main
    templates, args.image_tag, args.persistent
  File "create-workspace.py", line 249, in build_templates
    subprocess.check_call(args, stderr=subprocess.STDOUT)
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['docker', u'run', u'--name=build-pupy-linux32-df60', u'--ulimit', u'nofile=65535:65535', u'--security-opt', u'label=disable', u'--mount', u'type=bind,src=/home/tom/pupy,target=/build/workspace/project', u'alxchk/tc-linux32:latest', u'client/sources-linux/build-docker.sh']' returned non-zero exit status 2

**Comment by alxchk** [comment]
I don't see the error here. It should be somewhere upper

**Comment by leezp** [comment]
@alxchk  Envement: centos 7 ;    

and can't find https://github.com/n1nj4sec/pupy/releases/download/latest/payload_templates.txz

could you please send me a copy?

**Comment by alxchk** [comment]
No, you need to build them manually
