### ISSUE TITLE
Pupy's socksproxy module does not correctly close sockets in the event of a connection error

### ISSUE THREAD

**Issue by shellster** [n1nj4sec/pupy#88]
This is a horribly vague  bug report, and I apologize for that, but I wanted to at least point out that there is a problem somewhere.  I have been using pupy on a muti-week engagement involving Linux and OSX machines.  To use pupy, I've been using the pyinstaller built payloads.  Everything works well, except that pupy reliably crashes about once every 12 hours or sooner.  Even if the session isn't used, it eventually crashes.  I don't know if it is a memory leak, or something else.  I will try to add more information if I can find it.

**Comment by mandreko** [comment]
Often times when i see this, I also see the error:

> OSError: [Errno 24] Too many open files

**Comment by shellster** [comment]
[Errno 24] Too many open files: None

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "rpyc/core/protocol.py", line 305, in _dispatch_request
  File "rpyc/core/protocol.py", line 535, in _handle_call
  File "subprocess.py", line 566, in check_output
  File "subprocess.py", line 702, in __init__
  File "subprocess.py", line 1111, in _get_handles
  File "subprocess.py", line 1167, in pipe_cloexec
OSError: [Errno 24] Too many open files

Here's the stack trace I see.

**Comment by shellster** [comment]
I think I figured out the issue (with @mandreko's help).  I'm running pupy through pyinstaller builds. 

In pupy/pupy/packages/all/interactive_shell.py, near the top, is this line

    ON_POSIX = 'posix' in sys.builtin_module_names

This is later used in the file in Popen requests to set close_fds.  close_fds needs to be True in a POSIX environment, however pyinstaller isn't correctly including the posix module in builds.  Therefore I'm updating the description of this issue.  Currently, I have found that to create a linux/OSX client using pyinstaller, the following hidden imports must be included to get a correct build:
- uuid
- tty
- pty
- posix

**Comment by shellster** [comment]
Unfortunately adding posix still resulted in an eventual crash with the previous error about too many open files.  Not sure what is the root cause at this point.

**Comment by n1nj4sec** [comment]
hello, could you use lsof to check what kind of file descriptor is to much open ? Do you have the same problem when you use pp.py without pyinstaller by using the native python installed on your OSX/linux machine ?

**Comment by n1nj4sec** [comment]
A work-around could be to increase the limit using something like os.system("limit -n xxx")

**Comment by n1nj4sec** [comment]
by the way, posix is a built-in python module, it's useless to add it your pyinstaller hidden import list
```python
>>> import posix
>>> posix
<module 'posix' (built-in)>
```

**Comment by shellster** [comment]
I'll check lsof next time it pops up.  I (apparently) reduced the occurrence of the error by increasing ulimit -n.  The problem is definitely exacerbated (maybe caused by) the nmap connect scanning through the socks proxy module.

**Comment by shellster** [comment]
Alright, I captured some lsof output.  The pyinstaller payload is called "run".  There are just thousands of entries like this:

    run        2911       root  653u     sock                0,7       0t0   25540522 can't identify protocol
    run        2911       root  654u     sock                0,7       0t0   25540861 can't identify protocol
    run        2911       root  655u     sock                0,7       0t0   25540574 can't identify protocol
    run        2911       root  656u     sock                0,7       0t0   25540575 can't identify protocol
    run        2911       root  657u     sock                0,7       0t0   25540823 can't identify protocol

When scanning with nmap, the shell becomes unusable due to unending errors like this (which also post in the main pupysh window.):

	----------------------------------------
	Exception happened during processing of request from ('127.0.0.1', 57307)
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
		self.finish_request(request, client_address)
	  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
		self.RequestHandlerClass(request, client_address, self)
	  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
		self.handle()
	  File "[redacted]/pupy/pupy/modules/socks5proxy.py", line 145, in handle
		self._socks_response(CODE_NET_NOT_REACHABLE, terminate=True)
	  File "[redacted]/pupy/pupy/modules/socks5proxy.py", line 85, in _socks_response
		self.request.shutdown(socket.SHUT_RDWR)
	  File "/usr/lib/python2.7/socket.py", line 224, in meth
		return getattr(self._sock,name)(*args)
	error: [Errno 107] Transport endpoint is not connected
	----------------------------------------

**Comment by shellster** [comment]
Alright, after reading up on sockets, I believe I have finally figured out the issue.  The first issue, as shown above, is that the self.request.shutdown(socket.SHUT_RDWR) on line 85 is not being wrapped in a try/except, thus making pupy more-or-less unusable when performing connect scanning over the proxy, thanks to the constant error messages. 

The bigger issue, is that I believe each instance of request.shutdown(...) and request.close() need to be separately wrapped in try/except blocks.  The reason for this, as I understand it, is that request.shutdown(...) will throw an exception if there is data in the buffer waiting to be sent to the remote socket.  This happens whenever the server doesn't respond (such as when you scan a non-existent ip).  In this event, you still want to forcibly close the socket, otherwise, the module will continue to hold open the socket, which eventually results in the "OSError: [Errno 24] Too many open files" error.

**Comment by n1nj4sec** [comment]
thank you for your bug report ! does my patch on the dev branch fix the issue ?

**Comment by shellster** [comment]
I reviewed the patch and I believe it fixes the issue.  Unfortunately, I can't test it this week.  I'll reply to this issue once I have had a chance to test it.

**Comment by ptrovery** [comment]
i don't think the problem is fixed !
