### ISSUE TITLE
Missing File Python-stacktrace.h & Python-stacktrace.c

### ISSUE THREAD

**Issue by s1st3r** [n1nj4sec/pupy#884]
There some files not found on postmortem.c and i cant find them.
What are they for?

#include "Python-stacktrace.h"
#include "Python-stacktrace.c"

**Comment by alxchk** [comment]
They are in common/

This is used to build stacktrace for python in postmortem :)

**Comment by s1st3r** [comment]
Aha, someone edited and moved them there.

From this project you get to learn a lot. 

BTW at @alxchk , i have never been able to compile the project in Linux, i had move it to VSCode in Windows and do some more recoding to compile as SLN. Any pointers on how to use mingw to try compile on Linux.

**Comment by alxchk** [comment]
I'm not sure this can be built using mingw. The reason is you need to rebuild python as well. But.. But the project /is/ compiled from linux.. :)
You need to have toolchain in docker/podman for that. Just read the buil scripts
