### ISSUE TITLE
Pupy does not support interactive cmd.exe on windows

### ISSUE THREAD

**Issue by Technoturnovers** [n1nj4sec/pupy#89]
When using the interactive shell controlling windows, running interactive programs will automatically enter through all of the prompts.

Example:

```
C:\Windows>runas /user:HOSTNAME\USER notepad.exe
runas /user:HOSTNAME\USER notepad.exe
Enter the password for HOSTNAME\USER: 

C:\Windows>
```

Additionally, Pupy doesn't work with programs like GNU Nano, giving the error "Redirection is not supported."

**Comment by n1nj4sec** [comment]
yes, on windows the whole tty handling is not implemented and the input you enter is handled by python raw_input function. It looks like it's a real pain in the ass to implement it using ctypes or a c extension and I don't know any python library that could do this, so I don't plan to implement it any time soon

**Comment by Technoturnovers** [comment]
In the meantime, are there any workarounds, like a program that can do some sort of reverse ssh without any configuration? And i say without any configuration because i can't run Nano remotely to configure it.

**Comment by n1nj4sec** [comment]
well your options are only limited by your imagination ;) You can : 
- write your file locally and upload it
- use pyshell to have an interactive shell and edit your configuration file
- write a "edit" module that would be plugged with your local vi and would allow to edit files remotely ( don't use nano I wouldn't accept the PR :p )

**Comment by Technoturnovers** [comment]
Related, can you add support more more alternative windows shells, like powershell? Powershell doesn't work currently, it doesn't open a prompt.

Example:
`Opening interactive C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe ... (encoding : cp437)
Windows PowerShell 
Copyright (C) 2009 Microsoft Corporation. All rights reserved.

test`
And when i force cancel by doing Ctrl-C twice, the pupy shell locks up.

**Comment by n1nj4sec** [comment]
yes it's a known issue with powershell and python subprocess module, powershell doesn't seems to use standard stdin unless you pass it the "-Command -" argument

**Comment by n1nj4sec** [comment]
patch for interactive powershell 9cf348197ab684d3bb4bffa2fbd4dc1bd26a2c5d

**Comment by AlessandroZ** [comment]
For the interactive shell in windows, you could inspire you from the code of this python project: 
- https://github.com/curesec/tools/tree/master/aesshell

Here is the code of the client: 
- https://github.com/curesec/tools/blob/master/aesshell/bc.py

It's not perfect, but it could be an idea. I had some problems with this tool using powershell.
Hope it helps

**Comment by quentinhardy** [comment]
_aesshell_ [(https://github.com/curesec/tools/tree/master/aesshell)](https://github.com/curesec/tools/tree/master/aesshell) has not an interactive shell for Windows.
I don't know a python module for having interactive shell on Windows -:(

**Comment by alxchk** [comment]
This should work now. Please try.

**Comment by quentinhardy** [comment]
Interactive shell on Windows is OK now. I think this issue can be closed. Thank you for _ptyshell_.

**Comment by AlessandroZ** [comment]
This issue can be closed. It has already been implemented
