### ISSUE TITLE
Building binary for windows docker

### ISSUE THREAD

**Issue by yaboipotato** [n1nj4sec/pupy#892]
I built the things for windows but i get an error saying "crypto.cipher not found pycryptodome build failed" I've had no other issues with this other than this.

I'm running debian 9.11.

Also please update the documentation as fast as you can it's really hard to understand.

**Comment by alxchk** [comment]
Yep. Looks like new wheel package doesn't leave well with wine because of (broken?) unicode symbols in test file names. Pushed workaroudn for that. Should work

**Comment by yaboipotato** [comment]
thank  you i'll test it next time i can.

**Comment by yaboipotato** [comment]
I've managed to get windows client to work and to connect. :)
