### ISSUE TITLE
Please delete

### ISSUE THREAD

**Issue by Technoturnovers** [n1nj4sec/pupy#90]
When I run pupyx86.exe on windows without the server running, running it again with the server open doesn't make a new connection. (I know this is vague, but I can't really find any more details to give)

**Comment by Technoturnovers** [comment]
Turns out this was an error on my part, please delete

**Comment by void-in** [comment]
@Technoturnovers You can close this issue yourself. Github don't delete any issue/PR. When you close this, it won't be visible in the queue and should be good to go.
