### ISSUE TITLE
ImportError: No module named pupyrpc

### ISSUE THREAD

**Issue by Hkakashi** [n1nj4sec/pupy#903]
Hi, I'm using pupy for attack emulation. I can get an ec4 session but failed to spawn a shell. The full error message is pasted below. Thanks.

![image](https://user-images.githubusercontent.com/43193113/124534019-ffc2d380-de45-11eb-9e03-446e2631e240.png)

**Comment by alxchk** [comment]
It looks like you have mixed client and overall sources with different versions. Actually client is likely much older than sources. It's not fatal, as you can load missing part manually with load_package network.lib pupyrpc, but you will have more errors like that. It's better to rebuild

**Comment by Hkakashi** [comment]
Thanks for your help! The outdated client is exactly the root cause of this issue. Now it works perfectly.
