### ISSUE TITLE
Auto Reconnect

### ISSUE THREAD

**Issue by Technoturnovers** [n1nj4sec/pupy#91]
Could you add a feature that makes it so that when the pupy payload disconnects/get disconnected, it will automatically try to reconnect for a set amount of time? This would be really useful for when my internet cuts out, or i need to reboot my laptop for something.

**Comment by n1nj4sec** [comment]
it is already the case, it tries to reconnect every 30 seconds at max https://github.com/n1nj4sec/pupy/blob/master/pupy/pp.py#L106
