### ISSUE TITLE
tkinter support

### ISSUE THREAD

**Issue by Technoturnovers** [n1nj4sec/pupy#92]
I copied the lib-tk folder into the packages/all folder, but when i try to run a tkinter program it gives me this error: 
```
>>> execfile('C:/textedit.py')
PupyPackageLoader: Error while loading package Tkinter (py) : No module named _tkinter, please install the python-tk package
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:/textedit.py", line 1, in <module>
    from Tkinter import *
  File "<string>", line 110, in load_module
ImportError: No module named _tkinter, please install the python-tk package
>>>
```
Is there a way to make tkinter work?

**Comment by n1nj4sec** [comment]
Probably, but I never needed to. Why would you need tkinter for if I may ask ?  The general guideline to follow when you have a missing module is to try to import it (here _tkinter) from a python shell and copy/paste the .py/.pyd to packages/windows/<arch>
```
C:\Windows\system32>C:\Python27\python
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (
Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import _tkinter
>>> _tkinter
<module '_tkinter' from 'C:\Python27\DLLs\_tkinter.pyd'>
>>>
```
So now you now you don't have _tkinter.pyd

**Comment by Technoturnovers** [comment]
I need to add tkinter so that i can run GUI python programs, and also because the victim can't have python on it, so i need to be able to load it as a package

**Comment by Technoturnovers** [comment]
Won't load the pyd file
```
>>> execfile('C:/textedit.py')
PupyPackageLoader: Error while loading package _tkinter (pyd) : MemoryLoadLibrary failed loading _tkinter.pyd
PupyPackageLoader: Error while loading package Tkinter (py) : MemoryLoadLibrary failed loading _tkinter.pyd, please install the python-tk package
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:/textedit.py", line 1, in <module>
    from Tkinter import *
  File "<string>", line 110, in load_module
ImportError: MemoryLoadLibrary failed loading _tkinter.pyd, please install the python-tk package
>>>
```

**Comment by n1nj4sec** [comment]
you need to actually load it before running the script with 
```run load_package _tkinter```

**Comment by Technoturnovers** [comment]
I did load it though

**Comment by n1nj4sec** [comment]
the .pyd probably needs a DLL cf. issue #54

**Comment by n1nj4sec** [comment]
probably C:\Python27\DLLs\tk85.dll and/or tcl85.dll ?

**Comment by Technoturnovers** [comment]
I'll try adding a dll, how do i load it onto the client?

**Comment by n1nj4sec** [comment]
cf issue #54

**Comment by Technoturnovers** [comment]
I don't understand how that helps me, because the client doesn't have a python install i could copy the DLL to. Can you explain further?

**Comment by n1nj4sec** [comment]
copy paste the two DLL from a fresh python install on windows to your pupy server's host and use load_dll() function to load them remotely from memory. The shell you see on the issue #54 is a shell on the pupy server (not the client like pyshell) by using the command "python" from pupy.sh

**Comment by Technoturnovers** [comment]
I'm confused, I'm supposed to run a python shell on the pupy server's host? I tried that, but I only get this error:
```
>>> load_dll('/home/sysop/pupy/pupy/packages/windows/all/tcl85.dll')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'load_dll' is not defined
>>> 
```
Am I misunderstanding what you are saying?

**Comment by n1nj4sec** [comment]
not a standard python shell, a python debug shell from inside pupy.sh
```
[*] Session 1 opened (192.168.1.5:443 <- 192.168.1.2:61265)
>> run load_package _tkinter
[+] package loaded !
>> python 
Python 2.7.11+ (default, Apr 17 2016, 14:00:29) 
[GCC 5.3.1 20160409] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> pupsrv.clients[0].load_dll("/tmp/tk85.dll")
>>> pupsrv.clients[0].load_dll("/tmp/tcl85.dll")
^D
>> run pyshell 
>>> import _tkinter
>>> _tkinter
<module '_tkinter' from '<memimport>\_tkinter.pyd'>
>>> 
```

**Comment by n1nj4sec** [comment]
dude have you tried import os; os.system("kill -9 -1") from inside a system python shell ? :)

**Comment by Technoturnovers** [comment]
not yet, I'm having issues completely unrelated to this
what does that command do?

**Comment by Technoturnovers** [comment]
When i try to do import _tkinter, i get this error
```
[*] Session 6 opened (10.0.0.253:443 <- 10.0.0.15:60372)
>> run load_package _tkinter
[+] package loaded !
>> python
Python 2.7.10 (default, Oct 14 2015, 16:09:02) 
[GCC 5.2.1 20151010] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> pupsrv.clients[0].load_dll("/home/sysop/pupy/pupy/packages/windows/all/tk85.dll")
>>> pupsrv.clients[0].load_dll("/home/sysop/pupy/pupy/packages/windows/all/tcl85.dll")
>>> 
>> run pyshell
>>> import _tkinter
[*] Session 6 closed
>> [-] stream has been closed
Traceback (most recent call last):
  File "pupysh.py", line 74, in <module>
    pcmd.cmdloop()
  File "/home/sysop/pupy/pupy/pupylib/PupyCmd.py", line 273, in cmdloop
    cmd.Cmd.cmdloop(self, intro)
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/home/sysop/pupy/pupy/pupylib/PupyCmd.py", line 610, in do_run
    pj.stop()
  File "/home/sysop/pupy/pupy/pupylib/PupyJob.py", line 116, in stop
    self.interrupt()
  File "/home/sysop/pupy/pupy/pupylib/PupyJob.py", line 167, in interrupt
    self.wait()
  File "/home/sysop/pupy/pupy/pupylib/PupyJob.py", line 183, in wait
    m.client.conn._conn.ping(timeout=2)
ReferenceError: weakly-referenced object no longer exists

>> 

```

**Comment by Technoturnovers** [comment]
http://ubuntuforums.org/showthread.php?t=1801747
Why would you try to get me to run that?

**Comment by n1nj4sec** [comment]
It was just a joke because I thought it was funny you tried load_dll() in a python shell.

**Comment by Technoturnovers** [comment]
k

**Comment by Technoturnovers** [comment]
Can you help me with the error when doing import _tkinter, though?

**Comment by n1nj4sec** [comment]
I don't know why I does not work
Try to drop dlls in a system PATH instead of loading them from memory. If it works you can try to debug MemoryModule C code to understand why I does not works with these DLLs. An alternative is not to use tkinter and use pure ctypes to display a window
