### ISSUE TITLE
Run persistence before connection

### ISSUE THREAD

**Issue by alepacheco** [n1nj4sec/pupy#94]
Is there a way to make the persistence script run when the client is executed instead of manually running it?

**Comment by danny1991** [comment]
I think in config file, this should work? I don't know... :D

```
[on_connect]
#run_module = gather/keylogger start
```

**Comment by n1nj4sec** [comment]
yes, you can use @danny1991 method to add persistence when the payload connects back or you can add the persistence scriptlet when you generate the payload with pupygen (option -s persistence) to embed a persistence script that will run even if the payload is executed offline
