### ISSUE TITLE
Ability to run as root?

### ISSUE THREAD

**Issue by aiddenkeli** [n1nj4sec/pupy#98]
This is more of a request I guess. Is there a way to 'su' to root if the device is already rooted?

**Comment by n1nj4sec** [comment]
On android I suppose ? No, it would be nice to have a module to do this

**Comment by aiddenkeli** [comment]
Sorry yes on android. I will start looking at writing a module for it but I am not very skilled. If anyone who sees this would like this ability I humbly request they write a module and submit a pull request. If I get a module working I will do the same but I make no promises on quality. Thanks!

**Comment by MagicInventor** [comment]
In android all you have to do is run the su" command, it's not complicated to do.

**Comment by quentinhardy** [comment]
On a rooted Android device, _su_ command can be used for having a root shell.
I think this issue can be closed now.

**Comment by NeverMine17** [comment]
@MagicInventor, @quentinhardy, I think you don't get it. He wants to check for root before running `su`.
@aiddenkeli, You should see [this StackOverflow question](http://stackoverflow.com/questions/2806897/what-is-the-best-practices-for-checking-if-the-user-of-a-python-script-has-root). Hope its helps.

> Is there a way to 'su' to root **if the device is already rooted**?

Also it would be great if someone makes module that could use that feature.
For example a module that can dump Wi-Fi passwords.
This repository should help: https://github.com/Viralmaniar/Wifi-Dumper
